import { demoMatch } from "../../match-helpers";

export default demoMatch(
  "NCT06517212",
  "Excluded: needs ≥1 year of adjuvant endocrine therapy (letrozole since 9/8/26) · ctDNA, BMI unknown",
  "This phase 2 trial adds tirzepatide to endocrine therapy for node-positive HR+/HER2-negative early breast cancer with BMI > 27 and a positive Haystack MRD ctDNA test. Helen fits the disease and organ-function criteria (pN2a, ER 90%, HER2 IHC 2+/ISH not amplified, NED, ANC 2.3, eGFR 49), but she has taken letrozole for only 20 days against the ≥1 year required, and any adjuvant abemaciclib or ribociclib would have to be completed first. Her BMI cannot be calculated (68 kg, height not recorded) and ctDNA has never been sent; she could become a candidate from 9/8/27 (or after a CDK4/6 inhibitor) if her BMI exceeds 27 and Haystack ctDNA turns positive.",
  [
    {
      id: "NCT06517212-inc-1",
      status: "pass",
      rationale: "72-year-old woman (born 1954), well above the 18-year minimum.",
      evidence: [{ quote: "72 yo postmenopausal F", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT06517212-inc-2",
      status: "pass",
      rationale: "Node-positive (5/18, pN2a), ER 90% and HER2-negative by ASCO/CAP (IHC 2+, ISH not amplified), diagnosed 4/14/26; single unilateral primary with no neoadjuvant therapy, so no discordance rules apply.",
      evidence: [
        { quote: "Lymph nodes: 5 of 18 positive, largest deposit 1.6 cm, extranodal extension present.", source: "Pathology 2026-05-19" },
        { quote: "ER: positive, 90%, strong intensity", source: "Pathology 2026-05-19" },
        { quote: "HER2 ISH: not amplified (HER2/CEP17 ratio 1.3, mean HER2 copy number 3.4) - HER2-negative, HER2-low", source: "Pathology 2026-05-19" },
      ],
    },
    {
      id: "NCT06517212-inc-3",
      status: "unknown",
      confidence: "low",
      rationale: "Weight is 68 kg on 9/25/26 but height is not recorded, so BMI cannot be calculated; at 68 kg, BMI exceeds 27 only if she is shorter than about 159 cm.",
      evidence: [{ quote: "Wt 68 kg.", source: "Oncology note 2026-09-25" }],
      actionNeeded: "Measure height and calculate BMI; must be > 27 kg/m²",
    },
    {
      id: "NCT06517212-inc-4",
      status: "pass",
      rationale: "ECOG 1 at the 9/25/26 visit, with fatigue improving after chemotherapy.",
      evidence: [{ quote: "EXAM: ECOG 1.", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT06517212-inc-5",
      status: "fail",
      rationale: "Letrozole started 9/8/26, giving 20 days of adjuvant endocrine therapy as of 9/28/26 against ≥1 year required (reached 9/8/27); an adjuvant CDK4/6 inhibitor started after radiation would also need to be completed first.",
      evidence: [
        { quote: "letrozole 2.5 mg PO daily (started 9/8/2026)", source: "Medication list" },
        { quote: "Discussed adj abemaciclib x2 yrs vs ribociclib x3 yrs (w/ AI) vs clinical trial", source: "Oncology note 2026-09-25" },
      ],
    },
    {
      id: "NCT06517212-inc-6",
      status: "unknown",
      confidence: "low",
      rationale: "No ctDNA test of any kind has been sent (Signatera was considered but not ordered), so MRD status is unknown.",
      evidence: [{ quote: "ctDNA (Signatera) not sent; would send if trial requires.", source: "Oncology note 2026-09-25" }],
      actionNeeded: "Send Haystack MRD tumor-informed ctDNA test (built on mastectomy tissue); a positive result is required",
    },
    {
      id: "NCT06517212-inc-7",
      status: "pass",
      rationale: "FFPE blocks from the 5/12/26 modified radical mastectomy (primary tumor) are documented as available.",
      evidence: [{ quote: "MRM blocks available.", source: "Oncology note 2026-09-25" }],
      actionNeeded: "Confirm block tumor content is adequate for Haystack whole genome sequencing",
    },
    {
      id: "NCT06517212-inc-8",
      status: "unknown",
      confidence: "low",
      rationale: "No sign of metastasis now (NED on 9/25/26 exam; ALP 84 and LFTs normal; staging CT/bone scan 5/21/26 negative), but the criterion requires restaging after a positive ctDNA result, which does not yet exist.",
      evidence: [
        { quote: "s/p MRM + adj TC x4, on PMRT + letrozole. NED.", source: "Oncology note 2026-09-25" },
        { quote: "No evidence of distant metastatic disease.", source: "Staging CT + bone scan 2026-05-21" },
      ],
      actionNeeded: "If ctDNA is positive, restage with history, exam, CBC, CMP and CT chest/abdomen/pelvis plus bone scan; must show no metastases",
    },
    {
      id: "NCT06517212-inc-9",
      status: "pass",
      rationale: "Labs 9/23/26: ANC 2.3 × 10⁹/L (>1.5), platelets 201 × 10⁹/L (≥100) and Hgb 11.1 g/dL (≥9; mild post-chemotherapy anemia).",
      evidence: [{ quote: "WBC 4.4 | ANC 2.3 | Hgb 11.1 (L) | Plt 201", source: "Labs 2026-09-23" }],
    },
    {
      id: "NCT06517212-inc-10",
      status: "pass",
      rationale: "Labs 9/23/26: AST 22 and ALT 18 U/L (well within 3 × ULN) and total bilirubin 0.6 mg/dL (≤1.5 × ULN).",
      evidence: [{ quote: "AST 22 | ALT 18 | T bili 0.6", source: "Labs 2026-09-23" }],
    },
    {
      id: "NCT06517212-inc-11",
      status: "pass",
      rationale: "Creatinine 1.1 mg/dL (CKD 3a) with eGFR 49 on 9/23/26; Cockcroft-Gault CrCl is about 50 mL/min (72 y, 68 kg, female), above the ≥30 mL/min threshold.",
      evidence: [
        { quote: "Cr 1.1 | eGFR 49 (L)", source: "Labs 2026-09-23" },
        { quote: "CKD 3a (baseline Cr 1.0-1.1)", source: "Oncology note 2026-09-25" },
      ],
    },
    {
      id: "NCT06517212-inc-12",
      status: "pass",
      confidence: "low",
      rationale: "She attends regular oncology follow-up and lives with her husband; accessibility for study visits is confirmed at screening.",
      evidence: [{ quote: "SH: retired bookkeeper, lives w/ husband, never smoker, rare EtOH.", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT06517212-inc-13",
      status: "pass",
      confidence: "low",
      rationale: "Written informed consent is obtained at screening; she is keen to hear about trials.",
      evidence: [{ quote: "Pt keen to hear about trials before deciding -> research coordinator.", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT06517212-exc-1",
      status: "pass",
      confidence: "medium",
      rationale: "Surgical history lists only a left knee replacement (2019) and the right mastectomy (5/2026); no bariatric or endoscopic weight-loss procedure.",
      evidence: [{ quote: "PSH: L TKA 2019. R MRM 5/2026.", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT06517212-exc-2",
      status: "pass",
      confidence: "medium",
      rationale: "Her medication list (letrozole, apixaban, metoprolol, amlodipine, atorvastatin, calcium/vitamin D) contains no GLP-1, GIP or glucagon receptor agonist.",
    },
    {
      id: "NCT06517212-exc-3",
      status: "pass",
      confidence: "medium",
      rationale: "Her only recorded allergy is lisinopril (cough), and no prior GLP-1-class exposure appears in the record.",
      evidence: [{ quote: "ALLERGIES: lisinopril (cough)", source: "Allergies" }],
    },
    {
      id: "NCT06517212-exc-4",
      status: "pass",
      confidence: "medium",
      rationale: "No diabetes appears in her past medical history and no insulin or other glucose-lowering drug is on her medication list.",
    },
    {
      id: "NCT06517212-exc-5",
      status: "pass",
      confidence: "medium",
      rationale: "She has no recorded diabetes, so diabetic retinopathy is not expected; none is documented.",
    },
    {
      id: "NCT06517212-exc-6",
      status: "pass",
      rationale: "Staging CT and bone scan (5/21/26) were negative, and on 9/25/26 she is NED without bone pain, cough or headache.",
      evidence: [
        { quote: "No evidence of distant metastatic disease.", source: "Staging CT + bone scan 2026-05-21" },
        { quote: "No bone pain, cough, HA.", source: "Oncology note 2026-09-25" },
      ],
    },
    {
      id: "NCT06517212-exc-7",
      status: "pass",
      confidence: "medium",
      rationale: "No invasive cancer other than this breast cancer is recorded in her past medical history.",
    },
    {
      id: "NCT06517212-exc-8",
      status: "pass",
      confidence: "medium",
      rationale: "Single right-sided HR+/HER2-negative primary; the left breast has no masses on examination and no second primary is recorded.",
      evidence: [{ quote: "L breast no masses.", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT06517212-exc-9",
      status: "pass",
      confidence: "medium",
      rationale: "No active infection or antimicrobial therapy is recorded at the 9/25/26 visit; WBC 4.4 on 9/23/26.",
    },
    {
      id: "NCT06517212-exc-10",
      status: "unknown",
      confidence: "low",
      rationale: "HIV, hepatitis B and hepatitis C status are not documented in the record.",
      actionNeeded: "Obtain HIV test, HBsAg, anti-HBc and HCV antibody (HCV RNA if positive); active or persistent infection excludes",
    },
    {
      id: "NCT06517212-exc-11",
      status: "pass",
      confidence: "medium",
      rationale: "Paroxysmal AF is rate-controlled (sinus rhythm 9/21/26) and LVEF 52% without wall-motion abnormality; no stroke, MI, coronary event or heart failure is recorded.",
      evidence: [
        { quote: "ECHO 05/28/2026: LVEF 52% (low-normal), mild LA enlargement, no WMA.", source: "Echocardiogram 2026-05-28" },
        { quote: "paroxysmal AF (dx 2021) on apixaban, rate controlled on metoprolol", source: "Oncology note 2026-09-25" },
      ],
    },
    {
      id: "NCT06517212-exc-12",
      status: "pass",
      confidence: "medium",
      rationale: "No history of tuberculosis is recorded, and the 5/21/26 staging CT chest impression notes only post-mastectomy and degenerative spine changes.",
    },
    {
      id: "NCT06517212-exc-13",
      status: "not-applicable",
      rationale: "She is 72 and postmenopausal since about age 50, so pregnancy, lactation and contraception rules do not apply.",
      evidence: [{ quote: "72 yo postmenopausal F (menopause ~50, no HRT)", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT06517212-exc-14",
      status: "pass",
      confidence: "medium",
      rationale: "Never smoker with clear lungs, normal liver tests (AST 22, ALT 18, bilirubin 0.6) and no GI disease, gastroparesis or bowel surgery recorded.",
      evidence: [
        { quote: "Lungs clear.", source: "Oncology note 2026-09-25" },
        { quote: "AST 22 | ALT 18 | T bili 0.6", source: "Labs 2026-09-23" },
      ],
    },
    {
      id: "NCT06517212-exc-15",
      status: "pass",
      confidence: "medium",
      rationale: "No pancreatitis or gallstone disease appears in her history, and the 5/21/26 CT abdomen reported only degenerative spine changes.",
      evidence: [{ quote: "Mild degenerative changes of the spine.", source: "Staging CT 2026-05-21" }],
    },
    {
      id: "NCT06517212-exc-16",
      status: "pass",
      confidence: "medium",
      rationale: "The family history records only her sister's breast cancer at 66; no MEN 2 or medullary thyroid cancer is mentioned.",
      evidence: [{ quote: "FHx: sister breast ca at 66.", source: "Oncology note 2026-09-25" }],
      actionNeeded: "Confirm no family history of MEN 2 or medullary thyroid cancer",
    },
    {
      id: "NCT06517212-exc-17",
      status: "pass",
      confidence: "low",
      rationale: "Treating physician's judgment; her comorbidities (AF on apixaban, CKD 3a, osteopenia on an aromatase inhibitor) are stable, though intentional weight loss at 72 with osteopenia merits a bone-health discussion.",
      evidence: [{ quote: "osteopenia (DEXA 2025 T-score -2.1)", source: "Oncology note 2026-09-25" }],
      actionNeeded: "Treating physician to confirm trial participation is in her best interest",
    },
    {
      id: "NCT06517212-exc-18",
      status: "pass",
      confidence: "medium",
      rationale: "All prior therapy is standard (adjuvant TC, letrozole, radiation); no investigational agent is recorded.",
    },
    {
      id: "NCT06517212-exc-19",
      status: "pass",
      confidence: "medium",
      rationale: "Letrozole and the planned zoledronic acid are permitted; radiation ends about 10/20/26, and any adjuvant abemaciclib or ribociclib would have to be finished before entry rather than given alongside tirzepatide.",
      evidence: [{ quote: "zoledronic acid 4 mg IV q6 mo - PLANNED after RT", source: "Medication list" }],
      actionNeeded: "Confirm no CDK4/6 inhibitor or other anti-cancer therapy would run concurrently with study treatment",
    },
  ],
);
