import { demoMatch } from "../../match-helpers";

export default demoMatch(
  "NCT05868226",
  "pAF on metoprolol meets the arrhythmia exclusion · CrCl ≈ 50 mL/min bars small-molecule arms",
  "PRE-ISPY is a phase I/II platform whose general criteria admit patients at high risk of recurrence after curative-intent therapy; arm-specific criteria are not listed, so the arm Helen would enter (and whether it needs ctDNA positivity — Signatera has not been sent) is undetermined. She meets most general criteria: ECOG 1, adequate counts and liver tests, no CNS disease, chemotherapy completed 8/19/26. The main obstacle is GEC5: paroxysmal AF on metoprolol and apixaban is a cardiac arrhythmia requiring medication and would need a chaperone waiver. Her calculated CrCl of about 50 mL/min also rules out small-molecule arms, and IMP could not start before about 11/3/26, two weeks after radiotherapy ends.",
  [
    {
      id: "NCT05868226-inc-1",
      status: "pass",
      confidence: "low",
      rationale: "Consent is obtained at screening; the archival tissue requirement can be met, as the 5/12/26 mastectomy blocks are documented as available.",
      evidence: [{ quote: "MRM blocks available.", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT05868226-inc-2",
      status: "pass",
      rationale: "Age 72 (born 1954), well above the 18-year minimum.",
      evidence: [{ quote: "72 yo postmenopausal F", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT05868226-inc-3",
      status: "pass",
      rationale: "Female; the platform enrolls both sexes regardless of menopausal status.",
      evidence: [{ quote: "72 yo postmenopausal F", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT05868226-inc-4",
      status: "pass",
      rationale: "ECOG 1 at the 9/25/26 visit, within the required 0–2.",
      evidence: [{ quote: "EXAM: ECOG 1.", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT05868226-inc-5",
      status: "pass",
      confidence: "medium",
      rationale: "No evidence of disease after mastectomy and adjuvant TC for stage IIIA cancer, with ECOG 1; life expectancy is far beyond 12 weeks, though not formally stated.",
      evidence: [{ quote: "s/p MRM + adj TC x4, on PMRT + letrozole. NED.", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT05868226-inc-6",
      status: "unknown",
      confidence: "medium",
      rationale: "Labs 9/23/26 meet the count and liver limits (ANC 2.3, Plt 201, Hgb 11.1 with no transfusion recorded, bilirubin 0.6, AST 22/ALT 18). Cockcroft-Gault CrCl ≈ 50 mL/min (age 72, 68 kg, Cr 1.1) clears the >30 mL/min antibody threshold but not ≥60 mL/min for small molecules; arm undetermined.",
      evidence: [
        { quote: "ANC 2.3 | Hgb 11.1 (L) | Plt 201", source: "Labs 2026-09-23" },
        { quote: "Cr 1.1 | eGFR 49 (L)", source: "Labs 2026-09-23" },
        { quote: "AST 22 | ALT 18 | T bili 0.6", source: "Labs 2026-09-23" },
      ],
      actionNeeded: "Repeat CBC/CMP within 30 days of IMP start and confirm the arm: CrCl ≥ 60 mL/min needed for small molecules, > 30 mL/min for antibodies",
    },
    {
      id: "NCT05868226-inc-7",
      status: "not-applicable",
      rationale: "Explanatory note to GIC6 (laboratory cut-offs may be modified for specific regimens) rather than a separate requirement; nothing to assess beyond GIC6.",
    },
    {
      id: "NCT05868226-inc-8",
      status: "not-applicable",
      rationale: "Postmenopausal since about age 50 (now 72, no HRT), so pregnancy testing is not required; the sperm-donation clause applies to men.",
      evidence: [{ quote: "72 yo postmenopausal F (menopause ~50, no HRT)", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT05868226-inc-9",
      status: "not-applicable",
      rationale: "Contraception applies to women of childbearing potential and men; she is 72 and postmenopausal since about age 50.",
      evidence: [{ quote: "72 yo postmenopausal F (menopause ~50, no HRT)", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT05868226-inc-10",
      status: "pass",
      confidence: "medium",
      rationale: "Current toxicities are within limits: grade 1 fingertip neuropathy (≤2 allowed), grade 1 radiation erythema, Hgb 11.1 and a healed mastectomy scar. PMRT continues to 10/20/26, so skin toxicity must be rechecked once it ends.",
      evidence: [
        { quote: "G1 PN fingertps (numbness, buttons ok)", source: "Oncology note 2026-09-25" },
        { quote: "MRM scar healed, G1 RT erythema", source: "Oncology note 2026-09-25" },
      ],
      actionNeeded: "Reassess radiation dermatitis after PMRT ends (10/20/26); must be grade ≤1 before IMP start",
    },
    {
      id: "NCT05868226-inc-11",
      status: "pass",
      confidence: "low",
      rationale: "Willingness and ability to comply with visits and procedures is confirmed at screening; she is keen to hear about trials and lives at home with her husband.",
      evidence: [{ quote: "Pt keen to hear about trials before deciding", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT05868226-exc-1",
      status: "pass",
      confidence: "medium",
      rationale: "Last chemotherapy 8/19/26 (C4 of 4; the 'TC C3 today' line in the 9/25 plan is a stale copy-forward), 40 days ago, beyond the 3-week washout; letrozole needs none. PMRT ends 10/20/26, so the 2-week RT washout puts the earliest IMP start at about 11/3/26.",
      evidence: [
        { quote: "docetaxel + cyclophosphamide - COMPLETED 8/19/2026 (C4 of 4)", source: "Medication list" },
        { quote: "PMRT (chest wall + RNI) started 9/14/26, planned completion 10/20/26.", source: "Oncology note 2026-09-25" },
      ],
      actionNeeded: "Schedule IMP start no earlier than 2 weeks after the last RT fraction (planned 10/20/26, so on or after 11/3/26)",
    },
    {
      id: "NCT05868226-exc-2",
      status: "pass",
      confidence: "medium",
      rationale: "No investigational product on the medication list; current anticancer therapy is standard letrozole plus PMRT.",
      evidence: [{ quote: "letrozole 2.5 mg PO daily (started 9/8/2026)", source: "Medication list" }],
    },
    {
      id: "NCT05868226-exc-3",
      status: "pass",
      confidence: "medium",
      rationale: "She has never received any platform agent (T-DXd, zanidatamab, tucatinib, ALX148, TTX-MC138); the only recorded allergy is lisinopril cough, and docetaxel was completed without a reported reaction.",
      evidence: [{ quote: "ALLERGIES: lisinopril (cough)", source: "Allergies" }],
    },
    {
      id: "NCT05868226-exc-4",
      status: "pass",
      confidence: "medium",
      rationale: "No active infection, diabetes, adrenal insufficiency, PE or recent stroke recorded; CKD 3a is stable and BP 136/78 on amlodipine. The 2019 DVT was provoked and fully treated, not a pulmonary embolism.",
      evidence: [
        { quote: "CKD 3a stable.", source: "Oncology note 2026-09-25" },
        { quote: "provoked DVT L leg 2019 after L TKA, completed 3 mo anticoagulation", source: "Oncology note 2026-09-25" },
      ],
    },
    {
      id: "NCT05868226-exc-5",
      status: "fail",
      confidence: "medium",
      rationale: "Paroxysmal AF on metoprolol and apixaban is a 'cardiac arrhythmia requiring medication', which this criterion lists as clinically significant. QTcF 448 ms (<470), BP 136/78 and LVEF 52% without CHF are otherwise acceptable; rate-controlled pAF in sinus rhythm would need a waiver.",
      evidence: [
        { quote: "paroxysmal AF (dx 2021) on apixaban, rate controlled on metoprolol", source: "Oncology note 2026-09-25" },
        { quote: "ECG 09/21/2026: sinus rhythm 64, QTcF 448 ms.", source: "ECG 2026-09-21" },
      ],
      actionNeeded: "Ask the study chaperone whether rate-controlled paroxysmal AF in sinus rhythm is acceptable for the chosen arm",
    },
    {
      id: "NCT05868226-exc-6",
      status: "pass",
      confidence: "medium",
      rationale: "Early-stage disease with negative staging CT and no headache or neurological symptoms; no CNS disease recorded (brain imaging not indicated).",
      evidence: [{ quote: "No bone pain, cough, HA.", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT05868226-exc-7",
      status: "pass",
      confidence: "medium",
      rationale: "No liver disease, hepatitis or cirrhosis in the history; AST 22, ALT 18 and bilirubin 0.6 on 9/23/26 are normal, and alcohol use is rare.",
      evidence: [
        { quote: "AST 22 | ALT 18 | T bili 0.6", source: "Labs 2026-09-23" },
        { quote: "never smoker, rare EtOH", source: "Oncology note 2026-09-25" },
      ],
      actionNeeded: "Check hepatitis B/C serology if the selected arm requires it",
    },
    {
      id: "NCT05868226-exc-8",
      status: "pass",
      rationale: "Last major surgery was the right mastectomy on 5/12/26, about 4.5 months ago, well outside the 4-week window.",
      evidence: [{ quote: "R MRM 5/12/26", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT05868226-exc-9",
      status: "not-applicable",
      rationale: "72 and postmenopausal since about age 50; pregnancy and breastfeeding do not apply.",
      evidence: [{ quote: "72 yo postmenopausal F (menopause ~50, no HRT)", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT05868226-exc-10",
      status: "pass",
      confidence: "medium",
      rationale: "Lives at home with her husband; no institutionalisation or legal order is recorded.",
      evidence: [{ quote: "lives w/ husband", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT05868226-exc-11",
      status: "pass",
      confidence: "low",
      rationale: "Nothing clearly precludes participation, but the investigator will weigh therapeutic apixaban, CKD 3a (eGFR 49) and low-normal LVEF 52% (5/28/26) against the chosen regimen.",
      evidence: [
        { quote: "Cr 1.1 | eGFR 49 (L)", source: "Labs 2026-09-23" },
        { quote: "ECHO 05/28/2026: LVEF 52% (low-normal), mild LA enlargement, no WMA.", source: "Echo 2026-05-28" },
      ],
      actionNeeded: "Investigator to review apixaban interactions and bleeding risk; repeat echo if a HER2-directed arm is chosen",
    },
    {
      id: "NCT05868226-exc-12",
      status: "pass",
      confidence: "medium",
      rationale: "No other malignancy in the history; this breast cancer, diagnosed on core biopsy 4/14/26, is the disease under study.",
    },
  ],
);
