import { demoMatch } from "../../match-helpers";

export default demoMatch(
  "NCT05318469",
  "Excluded: prior checkpoint inhibitor in the metastatic setting (first-line pembrolizumab)",
  "First-line pembrolizumab + gemcitabine/carboplatin for metastatic TNBC (12/2025 to 9/2026) is prior checkpoint-inhibitor therapy in the metastatic setting, which this trial excludes; the only exception is (neo)adjuvant ICI given at least a year earlier. Otherwise she would fit well: TNBC, progression after one metastatic line, ECOG 1, measurable disease and organ function within limits. PD-L1 CPS 15 would also confine her to the Phase 1 cohort, as the Phase 2 expansion requires PD-L1-negative disease. Nothing in the record could reverse the ICI exclusion.",
  [
    {
      id: "NCT05318469-inc-1",
      status: "pass",
      rationale: "46 years old (born 1980).",
      evidence: [{ quote: "46 yo premenopausal F", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT05318469-inc-2",
      status: "pass",
      rationale: "ECOG 1 at the 9/25/26 visit.",
      evidence: [{ quote: "EXAM: ECOG 1.", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT05318469-inc-3",
      status: "pass",
      confidence: "medium",
      rationale: "ECOG 1, working part-time, with low-volume visceral disease and normal bilirubin; a life expectancy over 3 months is very likely.",
      evidence: [{ quote: "G1 fatigue, works part-time from home.", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT05318469-inc-4",
      status: "pass",
      rationale: "Histologically confirmed metastatic TNBC: ER 0%, PR 0%, HER2 IHC 0 on the RLL metastasis (11/20/25), concordant with the breast core.",
      evidence: [
        { quote: "ER 0%/PR 0%/HER2 IHC 0 (TNBC, not HER2-low)", source: "Oncology note 2026-09-25" },
        { quote: "Metastatic carcinoma, c/w breast primary (GATA3+, TTF-1 neg).", source: "Pathology 2025-11-25" },
      ],
    },
    {
      id: "NCT05318469-inc-5",
      status: "pass",
      rationale: "Progressed on one metastatic line (gemcitabine/carboplatin with pembrolizumab) on CT 9/15/26, within the 1–2 lines required.",
      evidence: [{ quote: "PD on 1L pembro + gem/carbo after ~9 mo.", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT05318469-inc-6",
      status: "pass",
      rationale: "Measurable disease: liver segment VI 2.1 cm and RLL nodule 1.8 cm on CT 9/15/26.",
      evidence: [{ quote: "Measurable dz: liver seg VI 2.1 cm, RLL 1.8 cm.", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT05318469-inc-7",
      status: "pass",
      rationale: "Residual toxicities are all grade ≤ 2: G1 fatigue, G1 transaminase rise, G2 chemotherapy anemia (Hgb 9.8) and G2 hypothyroidism on levothyroxine.",
      evidence: [
        { quote: "G1 fatigue, works part-time from home.", source: "Oncology note 2026-09-25" },
        { quote: "Anemia (chemo-related): Hgb 9.8, no bleeding.", source: "Oncology note 2026-09-25" },
      ],
    },
    {
      id: "NCT05318469-inc-8",
      status: "pass",
      confidence: "medium",
      rationale: "PD-L1 is positive (22C3 CPS 15), so she could only enter the Phase 1 safety cohort, which accepts any PD-L1 status; the Phase 2 expansion would be closed to her.",
      evidence: [{ quote: "PD-L1 IHC (22C3 pharmDx): CPS 15", source: "Pathology 2025-11-25" }],
    },
    {
      id: "NCT05318469-inc-9",
      status: "unknown",
      confidence: "low",
      rationale: "Blood counts, liver and renal values on 9/23/26 meet the listed thresholds, but coagulation tests and an echocardiogram (LVEF) are not on file.",
      actionNeeded: "Obtain INR/PT, aPTT (≤ 1.5 × ULN) and echocardiogram (LVEF ≥ 50%)",
    },
    {
      id: "NCT05318469-inc-10",
      status: "pass",
      rationale: "ANC 1.6 × 10⁹/L (1,600/mm³) on 9/23/26, just above the 1,500 threshold.",
      evidence: [{ quote: "ANC 1.6", source: "Labs 2026-09-23" }],
    },
    {
      id: "NCT05318469-inc-11",
      status: "pass",
      rationale: "Platelets 132 × 10⁹/L on 9/23/26.",
      evidence: [{ quote: "Plt 132 (L)", source: "Labs 2026-09-23" }],
    },
    {
      id: "NCT05318469-inc-12",
      status: "pass",
      rationale: "Hgb 9.8 g/dL on 9/23/26 without erythropoietin; last PRBC transfusion July 2026, more than 2 weeks before.",
      evidence: [
        { quote: "Hgb 9.8 (L)", source: "Labs 2026-09-23" },
        { quote: "1u PRBC 7/2026 for chemo-related anemia.", source: "Oncology note 2026-09-25" },
      ],
    },
    {
      id: "NCT05318469-inc-13",
      status: "pass",
      rationale: "Total bilirubin 0.9 mg/dL (normal) on 9/23/26.",
      evidence: [{ quote: "T bili 0.9", source: "Labs 2026-09-23" }],
    },
    {
      id: "NCT05318469-inc-14",
      status: "pass",
      rationale: "AST 58 (1.5 × ULN) with a liver metastasis, under the 3 × ULN limit that applies with liver involvement.",
      evidence: [{ quote: "AST 58 (H, 1.5x ULN)", source: "Labs 2026-09-23" }],
    },
    {
      id: "NCT05318469-inc-15",
      status: "pass",
      rationale: "ALT 61 (1.5 × ULN) with a liver metastasis, under the 3 × ULN limit that applies with liver involvement.",
      evidence: [{ quote: "ALT 61 (H, 1.5x ULN)", source: "Labs 2026-09-23" }],
    },
    {
      id: "NCT05318469-inc-16",
      status: "pass",
      rationale: "Creatinine 0.7 mg/dL on 9/23/26, within 1.5 × ULN.",
      evidence: [{ quote: "Cr 0.7", source: "Labs 2026-09-23" }],
    },
    {
      id: "NCT05318469-inc-17",
      status: "unknown",
      rationale: "No INR/PT or aPTT in the record; she is not anticoagulated.",
      actionNeeded: "Obtain INR/PT and aPTT; ≤ 1.5 × ULN required",
    },
    {
      id: "NCT05318469-inc-18",
      status: "unknown",
      rationale: "No echocardiogram on file; no prior anthracycline or cardiac history.",
      evidence: [{ quote: "No echo or ECG on file; order if trial requires.", source: "Oncology note 2026-09-25" }],
      actionNeeded: "Obtain echocardiogram; LVEF ≥ 50% required",
    },
    {
      id: "NCT05318469-inc-19",
      status: "unknown",
      confidence: "low",
      rationale: "Premenopausal with tubal ligation, so a pregnancy test is required; none on file.",
      evidence: [{ quote: "46 yo premenopausal F (s/p BTL 2014)", source: "Oncology note 2026-09-25" }],
      actionNeeded: "Obtain urine or serum pregnancy test at screening; must be negative",
    },
    {
      id: "NCT05318469-inc-20",
      status: "not-applicable",
      rationale: "Male contraception requirement; she is female.",
    },
    {
      id: "NCT05318469-inc-21",
      status: "pass",
      confidence: "low",
      rationale: "Bilateral tubal ligation (2014) counts as effective contraception; not-pregnant and not-breastfeeding status is confirmed at screening.",
      evidence: [{ quote: "46 yo premenopausal F (s/p BTL 2014)", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT05318469-inc-22",
      status: "pass",
      confidence: "low",
      rationale: "Interested in trials and able to consent; compliance is assessed at screening.",
      evidence: [{ quote: "Pt interested in trials, hopes to start within 3-4 wks.", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT05318469-exc-1",
      status: "pass",
      confidence: "medium",
      rationale: "No immunodeficiency (HIV negative) and no steroids or immunosuppressants on the medication list.",
    },
    {
      id: "NCT05318469-exc-2",
      status: "not-applicable",
      rationale: "Section heading for the prohibited-therapy exclusions that follow; each is assessed separately.",
    },
    {
      id: "NCT05318469-exc-3",
      status: "pass",
      confidence: "medium",
      rationale: "Last gem/carbo 8/26/26 and last pembrolizumab 9/2/26 (stopped for progression; the 'C9 D1 today' line is stale), so the 28-day window closes 9/30/26, before any realistic Day 1.",
      evidence: [
        { quote: "Pembro deferred 1 wk for AST/ALT ~2x ULN (HBV DNA neg), last dose 9/2/26.", source: "Oncology note 2026-09-25" },
        { quote: "All tx on hold since.", source: "Oncology note 2026-09-25" },
      ],
    },
    {
      id: "NCT05318469-exc-4",
      status: "fail",
      rationale: "Received pembrolizumab, a PD-1 inhibitor, for metastatic TNBC from 12/2025 to 9/2/26; the exception covers only (neo)adjuvant use.",
      evidence: [
        { quote: "1L pembrolizumab + gemcitabine/carboplatin (KEYNOTE-355) started 12/2025", source: "Oncology note 2026-09-25" },
        { quote: "pembrolizumab + gemcitabine/carboplatin - DISCONTINUED 9/2026 (PD)", source: "Medication list" },
      ],
    },
    {
      id: "NCT05318469-exc-5",
      status: "pass",
      confidence: "medium",
      rationale: "No radiotherapy is documented in her treatment history.",
    },
    {
      id: "NCT05318469-exc-6",
      status: "pass",
      confidence: "low",
      rationale: "No vaccinations recorded; live vaccines would be unusual during chemo-immunotherapy, but this is confirmed at screening.",
      actionNeeded: "Confirm no live vaccine in the 30 days before first dose",
    },
    {
      id: "NCT05318469-exc-7",
      status: "pass",
      rationale: "Not on warfarin or any anticoagulant.",
    },
    {
      id: "NCT05318469-exc-8",
      status: "pass",
      confidence: "medium",
      rationale: "No investigational agent or device in the past 4 weeks; prior therapy was standard first-line treatment.",
    },
    {
      id: "NCT05318469-exc-9",
      status: "pass",
      confidence: "medium",
      rationale: "Takes oral levothyroxine and entecavir daily; ondansetron is as-needed and no ongoing nausea or vomiting is described in the 9/25 history.",
      evidence: [{ quote: "ondansetron 8 mg PO q8h prn nausea", source: "Medication list" }],
      actionNeeded: "Confirm no ongoing nausea or vomiting at screening",
    },
    {
      id: "NCT05318469-exc-10",
      status: "pass",
      confidence: "low",
      rationale: "Bilateral tubal ligation (2014) and no pregnancy or breastfeeding recorded; confirmed at screening.",
      evidence: [{ quote: "46 yo premenopausal F (s/p BTL 2014)", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT05318469-exc-11",
      status: "pass",
      confidence: "medium",
      rationale: "Tolerated about 9 months of pembrolizumab without a recorded reaction; never received ivermectin or balstilimab; only listed allergy is penicillin.",
      evidence: [{ quote: "ALLERGIES: penicillin (hives)", source: "Allergies" }],
    },
    {
      id: "NCT05318469-exc-12",
      status: "pass",
      confidence: "medium",
      rationale: "No other prior malignancy recorded in the history or problem list.",
    },
    {
      id: "NCT05318469-exc-13",
      status: "pass",
      confidence: "medium",
      rationale: "No known CNS metastases: baseline MRI 11/18/25 negative and neurologically asymptomatic, though brain imaging is about 10 months old.",
      evidence: [
        { quote: "MRI BRAIN 11/18/2025 (baseline): no intracranial metastases.", source: "MRI brain 2025-11-18" },
        { quote: "No brain imaging since baseline 11/2025; asymptomatic.", source: "Oncology note 2026-09-25" },
      ],
    },
    {
      id: "NCT05318469-exc-14",
      status: "pass",
      rationale: "No pneumonitis on pembrolizumab, and CT 9/15/26 shows no interstitial lung disease or pneumonitis.",
      evidence: [{ quote: "No interstitial lung disease or pneumonitis.", source: "CT CAP 2026-09-15" }],
    },
    {
      id: "NCT05318469-exc-15",
      status: "pass",
      confidence: "medium",
      rationale: "Entecavir is prophylaxis for resolved hepatitis B (HBV DNA not detected 8/28/26), not treatment of an active infection; no other infection recorded.",
      evidence: [{ quote: "HBV (anti-HBc+, HBsAg neg): entecavir ppx, HBV DNA undetectable 8/2026.", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT05318469-exc-16",
      status: "pass",
      rationale: "HIV Ag/Ab negative in December 2025.",
      evidence: [{ quote: "Serologies 12/2025: HBsAg neg, anti-HBc POS, HCV Ab neg, HIV Ag/Ab neg", source: "Labs" }],
    },
    {
      id: "NCT05318469-exc-17",
      status: "pass",
      rationale: "HBsAg negative (hepatitis B is defined here as HBsAg reactive) and HCV antibody negative; anti-HBc positivity with undetectable DNA does not meet the definition.",
      evidence: [{ quote: "Serologies 12/2025: HBsAg neg, anti-HBc POS, HCV Ab neg, HIV Ag/Ab neg", source: "Labs" }],
    },
    {
      id: "NCT05318469-exc-18",
      status: "pass",
      confidence: "medium",
      rationale: "No tuberculosis history in the record; lungs clear.",
    },
    {
      id: "NCT05318469-exc-19",
      status: "pass",
      confidence: "low",
      rationale: "No high-risk intercurrent condition evident (no cardiac history, no diabetes, controlled thyroid); investigator's judgment.",
    },
    {
      id: "NCT05318469-exc-20",
      status: "pass",
      confidence: "low",
      rationale: "No confounding condition evident in the record; final judgment rests with the investigator.",
    },
    {
      id: "NCT05318469-exc-21",
      status: "pass",
      confidence: "medium",
      rationale: "No psychiatric or substance-use disorder recorded; never smoker.",
      evidence: [{ quote: "SH: accountant, 2 kids, never smoker.", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT05318469-exc-22",
      status: "pass",
      confidence: "low",
      rationale: "Tubal ligation (2014); no pregnancy, breastfeeding or plans to conceive recorded. Confirmed at screening.",
      evidence: [{ quote: "46 yo premenopausal F (s/p BTL 2014)", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT05318469-exc-23",
      status: "pass",
      confidence: "medium",
      rationale: "No allogeneic tissue or solid organ transplant in the history.",
    },
    {
      id: "NCT05318469-exc-24",
      status: "pass",
      rationale: "No cardiac history: no heart failure, angina, myocardial infarction, stroke or arrhythmia recorded.",
      evidence: [{ quote: "No DM, no cardiac hx.", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT05318469-exc-25",
      status: "unknown",
      rationale: "No urinalysis or urine protein result in the record.",
      actionNeeded: "Obtain urine dipstick; ≤ 1+ protein required, or 24-h urine protein < 1 g",
    },
    {
      id: "NCT05318469-exc-26",
      status: "pass",
      rationale: "No autoimmune disease before pembrolizumab; immune-related hypothyroidism on levothyroxine is replacement therapy, which is allowed.",
      evidence: [
        { quote: "No autoimmune dz prior to pembro.", source: "Oncology note 2026-09-25" },
        { quote: "irAE hypothyroidism G2: levothyroxine 88 mcg, TSH 2.2, continue.", source: "Oncology note 2026-09-25" },
      ],
    },
    {
      id: "NCT05318469-exc-27",
      status: "pass",
      confidence: "low",
      rationale: "No safety contraindication to study procedures evident; investigator's judgment at screening.",
    },
  ],
);
