import { demoMatch } from "../../match-helpers";

export default demoMatch(
  "NCT07078604",
  "Excluded: PD-L1 positive (CPS 15) and prior pembrolizumab for metastatic disease",
  "This vaccine trial is for PD-L1-negative metastatic TNBC with no prior immunotherapy in the metastatic setting. Her RLL metastasis is PD-L1 positive on 22C3 (CPS 15), and she received first-line pembrolizumab with gemcitabine/carboplatin, so three criteria exclude her outright. Line count (one prior metastatic line), subtype, ECOG and washout would otherwise fit, but no plausible new finding changes the outcome: even PD-L1-negative retesting of the liver lesion would leave the prior-immunotherapy exclusion in place.",
  [
    {
      id: "NCT07078604-inc-1",
      status: "pass",
      rationale: "46 years old (born 1980).",
      evidence: [{ quote: "46 yo premenopausal F", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT07078604-inc-2",
      status: "pass",
      rationale: "ECOG 1 at the 9/25/26 visit, within ECOG ≤ 2.",
      evidence: [{ quote: "EXAM: ECOG 1.", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT07078604-inc-3",
      status: "pass",
      rationale: "ER 0%, PR 0% and HER2 IHC 0 on the RLL metastasis and breast core (November 2025): triple-negative by ASCO/CAP.",
      evidence: [
        { quote: "ER 0%/PR 0%/HER2 IHC 0 (TNBC, not HER2-low)", source: "Oncology note 2026-09-25" },
        { quote: "HER2 IHC: 0 (no staining observed) - not HER2-low", source: "Pathology 2025-11-25" },
      ],
    },
    {
      id: "NCT07078604-inc-4",
      status: "fail",
      rationale: "PD-L1 is positive on 22C3 pharmDx (CPS 15, RLL metastasis 11/20/25), above the CPS ≥ 10 threshold used in metastatic TNBC.",
      evidence: [
        { quote: "PD-L1 IHC (22C3 pharmDx): CPS 15", source: "Pathology 2025-11-25" },
        { quote: "RLL nodule bx 11/20/25 c/w met TNBC, PD-L1 (22C3) CPS 15.", source: "Oncology note 2026-09-25" },
      ],
    },
    {
      id: "NCT07078604-inc-5",
      status: "pass",
      rationale: "Measurable metastatic disease on CT 9/15/26: liver segment VI 2.1 cm and RLL nodule 1.8 cm, neither irradiated.",
      evidence: [{ quote: "Measurable dz: liver seg VI 2.1 cm, RLL 1.8 cm.", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT07078604-inc-6",
      status: "pass",
      confidence: "medium",
      rationale: "Unirradiated, biopsiable sites exist (2.1 cm liver lesion, palpable left breast mass) and she is open to liver biopsy; the treating oncologist confirms.",
      evidence: [{ quote: "Archival tissue available (RLL core bx 11/2025); open to liver bx if needed.", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT07078604-inc-7",
      status: "fail",
      rationale: "Received pembrolizumab, a cancer immunotherapy, for metastatic disease from 12/2025 to 9/2/26.",
      evidence: [
        { quote: "1L pembrolizumab + gemcitabine/carboplatin (KEYNOTE-355) started 12/2025", source: "Oncology note 2026-09-25" },
        { quote: "pembrolizumab + gemcitabine/carboplatin - DISCONTINUED 9/2026 (PD)", source: "Medication list" },
      ],
    },
    {
      id: "NCT07078604-inc-8",
      status: "pass",
      rationale: "Permissive clause on prior ADCs; she is ADC-naive.",
      evidence: [{ quote: "No prior taxane, anthracycline, ADC or PARP inhibitor.", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT07078604-inc-9",
      status: "pass",
      confidence: "medium",
      rationale: "Second-line chemotherapy is being planned for her; ECOG 1 with adequate counts and organ function make her a standard-chemotherapy candidate.",
      evidence: [{ quote: "EXAM: ECOG 1.", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT07078604-inc-10",
      status: "pass",
      rationale: "Permissive clause on prior (neo)adjuvant chemotherapy; she presented de novo metastatic and had none.",
    },
    {
      id: "NCT07078604-inc-11",
      status: "pass",
      rationale: "Last pembrolizumab 9/2/26 (26 days) and gem/carbo 8/26/26 (33 days), beyond 14 days; no radiotherapy. Therapy on hold since the 9/15 CT despite the stale 'C9 D1 today' line.",
      evidence: [
        { quote: "Pembro deferred 1 wk for AST/ALT ~2x ULN (HBV DNA neg), last dose 9/2/26.", source: "Oncology note 2026-09-25" },
        { quote: "All tx on hold since.", source: "Oncology note 2026-09-25" },
      ],
    },
    {
      id: "NCT07078604-inc-12",
      status: "pass",
      rationale: "On denosumab 120 mg every 4 weeks for bone metastases, which the protocol allows to continue.",
      evidence: [{ quote: "denosumab 120 mg SC q4 weeks", source: "Medication list" }],
    },
    {
      id: "NCT07078604-inc-13",
      status: "pass",
      confidence: "medium",
      rationale: "No systemic steroids on the medication list; any dexamethasone given with chemotherapy premedication is exempt.",
    },
    {
      id: "NCT07078604-inc-14",
      status: "pass",
      confidence: "medium",
      rationale: "No recent major infection or surgery and no significant active illness: hypothyroidism controlled, HBV DNA undetectable, no cardiac history.",
    },
    {
      id: "NCT07078604-inc-15",
      status: "pass",
      confidence: "low",
      rationale: "She is open to a liver biopsy; willingness for up to two on-study biopsies is confirmed at consent.",
      evidence: [{ quote: "Archival tissue available (RLL core bx 11/2025); open to liver bx if needed.", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT07078604-inc-16",
      status: "pass",
      rationale: "WBC 3.9 on 9/23/26, above 2.5.",
      evidence: [{ quote: "WBC 3.9 (L)", source: "Labs 2026-09-23" }],
    },
    {
      id: "NCT07078604-inc-17",
      status: "unknown",
      rationale: "Only WBC and ANC are reported on 9/23/26; no absolute lymphocyte count.",
      actionNeeded: "Obtain CBC with differential within 28 days of first vaccine; lymphocytes ≥ 0.5 × 10³/µL required",
    },
    {
      id: "NCT07078604-inc-18",
      status: "pass",
      rationale: "ANC 1.6 on 9/23/26, above 1.0.",
      evidence: [{ quote: "ANC 1.6", source: "Labs 2026-09-23" }],
    },
    {
      id: "NCT07078604-inc-19",
      status: "pass",
      rationale: "Hemoglobin 9.8 g/dL on 9/23/26.",
      evidence: [{ quote: "Hgb 9.8 (L)", source: "Labs 2026-09-23" }],
    },
    {
      id: "NCT07078604-inc-20",
      status: "pass",
      rationale: "Platelets 132 on 9/23/26, above 75.",
      evidence: [{ quote: "Plt 132 (L)", source: "Labs 2026-09-23" }],
    },
    {
      id: "NCT07078604-inc-21",
      status: "pass",
      rationale: "Total bilirubin 0.9 mg/dL (normal) on 9/23/26.",
      evidence: [{ quote: "T bili 0.9", source: "Labs 2026-09-23" }],
    },
    {
      id: "NCT07078604-inc-22",
      status: "unknown",
      confidence: "medium",
      rationale: "AST 58 and ALT 61 are reported as 1.5 × ULN, exactly at this trial's limit (no liver-metastasis allowance); the precise ratio depends on the lab ULN, and they were ~2 × ULN in August.",
      evidence: [
        { quote: "AST 58 (H, 1.5x ULN)", source: "Labs 2026-09-23" },
        { quote: "ALT 61 (H, 1.5x ULN)", source: "Labs 2026-09-23" },
      ],
      actionNeeded: "Repeat AST/ALT with the lab's ULN within 28 days of first vaccine; each must be ≤ 1.5 × ULN",
    },
    {
      id: "NCT07078604-inc-23",
      status: "pass",
      rationale: "Creatinine 0.7 mg/dL on 9/23/26, within 1.5 × ULN.",
      evidence: [{ quote: "Cr 0.7", source: "Labs 2026-09-23" }],
    },
    {
      id: "NCT07078604-inc-24",
      status: "unknown",
      confidence: "low",
      rationale: "Premenopausal, so a negative urine pregnancy test is required at screening (none on file); tubal ligation would be one of the two contraceptive methods.",
      evidence: [{ quote: "46 yo premenopausal F (s/p BTL 2014)", source: "Oncology note 2026-09-25" }],
      actionNeeded: "Obtain urine pregnancy test at screening; confirm agreement to a second contraceptive method alongside BTL",
    },
    {
      id: "NCT07078604-exc-1",
      status: "pass",
      rationale: "Exactly one prior metastatic line (pembrolizumab + gemcitabine/carboplatin), not more than one.",
      evidence: [{ quote: "PD on 1L pembro + gem/carbo after ~9 mo.", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT07078604-exc-2",
      status: "fail",
      rationale: "Tumor is PD-L1 positive on 22C3 pharmDx (CPS 15, RLL metastasis 11/20/25); no retesting since.",
      evidence: [
        { quote: "PD-L1 IHC (22C3 pharmDx): CPS 15", source: "Pathology 2025-11-25" },
        { quote: "Note: no re-biopsy at progression; receptor status per 2025 tissue.", source: "Pathology 2025-11-25" },
      ],
    },
    {
      id: "NCT07078604-exc-3",
      status: "pass",
      confidence: "medium",
      rationale: "Not enrolled in any interventional trial; prior treatment was standard therapy.",
    },
    {
      id: "NCT07078604-exc-4",
      status: "pass",
      rationale: "No cardiac history: no cardiomyopathy, angina, heart failure or pericardial effusion recorded.",
      evidence: [{ quote: "No DM, no cardiac hx.", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT07078604-exc-5",
      status: "pass",
      rationale: "Her only autoimmune condition is immune-related hypothyroidism on levothyroxine, with no chronic steroids or immunosuppressants.",
      evidence: [{ quote: "irAE hypothyroidism G2: levothyroxine 88 mcg, TSH 2.2, continue.", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT07078604-exc-6",
      status: "pass",
      confidence: "medium",
      rationale: "No GM-CSF exposure or known contraindication is recorded; her only listed allergy is penicillin.",
      evidence: [{ quote: "ALLERGIES: penicillin (hives)", source: "Allergies" }],
    },
    {
      id: "NCT07078604-exc-7",
      status: "pass",
      confidence: "medium",
      rationale: "No non-breast or B-cell malignancy is recorded.",
    },
    {
      id: "NCT07078604-exc-8",
      status: "pass",
      confidence: "low",
      rationale: "Tubal ligation (2014); no pregnancy or breastfeeding recorded. Confirmed at screening.",
      evidence: [{ quote: "46 yo premenopausal F (s/p BTL 2014)", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT07078604-exc-9",
      status: "pass",
      rationale: "HIV and HCV antibody negative; HBsAg negative with HBV DNA not detected (8/28/26), so not hepatitis B as defined here.",
      evidence: [
        { quote: "Serologies 12/2025: HBsAg neg, anti-HBc POS, HCV Ab neg, HIV Ag/Ab neg", source: "Labs" },
        { quote: "HBV DNA 08/28/2026: not detected", source: "Labs" },
      ],
    },
    {
      id: "NCT07078604-exc-10",
      status: "pass",
      confidence: "medium",
      rationale: "No major surgery recorded; only core biopsies in November 2025.",
    },
    {
      id: "NCT07078604-exc-11",
      status: "pass",
      confidence: "low",
      rationale: "A scheduling rule rather than a barrier; seasonal vaccines would need to be spaced 14 days from STEMVAC doses.",
      actionNeeded: "Time any influenza or COVID-19 vaccination at least 14 days from STEMVAC doses",
    },
    {
      id: "NCT07078604-exc-12",
      status: "pass",
      confidence: "low",
      rationale: "No interfering condition evident in the record; treating physician's judgment.",
    },
  ],
);
