import { demoMatch } from "../../match-helpers";

export default demoMatch(
  "NCT06249048",
  "Fits Phase 1, not the Phase 2 TNBC cohort (no prior taxane/anthracycline) · ECG and coags open",
  "Phase 1 (advanced solid tumor progressing after at least one line) is her route: she progressed on first-line pembrolizumab + gemcitabine/carboplatin and has injectable, biopsiable lesions in the palpable 2.5 cm left breast primary and the 2.1 cm liver metastasis. The Phase 2 TNBC cohort needs prior taxane and/or anthracycline, which she has never had. AST/ALT at 1.5 × ULN sit under this trial's strict < 2 × ULN cap, which has no liver-metastasis allowance; they reached ~2 × ULN in August, so recheck. Also needed: INR/aPTT, triplicate ECG (QTcF ≤ 470 ms), a β-hCG within 72 h, no vaccine within 30 days, and an open Phase 1 slot.",
  [
    {
      id: "NCT06249048-inc-1",
      status: "pass",
      rationale: "46 years old at screening (born 1980).",
      evidence: [{ quote: "46 yo premenopausal F", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT06249048-inc-2",
      status: "pass",
      confidence: "low",
      rationale: "Works as an accountant and is engaged in trial planning; capacity and signed consent are confirmed at screening.",
      evidence: [{ quote: "Pt interested in trials, hopes to start within 3-4 wks.", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT06249048-inc-3",
      status: "pass",
      rationale: "ECOG 1 at the 9/25/26 visit.",
      evidence: [{ quote: "EXAM: ECOG 1.", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT06249048-inc-4",
      status: "pass",
      confidence: "medium",
      rationale: "ECOG 1, working part-time, low-volume visceral disease and normal bilirubin make a life expectancy ≥ 12 weeks very likely; formally the investigator's estimate.",
      evidence: [{ quote: "G1 fatigue, works part-time from home.", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT06249048-inc-5",
      status: "pass",
      rationale: "Weight 68.4 kg on 9/25/26.",
      evidence: [{ quote: "Wt 68.4 kg.", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT06249048-inc-6",
      status: "pass",
      confidence: "medium",
      rationale: "No major surgery is recorded; the primary was never resected and her only procedures were core biopsies in November 2025.",
    },
    {
      id: "NCT06249048-inc-7",
      status: "pass",
      confidence: "low",
      rationale: "Willingness to give research blood samples is confirmed at consent; she has regular blood draws already.",
    },
    {
      id: "NCT06249048-inc-8",
      status: "pass",
      confidence: "medium",
      rationale: "Palpable 2.5 cm left breast mass and a 2.1 cm liver segment VI lesion are candidate injection/biopsy sites, and she is open to liver biopsy; suitability is the investigator's call.",
      evidence: [
        { quote: "L breast 2.5 cm UOQ mass.", source: "Oncology note 2026-09-25" },
        { quote: "Archival tissue available (RLL core bx 11/2025); open to liver bx if needed.", source: "Oncology note 2026-09-25" },
      ],
      actionNeeded: "Confirm with the investigator that the breast mass or liver lesion is suitable for injection and pre/post biopsy",
    },
    {
      id: "NCT06249048-inc-9",
      status: "pass",
      rationale: "ANC 1.6 × 10⁹/L, platelets 132 × 10⁹/L and Hgb 9.8 g/dL on 9/23/26, above 1,000, 75,000 and 8.0 respectively.",
      evidence: [{ quote: "WBC 3.9 (L) | ANC 1.6 | Hgb 9.8 (L) | Plt 132 (L)", source: "Labs 2026-09-23" }],
    },
    {
      id: "NCT06249048-inc-10",
      status: "pass",
      rationale: "Creatinine 0.7 mg/dL on 9/23/26, below 1.5 × ULN.",
      evidence: [{ quote: "Cr 0.7", source: "Labs 2026-09-23" }],
    },
    {
      id: "NCT06249048-inc-11",
      status: "unknown",
      rationale: "No PT/INR in the record; relevant before intratumoral injection and biopsy. She is not anticoagulated.",
      actionNeeded: "Obtain PT/INR; must be < 1.5 × ULN",
    },
    {
      id: "NCT06249048-inc-12",
      status: "unknown",
      rationale: "No aPTT in the record; she takes no anticoagulant.",
      actionNeeded: "Obtain aPTT; must be ≤ 1.5 × ULN",
    },
    {
      id: "NCT06249048-inc-13",
      status: "pass",
      rationale: "AST 58 and ALT 61 are 1.5 × ULN (under the < 2 × ULN cap, with no liver-metastasis allowance) and bilirubin is 0.9 mg/dL. Transaminases were ~2 × ULN in late August.",
      evidence: [
        { quote: "AST 58 (H, 1.5x ULN)", source: "Labs 2026-09-23" },
        { quote: "ALT 61 (H, 1.5x ULN)", source: "Labs 2026-09-23" },
        { quote: "Pembro deferred 1 wk for AST/ALT ~2x ULN (HBV DNA neg), last dose 9/2/26.", source: "Oncology note 2026-09-25" },
      ],
      actionNeeded: "Repeat LFTs at screening; AST and ALT must stay < 2 × ULN",
    },
    {
      id: "NCT06249048-inc-14",
      status: "pass",
      rationale: "Histologically documented metastatic breast carcinoma (RLL lung biopsy 11/20/25).",
      evidence: [{ quote: "Metastatic carcinoma, c/w breast primary (GATA3+, TTF-1 neg).", source: "Pathology 2025-11-25" }],
    },
    {
      id: "NCT06249048-inc-15",
      status: "pass",
      rationale: "Radiological progression on CT 9/15/26 (new liver lesion, RLL nodule 1.2 → 1.8 cm) after about 9 months of first-line pembrolizumab + gemcitabine/carboplatin.",
      evidence: [
        { quote: "New 2.1 cm hypoattenuating lesion in hepatic segment VI, consistent with metastasis.", source: "CT CAP 2026-09-15" },
        { quote: "PD on 1L pembro + gem/carbo after ~9 mo.", source: "Oncology note 2026-09-25" },
      ],
    },
    {
      id: "NCT06249048-inc-16",
      status: "not-applicable",
      rationale: "Phase 2 TNBC cohort criterion. She has metastatic TNBC but would enter Phase 1, because she lacks the prior taxane/anthracycline Phase 2 requires.",
    },
    {
      id: "NCT06249048-inc-17",
      status: "not-applicable",
      rationale: "Phase 2 TNBC cohort only. She would not meet it (no prior taxane or anthracycline), so she is assessed for Phase 1.",
      evidence: [{ quote: "No prior taxane, anthracycline, ADC or PARP inhibitor.", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT06249048-inc-18",
      status: "not-applicable",
      rationale: "Phase 2 only. She would enter Phase 1; she does have measurable disease beyond a single lesion (liver 2.1 cm, RLL 1.8 cm).",
    },
    {
      id: "NCT06249048-inc-19",
      status: "not-applicable",
      rationale: "Phase 2 melanoma cohort only; she has breast cancer.",
    },
    {
      id: "NCT06249048-inc-20",
      status: "not-applicable",
      rationale: "Phase 2 only; she would enter Phase 1.",
    },
    {
      id: "NCT06249048-inc-21",
      status: "not-applicable",
      rationale: "Phase 2 checkpoint-resistance requirement; she would enter Phase 1 (her response then progression on pembrolizumab would fit secondary resistance).",
    },
    {
      id: "NCT06249048-inc-22",
      status: "not-applicable",
      rationale: "Phase 2 only (repeat of the measurable-disease rule); she would enter Phase 1.",
    },
    {
      id: "NCT06249048-exc-1",
      status: "pass",
      confidence: "medium",
      rationale: "No primary immune deficiency in the history; HIV negative.",
    },
    {
      id: "NCT06249048-exc-2",
      status: "pass",
      rationale: "Her only autoimmune condition is immune-related hypothyroidism on levothyroxine, which is explicitly excepted; no immunosuppression.",
      evidence: [
        { quote: "irAE hypothyroidism G2: levothyroxine 88 mcg, TSH 2.2, continue.", source: "Oncology note 2026-09-25" },
        { quote: "No autoimmune dz prior to pembro.", source: "Oncology note 2026-09-25" },
      ],
    },
    {
      id: "NCT06249048-exc-3",
      status: "pass",
      rationale: "Highest immune-related AE was grade 2 hypothyroidism; no pneumonitis or colitis, and no immune hepatitis.",
      evidence: [{ quote: "irAE hypothyroidism G2 2/2026 -> levothyroxine; no pneumonitis/colitis.", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT06249048-exc-4",
      status: "pass",
      confidence: "medium",
      rationale: "No organ transplant and no immunosuppressive medication recorded.",
    },
    {
      id: "NCT06249048-exc-5",
      status: "unknown",
      rationale: "No cardiac history, so the event-based parts pass, but no ECG is on file for the QTcF ≤ 470 ms requirement; she takes ondansetron as needed.",
      evidence: [
        { quote: "No echo or ECG on file; order if trial requires.", source: "Oncology note 2026-09-25" },
        { quote: "No DM, no cardiac hx.", source: "Oncology note 2026-09-25" },
      ],
      actionNeeded: "Obtain triplicate 12-lead ECG; QTcF must be ≤ 470 ms",
    },
    {
      id: "NCT06249048-exc-6",
      status: "not-applicable",
      rationale: "Section heading only; the recent-medical-concern exclusions are listed and assessed individually below.",
    },
    {
      id: "NCT06249048-exc-7",
      status: "pass",
      confidence: "medium",
      rationale: "No radiotherapy is documented to any site, including the breast primary and liver lesion that could be injected.",
    },
    {
      id: "NCT06249048-exc-8",
      status: "pass",
      rationale: "No anticoagulant on the medication list (levothyroxine, entecavir, denosumab, ondansetron prn, calcium/vitamin D).",
    },
    {
      id: "NCT06249048-exc-9",
      status: "pass",
      confidence: "medium",
      rationale: "No active infection recorded; entecavir is prophylaxis for resolved hepatitis B, not IV antibiotic therapy.",
    },
    {
      id: "NCT06249048-exc-10",
      status: "pass",
      confidence: "medium",
      rationale: "Anemia is chemotherapy-related with no bleeding recorded, and no bleeding disorder is known; coagulation tests are pending.",
      evidence: [{ quote: "Anemia (chemo-related): Hgb 9.8, no bleeding.", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT06249048-exc-11",
      status: "pass",
      confidence: "medium",
      rationale: "No wound, fistula, ulcer or fracture recorded; bone lesions are sclerotic and unchanged on CT 9/15/26.",
      evidence: [{ quote: "Sclerotic (treated) T11 and left iliac lesions, unchanged.", source: "CT CAP 2026-09-15" }],
    },
    {
      id: "NCT06249048-exc-12",
      status: "pass",
      rationale: "HIV and HCV antibody negative; hepatitis B is resolved, not active (HBsAg negative, HBV DNA not detected 8/28/26 on entecavir).",
      evidence: [
        { quote: "Serologies 12/2025: HBsAg neg, anti-HBc POS, HCV Ab neg, HIV Ag/Ab neg", source: "Labs" },
        { quote: "HBV DNA 08/28/2026: not detected", source: "Labs" },
      ],
    },
    {
      id: "NCT06249048-exc-13",
      status: "pass",
      confidence: "medium",
      rationale: "Anti-HBc positive, so HBV DNA is required; it was not detected on 8/28/26. Serologies date from 12/2025 and will be repeated at screening.",
      evidence: [
        { quote: "Serologies 12/2025: HBsAg neg, anti-HBc POS, HCV Ab neg, HIV Ag/Ab neg", source: "Labs" },
        { quote: "HBV DNA 08/28/2026: not detected", source: "Labs" },
      ],
      actionNeeded: "Repeat HIV Ab, HBsAg, anti-HBc, HCV Ab and HBV DNA at screening; HBV DNA must remain undetectable",
    },
    {
      id: "NCT06249048-exc-14",
      status: "pass",
      confidence: "medium",
      rationale: "No known brain or epidural metastasis: baseline MRI 11/18/25 negative, neurologically asymptomatic with a nonfocal exam; brain imaging is about 10 months old.",
      evidence: [
        { quote: "MRI BRAIN 11/18/2025 (baseline): no intracranial metastases.", source: "MRI brain 2025-11-18" },
        { quote: "No HA, no visual chnages, no focal weakness.", source: "Oncology note 2026-09-25" },
      ],
      actionNeeded: "Consider screening brain MRI (last 11/18/2025)",
    },
    {
      id: "NCT06249048-exc-15",
      status: "pass",
      confidence: "medium",
      rationale: "Provision for treated brain metastases; she has none known (baseline MRI 11/18/25 negative, asymptomatic).",
      evidence: [{ quote: "No brain imaging since baseline 11/2025; asymptomatic.", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT06249048-exc-16",
      status: "pass",
      confidence: "medium",
      rationale: "No other primary malignancy is recorded; germline panel negative.",
    },
    {
      id: "NCT06249048-exc-17",
      status: "pass",
      confidence: "low",
      rationale: "No serious illness evident (no cardiac history, no diabetes, ECOG 1); investigator's judgment at screening.",
    },
    {
      id: "NCT06249048-exc-18",
      status: "pass",
      confidence: "low",
      rationale: "No condition evident that would confound evaluation; final judgment rests with the investigator.",
    },
    {
      id: "NCT06249048-exc-19",
      status: "pass",
      rationale: "No prior IL-12 therapy; her only anticancer treatment has been pembrolizumab + gemcitabine/carboplatin.",
      evidence: [{ quote: "pembrolizumab + gemcitabine/carboplatin - DISCONTINUED 9/2026 (PD)", source: "Medication list" }],
    },
    {
      id: "NCT06249048-exc-20",
      status: "unknown",
      rationale: "This excludes any vaccine, not only live ones, within 30 days; vaccination history is not recorded and seasonal influenza/COVID-19 vaccination is typically offered this time of year.",
      actionNeeded: "Confirm no vaccine of any kind in the 30 days before first dose; schedule seasonal vaccines around the study",
    },
    {
      id: "NCT06249048-exc-21",
      status: "pass",
      rationale: "Last gemcitabine/carboplatin 8/26/26 and last pembrolizumab 9/2/26, more than 3 weeks ago; therapy has been on hold since the 9/15 CT (the 'C9 D1 today' line is stale).",
      evidence: [
        { quote: "Last gem/carbo 8/26/26.", source: "Oncology note 2026-09-25" },
        { quote: "All tx on hold since.", source: "Oncology note 2026-09-25" },
      ],
    },
    {
      id: "NCT06249048-exc-22",
      status: "pass",
      confidence: "medium",
      rationale: "No prior trial enrollment is recorded.",
    },
    {
      id: "NCT06249048-exc-23",
      status: "pass",
      confidence: "medium",
      rationale: "Not enrolled in any other interventional study; she has received standard therapy only.",
    },
    {
      id: "NCT06249048-exc-24",
      status: "pass",
      confidence: "medium",
      rationale: "Tolerated about 9 months of pembrolizumab without a recorded reaction and has never received STX-001; only listed allergy is penicillin.",
      evidence: [{ quote: "ALLERGIES: penicillin (hives)", source: "Allergies" }],
    },
    {
      id: "NCT06249048-exc-25",
      status: "pass",
      confidence: "medium",
      rationale: "No psychiatric or substance-use disorder recorded; never smoker, working as an accountant.",
      evidence: [{ quote: "SH: accountant, 2 kids, never smoker.", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT06249048-exc-26",
      status: "unknown",
      confidence: "low",
      rationale: "Premenopausal (tubal ligation, ovaries intact), so she needs a negative serum β-hCG within 72 hours of the first dose; none on file. No pregnancy or breastfeeding is recorded.",
      evidence: [{ quote: "46 yo premenopausal F (s/p BTL 2014)", source: "Oncology note 2026-09-25" }],
      actionNeeded: "Obtain serum β-hCG within 72 h before first dose; must be negative",
    },
    {
      id: "NCT06249048-exc-27",
      status: "pass",
      confidence: "medium",
      rationale: "Bilateral tubal ligation (2014) is itself a highly effective contraceptive method.",
      evidence: [{ quote: "46 yo premenopausal F (s/p BTL 2014)", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT06249048-exc-28",
      status: "pass",
      confidence: "low",
      rationale: "Engaged and keen on a trial; ability to follow the protocol is confirmed at screening.",
    },
  ],
);
