import { demoMatch } from "../../match-helpers";

export default demoMatch(
  "NCT04683679",
  "Fits the ICI-pretreated TNBC cohort · coagulation, ECG and pregnancy test still needed",
  "She fits the TNBC cohort: metastatic TNBC that progressed on first-line pembrolizumab (prior ICI with progression satisfies the PD-L1 rule), one prior metastatic line, measurable liver and RLL lesions that can stay outside the RT field, and candidate ablative-RT targets in the intact left breast primary and T11/iliac bone. Her only irAE was grade 2 hypothyroidism on replacement and HBsAg is negative, so neither excludes. Before screening: INR/aPTT, a resting ECG, a pregnancy test and a radiation-oncology view on the target site; the preferred 4-week washout from pembrolizumab (last 9/2/26) is complete on 9/30/26.",
  [
    {
      id: "NCT04683679-inc-1",
      status: "pass",
      rationale: "46-year-old woman with histologically confirmed TNBC (ER 0%, PR 0%, HER2 IHC 0 on the breast core and RLL metastasis, November 2025).",
      evidence: [
        { quote: "46 yo premenopausal F", source: "Oncology note 2026-09-25" },
        { quote: "ER 0%/PR 0%/HER2 IHC 0 (TNBC, not HER2-low)", source: "Oncology note 2026-09-25" },
      ],
    },
    {
      id: "NCT04683679-inc-2",
      status: "pass",
      rationale: "ECOG 1 at the 9/25/26 visit, within 30 days of any allocation date in the coming month.",
      evidence: [{ quote: "EXAM: ECOG 1.", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT04683679-inc-3",
      status: "pass",
      rationale: "ER 0%, PR 0% and HER2 IHC 0 on the RLL metastasis (11/20/25), concordant with the breast core: meets ER < 5%, PR < 5%, HER2 0–1+.",
      evidence: [
        { quote: "ER: negative (0%)", source: "Pathology 2025-11-25" },
        { quote: "PR: negative (0%)", source: "Pathology 2025-11-25" },
        { quote: "HER2 IHC: 0 (no staining observed) - not HER2-low", source: "Pathology 2025-11-25" },
      ],
    },
    {
      id: "NCT04683679-inc-4",
      status: "not-applicable",
      rationale: "Defines the ER+ cohort; she would enter the TNBC cohort (ER 0%).",
    },
    {
      id: "NCT04683679-inc-5",
      status: "pass",
      rationale: "De novo metastatic TNBC (lung, mediastinal/hilar nodes, bone, and a new liver lesion), lung metastasis biopsy-proven 11/20/25.",
      evidence: [
        { quote: "De novo metastatic TNBC (HER2 IHC 0, PD-L1 CPS 15), lung/nodal/bone, now new liver met.", source: "Oncology note 2026-09-25" },
      ],
    },
    {
      id: "NCT04683679-inc-6",
      status: "not-applicable",
      rationale: "Defines the metastatic ER+ cohort; she would enter the TNBC cohort.",
    },
    {
      id: "NCT04683679-inc-7",
      status: "pass",
      rationale: "Received pembrolizumab with gemcitabine/carboplatin from 12/2025 and progressed on CT 9/15/26, so the prior-ICI-with-progression arm of this rule is met despite PD-L1 CPS 15.",
      evidence: [
        { quote: "1L pembrolizumab + gemcitabine/carboplatin (KEYNOTE-355) started 12/2025", source: "Oncology note 2026-09-25" },
        { quote: "PD on 1L pembro + gem/carbo after ~9 mo.", source: "Oncology note 2026-09-25" },
      ],
    },
    {
      id: "NCT04683679-inc-8",
      status: "pass",
      rationale: "PD-L1 already determined (22C3, CPS 15, on the RLL metastasis) and archival tissue from that biopsy is available.",
      evidence: [
        { quote: "PD-L1 IHC (22C3 pharmDx): CPS 15", source: "Pathology 2025-11-25" },
        { quote: "Archival tissue available (RLL core bx 11/2025); open to liver bx if needed.", source: "Oncology note 2026-09-25" },
      ],
    },
    {
      id: "NCT04683679-inc-9",
      status: "pass",
      confidence: "low",
      rationale: "Written informed consent is obtained at screening; she is interested in trials and has capacity.",
      evidence: [{ quote: "Pt interested in trials, hopes to start within 3-4 wks.", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT04683679-inc-10",
      status: "pass",
      rationale: "Two measurable non-bone lesions on CT 9/15/26 (liver segment VI 2.1 cm, RLL nodule 1.8 cm), so one can be left unirradiated as the RECIST target.",
      evidence: [{ quote: "Measurable dz: liver seg VI 2.1 cm, RLL 1.8 cm.", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT04683679-inc-11",
      status: "pass",
      confidence: "medium",
      rationale: "Permissive clause on previously irradiated lesions; no radiotherapy is documented, and her measurable liver and RLL lesions are unirradiated.",
    },
    {
      id: "NCT04683679-inc-12",
      status: "pass",
      rationale: "One prior line for metastatic TNBC (pembrolizumab + gemcitabine/carboplatin, stopped for progression), within the limit of 3.",
      evidence: [{ quote: "pembrolizumab + gemcitabine/carboplatin - DISCONTINUED 9/2026 (PD)", source: "Medication list" }],
    },
    {
      id: "NCT04683679-inc-13",
      status: "pass",
      confidence: "medium",
      rationale: "Candidate RT sites exist: the intact 2.5 cm left breast primary, T11 and left iliac bone metastases, and the liver/RLL lesions; suitability for ablative RT is a radiation-oncology call.",
      evidence: [
        { quote: "L breast 2.5 cm UOQ mass.", source: "Oncology note 2026-09-25" },
        { quote: "Sclerotic (treated) T11 and left iliac lesions, unchanged.", source: "CT CAP 2026-09-15" },
      ],
      actionNeeded: "Confirm with radiation oncology an RT target (e.g. left breast primary or T11) that leaves a measurable lesion outside the field",
    },
    {
      id: "NCT04683679-inc-14",
      status: "pass",
      rationale: "Archival FFPE tissue from the RLL core biopsy (11/2025) is available, and she is open to a fresh liver biopsy, which the protocol prefers.",
      evidence: [{ quote: "Archival tissue available (RLL core bx 11/2025); open to liver bx if needed.", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT04683679-inc-15",
      status: "pass",
      confidence: "low",
      rationale: "Premenopausal, so likely a WOCBP under Appendix C; bilateral tubal ligation (2014) provides highly effective contraception. Not-pregnant/not-breastfeeding status is confirmed at screening.",
      evidence: [{ quote: "46 yo premenopausal F (s/p BTL 2014)", source: "Oncology note 2026-09-25" }],
      actionNeeded: "Confirm not pregnant or breastfeeding at screening and document BTL as her contraceptive method",
    },
    {
      id: "NCT04683679-inc-16",
      status: "unknown",
      confidence: "low",
      rationale: "Labs 9/23/26 meet the hematology, renal and hepatic rows of Table 2, but no INR/PT or aPTT is on file for the coagulation row.",
      evidence: [{ quote: "WBC 3.9 (L) | ANC 1.6 | Hgb 9.8 (L) | Plt 132 (L)", source: "Labs 2026-09-23" }],
      actionNeeded: "Add INR/PT and aPTT (≤ 1.5 × ULN); repeat full Table 2 labs if treatment starts after 10/23/26 (30-day window)",
    },
    {
      id: "NCT04683679-inc-17",
      status: "not-applicable",
      rationale: "Table heading for the organ-function values; each row is assessed separately.",
    },
    {
      id: "NCT04683679-inc-18",
      status: "not-applicable",
      rationale: "Column heading of the organ-function table, not a requirement in itself.",
    },
    {
      id: "NCT04683679-inc-19",
      status: "pass",
      rationale: "ANC 1.6 × 10⁹/L, platelets 132 × 10⁹/L and Hgb 9.8 g/dL on 9/23/26; last transfusion was 1 unit PRBC in July 2026, more than 28 days ago.",
      evidence: [
        { quote: "WBC 3.9 (L) | ANC 1.6 | Hgb 9.8 (L) | Plt 132 (L)", source: "Labs 2026-09-23" },
        { quote: "1u PRBC 7/2026 for chemo-related anemia.", source: "Oncology note 2026-09-25" },
      ],
    },
    {
      id: "NCT04683679-inc-20",
      status: "pass",
      rationale: "Creatinine 0.7 mg/dL on 9/23/26, well within 1.5 × ULN.",
      evidence: [{ quote: "Cr 0.7", source: "Labs 2026-09-23" }],
    },
    {
      id: "NCT04683679-inc-21",
      status: "pass",
      rationale: "Total bilirubin 0.9 mg/dL (normal); AST 58 and ALT 61 are 1.5 × ULN, under 2.5 × ULN and well under the 5 × ULN allowed with her liver metastasis.",
      evidence: [
        { quote: "AST 58 (H, 1.5x ULN)", source: "Labs 2026-09-23" },
        { quote: "ALT 61 (H, 1.5x ULN)", source: "Labs 2026-09-23" },
        { quote: "T bili 0.9", source: "Labs 2026-09-23" },
      ],
    },
    {
      id: "NCT04683679-inc-22",
      status: "unknown",
      rationale: "No INR/PT or aPTT in the record; she is not on anticoagulants.",
      actionNeeded: "Obtain INR/PT and aPTT; each must be ≤ 1.5 × ULN",
    },
    {
      id: "NCT04683679-inc-23",
      status: "not-applicable",
      rationale: "Abbreviation key for the organ-function table; it sets no requirement.",
    },
    {
      id: "NCT04683679-inc-24",
      status: "pass",
      rationale: "Hgb 9.8 g/dL on 9/23/26 without erythropoietin (none on the medication list); last PRBC transfusion was July 2026, well over 2 weeks before.",
      evidence: [
        { quote: "Hgb 9.8 (L)", source: "Labs 2026-09-23" },
        { quote: "1u PRBC 7/2026 for chemo-related anemia.", source: "Oncology note 2026-09-25" },
      ],
    },
    {
      id: "NCT04683679-inc-25",
      status: "not-applicable",
      rationale: "Method footnote on calculating creatinine clearance; her creatinine of 0.7 mg/dL already satisfies the renal row.",
    },
    {
      id: "NCT04683679-inc-26",
      status: "not-applicable",
      rationale: "Administrative note about adapting laboratory thresholds to local guidelines; no patient requirement.",
    },
    {
      id: "NCT04683679-inc-27",
      status: "pass",
      confidence: "low",
      rationale: "Agreement not to breastfeed for 180 days after the last dose is confirmed at consent; nothing suggests she is breastfeeding.",
    },
    {
      id: "NCT04683679-inc-28",
      status: "pass",
      confidence: "medium",
      rationale: "Permissive provision for steroid users; she takes no corticosteroids (levothyroxine, entecavir, denosumab, prn ondansetron, calcium/vitamin D).",
    },
    {
      id: "NCT04683679-inc-29",
      status: "pass",
      confidence: "low",
      rationale: "Already takes oral levothyroxine and entecavir daily; ability to swallow olaparib tablets is confirmed at screening.",
      evidence: [{ quote: "entecavir 0.5 mg PO daily (HBV ppx)", source: "Medication list" }],
    },
    {
      id: "NCT04683679-exc-1",
      status: "pass",
      rationale: "One prior line of systemic therapy for metastatic TNBC, not more than 3.",
      evidence: [{ quote: "PD on 1L pembro + gem/carbo after ~9 mo.", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT04683679-exc-2",
      status: "unknown",
      confidence: "low",
      rationale: "Premenopausal with BTL, so a screening pregnancy test is required and none is on file. The bundled 2-week washout is met: 26 days since pembrolizumab (9/2/26), 33 since gemcitabine/carboplatin (8/26/26).",
      evidence: [{ quote: "46 yo premenopausal F (s/p BTL 2014)", source: "Oncology note 2026-09-25" }],
      actionNeeded: "Obtain urine pregnancy test within 72 h (or serum within 14 days) of first dose; must be negative",
    },
    {
      id: "NCT04683679-exc-3",
      status: "pass",
      confidence: "medium",
      rationale: "Last pembrolizumab 9/2/26 and gem/carbo 8/26/26, with all therapy on hold since the 9/15 CT (the 'C9 D1 today' line is stale), so the 4-week washout completes 9/30/26. Residual G2 anemia (Hgb 9.8) meets Table 2; hypothyroidism is replaced.",
      evidence: [
        { quote: "Pembro deferred 1 wk for AST/ALT ~2x ULN (HBV DNA neg), last dose 9/2/26.", source: "Oncology note 2026-09-25" },
        { quote: "All tx on hold since.", source: "Oncology note 2026-09-25" },
      ],
      actionNeeded: "Confirm with the PI that G2 chemotherapy anemia (Hgb 9.8) and replaced G2 hypothyroidism count as baseline",
    },
    {
      id: "NCT04683679-exc-4",
      status: "pass",
      confidence: "medium",
      rationale: "No radiotherapy is documented in an otherwise detailed treatment history; bone lesions were treated systemically with denosumab.",
    },
    {
      id: "NCT04683679-exc-5",
      status: "pass",
      rationale: "Her only immune-related AE was grade 2 hypothyroidism; no pneumonitis or colitis, and the August transaminase rise (~2 × ULN) had no features of immune hepatitis.",
      evidence: [
        { quote: "irAE hypothyroidism G2 2/2026 -> levothyroxine; no pneumonitis/colitis.", source: "Oncology note 2026-09-25" },
        { quote: "AST/ALT ~1.5x ULN, bili nl: likely liver met, no features of immune hepatitis.", source: "Oncology note 2026-09-25" },
      ],
    },
    {
      id: "NCT04683679-exc-6",
      status: "pass",
      confidence: "low",
      rationale: "No vaccinations are recorded; live vaccines would be unusual during chemo-immunotherapy, but this is confirmed at screening.",
      actionNeeded: "Confirm no live vaccine (including intranasal influenza) in the 30 days before first dose",
    },
    {
      id: "NCT04683679-exc-7",
      status: "pass",
      confidence: "medium",
      rationale: "No prior trial participation or investigational agent is recorded; her only therapy was standard pembrolizumab + gemcitabine/carboplatin.",
    },
    {
      id: "NCT04683679-exc-8",
      status: "pass",
      confidence: "medium",
      rationale: "No immunodeficiency (HIV negative 12/2025) and no steroids or immunosuppressants on the medication list.",
      evidence: [{ quote: "Serologies 12/2025: HBsAg neg, anti-HBc POS, HCV Ab neg, HIV Ag/Ab neg", source: "Labs" }],
    },
    {
      id: "NCT04683679-exc-9",
      status: "pass",
      confidence: "medium",
      rationale: "No second malignancy is mentioned in the history, problem list or imaging; germline panel negative.",
    },
    {
      id: "NCT04683679-exc-10",
      status: "pass",
      confidence: "medium",
      rationale: "Received about 9 months of pembrolizumab with no hypersensitivity recorded, and has never had olaparib; her only listed allergy is penicillin.",
      evidence: [{ quote: "ALLERGIES: penicillin (hives)", source: "Allergies" }],
    },
    {
      id: "NCT04683679-exc-11",
      status: "pass",
      rationale: "No autoimmune disease before pembrolizumab; the immune-related hypothyroidism is treated with levothyroxine replacement, which the criterion does not count as systemic treatment.",
      evidence: [
        { quote: "No autoimmune dz prior to pembro.", source: "Oncology note 2026-09-25" },
        { quote: "irAE hypothyroidism G2: levothyroxine 88 mcg, TSH 2.2, continue.", source: "Oncology note 2026-09-25" },
      ],
    },
    {
      id: "NCT04683679-exc-12",
      status: "pass",
      rationale: "No pneumonitis during pembrolizumab, and CT 9/15/26 shows no interstitial lung disease or pneumonitis.",
      evidence: [
        { quote: "No interstitial lung disease or pneumonitis.", source: "CT CAP 2026-09-15" },
        { quote: "irAE hypothyroidism G2 2/2026 -> levothyroxine; no pneumonitis/colitis.", source: "Oncology note 2026-09-25" },
      ],
    },
    {
      id: "NCT04683679-exc-13",
      status: "pass",
      confidence: "medium",
      rationale: "Entecavir is prophylaxis for resolved hepatitis B (HBsAg negative, HBV DNA undetectable 8/28/26), not treatment of an active infection; no other infection is recorded.",
      evidence: [{ quote: "HBV (anti-HBc+, HBsAg neg): entecavir ppx, HBV DNA undetectable 8/2026.", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT04683679-exc-14",
      status: "pass",
      rationale: "HIV Ag/Ab negative in December 2025.",
      evidence: [{ quote: "Serologies 12/2025: HBsAg neg, anti-HBc POS, HCV Ab neg, HIV Ag/Ab neg", source: "Labs" }],
    },
    {
      id: "NCT04683679-exc-15",
      status: "pass",
      rationale: "HBsAg negative (the criterion defines hepatitis B as HBsAg reactive) and HCV antibody negative; anti-HBc positivity with undetectable HBV DNA on entecavir does not meet the exclusion.",
      evidence: [
        { quote: "Serologies 12/2025: HBsAg neg, anti-HBc POS, HCV Ab neg, HIV Ag/Ab neg", source: "Labs" },
        { quote: "HBV DNA 08/28/2026: not detected", source: "Labs" },
      ],
    },
    {
      id: "NCT04683679-exc-16",
      status: "pass",
      confidence: "medium",
      rationale: "No tuberculosis history in the record; lungs clear and CT shows no features of active TB.",
    },
    {
      id: "NCT04683679-exc-17",
      status: "pass",
      confidence: "low",
      rationale: "No confounding condition evident: ECOG 1, working part-time, organ function adequate; final judgment rests with the investigator.",
    },
    {
      id: "NCT04683679-exc-18",
      status: "pass",
      confidence: "medium",
      rationale: "No psychiatric or substance-use disorder in the history; never smoker, working as an accountant.",
      evidence: [{ quote: "SH: accountant, 2 kids, never smoker.", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT04683679-exc-19",
      status: "pass",
      confidence: "low",
      rationale: "Bilateral tubal ligation in 2014 and no pregnancy or breastfeeding documented; confirmed by screening pregnancy test.",
      evidence: [{ quote: "46 yo premenopausal F (s/p BTL 2014)", source: "Oncology note 2026-09-25" }],
      actionNeeded: "Confirm negative pregnancy test and no breastfeeding at screening",
    },
    {
      id: "NCT04683679-exc-20",
      status: "pass",
      confidence: "medium",
      rationale: "No allogeneic tissue or solid organ transplant in the history.",
    },
    {
      id: "NCT04683679-exc-21",
      status: "unknown",
      rationale: "No ECG on file; no cardiac history, but she takes ondansetron as needed, which can prolong QT.",
      evidence: [
        { quote: "No echo or ECG on file; order if trial requires.", source: "Oncology note 2026-09-25" },
        { quote: "ondansetron 8 mg PO q8h prn nausea", source: "Medication list" },
      ],
      actionNeeded: "Obtain resting 12-lead ECG; QTcF must be ≤ 500 ms with no uncontrolled cardiac condition",
    },
    {
      id: "NCT04683679-exc-22",
      status: "pass",
      rationale: "No toxicity above grade 2: G1 fatigue, G1 transaminase rise, G2 chemotherapy anemia (Hgb 9.8) and G2 hypothyroidism on levothyroxine.",
      evidence: [
        { quote: "G1 fatigue, works part-time from home.", source: "Oncology note 2026-09-25" },
        { quote: "Anemia (chemo-related): Hgb 9.8, no bleeding.", source: "Oncology note 2026-09-25" },
      ],
    },
    {
      id: "NCT04683679-exc-23",
      status: "pass",
      confidence: "medium",
      rationale: "Mild cytopenias (WBC 3.9, Hgb 9.8, platelets 132 on 9/23/26) are attributed to gemcitabine/carboplatin, last given 8/26/26; no MDS/AML features are described.",
      evidence: [{ quote: "WBC 3.9 (L) | ANC 1.6 | Hgb 9.8 (L) | Plt 132 (L)", source: "Labs 2026-09-23" }],
      actionNeeded: "Recheck CBC off chemotherapy before olaparib; persistent cytopenias would need MDS work-up",
    },
    {
      id: "NCT04683679-exc-24",
      status: "pass",
      confidence: "medium",
      rationale: "Neurologically asymptomatic with a nonfocal exam; baseline brain MRI (11/18/25) was negative and a scan is not required. No spinal cord compression is described at the sclerotic T11 lesion.",
      evidence: [
        { quote: "No HA, no visual chnages, no focal weakness.", source: "Oncology note 2026-09-25" },
        { quote: "MRI BRAIN 11/18/2025 (baseline): no intracranial metastases.", source: "MRI brain 2025-11-18" },
      ],
    },
    {
      id: "NCT04683679-exc-25",
      status: "pass",
      confidence: "medium",
      rationale: "No serious uncontrolled medical disorder: no cardiac history, no diabetes, no interstitial lung disease on CT 9/15/26.",
      evidence: [
        { quote: "No DM, no cardiac hx.", source: "Oncology note 2026-09-25" },
        { quote: "No interstitial lung disease or pneumonitis.", source: "CT CAP 2026-09-15" },
      ],
    },
    {
      id: "NCT04683679-exc-26",
      status: "pass",
      confidence: "low",
      rationale: "Takes oral medications daily and no gastrointestinal disorder affecting absorption is recorded; confirmed at screening.",
    },
    {
      id: "NCT04683679-exc-27",
      status: "pass",
      rationale: "No strong or moderate CYP3A inhibitors on her medication list (levothyroxine, entecavir, denosumab, ondansetron prn, calcium/vitamin D).",
      evidence: [{ quote: "levothyroxine 88 mcg PO daily", source: "Medication list" }],
    },
    {
      id: "NCT04683679-exc-28",
      status: "pass",
      rationale: "No strong or moderate CYP3A inducers on her medication list (levothyroxine, entecavir, denosumab, ondansetron prn, calcium/vitamin D).",
    },
    {
      id: "NCT04683679-exc-29",
      status: "pass",
      confidence: "medium",
      rationale: "No major surgery recorded; her only procedures were core biopsies in November 2025.",
    },
    {
      id: "NCT04683679-exc-30",
      status: "pass",
      confidence: "medium",
      rationale: "No bone marrow or cord blood transplant in the history.",
    },
    {
      id: "NCT04683679-exc-31",
      status: "pass",
      confidence: "low",
      rationale: "Engaged in care and keen on a trial; compliance is judged by the investigator at screening.",
      evidence: [{ quote: "Pt interested in trials, hopes to start within 3-4 wks.", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT04683679-exc-32",
      status: "pass",
      confidence: "medium",
      rationale: "No prior trial enrollment is recorded; her only treatment has been standard first-line therapy.",
    },
  ],
);
