import { demoMatch } from "../../match-helpers";

export default demoMatch(
  "NCT05422794",
  "Fits the dose-escalation cohort only · coagulation and pregnancy test pending",
  "She can only enter dose escalation: the expansion cohort needs PD-L1-negative disease with no prior metastatic checkpoint inhibitor, and she has CPS 15 and progressed on first-line pembrolizumab. Escalation accepts any number of lines and prior ICI, and she is taxane-naive, with TNBC, measurable disease, ECOG 1, labs within limits (AST/ALT 1.5 × ULN with liver metastasis) and resolved HBV with undetectable DNA on entecavir. Still needed: INR/aPTT, a pregnancy test within 2 weeks of registration, and the site's confirmation that an escalation slot is open.",
  [
    {
      id: "NCT05422794-inc-1",
      status: "pass",
      rationale: "ER 0%, PR 0%, HER2 IHC 0 on the most recent tissue (RLL metastasis, 11/20/25), with metastatic disease confirmed on that biopsy.",
      evidence: [
        { quote: "ER: negative (0%)", source: "Pathology 2025-11-25" },
        { quote: "HER2 IHC: 0 (no staining observed) - not HER2-low", source: "Pathology 2025-11-25" },
        { quote: "Metastatic carcinoma, c/w breast primary (GATA3+, TTF-1 neg).", source: "Pathology 2025-11-25" },
      ],
    },
    {
      id: "NCT05422794-inc-2",
      status: "pass",
      rationale: "De novo metastatic disease involving lung, nodes, bone and now liver.",
      evidence: [
        { quote: "De novo metastatic TNBC (HER2 IHC 0, PD-L1 CPS 15), lung/nodal/bone, now new liver met.", source: "Oncology note 2026-09-25" },
      ],
    },
    {
      id: "NCT05422794-inc-3",
      status: "pass",
      rationale: "PD-L1 is not required for dose escalation; archival tissue from the RLL core biopsy (11/2025) is available for central testing.",
      evidence: [{ quote: "Archival tissue available (RLL core bx 11/2025); open to liver bx if needed.", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT05422794-inc-4",
      status: "pass",
      rationale: "Dose escalation allows any number of metastatic lines and prior checkpoint inhibitor; she has had one line, pembrolizumab + gemcitabine/carboplatin.",
      evidence: [{ quote: "1L pembrolizumab + gemcitabine/carboplatin (KEYNOTE-355) started 12/2025", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT05422794-inc-5",
      status: "pass",
      rationale: "Measurable disease on CT 9/15/26: liver segment VI 2.1 cm and RLL nodule 1.8 cm.",
      evidence: [{ quote: "Measurable dz: liver seg VI 2.1 cm, RLL 1.8 cm.", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT05422794-inc-6",
      status: "not-applicable",
      rationale: "Dose-expansion cohort only; she would not qualify for it anyway, as PD-L1 is positive (22C3 CPS 15).",
      evidence: [{ quote: "PD-L1 IHC (22C3 pharmDx): CPS 15", source: "Pathology 2025-11-25" }],
    },
    {
      id: "NCT05422794-inc-7",
      status: "not-applicable",
      rationale: "Dose-expansion cohort only; she would enter dose escalation (one prior metastatic line would otherwise be allowed here).",
    },
    {
      id: "NCT05422794-inc-8",
      status: "not-applicable",
      rationale: "Dose-expansion cohort only; she would enter dose escalation, where evaluable or measurable disease suffices.",
    },
    {
      id: "NCT05422794-inc-9",
      status: "not-applicable",
      rationale: "Dose-expansion cohort only (paired research biopsies); she would enter dose escalation.",
    },
    {
      id: "NCT05422794-inc-10",
      status: "pass",
      rationale: "46 years old (born 1980).",
      evidence: [{ quote: "46 yo premenopausal F", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT05422794-inc-11",
      status: "pass",
      rationale: "ECOG 1 on 9/25/26, within the ECOG ≤ 2 limit.",
      evidence: [{ quote: "EXAM: ECOG 1.", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT05422794-inc-12",
      status: "pass",
      rationale: "ANC 1.6 × 10⁹/L (1,600/mcL) on 9/23/26.",
      evidence: [{ quote: "ANC 1.6", source: "Labs 2026-09-23" }],
    },
    {
      id: "NCT05422794-inc-13",
      status: "pass",
      rationale: "Platelets 132 × 10⁹/L on 9/23/26; worth tracking, as BET inhibitors commonly lower platelets.",
      evidence: [{ quote: "Plt 132 (L)", source: "Labs 2026-09-23" }],
    },
    {
      id: "NCT05422794-inc-14",
      status: "pass",
      rationale: "Hemoglobin 9.8 g/dL on 9/23/26 (last transfusion July 2026).",
      evidence: [{ quote: "Hgb 9.8 (L)", source: "Labs 2026-09-23" }],
    },
    {
      id: "NCT05422794-inc-15",
      status: "pass",
      rationale: "Total bilirubin 0.9 mg/dL (normal) on 9/23/26.",
      evidence: [{ quote: "T bili 0.9", source: "Labs 2026-09-23" }],
    },
    {
      id: "NCT05422794-inc-16",
      status: "pass",
      rationale: "AST 58 and ALT 61 are 1.5 × ULN, under 3 × ULN and well under the 5 × ULN allowed with her liver metastasis.",
      evidence: [
        { quote: "AST 58 (H, 1.5x ULN)", source: "Labs 2026-09-23" },
        { quote: "ALT 61 (H, 1.5x ULN)", source: "Labs 2026-09-23" },
      ],
    },
    {
      id: "NCT05422794-inc-17",
      status: "pass",
      rationale: "Creatinine 0.7 mg/dL on 9/23/26, within 1.5 × ULN.",
      evidence: [{ quote: "Cr 0.7", source: "Labs 2026-09-23" }],
    },
    {
      id: "NCT05422794-inc-18",
      status: "unknown",
      rationale: "No INR or PT in the record; she is not anticoagulated.",
      actionNeeded: "Obtain INR/PT; ≤ 1.5 × ULN required",
    },
    {
      id: "NCT05422794-inc-19",
      status: "unknown",
      rationale: "No aPTT in the record; she is not anticoagulated.",
      actionNeeded: "Obtain aPTT; ≤ 1.5 × ULN required",
    },
    {
      id: "NCT05422794-inc-20",
      status: "pass",
      rationale: "Permissive provision for people with HIV; she is HIV Ag/Ab negative (12/2025).",
      evidence: [{ quote: "Serologies 12/2025: HBsAg neg, anti-HBc POS, HCV Ab neg, HIV Ag/Ab neg", source: "Labs" }],
    },
    {
      id: "NCT05422794-inc-21",
      status: "pass",
      rationale: "Resolved HBV (anti-HBc positive, HBsAg negative) on entecavir prophylaxis with HBV DNA not detected on 8/28/26, which meets the undetectable-on-suppression requirement.",
      evidence: [
        { quote: "HBV (anti-HBc+, HBsAg neg): entecavir ppx, HBV DNA undetectable 8/2026.", source: "Oncology note 2026-09-25" },
        { quote: "HBV DNA 08/28/2026: not detected", source: "Labs" },
      ],
      actionNeeded: "Repeat HBV DNA at screening and continue entecavir on study",
    },
    {
      id: "NCT05422794-inc-22",
      status: "pass",
      rationale: "Permissive HCV provision; HCV antibody negative in December 2025.",
      evidence: [{ quote: "Serologies 12/2025: HBsAg neg, anti-HBc POS, HCV Ab neg, HIV Ag/Ab neg", source: "Labs" }],
    },
    {
      id: "NCT05422794-inc-23",
      status: "pass",
      confidence: "medium",
      rationale: "Permissive provision for treated CNS metastases; she has none known (baseline MRI 11/18/25 negative, neurologically asymptomatic).",
      evidence: [{ quote: "MRI BRAIN 11/18/2025 (baseline): no intracranial metastases.", source: "MRI brain 2025-11-18" }],
    },
    {
      id: "NCT05422794-inc-24",
      status: "pass",
      confidence: "medium",
      rationale: "Permissive provision for active brain metastases; she is asymptomatic, though brain imaging has not been repeated since 11/2025.",
      evidence: [{ quote: "No brain imaging since baseline 11/2025; asymptomatic.", source: "Oncology note 2026-09-25" }],
      actionNeeded: "Consider screening brain MRI (last 11/18/2025) per protocol imaging requirements",
    },
    {
      id: "NCT05422794-inc-25",
      status: "pass",
      confidence: "medium",
      rationale: "Permissive provision for prior malignancies; no other cancer is recorded.",
    },
    {
      id: "NCT05422794-inc-26",
      status: "pass",
      confidence: "medium",
      rationale: "No cardiac history and functionally active (ECOG 1, working part-time), consistent with NYHA class I.",
      evidence: [{ quote: "No DM, no cardiac hx.", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT05422794-inc-27",
      status: "pass",
      confidence: "medium",
      rationale: "No neuropathy is recorded; she is taxane-naive and her only toxicities listed are fatigue, anemia, transaminase rise and hypothyroidism.",
      evidence: [{ quote: "No prior taxane, anthracycline, ADC or PARP inhibitor.", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT05422794-inc-28",
      status: "pass",
      confidence: "low",
      rationale: "Takes oral levothyroxine and entecavir daily; ability to swallow ZEN-3694 is confirmed at screening.",
      evidence: [{ quote: "levothyroxine 88 mcg PO daily", source: "Medication list" }],
    },
    {
      id: "NCT05422794-inc-29",
      status: "pass",
      rationale: "Last gemcitabine/carboplatin 8/26/26 (33 days) and last pembrolizumab 9/2/26 (26 days), both over 3 weeks; therapy on hold since the 9/15 CT despite the stale 'C9 D1 today' line.",
      evidence: [
        { quote: "Last gem/carbo 8/26/26.", source: "Oncology note 2026-09-25" },
        { quote: "Pembro deferred 1 wk for AST/ALT ~2x ULN (HBV DNA neg), last dose 9/2/26.", source: "Oncology note 2026-09-25" },
        { quote: "All tx on hold since.", source: "Oncology note 2026-09-25" },
      ],
    },
    {
      id: "NCT05422794-inc-30",
      status: "pass",
      confidence: "medium",
      rationale: "No radiotherapy is documented, so neither the 1-week window nor the 25% marrow limit is at issue.",
    },
    {
      id: "NCT05422794-inc-31",
      status: "pass",
      confidence: "medium",
      rationale: "No tyrosine kinase inhibitor or small-molecule anticancer agent has been given; prior therapy was pembrolizumab + gemcitabine/carboplatin only.",
    },
    {
      id: "NCT05422794-inc-32",
      status: "pass",
      confidence: "medium",
      rationale: "Residual toxicities are G1 fatigue and transaminases, G2 anemia (Hgb 9.8, within the protocol's Hgb ≥ 9 g/dL) and G2 hypothyroidism controlled on levothyroxine (TSH 2.2).",
      evidence: [
        { quote: "Anemia (chemo-related): Hgb 9.8, no bleeding.", source: "Oncology note 2026-09-25" },
        { quote: "irAE hypothyroidism G2: levothyroxine 88 mcg, TSH 2.2, continue.", source: "Oncology note 2026-09-25" },
      ],
      actionNeeded: "Confirm with the PI that G2 anemia meeting the Hgb threshold and replaced hypothyroidism are acceptable",
    },
    {
      id: "NCT05422794-inc-33",
      status: "pass",
      confidence: "low",
      rationale: "Of childbearing potential (premenopausal); bilateral tubal ligation (2014) exceeds the required contraception, and agreement is confirmed at consent.",
      evidence: [{ quote: "46 yo premenopausal F (s/p BTL 2014)", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT05422794-inc-34",
      status: "unknown",
      confidence: "low",
      rationale: "Premenopausal with tubal ligation but ovaries and uterus intact, so of childbearing potential by this protocol's definition; no pregnancy test on file. The male-contraception part does not apply.",
      evidence: [{ quote: "46 yo premenopausal F (s/p BTL 2014)", source: "Oncology note 2026-09-25" }],
      actionNeeded: "Obtain serum or urine pregnancy test within 2 weeks before registration; must be negative",
    },
    {
      id: "NCT05422794-inc-35",
      status: "pass",
      confidence: "low",
      rationale: "Has capacity and is interested in trials; written consent is obtained at screening.",
      evidence: [{ quote: "Pt interested in trials, hopes to start within 3-4 wks.", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT05422794-exc-1",
      status: "pass",
      confidence: "medium",
      rationale: "Received about 9 months of pembrolizumab without a recorded reaction, has never had a taxane or BET inhibitor, and her only listed allergy is penicillin.",
      evidence: [{ quote: "ALLERGIES: penicillin (hives)", source: "Allergies" }],
    },
    {
      id: "NCT05422794-exc-2",
      status: "pass",
      confidence: "medium",
      rationale: "No uncontrolled intercurrent illness: hypothyroidism controlled (TSH 2.2), HBV DNA undetectable, no cardiac history or diabetes.",
      evidence: [{ quote: "No DM, no cardiac hx.", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT05422794-exc-3",
      status: "pass",
      rationale: "No autoimmune disease before pembrolizumab; immune-related hypothyroidism is managed with levothyroxine replacement, which the criterion does not count as systemic treatment.",
      evidence: [
        { quote: "No autoimmune dz prior to pembro.", source: "Oncology note 2026-09-25" },
        { quote: "irAE hypothyroidism G2: levothyroxine 88 mcg, TSH 2.2, continue.", source: "Oncology note 2026-09-25" },
      ],
    },
    {
      id: "NCT05422794-exc-4",
      status: "pass",
      confidence: "medium",
      rationale: "No gastrointestinal disorder or bowel/stomach resection is recorded; abdomen soft and nontender.",
    },
    {
      id: "NCT05422794-exc-5",
      status: "pass",
      confidence: "low",
      rationale: "Bilateral tubal ligation (2014) and no pregnancy or breastfeeding recorded; confirmed by the screening pregnancy test.",
      evidence: [{ quote: "46 yo premenopausal F (s/p BTL 2014)", source: "Oncology note 2026-09-25" }],
      actionNeeded: "Confirm negative pregnancy test and no breastfeeding at screening",
    },
    {
      id: "NCT05422794-exc-6",
      status: "pass",
      rationale: "Her only anticancer therapy has been pembrolizumab + gemcitabine/carboplatin; no ZEN-3694 or other BET inhibitor.",
      evidence: [{ quote: "pembrolizumab + gemcitabine/carboplatin - DISCONTINUED 9/2026 (PD)", source: "Medication list" }],
    },
    {
      id: "NCT05422794-exc-7",
      status: "not-applicable",
      rationale: "Dose-expansion cohort only; she would enter escalation. In expansion this would exclude her (pembrolizumab for metastatic disease 12/2025–9/2026).",
    },
    {
      id: "NCT05422794-exc-8",
      status: "not-applicable",
      rationale: "Dose-expansion cohort only; she would enter escalation. She is taxane-naive in any case.",
      evidence: [{ quote: "No prior taxane, anthracycline, ADC or PARP inhibitor.", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT05422794-exc-9",
      status: "pass",
      rationale: "No strong CYP3A4 inhibitors or inducers on her medication list (levothyroxine, entecavir, denosumab, ondansetron prn, calcium/vitamin D).",
    },
    {
      id: "NCT05422794-exc-10",
      status: "pass",
      rationale: "Not on any factor Xa or IIa inhibitor; no anticoagulant on the medication list.",
    },
    {
      id: "NCT05422794-exc-11",
      status: "pass",
      confidence: "medium",
      rationale: "No bone-targeted radionuclide recorded; bone metastases are managed with denosumab, which is not a radionuclide.",
      evidence: [{ quote: "Bone mets: denosumab 120 mg q4w + Ca/vit D.", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT05422794-exc-12",
      status: "pass",
      rationale: "No cardiac history, so no myocardial infarction or unstable angina in the past 6 months.",
      evidence: [{ quote: "No DM, no cardiac hx.", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT05422794-exc-13",
      status: "pass",
      confidence: "medium",
      rationale: "No immunodeficiency (HIV negative) and no systemic steroids or immunosuppressants on the medication list.",
    },
    {
      id: "NCT05422794-exc-14",
      status: "pass",
      rationale: "No pneumonitis during pembrolizumab, and CT 9/15/26 shows no interstitial lung disease or pneumonitis.",
      evidence: [
        { quote: "No interstitial lung disease or pneumonitis.", source: "CT CAP 2026-09-15" },
        { quote: "irAE hypothyroidism G2 2/2026 -> levothyroxine; no pneumonitis/colitis.", source: "Oncology note 2026-09-25" },
      ],
    },
    {
      id: "NCT05422794-exc-15",
      status: "pass",
      confidence: "medium",
      rationale: "No tuberculosis history is recorded; lungs clear on exam.",
    },
    {
      id: "NCT05422794-exc-16",
      status: "pass",
      confidence: "low",
      rationale: "No vaccinations recorded; live vaccines would be unusual during chemo-immunotherapy, but this is confirmed at screening.",
      actionNeeded: "Confirm no live vaccine in the 30 days before planned treatment start",
    },
    {
      id: "NCT05422794-exc-17",
      status: "pass",
      confidence: "medium",
      rationale: "Bone disease is limited to two sclerotic, stable lesions (T11, left ilium); mild cytopenias are explained by recent gemcitabine/carboplatin, with no sign of marrow infiltration.",
      evidence: [
        { quote: "Sclerotic (treated) T11 and left iliac lesions, unchanged.", source: "CT CAP 2026-09-15" },
        { quote: "1u PRBC 7/2026 for chemo-related anemia.", source: "Oncology note 2026-09-25" },
      ],
    },
  ],
);
