import { demoMatch } from "../../match-helpers";

export default demoMatch(
  "NCT06062498",
  "ESR1 Y537S after 1L AI + ribociclib fits · iliac lesion must be confirmed 'mainly lytic'",
  "Linda fits the biology this trial targets: ER 90%/HER2 IHC 0 lobular cancer, ESR1 Y537S on ctDNA, and progression after about 27 months of letrozole + ribociclib, with no prior elacestrant, fulvestrant or chemotherapy. The deciding question is disease assessment: she has no RECIST-measurable lesion, so entry depends on radiology calling the mixed left iliac lesion (2.3 cm lytic component) 'mainly lytic'. Creatinine clearance is borderline at about 52 mL/min against a 50 mL/min floor. If randomized to the combination arm she would receive palbociclib or abemaciclib, given prior ribociclib.",
  [
    {
      id: "NCT06062498-inc-1",
      status: "pass",
      rationale: "ER-positive (90%, strong) and HER2 IHC 0 on the May 2024 iliac bone metastasis, matching the 2017 primary (ER 95%, HER2 IHC 0).",
      evidence: [
        { quote: "ER: positive, 90%, strong", source: "Bone biopsy 2024-05-21" },
        { quote: "HER2 IHC: 0 (negative)", source: "Bone biopsy 2024-05-21" },
        { quote: "ER 95% strong, PR 40%, HER2 IHC 0.", source: "Primary 2017" },
      ],
    },
    {
      id: "NCT06062498-inc-2",
      status: "pass",
      rationale: "ER staining is 90% on the metastatic biopsy and 95% on the primary, well above the trial's >10% cut-off; no fresh biopsy is required.",
      evidence: [
        { quote: "ER: positive, 90%, strong", source: "Bone biopsy 2024-05-21" },
        { quote: "ER 95% strong, PR 40%, HER2 IHC 0.", source: "Primary 2017" },
      ],
    },
    {
      id: "NCT06062498-inc-3",
      status: "pass",
      rationale: "ESR1 p.Y537S (VAF 2.1%) on Guardant360 ctDNA collected 2026-09-16; ctDNA results from standard-of-care testing are explicitly accepted.",
      evidence: [{ quote: "ESR1 p.Y537S, VAF 2.1%", source: "Guardant360 2026-09-23" }],
    },
    {
      id: "NCT06062498-inc-4",
      status: "unknown",
      confidence: "medium",
      rationale: "Bone-only disease, not RECIST-measurable. The left iliac lesion is mixed lytic/sclerotic with a 2.3 cm lytic component and no soft-tissue mass; whether it is 'mainly lytic' is not stated.",
      evidence: [
        { quote: "Bone-only dz, NOT measurable by RECIST 1.1 (evaluable only).", source: "Oncology note 2026-09-25" },
        { quote: "Mixed lytic/sclerotic L iliac lesion, lytic component 2.3 cm, no extraosseous soft tissue component.", source: "PET/CT 2026-09-09" },
      ],
      actionNeeded: "Ask radiology to review the left iliac lesion on CT/MRI and confirm it is predominantly lytic; otherwise she has no qualifying lesion",
    },
    {
      id: "NCT06062498-inc-5",
      status: "pass",
      confidence: "medium",
      rationale: "Two prior endocrine therapies: adjuvant anastrozole 2017–2022 and first-line letrozole + ribociclib for metastatic disease. This reads the criterion as counting the adjuvant AI, consistent with inc-23 allowing one metastatic line.",
      evidence: [
        { quote: "Adj anastrozole 10/2017-10/2022 (5 yrs completed).", source: "Oncology note 2026-09-25" },
        { quote: "1L letrozole + ribociclib from 6/2024 (400 mg from 10/2024, G3 neutropenia)", source: "Oncology note 2026-09-25" },
      ],
      actionNeeded: "Confirm with the study team that adjuvant anastrozole counts toward the two required prior endocrine therapies",
    },
    {
      id: "NCT06062498-inc-6",
      status: "pass",
      rationale: "Age 67, postmenopausal; the childbearing-potential wording does not apply to her.",
      evidence: [{ quote: "67 yo postmenopausal F", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT06062498-inc-7",
      status: "not-applicable",
      rationale: "FSH confirmation applies only to possibly menopausal patients under 55; she is 67 and postmenopausal.",
      evidence: [{ quote: "67 yo postmenopausal F", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT06062498-inc-8",
      status: "pass",
      rationale: "ECOG 1 on 2026-09-25; bone pain limits walking to about two blocks but she is independent in ADLs.",
      evidence: [
        { quote: "EXAM: ECOG 1.", source: "Oncology note 2026-09-25" },
        { quote: "walking limited to ~2 blocks, cane outdoors, independant in ADLs", source: "Oncology note 2026-09-25" },
      ],
    },
    {
      id: "NCT06062498-inc-9",
      status: "pass",
      confidence: "medium",
      rationale: "Labs from 2026-09-22 meet each listed threshold (see the items below); creatinine clearance is the tight one at about 52 mL/min.",
      evidence: [
        { quote: "WBC 3.6 (L) | ANC 1.7 | Hgb 11.4 (L) | Plt 168", source: "Labs 2026-09-22" },
        { quote: "Cr 1.1 | eGFR 52 (L)", source: "Labs 2026-09-22" },
      ],
    },
    {
      id: "NCT06062498-inc-10",
      status: "pass",
      rationale: "On 2026-09-22: WBC 3,600/mcL, ANC 1,700/mcL, Hgb 11.4 g/dL, platelets 168,000/mcL, total bilirubin 0.5 mg/dL and AST 24 U/L, all within the stated limits. No liver metastases.",
      evidence: [
        { quote: "WBC 3.6 (L) | ANC 1.7 | Hgb 11.4 (L) | Plt 168", source: "Labs 2026-09-22" },
        { quote: "AST 24 | ALT 19 | T bili 0.5", source: "Labs 2026-09-22" },
      ],
    },
    {
      id: "NCT06062498-inc-11",
      status: "pass",
      rationale: "ALT 19 U/L on 2026-09-22, within normal limits and far below 3 × ULN; no liver metastases on PET/CT.",
      evidence: [
        { quote: "AST 24 | ALT 19 | T bili 0.5", source: "Labs 2026-09-22" },
        { quote: "No FDG-avid visceral, nodal or soft tissue disease.", source: "PET/CT 2026-09-09" },
      ],
    },
    {
      id: "NCT06062498-inc-12",
      status: "pass",
      confidence: "medium",
      rationale: "Cockcroft-Gault (female) with age 67, weight 66 kg and creatinine 1.1 mg/dL gives about 52 mL/min, just above the 50 mL/min floor; eGFR 52 (CKD 3a, stable).",
      evidence: [
        { quote: "Cr 1.1 | eGFR 52 (L)", source: "Labs 2026-09-22" },
        { quote: "Wt 66 kg.", source: "Oncology note 2026-09-25" },
      ],
      actionNeeded: "Recalculate Cockcroft-Gault clearance on screening labs; ≥ 50 mL/min required (about 52 mL/min on 2026-09-22)",
    },
    {
      id: "NCT06062498-inc-13",
      status: "not-applicable",
      rationale: "This is the formula for patients designated male at birth; she is female, so the DFAB formula in the next item applies.",
      evidence: [{ quote: "67 yo postmenopausal F", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT06062498-inc-14",
      status: "pass",
      confidence: "medium",
      rationale: "DFAB formula: 0.85 × (140 − 67) × 66 kg / (1.1 × 72) ≈ 52 mL/min, borderline above 50. No growth-factor or transfusion support is documented.",
      evidence: [
        { quote: "Cr 1.1 | eGFR 52 (L)", source: "Labs 2026-09-22" },
        { quote: "Wt 66 kg.", source: "Oncology note 2026-09-25" },
      ],
    },
    {
      id: "NCT06062498-inc-15",
      status: "pass",
      confidence: "medium",
      rationale: "Applies only to patients with known HIV; HIV is not on her otherwise detailed problem list.",
      evidence: [{ quote: "PMH: CKD 3a, T2DM diet-controlled (A1c 6.4% 8/2026), osteoporosis (DEXA 2021 T-score -2.6), depression.", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT06062498-inc-16",
      status: "pass",
      confidence: "medium",
      rationale: "Applies only to known chronic hepatitis B; none is recorded, and AST 24 / ALT 19 are normal.",
      evidence: [{ quote: "AST 24 | ALT 19 | T bili 0.5", source: "Labs 2026-09-22" }],
    },
    {
      id: "NCT06062498-inc-17",
      status: "pass",
      confidence: "medium",
      rationale: "Applies only to known hepatitis C; none is recorded, and liver enzymes are normal.",
      evidence: [{ quote: "AST 24 | ALT 19 | T bili 0.5", source: "Labs 2026-09-22" }],
    },
    {
      id: "NCT06062498-inc-18",
      status: "pass",
      confidence: "medium",
      rationale: "No malignancy other than the breast cancer is recorded in her history; prior non-interfering cancers would be allowed in any case.",
    },
    {
      id: "NCT06062498-inc-19",
      status: "pass",
      confidence: "medium",
      rationale: "No cardiac disease on her problem list and no anthracycline or HER2 therapy; QTcF rose to 440–455 ms on ribociclib. Walking is limited by bone pain, not dyspnoea. The contraception clause does not apply at 67.",
      evidence: [{ quote: "QTcF 462 ms on 9/17 ECG (440-455 on ribociclib), on escitalopram.", source: "Oncology note 2026-09-25" }],
      actionNeeded: "Document NYHA class at screening (class 2B or better required)",
    },
    {
      id: "NCT06062498-inc-20",
      status: "not-applicable",
      rationale: "Part of the protocol's definition of childbearing potential, not an entry requirement; at 67 and postmenopausal she is not of childbearing potential.",
      evidence: [{ quote: "67 yo postmenopausal F", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT06062498-inc-21",
      status: "pass",
      confidence: "low",
      rationale: "The menses, contraception and pregnancy-test parts concern people of childbearing potential and do not apply to her (67, postmenopausal); informed consent is confirmed at screening.",
      evidence: [{ quote: "67 yo postmenopausal F", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT06062498-inc-22",
      status: "pass",
      confidence: "medium",
      rationale: "Heading for the Arm 2 (elacestrant + CDK4/6 inhibitor) requirements; randomization is after registration, and she meets the Arm 2 items that follow (one metastatic endocrine line, with a CDK4/6 inhibitor).",
    },
    {
      id: "NCT06062498-inc-23",
      status: "pass",
      rationale: "One prior hormonal therapy in the metastatic setting (letrozole), given with the CDK4/6 inhibitor ribociclib from June 2024 to September 2026.",
      evidence: [
        { quote: "1L letrozole + ribociclib from 6/2024 (400 mg from 10/2024, G3 neutropenia)", source: "Oncology note 2026-09-25" },
        { quote: "Ribociclib/letrozole stopped 9/14/26 (~27 mo).", source: "Oncology note 2026-09-25" },
      ],
    },
    {
      id: "NCT06062498-inc-24",
      status: "pass",
      rationale: "Her only CDK4/6 inhibitor exposure is ribociclib, so if randomized to Arm 2 she would be assigned palbociclib or abemaciclib.",
      evidence: [{ quote: "letrozole 2.5 mg daily + ribociclib 400 mg - DISCONTINUED 9/14/2026 (PD)", source: "Medication list" }],
    },
    {
      id: "NCT06062498-exc-1",
      status: "pass",
      rationale: "The note states no prior oral SERD; she has never received elacestrant.",
      evidence: [{ quote: "No prior chemo for MBC, no fulvestrant, no oral SERD, no PI3K/AKT/mTOR inhibitor.", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT06062498-exc-2",
      status: "pass",
      rationale: "She has never received chemotherapy, and her only radiotherapy was a single 8 Gy fraction to the left hip in July 2024, more than two years ago.",
      evidence: [
        { quote: "Oncotype RS 14 -> no chemo, no PMRT.", source: "Oncology note 2026-09-25" },
        { quote: "Palliative RT L hip 8 Gy x1 7/2024.", source: "Oncology note 2026-09-25" },
      ],
    },
    {
      id: "NCT06062498-exc-3",
      status: "pass",
      confidence: "medium",
      rationale: "No corticosteroids or immunosuppressants on her current medication list (zoledronic acid, tramadol, escitalopram, calcium/vitamin D).",
    },
    {
      id: "NCT06062498-exc-4",
      status: "pass",
      confidence: "medium",
      rationale: "No known brain metastases and no neurological symptoms, but she has never had brain imaging.",
      evidence: [
        { quote: "No brain imaging to date (asymptomatic); MRI if trial requires.", source: "Oncology note 2026-09-25" },
        { quote: "No HA or visual chnages.", source: "Oncology note 2026-09-25" },
      ],
      actionNeeded: "Obtain brain MRI only if the protocol mandates baseline CNS imaging",
    },
    {
      id: "NCT06062498-exc-5",
      status: "pass",
      rationale: "No residual toxicity above grade 3: the 2024 grade 3 neutropenia resolved with dose reduction (ANC 1.7 on 2026-09-22), and the 3,600 WBC is grade 1 at most.",
      evidence: [
        { quote: "1L letrozole + ribociclib from 6/2024 (400 mg from 10/2024, G3 neutropenia)", source: "Oncology note 2026-09-25" },
        { quote: "WBC 3.6 (L) | ANC 1.7 | Hgb 11.4 (L) | Plt 168", source: "Labs 2026-09-22" },
      ],
    },
    {
      id: "NCT06062498-exc-6",
      status: "pass",
      rationale: "No investigational agents. Ribociclib was stopped on 2026-09-14 (14 days ago as of 2026-09-28), so the 14-day CDK4/6 inhibitor washout is met; the 'continue ribociclib' line in the plan is a stale copy-forward.",
      evidence: [{ quote: "letrozole 2.5 mg daily + ribociclib 400 mg - DISCONTINUED 9/14/2026 (PD)", source: "Medication list" }],
    },
    {
      id: "NCT06062498-exc-7",
      status: "pass",
      rationale: "Bone-only disease with no visceral, nodal or soft-tissue involvement on PET/CT 2026-09-09; no effusions or liver disease.",
      evidence: [{ quote: "No FDG-avid visceral, nodal or soft tissue disease.", source: "PET/CT 2026-09-09" }],
    },
    {
      id: "NCT06062498-exc-8",
      status: "pass",
      confidence: "medium",
      rationale: "No pneumonitis or ILD in her history, and the 2026-09-09 PET/CT describes no lung disease; she is a never-smoker.",
      evidence: [{ quote: "SH: widowed, lives alone, never smoker, no EtOH.", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT06062498-exc-9",
      status: "pass",
      confidence: "medium",
      rationale: "No surgery since the 2017 mastectomy is recorded; the most recent procedure was a CT-guided bone biopsy in May 2024.",
    },
    {
      id: "NCT06062498-exc-10",
      status: "pass",
      confidence: "medium",
      rationale: "Current medications (zoledronic acid, tramadol, escitalopram, calcium/vitamin D) include no strong or moderate CYP3A4 inhibitor or inducer; ribociclib, a CYP3A4 inhibitor, was stopped 2026-09-14.",
      evidence: [{ quote: "letrozole 2.5 mg daily + ribociclib 400 mg - DISCONTINUED 9/14/2026 (PD)", source: "Medication list" }],
    },
    {
      id: "NCT06062498-exc-11",
      status: "pass",
      confidence: "medium",
      rationale: "Her only recorded allergy is codeine (nausea, an intolerance); she has never received elacestrant or another SERD.",
      evidence: [{ quote: "ALLERGIES: codeine (nausea)", source: "Allergies" }],
    },
    {
      id: "NCT06062498-exc-12",
      status: "pass",
      confidence: "medium",
      rationale: "BP 136/82 without antihypertensives; depression is stable on escitalopram. She lives alone but is independent in ADLs and engaged in planning. No uncontrolled illness is documented.",
      evidence: [
        { quote: "BP 136/82 HR 70.", source: "Oncology note 2026-09-25" },
        { quote: "Depression - escitalopram 10 mg, stable.", source: "Oncology note 2026-09-25" },
      ],
    },
    {
      id: "NCT06062498-exc-13",
      status: "pass",
      confidence: "medium",
      rationale: "No GI disease or malabsorption recorded; she took oral letrozole and ribociclib for about 27 months and prefers oral treatment.",
      evidence: [{ quote: "Pt prefers oral tx, open to trials", source: "Oncology note 2026-09-25" }],
    },
  ],
);
