import { demoMatch } from "../../match-helpers";

export default demoMatch(
  "NCT07198724",
  "Excluded: requires RECIST-measurable disease; hers is bone-only · HER2-ultralow not assessed",
  "She meets the treatment-history requirements (CDK4/6 inhibitor and endocrine-resistant, no prior chemotherapy, ADC or oral SERD) and has a current ESR1 result, but the trial requires RECIST 1.1-measurable disease and her metastases are bone-only without a soft-tissue component. Separately, HER2 is reported as IHC 0 on both specimens, so eligibility would also need a pathology re-read showing faint membranous staining (HER2-ultralow), plus an echocardiogram and hepatitis serology. Only new measurable disease would reopen this trial.",
  [
    {
      id: "NCT07198724-inc-1",
      status: "unknown",
      confidence: "medium",
      rationale: "ER 90% qualifies, but HER2 is IHC 0 on the 2024 bone biopsy and the 2017 primary, so she is not HER2-low; whether either sample shows faint membranous staining (HER2-ultralow) was never reported, and decalcified bone is unreliable for HER2 IHC.",
      evidence: [
        { quote: "HER2 IHC: 0 (negative)", source: "Bone biopsy 2024-05-21" },
        { quote: "ER 95% strong, PR 40%, HER2 IHC 0.", source: "Primary 2017" },
        { quote: "Specimen: Bone, left iliac, CT-guided core biopsy (decalcified)", source: "Bone biopsy 2024-05-21" },
      ],
      actionNeeded: "Ask pathology to re-score HER2 on the 2017 mastectomy block for faint membranous staining (HER2-ultralow); IHC 0 with no staining excludes",
    },
    {
      id: "NCT07198724-inc-2",
      status: "pass",
      rationale: "Prior CDK4/6 inhibitor: ribociclib with letrozole for metastatic disease from June 2024 until progression in September 2026.",
      evidence: [
        { quote: "1L letrozole + ribociclib from 6/2024 (400 mg from 10/2024, G3 neutropenia)", source: "Oncology note 2026-09-25" },
        { quote: "PD on 1L AI + CDK4/6i after ~27 mo.", source: "Oncology note 2026-09-25" },
      ],
    },
    {
      id: "NCT07198724-inc-3",
      status: "pass",
      rationale: "No chemotherapy or antibody-drug conjugate in the metastatic setting (zero of the one allowed).",
      evidence: [{ quote: "No prior chemo for MBC, no fulvestrant, no oral SERD, no PI3K/AKT/mTOR inhibitor.", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT07198724-inc-4",
      status: "fail",
      rationale: "Bone-only disease, explicitly not measurable by RECIST 1.1; the 2.3 cm lytic component of the left iliac lesion has no extraosseous soft-tissue mass, so it does not qualify as a measurable lesion.",
      evidence: [
        { quote: "Bone-only dz, NOT measurable by RECIST 1.1 (evaluable only).", source: "Oncology note 2026-09-25" },
        { quote: "Mixed lytic/sclerotic L iliac lesion, lytic component 2.3 cm, no extraosseous soft tissue component.", source: "PET/CT 2026-09-09" },
      ],
    },
    {
      id: "NCT07198724-inc-5",
      status: "pass",
      rationale: "ESR1 status is known from Guardant360 CDx ctDNA collected 2026-09-16 (ESR1 Y537S), 12 days ago and within the 60-day validation window.",
      evidence: [
        { quote: "MOLECULAR - Guardant360 CDx (ctDNA), collected 2026-09-16, reported 2026-09-23:", source: "Guardant360 2026-09-23" },
        { quote: "ESR1 p.Y537S, VAF 2.1%", source: "Guardant360 2026-09-23" },
      ],
    },
    {
      id: "NCT07198724-inc-6",
      status: "pass",
      rationale: "67-year-old woman, well above the 18-year minimum.",
      evidence: [{ quote: "67 yo postmenopausal F", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT07198724-inc-7",
      status: "pass",
      rationale: "ECOG 1 on 2026-09-25, within the ≤ 2 limit.",
      evidence: [{ quote: "EXAM: ECOG 1.", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT07198724-inc-8",
      status: "pass",
      rationale: "Labs from 2026-09-22 meet each marrow, liver and renal threshold listed below.",
      evidence: [
        { quote: "WBC 3.6 (L) | ANC 1.7 | Hgb 11.4 (L) | Plt 168", source: "Labs 2026-09-22" },
        { quote: "AST 24 | ALT 19 | T bili 0.5", source: "Labs 2026-09-22" },
      ],
    },
    {
      id: "NCT07198724-inc-9",
      status: "pass",
      rationale: "ANC 1,700/µL on 2026-09-22, above 1,500/µL.",
      evidence: [{ quote: "WBC 3.6 (L) | ANC 1.7 | Hgb 11.4 (L) | Plt 168", source: "Labs 2026-09-22" }],
    },
    {
      id: "NCT07198724-inc-10",
      status: "pass",
      rationale: "Platelets 168,000/µL on 2026-09-22.",
      evidence: [{ quote: "WBC 3.6 (L) | ANC 1.7 | Hgb 11.4 (L) | Plt 168", source: "Labs 2026-09-22" }],
    },
    {
      id: "NCT07198724-inc-11",
      status: "pass",
      rationale: "Hemoglobin 11.4 g/dL on 2026-09-22, above 9.0 g/dL.",
      evidence: [{ quote: "WBC 3.6 (L) | ANC 1.7 | Hgb 11.4 (L) | Plt 168", source: "Labs 2026-09-22" }],
    },
    {
      id: "NCT07198724-inc-12",
      status: "pass",
      rationale: "Total bilirubin 0.5 mg/dL on 2026-09-22, within normal limits.",
      evidence: [{ quote: "AST 24 | ALT 19 | T bili 0.5", source: "Labs 2026-09-22" }],
    },
    {
      id: "NCT07198724-inc-13",
      status: "pass",
      rationale: "AST 24 and ALT 19 U/L on 2026-09-22, within normal limits.",
      evidence: [{ quote: "AST 24 | ALT 19 | T bili 0.5", source: "Labs 2026-09-22" }],
    },
    {
      id: "NCT07198724-inc-14",
      status: "pass",
      rationale: "Creatinine 1.1 mg/dL on 2026-09-22, not flagged high, so well under 1.5 × ULN (eGFR 52, stable CKD 3a).",
      evidence: [{ quote: "Cr 1.1 | eGFR 52 (L)", source: "Labs 2026-09-22" }],
    },
    {
      id: "NCT07198724-inc-15",
      status: "pass",
      rationale: "Her creatinine is not above ULN, so this alternative is not needed; Cockcroft-Gault clearance (67 y, 66 kg, Cr 1.1, female) is about 52 mL/min in any case, above 45.",
      evidence: [
        { quote: "Cr 1.1 | eGFR 52 (L)", source: "Labs 2026-09-22" },
        { quote: "Wt 66 kg.", source: "Oncology note 2026-09-25" },
      ],
    },
    {
      id: "NCT07198724-inc-16",
      status: "unknown",
      confidence: "low",
      rationale: "No echocardiogram or MUGA has ever been done, so baseline LVEF is unknown.",
      evidence: [{ quote: "No echocardiogram on file.", source: "Cardiac testing" }],
      actionNeeded: "Obtain echocardiogram (MUGA if inconclusive) before registration; LVEF ≥ 50% required",
    },
    {
      id: "NCT07198724-inc-17",
      status: "pass",
      confidence: "medium",
      rationale: "These conditions apply only to patients with CNS metastases; she has no known CNS disease and no neurological symptoms, though she has never had brain imaging.",
      evidence: [{ quote: "No brain imaging to date (asymptomatic); MRI if trial requires.", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT07198724-inc-18",
      status: "pass",
      rationale: "Postmenopausal by the age criterion: she is 67 (≥ 60 years).",
      evidence: [{ quote: "67 yo postmenopausal F", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT07198724-inc-19",
      status: "not-applicable",
      rationale: "Pregnancy testing applies to premenopausal women; she is 67 and postmenopausal by the protocol definition.",
      evidence: [{ quote: "67 yo postmenopausal F", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT07198724-inc-20",
      status: "not-applicable",
      rationale: "Contraception applies to women of childbearing potential and men; she is a 67-year-old postmenopausal woman.",
      evidence: [{ quote: "67 yo postmenopausal F", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT07198724-inc-21",
      status: "pass",
      confidence: "low",
      rationale: "She took oral letrozole and ribociclib for about 27 months and prefers oral treatment; confirmed at screening.",
      evidence: [{ quote: "Pt prefers oral tx, open to trials", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT07198724-inc-22",
      status: "pass",
      confidence: "low",
      rationale: "She is open to trials and has been referred to the research coordinator; informed consent is confirmed at screening.",
      evidence: [{ quote: "Pt prefers oral tx, open to trials", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT07198724-exc-1",
      status: "pass",
      rationale: "She has never received chemotherapy or an antibody-drug conjugate, including topoisomerase-inhibitor ADCs such as T-DXd.",
      evidence: [
        { quote: "Oncotype RS 14 -> no chemo, no PMRT.", source: "Oncology note 2026-09-25" },
        { quote: "No prior chemo for MBC, no fulvestrant, no oral SERD, no PI3K/AKT/mTOR inhibitor.", source: "Oncology note 2026-09-25" },
      ],
    },
    {
      id: "NCT07198724-exc-2",
      status: "pass",
      rationale: "No prior oral SERD, SERM, PROTAC or CERAN. Letrozole/ribociclib stopped 2026-09-14, 14 days ago as of 2026-09-28, beyond the 7-day endocrine/targeted washout.",
      evidence: [
        { quote: "No prior chemo for MBC, no fulvestrant, no oral SERD, no PI3K/AKT/mTOR inhibitor.", source: "Oncology note 2026-09-25" },
        { quote: "letrozole 2.5 mg daily + ribociclib 400 mg - DISCONTINUED 9/14/2026 (PD)", source: "Medication list" },
      ],
    },
    {
      id: "NCT07198724-exc-3",
      status: "pass",
      confidence: "medium",
      rationale: "No known brain metastases and no headache or visual symptoms; brain imaging has never been performed.",
      evidence: [
        { quote: "No brain imaging to date (asymptomatic); MRI if trial requires.", source: "Oncology note 2026-09-25" },
        { quote: "No HA or visual chnages.", source: "Oncology note 2026-09-25" },
      ],
    },
    {
      id: "NCT07198724-exc-4",
      status: "pass",
      confidence: "medium",
      rationale: "No investigational agent or device appears in her treatment history; her only systemic therapies have been anastrozole, letrozole and ribociclib.",
    },
    {
      id: "NCT07198724-exc-5",
      status: "pass",
      confidence: "medium",
      rationale: "Only recorded allergy is codeine (nausea); she has never received elacestrant, a SERD or T-DXd.",
      evidence: [{ quote: "ALLERGIES: codeine (nausea)", source: "Allergies" }],
    },
    {
      id: "NCT07198724-exc-6",
      status: "pass",
      confidence: "medium",
      rationale: "No history of pneumonitis, and PET/CT on 2026-09-09 showed no visceral or lung disease; screening imaging will need to confirm no ILD.",
      evidence: [{ quote: "No FDG-avid visceral, nodal or soft tissue disease.", source: "PET/CT 2026-09-09" }],
    },
    {
      id: "NCT07198724-exc-7",
      status: "not-applicable",
      rationale: "Pregnancy and breastfeeding exclusions cannot apply to a 67-year-old postmenopausal woman.",
      evidence: [{ quote: "67 yo postmenopausal F", source: "Oncology note 2026-09-25" }],
    },
    {
      id: "NCT07198724-exc-8",
      status: "pass",
      confidence: "medium",
      rationale: "No tuberculosis in her history, and PET/CT shows no pulmonary or nodal disease.",
      evidence: [{ quote: "No FDG-avid visceral, nodal or soft tissue disease.", source: "PET/CT 2026-09-09" }],
    },
    {
      id: "NCT07198724-exc-9",
      status: "pass",
      confidence: "medium",
      rationale: "Diabetes is diet-controlled (HbA1c 6.4%, August 2026); no cardiovascular disease, active infection, GI disorder or arrhythmia requiring medication recorded; depression is stable.",
      evidence: [
        { quote: "T2DM diet-controlled (A1c 6.4% 8/2026)", source: "Oncology note 2026-09-25" },
        { quote: "Depression - escitalopram 10 mg, stable.", source: "Oncology note 2026-09-25" },
      ],
    },
    {
      id: "NCT07198724-exc-10",
      status: "unknown",
      confidence: "low",
      rationale: "No liver disease (bilirubin 0.5, albumin 3.8) and no MI, coronary event or heart failure recorded, but hepatitis B and C serology has not been documented.",
      evidence: [
        { quote: "AST 24 | ALT 19 | T bili 0.5", source: "Labs 2026-09-22" },
        { quote: "Albumin 3.8", source: "Labs 2026-09-22" },
      ],
      actionNeeded: "Obtain HBsAg, anti-HBc and HCV antibody (reflex HCV RNA); active hepatitis B or C excludes",
    },
    {
      id: "NCT07198724-exc-11",
      status: "pass",
      confidence: "medium",
      rationale: "No malignancy other than the breast cancer is recorded; family history is the only other cancer mentioned.",
    },
  ],
);
