// Generated by scripts/build-match-index.ts (npm run demo:index). Do not edit by hand.
import type { TrialMatch } from "@/lib/types";
import m0 from "./matches/aisha-k/NCT04468061";
import m1 from "./matches/aisha-k/NCT04585750";
import m2 from "./matches/aisha-k/NCT04683679";
import m3 from "./matches/aisha-k/NCT05318469";
import m4 from "./matches/aisha-k/NCT05422794";
import m5 from "./matches/aisha-k/NCT05741164";
import m6 from "./matches/aisha-k/NCT06103864";
import m7 from "./matches/aisha-k/NCT06249048";
import m8 from "./matches/aisha-k/NCT06324240";
import m9 from "./matches/aisha-k/NCT06492759";
import m10 from "./matches/aisha-k/NCT06637306";
import m11 from "./matches/aisha-k/NCT06841354";
import m12 from "./matches/aisha-k/NCT06926868";
import m13 from "./matches/aisha-k/NCT06963905";
import m14 from "./matches/aisha-k/NCT07078604";
import m15 from "./matches/aisha-k/NCT07173751";
import m16 from "./matches/danielle-r/NCT04333706";
import m17 from "./matches/danielle-r/NCT04434040";
import m18 from "./matches/danielle-r/NCT04768426";
import m19 from "./matches/danielle-r/NCT05633654";
import m20 from "./matches/danielle-r/NCT05812807";
import m21 from "./matches/danielle-r/NCT05929768";
import m22 from "./matches/danielle-r/NCT06134375";
import m23 from "./matches/danielle-r/NCT06245889";
import m24 from "./matches/danielle-r/NCT06324240";
import m25 from "./matches/danielle-r/NCT06393374";
import m26 from "./matches/danielle-r/NCT06435351";
import m27 from "./matches/danielle-r/NCT06637306";
import m28 from "./matches/danielle-r/NCT06797635";
import m29 from "./matches/danielle-r/NCT07069595";
import m30 from "./matches/danielle-r/NCT07407920";
import m31 from "./matches/danielle-r/NCT07652242";
import m32 from "./matches/helen-w/NCT02476786";
import m33 from "./matches/helen-w/NCT04553770";
import m34 from "./matches/helen-w/NCT05472792";
import m35 from "./matches/helen-w/NCT05774951";
import m36 from "./matches/helen-w/NCT05795101";
import m37 from "./matches/helen-w/NCT05827081";
import m38 from "./matches/helen-w/NCT05868226";
import m39 from "./matches/helen-w/NCT06058377";
import m40 from "./matches/helen-w/NCT06444269";
import m41 from "./matches/helen-w/NCT06492616";
import m42 from "./matches/helen-w/NCT06507618";
import m43 from "./matches/helen-w/NCT06517212";
import m44 from "./matches/helen-w/NCT07137416";
import m45 from "./matches/helen-w/NCT07191717";
import m46 from "./matches/helen-w/NCT07391774";
import m47 from "./matches/helen-w/NCT07541079";
import m48 from "./matches/james-t/NCT05216432";
import m49 from "./matches/james-t/NCT05950945";
import m50 from "./matches/james-t/NCT06224673";
import m51 from "./matches/james-t/NCT06263543";
import m52 from "./matches/james-t/NCT06312176";
import m53 from "./matches/james-t/NCT06380751";
import m54 from "./matches/james-t/NCT06488378";
import m55 from "./matches/james-t/NCT06533826";
import m56 from "./matches/james-t/NCT06568692";
import m57 from "./matches/james-t/NCT06790693";
import m58 from "./matches/james-t/NCT07060807";
import m59 from "./matches/james-t/NCT07062965";
import m60 from "./matches/james-t/NCT07112053";
import m61 from "./matches/james-t/NCT07137416";
import m62 from "./matches/james-t/NCT07198724";
import m63 from "./matches/james-t/NCT07287917";
import m64 from "./matches/linda-p/NCT04802759";
import m65 from "./matches/linda-p/NCT05573126";
import m66 from "./matches/linda-p/NCT05646862";
import m67 from "./matches/linda-p/NCT05696626";
import m68 from "./matches/linda-p/NCT05716516";
import m69 from "./matches/linda-p/NCT06062498";
import m70 from "./matches/linda-p/NCT06369285";
import m71 from "./matches/linda-p/NCT06726148";
import m72 from "./matches/linda-p/NCT07060807";
import m73 from "./matches/linda-p/NCT07062965";
import m74 from "./matches/linda-p/NCT07085767";
import m75 from "./matches/linda-p/NCT07198724";
import m76 from "./matches/linda-p/NCT07222215";
import m77 from "./matches/linda-p/NCT07288359";
import m78 from "./matches/linda-p/NCT07368998";
import m79 from "./matches/linda-p/NCT07612215";
import m80 from "./matches/margaret-h/NCT04802759";
import m81 from "./matches/margaret-h/NCT05216432";
import m82 from "./matches/margaret-h/NCT05455619";
import m83 from "./matches/margaret-h/NCT05646862";
import m84 from "./matches/margaret-h/NCT05950945";
import m85 from "./matches/margaret-h/NCT06263543";
import m86 from "./matches/margaret-h/NCT06533826";
import m87 from "./matches/margaret-h/NCT06757634";
import m88 from "./matches/margaret-h/NCT06790693";
import m89 from "./matches/margaret-h/NCT06982521";
import m90 from "./matches/margaret-h/NCT07174336";
import m91 from "./matches/margaret-h/NCT07198724";
import m92 from "./matches/margaret-h/NCT07287917";
import m93 from "./matches/margaret-h/NCT07368998";
import m94 from "./matches/margaret-h/NCT07383506";
import m95 from "./matches/margaret-h/NCT07405801";
import m96 from "./matches/priya-s/NCT01042379";
import m97 from "./matches/priya-s/NCT02945579";
import m98 from "./matches/priya-s/NCT04144023";
import m99 from "./matches/priya-s/NCT04329065";
import m100 from "./matches/priya-s/NCT04886531";
import m101 from "./matches/priya-s/NCT04893109";
import m102 from "./matches/priya-s/NCT05035836";
import m103 from "./matches/priya-s/NCT05559164";
import m104 from "./matches/priya-s/NCT05795101";
import m105 from "./matches/priya-s/NCT06876714";
import m106 from "./matches/priya-s/NCT06949410";
import m107 from "./matches/priya-s/NCT07102381";
import m108 from "./matches/priya-s/NCT07220135";
import m109 from "./matches/priya-s/NCT07402473";
import m110 from "./matches/priya-s/NCT07407920";
import m111 from "./matches/priya-s/NCT07506876";
import m112 from "./matches/rosa-v/NCT04348747";
import m113 from "./matches/rosa-v/NCT04899908";
import m114 from "./matches/rosa-v/NCT05748834";
import m115 from "./matches/rosa-v/NCT05894239";
import m116 from "./matches/rosa-v/NCT05950945";
import m117 from "./matches/rosa-v/NCT05969860";
import m118 from "./matches/rosa-v/NCT06324357";
import m119 from "./matches/rosa-v/NCT06435429";
import m120 from "./matches/rosa-v/NCT06439693";
import m121 from "./matches/rosa-v/NCT06686394";
import m122 from "./matches/rosa-v/NCT06949410";
import m123 from "./matches/rosa-v/NCT07007559";
import m124 from "./matches/rosa-v/NCT07136428";
import m125 from "./matches/rosa-v/NCT07413939";
import m126 from "./matches/rosa-v/NCT07441889";
import m127 from "./matches/rosa-v/NCT07459673";

/**
 * Precomputed criterion-level matches for demo mode:
 *   DEMO_MATCHES[patientId][nctId] → TrialMatch
 * One file per patient × trial under ./matches/<patient>/, authored with
 * demoMatch() from ./match-helpers and checked by ./matches.test.ts.
 */
export const DEMO_MATCHES: Record<string, Record<string, TrialMatch>> = {
  "aisha-k": {
    NCT04468061: m0,
    NCT04585750: m1,
    NCT04683679: m2,
    NCT05318469: m3,
    NCT05422794: m4,
    NCT05741164: m5,
    NCT06103864: m6,
    NCT06249048: m7,
    NCT06324240: m8,
    NCT06492759: m9,
    NCT06637306: m10,
    NCT06841354: m11,
    NCT06926868: m12,
    NCT06963905: m13,
    NCT07078604: m14,
    NCT07173751: m15,
  },
  "danielle-r": {
    NCT04333706: m16,
    NCT04434040: m17,
    NCT04768426: m18,
    NCT05633654: m19,
    NCT05812807: m20,
    NCT05929768: m21,
    NCT06134375: m22,
    NCT06245889: m23,
    NCT06324240: m24,
    NCT06393374: m25,
    NCT06435351: m26,
    NCT06637306: m27,
    NCT06797635: m28,
    NCT07069595: m29,
    NCT07407920: m30,
    NCT07652242: m31,
  },
  "helen-w": {
    NCT02476786: m32,
    NCT04553770: m33,
    NCT05472792: m34,
    NCT05774951: m35,
    NCT05795101: m36,
    NCT05827081: m37,
    NCT05868226: m38,
    NCT06058377: m39,
    NCT06444269: m40,
    NCT06492616: m41,
    NCT06507618: m42,
    NCT06517212: m43,
    NCT07137416: m44,
    NCT07191717: m45,
    NCT07391774: m46,
    NCT07541079: m47,
  },
  "james-t": {
    NCT05216432: m48,
    NCT05950945: m49,
    NCT06224673: m50,
    NCT06263543: m51,
    NCT06312176: m52,
    NCT06380751: m53,
    NCT06488378: m54,
    NCT06533826: m55,
    NCT06568692: m56,
    NCT06790693: m57,
    NCT07060807: m58,
    NCT07062965: m59,
    NCT07112053: m60,
    NCT07137416: m61,
    NCT07198724: m62,
    NCT07287917: m63,
  },
  "linda-p": {
    NCT04802759: m64,
    NCT05573126: m65,
    NCT05646862: m66,
    NCT05696626: m67,
    NCT05716516: m68,
    NCT06062498: m69,
    NCT06369285: m70,
    NCT06726148: m71,
    NCT07060807: m72,
    NCT07062965: m73,
    NCT07085767: m74,
    NCT07198724: m75,
    NCT07222215: m76,
    NCT07288359: m77,
    NCT07368998: m78,
    NCT07612215: m79,
  },
  "margaret-h": {
    NCT04802759: m80,
    NCT05216432: m81,
    NCT05455619: m82,
    NCT05646862: m83,
    NCT05950945: m84,
    NCT06263543: m85,
    NCT06533826: m86,
    NCT06757634: m87,
    NCT06790693: m88,
    NCT06982521: m89,
    NCT07174336: m90,
    NCT07198724: m91,
    NCT07287917: m92,
    NCT07368998: m93,
    NCT07383506: m94,
    NCT07405801: m95,
  },
  "priya-s": {
    NCT01042379: m96,
    NCT02945579: m97,
    NCT04144023: m98,
    NCT04329065: m99,
    NCT04886531: m100,
    NCT04893109: m101,
    NCT05035836: m102,
    NCT05559164: m103,
    NCT05795101: m104,
    NCT06876714: m105,
    NCT06949410: m106,
    NCT07102381: m107,
    NCT07220135: m108,
    NCT07402473: m109,
    NCT07407920: m110,
    NCT07506876: m111,
  },
  "rosa-v": {
    NCT04348747: m112,
    NCT04899908: m113,
    NCT05748834: m114,
    NCT05894239: m115,
    NCT05950945: m116,
    NCT05969860: m117,
    NCT06324357: m118,
    NCT06435429: m119,
    NCT06439693: m120,
    NCT06686394: m121,
    NCT06949410: m122,
    NCT07007559: m123,
    NCT07136428: m124,
    NCT07413939: m125,
    NCT07441889: m126,
    NCT07459673: m127,
  },
};
