"use client";

import { useEffect, useRef, useState } from "react";
import { AnimatePresence, motion } from "motion/react";
import { Copy } from "lucide-react";
import { Badge, Button, GlassPanel, cn } from "@/components/ui";
import { formatPhase, formatStatus, tierLabel } from "@/lib/ctgov/format";
import {
  rankTrials,
  useShortlistedCount,
  useTierCounts,
  useWorkspace,
  type WorkspaceState,
} from "./store";
import { TIERS, TIER_DOT, formatInt, patientDisplay } from "./labels";

/** Plain-text export of the shortlisted trials. */
export function buildShortlistText(state: WorkspaceState): string {
  const { profile, patientLabel, trials, matches, matchStatus, reviews } = state;
  const patient = patientDisplay(profile, patientLabel);
  const ranked = rankTrials(trials, matches, matchStatus, reviews).filter(
    (e) => e.review === "shortlisted" && e.match,
  );
  const screened = Object.keys(matches).length;
  const strong = Object.values(matches).filter((m) => m.tier === "strong").length;
  const possible = Object.values(matches).filter((m) => m.tier === "possible").length;

  const lines: string[] = [];
  lines.push(`Trial shortlist — ${patient.label}${patient.ageSex ? ` (${patient.ageSex})` : ""}`);
  lines.push(
    `${screened} trials screened · ${strong} strong · ${possible} possible · ${ranked.length} shortlisted`,
  );
  lines.push("");

  ranked.forEach((e, i) => {
    const m = e.match!;
    const textById = new Map(e.trial.criteria.map((c) => [c.id, c.text]));
    const short = (id: string) => {
      const t = textById.get(id) ?? id;
      return t.length > 140 ? `${t.slice(0, 137).trimEnd()}…` : t;
    };
    lines.push(`${i + 1}. ${e.trial.nctId} — ${e.trial.title}`);
    lines.push(
      `   ${tierLabel(m.tier)} · score ${m.score}/100 · ${formatPhase(e.trial.phases)} · ${formatStatus(e.trial.status)}`,
    );
    lines.push(`   ${m.headline}`);
    lines.push(
      m.blockers.length > 0 ? `   Blockers: ${m.blockers.map(short).join("; ")}` : "   Blockers: none",
    );
    if (m.confirmations.length > 0) {
      lines.push(`   To confirm: ${m.confirmations.map(short).join("; ")}`);
    }
    lines.push(`   ${e.trial.url}`);
    lines.push("");
  });

  lines.push("Generated by Trial Matcher (prototype). Verdicts require clinician review.");
  return lines.join("\n");
}

async function copyText(text: string): Promise<void> {
  try {
    await navigator.clipboard.writeText(text);
  } catch {
    const el = document.createElement("textarea");
    el.value = text;
    el.setAttribute("readonly", "");
    el.style.position = "fixed";
    el.style.opacity = "0";
    document.body.appendChild(el);
    el.select();
    document.execCommand("copy");
    document.body.removeChild(el);
  }
}

function CopyShortlist() {
  const shortlisted = useShortlistedCount();
  const [copied, setCopied] = useState(false);
  const timer = useRef<number | undefined>(undefined);

  useEffect(() => () => window.clearTimeout(timer.current), []);

  const onCopy = async () => {
    await copyText(buildShortlistText(useWorkspace.getState()));
    setCopied(true);
    window.clearTimeout(timer.current);
    timer.current = window.setTimeout(() => setCopied(false), 1800);
  };

  return (
    <span className="inline-flex items-center gap-2">
      <AnimatePresence>
        {copied && (
          <motion.span
            initial={{ opacity: 0, y: 4 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -4 }}
            transition={{ duration: 0.18, ease: "easeOut" }}
            role="status"
          >
            <Badge tone="accent" dot>
              Copied
            </Badge>
          </motion.span>
        )}
      </AnimatePresence>
      <Button
        variant="secondary"
        size="sm"
        icon={<Copy />}
        onClick={() => void onCopy()}
        disabled={shortlisted === 0}
        title={shortlisted === 0 ? "Shortlist a trial first" : "Copy the shortlist as plain text"}
      >
        Copy shortlist
      </Button>
    </span>
  );
}

function ProgressBar({ done, total }: { done: number; total: number }) {
  const fraction = total > 0 ? done / total : 0;
  return (
    <div
      className="mt-3 h-0.5 w-full overflow-hidden rounded-full bg-ink-100"
      role="progressbar"
      aria-valuemin={0}
      aria-valuemax={total}
      aria-valuenow={done}
      aria-label="Screening progress"
    >
      {done === 0 ? (
        <div className="h-full w-full animate-shimmer bg-[linear-gradient(90deg,transparent,var(--color-accent-400),transparent)] bg-[length:50%_100%]" />
      ) : (
        <div
          className="h-full w-full origin-left bg-accent-500 transition-transform duration-300 ease-out-quart"
          style={{ transform: `scaleX(${fraction})` }}
        />
      )}
    </div>
  );
}

export function SummaryStrip() {
  const counts = useTierCounts();
  const matching = useWorkspace((s) => s.matching);
  const trialsMeta = useWorkspace((s) => s.trialsMeta);
  const done = counts.screened + counts.errors;

  return (
    <GlassPanel as="section" aria-label="Screening summary" padding="none" className="px-5 py-3.5">
      <div className="flex flex-wrap items-center justify-between gap-x-6 gap-y-3">
        <div className="flex flex-wrap items-center gap-x-3 gap-y-1 text-[13.5px] text-ink-600">
          {matching ? (
            <span className="font-mono text-[13px] tnum text-ink-800" aria-live="polite">
              Screening {done} / {counts.total}
            </span>
          ) : (
            <span className="tnum">
              <span className="font-medium text-ink-900">{formatInt(counts.total)}</span> trials screened
            </span>
          )}
          {TIERS.map((tier) => (
            <span key={tier} className="flex items-center gap-1.5">
              <span className={cn("size-1.5 rounded-full", TIER_DOT[tier])} aria-hidden />
              <span className="tnum">
                <span className="font-medium text-ink-800">{counts[tier]}</span> {tier}
              </span>
            </span>
          ))}
        </div>
        <div className="flex flex-wrap items-center gap-2">
          {trialsMeta && (
            <>
              <Badge tone="neutral" className="max-w-[320px]" title={trialsMeta.queryDescription}>
                <span className="min-w-0 truncate">{trialsMeta.queryDescription}</span>
              </Badge>
              <Badge tone="neutral" dot>
                {trialsMeta.source === "registry" ? "ClinicalTrials.gov" : "Bundled fixture"}
              </Badge>
            </>
          )}
          <CopyShortlist />
        </div>
      </div>
      {matching && <ProgressBar done={done} total={counts.total} />}
    </GlassPanel>
  );
}
