import { demoMatch } from "../../match-helpers";

export default demoMatch(
  "NCT06435429",
  "Fits the post-T-DXd design · hepatitis/HIV serology and grade 2 neuropathy exception to confirm",
  "Rosa matches the core of this phase 3 study: HER2 IHC 3+ disease that progressed on T-DXd in July 2026 after two HER2-directed lines, measurable liver disease, treated and stable brain metastases off steroids, ECOG 1 and adequate labs and LVEF (55%). Open items are hepatitis B/C and HIV serology, whether her residual grade 2 docetaxel neuropathy is a protocol exception, and central HER2 confirmation on 2024 tissue; capecitabine or gemcitabine would suit her as the partner chemotherapy. Enrolling means forgoing tucatinib-based third-line therapy, which has intracranial activity, at least until progression; with SRS on 8/7/26, restaging CT (last 7/20) and repeat MRI will be needed within the screening window.",
  [
    {
      id: "NCT06435429-inc-1",
      status: "pass",
      rationale: "She is 66 years old.",
      evidence: [{ quote: "66 yo postmenopausal F", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT06435429-inc-2",
      status: "pass",
      confidence: "medium",
      rationale: "Local IHC 3+ on both the primary core and the liver metastasis (01/2024) is HER2-positive by ASCO-CAP; central confirmation is pending and there has been no biopsy since T-DXd.",
      evidence: [
        { quote: "HER2 IHC: 3+ (positive), complete intense circumferential staining in >10% of cells", source: "Pathology 2024-01-19" },
        { quote: "Note: no repeat biopsy at progression on T-DXd; HER2 status per 2024 tissue.", source: "Pathology" },
      ],
      actionNeeded: "Send archival 2024 tissue (or a fresh biopsy) to the central lab for HER2 confirmation",
    },
    {
      id: "NCT06435429-inc-3",
      status: "pass",
      rationale: "Metastatic HER2-positive disease that progressed on T-DXd: liver progression and three new brain metastases in 7/2026, T-DXd stopped for PD.",
      evidence: [
        { quote: "7/2026: PD in liver + new HA -> MRI brain 7/22/26 w/ 3 new brain mets (largest 1.4 cm R frontal).", source: "Onc note 2026-09-24" },
        { quote: "trastuzumab deruxtecan - DISCONTINUED 07/2026 (PD)", source: "Medications" },
      ],
    },
    {
      id: "NCT06435429-inc-4",
      status: "pass",
      rationale: "Two HER2-directed lines for metastatic disease: first-line THP then trastuzumab/pertuzumab maintenance, and second-line T-DXd.",
      evidence: [{ quote: "PD on 1L THP/HP and 2L T-DXd.", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT06435429-inc-5",
      status: "pass",
      rationale: "Two HER2-directed lines in the metastatic setting, below the maximum of four; no prior tucatinib, T-DM1, lapatinib or neratinib.",
      evidence: [{ quote: "No prior tucatinib, T-DM1, lapatinib or neratinib.", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT06435429-inc-6",
      status: "pass",
      rationale: "Measurable liver metastases of 2.8 cm (segment VII) and 2.2 cm (segment V) on CT 7/20/26, both ≥ 1 cm.",
      evidence: [{ quote: "Measurable liver dz: seg VII 2.8 cm, seg V 2.2 cm.", source: "Onc note 2026-09-24" }],
      actionNeeded: "Repeat CT chest/abdomen/pelvis within the screening window (last scan 7/20/26, 10 weeks ago)",
    },
    {
      id: "NCT06435429-inc-7",
      status: "pass",
      confidence: "medium",
      rationale: "Capecitabine (CrCl ~62 mL/min, bilirubin 0.8) or gemcitabine are suitable options; residual grade 2 neuropathy makes eribulin or vinorelbine less attractive.",
      evidence: [
        { quote: "Cr 0.9 | est CrCl ~62 mL/min (CG)", source: "Labs 2026-09-22" },
        { quote: "Residual G2 PN hands/feet from docetaxel", source: "Onc note 2026-09-24" },
      ],
    },
    {
      id: "NCT06435429-inc-8",
      status: "pass",
      rationale: "Three brain metastases treated with Gamma Knife SRS on 8/7/26 (52 days ago), smaller with no new lesions on MRI 9/12/26, asymptomatic and off dexamethasone since 8/30/26.",
      evidence: [
        { quote: "Treated brain mets (GK SRS 8/7/26) stable on 9/12 MRI, off steroids.", source: "Onc note 2026-09-24" },
        { quote: "No new enhancing lesions. No vasogenic edema, no mass effect, no hemorrhage.", source: "MRI brain 2026-09-12" },
      ],
      actionNeeded: "Confirm the protocol's post-SRS and steroid-free intervals; repeat brain MRI if 9/12/26 falls outside the screening window",
    },
    {
      id: "NCT06435429-inc-9",
      status: "pass",
      confidence: "medium",
      rationale: "ECOG 1 with normal bilirubin, controlled intracranial disease and several remaining HER2-directed options; a life expectancy of ≥ 6 months is reasonable.",
      evidence: [{ quote: "EXAM: ECOG 1.", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT06435429-inc-10",
      status: "pass",
      rationale: "ANC 3.1, platelets 165 and hemoglobin 10.9 g/dL on 2026-09-22 meet standard thresholds (ANC ≥ 1.5, platelets ≥ 100, Hgb ≥ 9).",
      evidence: [{ quote: "WBC 5.8 | ANC 3.1 | Hgb 10.9 (L) | Plt 165", source: "Labs 2026-09-22" }],
    },
    {
      id: "NCT06435429-inc-11",
      status: "pass",
      rationale: "Bilirubin 0.8 mg/dL, AST 52 (1.3 × ULN), ALT 48 and albumin 3.6 on 2026-09-22; transaminases are within ≤ 2.5 × ULN even before the liver-metastasis allowance.",
      evidence: [{ quote: "AST 52 (H, 1.3x ULN) | ALT 48 (H) | T bili 0.8 | Alk phos 130 (H) | Albumin 3.6", source: "Labs 2026-09-22" }],
    },
    {
      id: "NCT06435429-inc-12",
      status: "pass",
      rationale: "Estimated CrCl ~62 mL/min by Cockcroft-Gault on 2026-09-22, above the 50 mL/min minimum.",
      evidence: [{ quote: "est CrCl ~62 mL/min (CG)", source: "Labs 2026-09-22" }],
    },
    {
      id: "NCT06435429-inc-13",
      status: "pass",
      rationale: "LVEF 55% by echo on 2026-09-10 (18 days ago), above 50%; down from 62% in 2024 and asymptomatic. The 4-week window closes on 2026-10-08.",
      evidence: [{ quote: "ECHO 2026-09-10: LVEF 55% (biplane Simpson's).", source: "Echo 2026-09-10" }],
      actionNeeded: "Repeat echocardiogram if first dose falls after 2026-10-08; LVEF ≥ 50% required",
    },
    {
      id: "NCT06435429-inc-14",
      status: "pass",
      rationale: "ECOG 1 at the 2026-09-24 visit.",
      evidence: [{ quote: "EXAM: ECOG 1.", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT06435429-inc-15",
      status: "pass",
      confidence: "low",
      rationale: "Lead-in to the sex-specific requirements; only the female provisions apply to her, confirmed at screening.",
    },
    {
      id: "NCT06435429-inc-16",
      status: "not-applicable",
      rationale: "Male-participant requirement; the patient is female.",
    },
    {
      id: "NCT06435429-inc-17",
      status: "pass",
      rationale: "66-year-old postmenopausal woman: not pregnant or breastfeeding and of non-childbearing potential.",
      evidence: [{ quote: "66 yo postmenopausal F", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT06435429-inc-18",
      status: "pass",
      confidence: "low",
      rationale: "Capacity to consent is confirmed at screening; she is alert and open to a trial if screening is prompt.",
      evidence: [{ quote: "Pt open to trial if screening within 3-4 wks.", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT06435429-exc-1",
      status: "pass",
      confidence: "medium",
      rationale: "No leptomeningeal disease on the 9/12/26 contrast MRI, which shows only the treated parenchymal lesions, and she has no neurological symptoms.",
      evidence: [{ quote: "all decreased, consistent with treatment response", source: "MRI brain 2026-09-12" }],
    },
    {
      id: "NCT06435429-exc-2",
      status: "pass",
      confidence: "medium",
      rationale: "Hypertension controlled on lisinopril (BP 128/74), no CAD, LVEF 55% and asymptomatic; ECG/QTc is not on file.",
      evidence: [
        { quote: "BP 128/74 HR 82 SpO2 97% RA.", source: "Exam 2026-09-24" },
        { quote: "No CAD.", source: "PMH" },
      ],
    },
    {
      id: "NCT06435429-exc-3",
      status: "unknown",
      confidence: "medium",
      rationale: "Residual grade 2 peripheral neuropathy from docetaxel persists (stable, on gabapentin); whether it falls under the protocol's exceptions is not stated here.",
      evidence: [{ quote: "G2 PN (docetaxel): stable, gabapentin 300 mg qhs.", source: "Onc note 2026-09-24" }],
      actionNeeded: "Confirm with the protocol whether stable grade 2 peripheral neuropathy is an allowed exception",
    },
    {
      id: "NCT06435429-exc-4",
      status: "pass",
      confidence: "medium",
      rationale: "No infection or IV antimicrobials recorded; no cough or dyspnoea and SpO2 97%.",
      evidence: [{ quote: "No cough/SOB.", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT06435429-exc-5",
      status: "unknown",
      confidence: "low",
      rationale: "HIV status is not documented; no HIV in the PMH.",
      actionNeeded: "Obtain HIV-1/2 serology; only well-controlled HIV is allowed",
    },
    {
      id: "NCT06435429-exc-6",
      status: "unknown",
      confidence: "low",
      rationale: "Hepatitis B and C status is not documented; the mild AST/ALT rise is likely from liver metastases.",
      evidence: [{ quote: "AST 52 (H, 1.3x ULN)", source: "Labs 2026-09-22" }],
      actionNeeded: "Obtain HBsAg, anti-HBc and anti-HCV (with HBV DNA/HCV RNA if positive); active infection excludes",
    },
    {
      id: "NCT06435429-exc-7",
      status: "pass",
      confidence: "medium",
      rationale: "No respiratory symptoms (no cough or dyspnoea, lungs clear, SpO2 97%) and no recent infection recorded.",
      evidence: [{ quote: "No cough/SOB.", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT06435429-exc-8",
      status: "pass",
      confidence: "medium",
      rationale: "She received trastuzumab, pertuzumab (IV and subcutaneous Phesgo) and T-DXd over 2.5 years with no reactions recorded; NKDA.",
      evidence: [{ quote: "ALLERGIES: NKDA", source: "Allergies" }],
    },
    {
      id: "NCT06435429-exc-9",
      status: "pass",
      rationale: "She has received trastuzumab-based therapy since 2/2024 without documented contraindication, and LVEF is 55%.",
      evidence: [{ quote: "1L THP (docetaxel x6, 2/2024-6/2024) then HP maint (Phesgo), best response PR", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT06435429-exc-10",
      status: "pass",
      confidence: "medium",
      rationale: "Comorbidities are controlled (T2DM with A1c 6.9%, hypertension, hypothyroidism with TSH 2.4); no psychiatric history.",
      evidence: [{ quote: "T2DM (metformin, A1c 6.9% 7/2026)", source: "PMH" }],
    },
    {
      id: "NCT06435429-exc-11",
      status: "pass",
      confidence: "medium",
      rationale: "Adequate renal and hepatic function supports capecitabine or gemcitabine; grade 2 neuropathy argues against eribulin or vinorelbine but does not prevent all options.",
      evidence: [{ quote: "est CrCl ~62 mL/min (CG)", source: "Labs 2026-09-22" }],
    },
    {
      id: "NCT06435429-exc-12",
      status: "pass",
      confidence: "medium",
      rationale: "No contraindicating condition is recorded beyond her cancer and controlled comorbidities.",
    },
    {
      id: "NCT06435429-exc-13",
      status: "pass",
      confidence: "medium",
      rationale: "No transplant history; the surgical history lists only a port placement.",
      evidence: [{ quote: "PSH: port 2/2024. No breast surgery.", source: "PSH" }],
    },
    {
      id: "NCT06435429-exc-14",
      status: "pass",
      confidence: "medium",
      rationale: "Last T-DXd 2026-07-06 (84 days ago) and SRS 8/7/26 (52 days ago) exceed usual washouts; she is on no anticancer therapy now.",
      evidence: [{ quote: "2L T-DXd 5.4 mg/kg 4/2025-7/2026 (last dose 07/06/2026)", source: "Onc note 2026-09-24" }],
      actionNeeded: "Check the protocol's specific washout periods against these dates",
    },
    {
      id: "NCT06435429-exc-15",
      status: "pass",
      rationale: "No trauma or surgery in the past 4 weeks; her only procedure was a port placement in 2/2024.",
      evidence: [{ quote: "PSH: port 2/2024. No breast surgery.", source: "PSH" }],
    },
    {
      id: "NCT06435429-exc-16",
      status: "pass",
      rationale: "No known drug allergies, and she has tolerated trastuzumab previously.",
      evidence: [{ quote: "ALLERGIES: NKDA", source: "Allergies" }],
    },
    {
      id: "NCT06435429-exc-17",
      status: "not-applicable",
      rationale: "She is 66 and postmenopausal; pregnancy, breastfeeding and pregnancy planning do not apply.",
    },
  ],
);
