import { demoMatch } from "../../match-helpers";

export default demoMatch(
  "NCT07007559",
  "Fits the post-T-DXd HER2+ population · needs a fresh post-T-DXd biopsy and DPD status",
  "Good fit for evorpacept plus trastuzumab and chemotherapy after T-DXd: HER2 3+, two prior HER2-directed lines including T-DXd with progression in July 2026, measurable liver disease, treated brain metastases, ECOG 1 and adequate organ function. Entry requires a new biopsy taken after T-DXd confirming HER2 positivity; the progressing liver lesions are accessible, and HER2 loss after T-DXd would exclude her. Her grade 2 neuropathy points to capecitabine or gemcitabine as the chemotherapy partner, so DPD status should be checked.",
  [
    {
      id: "NCT07007559-inc-1",
      status: "unknown",
      confidence: "medium",
      rationale: "HER2 3+ status rests on 2024 tissue; no biopsy has been taken since T-DXd stopped (last dose 2026-07-06), so the required post-T-DXd tissue confirming HER2 positivity does not yet exist.",
      evidence: [{ quote: "no repeat biopsy at progression on T-DXd; HER2 status per 2024 tissue", source: "Pathology" }],
      actionNeeded: "Biopsy a progressing liver lesion before C1D1 and confirm HER2-positive (IHC 3+ or ISH+); tissue must be ≤ 6 months old at C1D1",
    },
    {
      id: "NCT07007559-inc-2",
      status: "pass",
      rationale: "Two HER2-directed lines for metastatic disease, including T-DXd (04/2025–07/2026), within the limit of four.",
      evidence: [
        { quote: "Metastatic HER2+ (IHC 3+) HR-negative breast ca, de novo stage IV, PD on 1L THP/HP and 2L T-DXd.", source: "Onc note 2026-09-24" },
      ],
    },
    {
      id: "NCT07007559-inc-3",
      status: "pass",
      rationale: "Progressed on T-DXd, her most recent line: liver progression on CT 07/20/2026 and three new brain metastases on MRI 07/22/2026.",
      evidence: [
        { quote: "7/2026: PD in liver + new HA -> MRI brain 7/22/26 w/ 3 new brain mets (largest 1.4 cm R frontal).", source: "Onc note 2026-09-24" },
        { quote: "trastuzumab deruxtecan - DISCONTINUED 07/2026 (PD)", source: "Medications" },
      ],
    },
    {
      id: "NCT07007559-inc-4",
      status: "pass",
      confidence: "medium",
      rationale: "Capecitabine or gemcitabine remain suitable (CrCl ~62 mL/min, bilirubin normal); her grade 2 neuropathy makes paclitaxel, eribulin and vinorelbine less appropriate.",
      evidence: [
        { quote: "Residual G2 PN hands/feet from docetaxel", source: "Onc note 2026-09-24" },
        { quote: "Cr 0.9 | est CrCl ~62 mL/min (CG)", source: "Labs 2026-09-22" },
      ],
      actionNeeded: "Choose a non-neurotoxic chemotherapy partner; check DPD status before capecitabine",
    },
    {
      id: "NCT07007559-inc-5",
      status: "pass",
      rationale: "Measurable liver metastases of 2.8 cm (segment VII) and 2.2 cm (segment V) on CT 07/20/2026.",
      evidence: [{ quote: "Measurable liver dz: seg VII 2.8 cm, seg V 2.2 cm.", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT07007559-inc-6",
      status: "pass",
      rationale: "LVEF 55% on echo 2026-09-10, asymptomatic.",
      evidence: [{ quote: "ECHO 2026-09-10: LVEF 55% (biplane Simpson's).", source: "Echo 2026-09-10" }],
    },
    {
      id: "NCT07007559-inc-7",
      status: "pass",
      rationale: "ECOG 1 at the 2026-09-24 visit.",
      evidence: [{ quote: "EXAM: ECOG 1.", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT07007559-inc-8",
      status: "pass",
      confidence: "medium",
      rationale: "ECOG 1 with normal bilirubin and controlled brain disease; life expectancy well beyond 3 months is expected.",
    },
    {
      id: "NCT07007559-inc-9",
      status: "pass",
      rationale: "Cockcroft-Gault CrCl ~62 mL/min (creatinine 0.9, 2026-09-22), above the 30 mL/min threshold.",
      evidence: [{ quote: "Cr 0.9 | est CrCl ~62 mL/min (CG)", source: "Labs 2026-09-22" }],
    },
    {
      id: "NCT07007559-inc-10",
      status: "pass",
      rationale: "Bilirubin 0.8 mg/dL; AST 52 (1.3 × ULN) and ALT 48 with liver metastases, well within ≤ 5 × ULN (labs 2026-09-22).",
      evidence: [{ quote: "AST 52 (H, 1.3x ULN) | ALT 48 (H) | T bili 0.8", source: "Labs 2026-09-22" }],
    },
    {
      id: "NCT07007559-inc-11",
      status: "pass",
      confidence: "medium",
      rationale: "Residual grade 2 neuropathy from docetaxel is more than 2 years old, stable and likely irreversible; it fits the exception for non-reversible AEs if the investigator judges it no safety risk.",
      evidence: [{ quote: "G2 PN (docetaxel): stable, gabapentin 300 mg qhs.", source: "Onc note 2026-09-24" }],
      actionNeeded: "Investigator to document the neuropathy as irreversible and not a safety risk",
    },
    {
      id: "NCT07007559-exc-1",
      status: "pass",
      rationale: "No untreated CNS metastases: all three lesions were treated with SRS on 2026-08-07, and MRI 2026-09-12 shows no new lesions.",
      evidence: [{ quote: "MRI brain 9/12/26: treated lesions smaller, no new lesions, no edema.", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT07007559-exc-2",
      status: "pass",
      confidence: "medium",
      rationale: "No anti-CD47 or anti-SIRPα exposure: her prior agents were docetaxel, trastuzumab, pertuzumab and T-DXd.",
    },
    {
      id: "NCT07007559-exc-3",
      status: "pass",
      confidence: "medium",
      rationale: "She has received trastuzumab-based therapy since 2024 without documented cardiotoxicity; LVEF is 55% (2026-09-10), though down from 62% at baseline.",
      evidence: [{ quote: "Prior LVEF 62% (01/2024), 58% (03/2025).", source: "Echo 2026-09-10" }],
    },
    {
      id: "NCT07007559-exc-4",
      status: "unknown",
      confidence: "medium",
      rationale: "She has never received a fluoropyrimidine, so there is no prior 5-FU toxicity, but DPD status has not been tested.",
      actionNeeded: "Obtain DPYD genotyping (or DPD phenotype); complete DPD deficiency excludes",
    },
    {
      id: "NCT07007559-exc-5",
      status: "pass",
      rationale: "Last T-DXd 2026-07-06 is 84 days ago (> 28 days for an ADC) and SRS 2026-08-07 is 52 days ago (> 14 days); the 'T-DXd C14 D1 today' line is a stale copy-forward.",
      evidence: [
        { quote: "trastuzumab deruxtecan - DISCONTINUED 07/2026 (PD)", source: "Medications" },
        { quote: "GK SRS to all 3 lesions 8/7/26 (20 Gy).", source: "Onc note 2026-09-24" },
      ],
    },
    {
      id: "NCT07007559-exc-6",
      status: "pass",
      confidence: "medium",
      rationale: "Chronic mild anemia (Hgb 10.9) without bleeding, but no autoimmune hemolysis, immune thrombocytopenia (platelets 165) or transfusion reaction is recorded.",
      evidence: [{ quote: "Mild anemia Hgb 10.9, chronic, no bleeding.", source: "Onc note 2026-09-24" }],
      actionNeeded: "Consider a hemolysis screen (reticulocytes, LDH, DAT) given evorpacept's anemia risk",
    },
    {
      id: "NCT07007559-exc-7",
      status: "pass",
      confidence: "medium",
      rationale: "No organ or tissue transplant is recorded in her history.",
    },
    {
      id: "NCT07007559-exc-8",
      status: "pass",
      confidence: "medium",
      rationale: "No active cardiovascular disease: no CAD, BP 128/74 on lisinopril, LVEF 55%.",
      evidence: [
        { quote: "No CAD. Never smoker.", source: "Onc note 2026-09-24" },
        { quote: "BP 128/74 HR 82 SpO2 97% RA.", source: "Onc note 2026-09-24" },
      ],
    },
    {
      id: "NCT07007559-exc-9",
      status: "pass",
      confidence: "medium",
      rationale: "Two years of trastuzumab, pertuzumab and T-DXd infusions without a recorded reaction, and no known drug allergies.",
      evidence: [{ quote: "ALLERGIES: NKDA", source: "Allergies" }],
    },
    {
      id: "NCT07007559-exc-10",
      status: "pass",
      confidence: "medium",
      rationale: "Hypothyroidism on levothyroxine replacement only (TSH 2.4); hormone replacement is not systemic autoimmune treatment, and no other autoimmune disease is recorded.",
      evidence: [{ quote: "levothyroxine 100 mcg PO daily", source: "Medications" }],
      actionNeeded: "Confirm with the sponsor that levothyroxine replacement is acceptable",
    },
    {
      id: "NCT07007559-exc-11",
      status: "pass",
      confidence: "medium",
      rationale: "No other primary malignancy within 2 years is recorded.",
    },
  ],
);
