import { demoMatch } from "../../match-helpers";

export default demoMatch(
  "NCT05969860",
  "Not on a listed regimen now (T-DXd stopped 7/2026) · could fit once on tucatinib-HER2CLIMB",
  "This is a care-delivery study of home versus clinic administration of standard therapy, not a treatment option in itself. Rosa has been off all anti-cancer therapy since T-DXd was stopped for progression (last dose 2026-07-06; the 'C14 D1 today' line in the 9/24 note is a stale copy-forward), so she does not meet the requirement to be receiving a listed regimen. If she chooses standard third-line tucatinib + trastuzumab + capecitabine, that regimen is listed and explicitly permitted; she could then be screened once tolerability is documented and her home is confirmed to be within the service area.",
  [
    {
      id: "NCT05969860-inc-1",
      status: "pass",
      rationale: "Invasive ductal carcinoma of the right breast confirmed on core biopsy (01/2024), with metastatic carcinoma on axillary node and liver biopsies.",
      evidence: [
        { quote: "Right breast core: Invasive ductal carcinoma, grade 3 (Nottingham 9/9).", source: "Pathology 2024-01-19" },
        { quote: "Liver bx 2024-01-23: metastatic carcinoma c/w breast primary, HER2 IHC 3+.", source: "Pathology" },
      ],
    },
    {
      id: "NCT05969860-inc-2",
      status: "fail",
      confidence: "medium",
      rationale: "She is not receiving any anti-cancer regimen: T-DXd was discontinued for progression (last dose 2026-07-06; 'C14 D1 today' is stale copy-forward) and the third-line choice is still open. She would qualify once on standard tucatinib + trastuzumab + capecitabine.",
      evidence: [
        { quote: "trastuzumab deruxtecan - DISCONTINUED 07/2026 (PD)", source: "Medications" },
        { quote: "Discussed 3L tucatinib + trastuzumab + capecitabine (HER2CLIMB) vs clinical trial.", source: "Onc note 2026-09-24" },
      ],
      actionNeeded: "Re-screen after she starts standard tucatinib + trastuzumab + capecitabine, if that is chosen over a therapeutic trial",
    },
    {
      id: "NCT05969860-inc-3",
      status: "pass",
      rationale: "Introductory note to the disease and regimen lists: breast cancer is an eligible disease type, so any listed regimen would qualify; no immunotherapy is planned for her HER2-positive, HR-negative disease.",
      evidence: [{ quote: "Metastatic HER2+ (IHC 3+) HR-negative breast ca, de novo stage IV", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT05969860-inc-4",
      status: "pass",
      rationale: "Breast cancer is on the eligible disease list; she has de novo metastatic HER2-positive breast cancer.",
      evidence: [{ quote: "de novo metastatic R breast IDC, grade 3, ER-/PR-/HER2 3+, dx Jan 2024", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT05969860-inc-5",
      status: "not-applicable",
      rationale: "Infusional 5-FU-based regimen; she is not receiving it, and the trastuzumab-capecitabine option she is weighing falls under the trastuzumab ± tucatinib ± capecitabine item.",
    },
    {
      id: "NCT05969860-inc-6",
      status: "not-applicable",
      rationale: "5-FU with nivolumab is a gastrointestinal regimen and not part of the treatment of her HER2-positive breast cancer.",
    },
    {
      id: "NCT05969860-inc-7",
      status: "not-applicable",
      rationale: "Atezolizumab ± bevacizumab (lung and liver cancer regimens) is not a therapy she is receiving or being considered for.",
    },
    {
      id: "NCT05969860-inc-8",
      status: "not-applicable",
      rationale: "Atezolizumab with BRAF/MEK inhibitors is a melanoma regimen; not relevant to her HER2-positive breast cancer.",
    },
    {
      id: "NCT05969860-inc-9",
      status: "not-applicable",
      rationale: "Avelumab (urothelial and Merkel cell carcinoma) is not part of her treatment.",
    },
    {
      id: "NCT05969860-inc-10",
      status: "not-applicable",
      rationale: "Avelumab + axitinib is a renal cell carcinoma regimen; not relevant to her breast cancer.",
    },
    {
      id: "NCT05969860-inc-11",
      status: "not-applicable",
      rationale: "Single-agent bevacizumab is not a regimen she is receiving or being considered for.",
    },
    {
      id: "NCT05969860-inc-12",
      status: "not-applicable",
      rationale: "Bevacizumab + capecitabine is not her planned regimen; capecitabine would be given with trastuzumab and tucatinib, covered by a separate listed item.",
    },
    {
      id: "NCT05969860-inc-13",
      status: "not-applicable",
      rationale: "Bevacizumab + irinotecan is a colorectal-type regimen; not relevant to her HER2-positive breast cancer.",
    },
    {
      id: "NCT05969860-inc-14",
      status: "not-applicable",
      rationale: "Bevacizumab with a PARP inhibitor or lenvatinib (ovarian/endometrial regimens) is not part of her treatment.",
    },
    {
      id: "NCT05969860-inc-15",
      status: "not-applicable",
      rationale: "Bevacizumab with temozolomide, lomustine or everolimus are glioblastoma regimens; her brain metastases were treated with SRS.",
    },
    {
      id: "NCT05969860-inc-16",
      status: "not-applicable",
      rationale: "Bevacizumab + trifluridine/tipiracil is a colorectal regimen; not relevant to her breast cancer.",
    },
    {
      id: "NCT05969860-inc-17",
      status: "not-applicable",
      rationale: "Bortezomib is a myeloma agent; not relevant to her HER2-positive breast cancer.",
    },
    {
      id: "NCT05969860-inc-18",
      status: "not-applicable",
      rationale: "Bortezomib-based combinations are myeloma regimens; not relevant to her breast cancer.",
    },
    {
      id: "NCT05969860-inc-19",
      status: "not-applicable",
      rationale: "Bortezomib + venetoclax is a myeloma regimen; not relevant to her breast cancer.",
    },
    {
      id: "NCT05969860-inc-20",
      status: "not-applicable",
      rationale: "Carfilzomib is a myeloma agent; not relevant to her HER2-positive breast cancer.",
    },
    {
      id: "NCT05969860-inc-21",
      status: "not-applicable",
      rationale: "Carfilzomib-based combinations are myeloma regimens; not relevant to her breast cancer.",
    },
    {
      id: "NCT05969860-inc-22",
      status: "not-applicable",
      rationale: "Carfilzomib + venetoclax is a myeloma regimen; not relevant to her breast cancer.",
    },
    {
      id: "NCT05969860-inc-23",
      status: "not-applicable",
      rationale: "Cemiplimab (cutaneous SCC, basal cell and lung cancer) is not part of her treatment.",
    },
    {
      id: "NCT05969860-inc-24",
      status: "not-applicable",
      rationale: "Single-agent cisplatin is not a regimen she is receiving or being considered for.",
    },
    {
      id: "NCT05969860-inc-25",
      status: "not-applicable",
      rationale: "Cisplatin/5-FU is a head-and-neck/gastrointestinal regimen; not relevant to her breast cancer.",
    },
    {
      id: "NCT05969860-inc-26",
      status: "not-applicable",
      rationale: "Cisplatin/etoposide (small-cell and germ-cell regimens) is not relevant to her breast cancer.",
    },
    {
      id: "NCT05969860-inc-27",
      status: "not-applicable",
      rationale: "Cisplatin + durvalumab (lung/biliary regimen) is not part of her treatment.",
    },
    {
      id: "NCT05969860-inc-28",
      status: "not-applicable",
      rationale: "Cisplatin + gemcitabine (biliary/bladder regimen) is not her planned therapy.",
    },
    {
      id: "NCT05969860-inc-29",
      status: "not-applicable",
      rationale: "Cisplatin + gemcitabine + durvalumab is a biliary tract regimen; not relevant to her breast cancer.",
    },
    {
      id: "NCT05969860-inc-30",
      status: "not-applicable",
      rationale: "Daratumumab-based regimens are for multiple myeloma; not relevant to her breast cancer.",
    },
    {
      id: "NCT05969860-inc-31",
      status: "not-applicable",
      rationale: "Daratumumab + bortezomib combinations are myeloma regimens; not relevant to her breast cancer.",
    },
    {
      id: "NCT05969860-inc-32",
      status: "not-applicable",
      rationale: "Daratumumab + carfilzomib combinations are myeloma regimens; not relevant to her breast cancer.",
    },
    {
      id: "NCT05969860-inc-33",
      status: "not-applicable",
      rationale: "Degarelix is androgen deprivation for prostate cancer; not applicable to a woman with breast cancer.",
    },
    {
      id: "NCT05969860-inc-34",
      status: "not-applicable",
      rationale: "Single-agent durvalumab (lung/biliary) is not part of her treatment.",
    },
    {
      id: "NCT05969860-inc-35",
      status: "not-applicable",
      rationale: "Durvalumab + tremelimumab (hepatocellular/lung regimen) is not relevant to her breast cancer.",
    },
    {
      id: "NCT05969860-inc-36",
      status: "not-applicable",
      rationale: "Eribulin is a later-line breast option but not one she is receiving or planned for; the third-line plan under discussion is tucatinib-based.",
    },
    {
      id: "NCT05969860-inc-37",
      status: "not-applicable",
      rationale: "FOLFIRI ± bevacizumab is a colorectal regimen; not relevant to her breast cancer.",
    },
    {
      id: "NCT05969860-inc-38",
      status: "not-applicable",
      rationale: "She is no longer on T-DXd: it was discontinued for progression, last dose 2026-07-06 (84 days ago). The 'T-DXd C14 D1 today ... continue q3w' line in the 9/24 note is a stale copy-forward.",
      evidence: [
        { quote: "trastuzumab deruxtecan - DISCONTINUED 07/2026 (PD)", source: "Medications" },
        { quote: "2L T-DXd 5.4 mg/kg 4/2025-7/2026 (last dose 07/06/2026)", source: "Onc note 2026-09-24" },
      ],
    },
    {
      id: "NCT05969860-inc-39",
      status: "not-applicable",
      rationale: "Fulvestrant is endocrine therapy for HR-positive disease; her tumor is ER 0% and PR 0%.",
      evidence: [{ quote: "ER: negative (0%)", source: "Pathology 2024-01-19" }],
    },
    {
      id: "NCT05969860-inc-40",
      status: "not-applicable",
      rationale: "Fulvestrant with a CDK4/6, PI3K or AKT inhibitor is for HR-positive disease; her tumor is ER- and PR-negative.",
      evidence: [{ quote: "ER-/PR-/HER2 3+", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT05969860-inc-41",
      status: "not-applicable",
      rationale: "Single-agent gemcitabine is not a regimen she is receiving or being considered for.",
    },
    {
      id: "NCT05969860-inc-42",
      status: "not-applicable",
      rationale: "Gemcitabine + durvalumab is a biliary tract regimen; not relevant to her breast cancer.",
    },
    {
      id: "NCT05969860-inc-43",
      status: "not-applicable",
      rationale: "Gemcitabine + nab-paclitaxel is a pancreatic regimen; not relevant to her breast cancer.",
    },
    {
      id: "NCT05969860-inc-44",
      status: "not-applicable",
      rationale: "Goserelin (ovarian suppression or prostate cancer) has no role: she is 66, postmenopausal and HR-negative.",
      evidence: [{ quote: "66 yo postmenopausal F", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT05969860-inc-45",
      status: "not-applicable",
      rationale: "Single-agent irinotecan is not a regimen she is receiving or being considered for.",
    },
    {
      id: "NCT05969860-inc-46",
      status: "not-applicable",
      rationale: "Irinotecan + capecitabine is a gastrointestinal regimen; not her planned therapy.",
    },
    {
      id: "NCT05969860-inc-47",
      status: "not-applicable",
      rationale: "Lanreotide is a somatostatin analogue for neuroendocrine tumors; not relevant to her breast cancer.",
    },
    {
      id: "NCT05969860-inc-48",
      status: "not-applicable",
      rationale: "Leuprolide (prostate cancer or premenopausal ovarian suppression) has no role in a postmenopausal woman with HR-negative disease.",
    },
    {
      id: "NCT05969860-inc-49",
      status: "not-applicable",
      rationale: "Nivolumab is not part of her treatment; no immunotherapy is planned.",
    },
    {
      id: "NCT05969860-inc-50",
      status: "not-applicable",
      rationale: "Nivolumab + cabozantinib is a renal cell carcinoma regimen; not relevant to her breast cancer.",
    },
    {
      id: "NCT05969860-inc-51",
      status: "not-applicable",
      rationale: "Nivolumab-relatlimab is a melanoma regimen; not relevant to her breast cancer.",
    },
    {
      id: "NCT05969860-inc-52",
      status: "not-applicable",
      rationale: "Octreotide is a somatostatin analogue for neuroendocrine tumors; not relevant to her breast cancer.",
    },
    {
      id: "NCT05969860-inc-53",
      status: "not-applicable",
      rationale: "Single-agent paclitaxel is not planned, and she has residual grade 2 neuropathy from prior docetaxel.",
      evidence: [{ quote: "Residual G2 PN hands/feet from docetaxel", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT05969860-inc-54",
      status: "not-applicable",
      rationale: "Pembrolizumab is not part of her treatment; no immunotherapy is planned for her HER2-positive, HR-negative disease.",
    },
    {
      id: "NCT05969860-inc-55",
      status: "not-applicable",
      rationale: "Pembrolizumab combinations (renal, endometrial, melanoma and other regimens) are not relevant to her breast cancer.",
    },
    {
      id: "NCT05969860-inc-56",
      status: "not-applicable",
      rationale: "Pemetrexed (lung cancer/mesothelioma) is not relevant to her breast cancer.",
    },
    {
      id: "NCT05969860-inc-57",
      status: "not-applicable",
      rationale: "Pertuzumab was given in first-line THP and Phesgo maintenance and stopped at progression in 3/2025; she is not receiving it now.",
      evidence: [{ quote: "then HP maint (Phesgo), best response PR; PD 3/2025 w/ new liver lesions.", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT05969860-inc-58",
      status: "not-applicable",
      rationale: "Pemetrexed + pembrolizumab is a lung cancer regimen; not relevant to her breast cancer.",
    },
    {
      id: "NCT05969860-inc-59",
      status: "not-applicable",
      rationale: "Rituximab is for lymphoma; not relevant to her breast cancer.",
    },
    {
      id: "NCT05969860-inc-60",
      status: "not-applicable",
      rationale: "Trastuzumab + paclitaxel is not planned: she has progressed on two trastuzumab-based lines and has residual grade 2 taxane neuropathy.",
      evidence: [{ quote: "PD on 1L THP/HP and 2L T-DXd.", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT05969860-inc-61",
      status: "unknown",
      confidence: "medium",
      rationale: "Her standard third-line option, tucatinib + trastuzumab + capecitabine (HER2CLIMB), is covered by this listed regimen, but she has not started it; the choice between it and a therapeutic trial is pending.",
      evidence: [{ quote: "Discussed 3L tucatinib + trastuzumab + capecitabine (HER2CLIMB) vs clinical trial.", source: "Onc note 2026-09-24" }],
      actionNeeded: "Confirm she starts trastuzumab + tucatinib + capecitabine as standard of care before pre-registration",
    },
    {
      id: "NCT05969860-inc-62",
      status: "not-applicable",
      rationale: "Decitabine is for myelodysplastic syndrome; not relevant to her breast cancer.",
    },
    {
      id: "NCT05969860-inc-63",
      status: "not-applicable",
      rationale: "Growth-factor/ESA provision only; she receives no filgrastim or epoetin, and her chronic mild anemia (Hgb 10.9) is untreated.",
      evidence: [{ quote: "Mild anemia Hgb 10.9, chronic, no bleeding.", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT05969860-inc-64",
      status: "not-applicable",
      rationale: "Permissive note on bone-modifying agents; she has no documented bone metastases and receives no zoledronic acid or denosumab.",
    },
    {
      id: "NCT05969860-inc-65",
      status: "unknown",
      confidence: "low",
      rationale: "No infusion reactions are recorded over 2.5 years of trastuzumab, pertuzumab and T-DXd, but tolerability of the regimen she would be enrolled on has not been established because it has not started.",
      evidence: [{ quote: "1L THP (docetaxel x6, 2/2024-6/2024) then HP maint (Phesgo), best response PR", source: "Onc note 2026-09-24" }],
      actionNeeded: "After starting the standard regimen, treating physician to document adequate tolerability and no infusion reactions before consent",
    },
    {
      id: "NCT05969860-inc-66",
      status: "unknown",
      confidence: "low",
      rationale: "There is no currently prescribed regimen to continue; tucatinib-based third-line therapy would normally run until progression, but no plan is documented yet.",
      actionNeeded: "Document a plan to continue the chosen standard regimen for ≥ 24 weeks from the cycle after randomization",
    },
    {
      id: "NCT05969860-inc-67",
      status: "pass",
      confidence: "low",
      rationale: "Home address relative to the supplier and paramedic network is not recorded (she lives with her daughter); confirmed at screening.",
      evidence: [{ quote: "SH: lives w/ daughter, no EtOH.", source: "Onc note 2026-09-24" }],
      actionNeeded: "Confirm her residence is within the home-infusion supplier and paramedic service area",
    },
    {
      id: "NCT05969860-inc-68",
      status: "pass",
      confidence: "low",
      rationale: "Home connectivity is not documented; wifi or a wireless network solution is confirmed at screening.",
      actionNeeded: "Confirm home wifi or suitability for the study's wireless network solution",
    },
    {
      id: "NCT05969860-inc-69",
      status: "pass",
      rationale: "She is 66 years old.",
      evidence: [{ quote: "66 yo postmenopausal F", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT05969860-inc-70",
      status: "pass",
      confidence: "low",
      rationale: "Signed informed consent is obtained at screening; no capacity concerns are recorded.",
    },
    {
      id: "NCT05969860-inc-71",
      status: "pass",
      confidence: "low",
      rationale: "Willingness and ability to comply are confirmed at screening; she is alert, independent and engaged in trial discussions.",
      evidence: [{ quote: "Pt open to trial if screening within 3-4 wks.", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT05969860-inc-72",
      status: "pass",
      rationale: "ECOG 1 at the 2026-09-24 visit, within the allowed 0-2.",
      evidence: [{ quote: "EXAM: ECOG 1.", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT05969860-inc-73",
      status: "pass",
      confidence: "low",
      rationale: "Alert with intact cranial nerves and no focal deficits after SRS, and lives with her daughter who could assist; confirmed at screening.",
      evidence: [{ quote: "Alert, CN II-XII intact, no drift, gait steady.", source: "Exam 2026-09-24" }],
    },
    {
      id: "NCT05969860-inc-74",
      status: "unknown",
      confidence: "low",
      rationale: "Randomization requires Command Center confirmation of tolerability between pre-registration and registration, which cannot be assessed until she is on a listed regimen.",
      actionNeeded: "Command Center to confirm adequate tolerability and no infusion reactions after pre-registration",
    },
    {
      id: "NCT05969860-exc-1",
      status: "pass",
      rationale: "No investigational agent on the medication list. Tucatinib + capecitabine with trastuzumab is explicitly permitted; enrolling on a therapeutic trial instead would trigger this exclusion.",
      evidence: [{ quote: "trastuzumab deruxtecan - DISCONTINUED 07/2026 (PD)", source: "Medications" }],
    },
    {
      id: "NCT05969860-exc-2",
      status: "pass",
      confidence: "medium",
      rationale: "ECOG 1 with steady gait and no falls; she lives with her daughter but there is no indication she needs round-the-clock help with ADLs.",
      evidence: [{ quote: "Alert, CN II-XII intact, no drift, gait steady.", source: "Exam 2026-09-24" }],
    },
    {
      id: "NCT05969860-exc-3",
      status: "pass",
      rationale: "Seen as an outpatient in medical oncology clinic on 2026-09-24; not hospitalized.",
      evidence: [{ quote: "MEDICAL ONCOLOGY FOLLOW-UP NOTE", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT05969860-exc-4",
      status: "pass",
      confidence: "medium",
      rationale: "Comorbidities are controlled: T2DM with A1c 6.9%, hypertension on lisinopril (BP 128/74), hypothyroidism with TSH 2.4, stable grade 2 neuropathy. None would preclude home administration.",
      evidence: [
        { quote: "T2DM (metformin, A1c 6.9% 7/2026)", source: "PMH" },
        { quote: "BP 128/74 HR 82 SpO2 97% RA.", source: "Exam 2026-09-24" },
      ],
    },
    {
      id: "NCT05969860-exc-5",
      status: "pass",
      confidence: "medium",
      rationale: "No active infection, heart failure, angina, arrhythmia or MI is recorded: no CAD, LVEF 55% (9/10/26) and asymptomatic, HR 82, no psychiatric history.",
      evidence: [
        { quote: "LVEF 55% on 9/10/26 echo (baseline 62% in 2024), asymptomatic.", source: "Onc note 2026-09-24" },
        { quote: "No CAD.", source: "PMH" },
      ],
    },
  ],
);
