import { demoMatch } from "../../match-helpers";

export default demoMatch(
  "NCT06949410",
  "Excluded: curative-setting vaccine study; she has de novo stage IV disease and no (neo)adjuvant HER2 therapy",
  "This HER2 peptide vaccine trial is for high-risk, non-metastatic HER2-positive breast cancer after curative-intent (neo)adjuvant HER2 therapy. Rosa has de novo stage IV disease with liver, lung, nodal and brain metastases, and all of her HER2-directed therapy has been given in the metastatic setting, so she fails the setting, high-risk definition and distant-disease criteria. Her HER2 IHC 3+ status, ECOG 1 and organ function would otherwise fit, but nothing in her course can change these blockers.",
  [
    {
      id: "NCT06949410-inc-1",
      status: "pass",
      rationale: "She is 66 years old.",
      evidence: [{ quote: "66 yo postmenopausal F", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT06949410-inc-2",
      status: "pass",
      confidence: "low",
      rationale: "Written consent and HIPAA authorization are obtained at screening; no capacity concerns are recorded.",
    },
    {
      id: "NCT06949410-inc-3",
      status: "pass",
      rationale: "HER2 IHC 3+ on the primary core and liver metastasis; ER/PR-negative status is allowed.",
      evidence: [{ quote: "HER2 IHC: 3+ (positive), complete intense circumferential staining in >10% of cells", source: "Pathology 2024-01-19" }],
    },
    {
      id: "NCT06949410-inc-4",
      status: "fail",
      rationale: "None of the high-risk categories apply: she was stage IV at diagnosis (cT3 cN2 M1), not clinical stage III, inflammatory, residual disease after neoadjuvant therapy or local recurrence, and had no breast surgery.",
      evidence: [
        { quote: "cT3 cN2 M1: bilat lung nodules, mediastinal LN, solitary liver lesion", source: "Onc note 2026-09-24" },
        { quote: "PSH: port 2/2024. No breast surgery.", source: "PSH" },
      ],
    },
    {
      id: "NCT06949410-inc-5",
      status: "fail",
      rationale: "She has never received neoadjuvant or adjuvant HER2 therapy; THP, Phesgo and T-DXd were all given for de novo metastatic disease.",
      evidence: [{ quote: "Metastatic HER2+ (IHC 3+) HR-negative breast ca, de novo stage IV, PD on 1L THP/HP and 2L T-DXd.", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT06949410-inc-6",
      status: "pass",
      confidence: "medium",
      rationale: "Her last HER2-targeted dose (T-DXd, 2026-07-06) was 84 days ago, within 6 months, though the criterion presumes curative-setting therapy.",
      evidence: [{ quote: "2L T-DXd 5.4 mg/kg 4/2025-7/2026 (last dose 07/06/2026)", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT06949410-inc-7",
      status: "pass",
      rationale: "Last cytotoxic-payload therapy (T-DXd) 84 days ago and SRS 52 days ago, both beyond 30 days; residual docetaxel neuropathy is grade 2, within the allowed ≤ 2.",
      evidence: [
        { quote: "GK SRS to all 3 lesions 8/7/26 (20 Gy).", source: "Onc note 2026-09-24" },
        { quote: "Residual G2 PN hands/feet from docetaxel", source: "Onc note 2026-09-24" },
      ],
    },
    {
      id: "NCT06949410-inc-8",
      status: "pass",
      rationale: "ECOG 1 at the 2026-09-24 visit, within the allowed 0-2.",
      evidence: [{ quote: "EXAM: ECOG 1.", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT06949410-inc-9",
      status: "pass",
      confidence: "medium",
      rationale: "On 2026-09-22: bilirubin 0.8, AST 1.3 × ULN, ALT 48 (mildly high, ULN not stated), ANC 3.1, platelets 165. CrCl ~62 mL/min by Cockcroft-Gault is only just above the > 60 threshold.",
      evidence: [
        { quote: "est CrCl ~62 mL/min (CG)", source: "Labs 2026-09-22" },
        { quote: "AST 52 (H, 1.3x ULN)", source: "Labs 2026-09-22" },
      ],
      actionNeeded: "Repeat chemistry at screening; CrCl must remain > 60 mL/min (CG) and ALT < 2 × ULN",
    },
    {
      id: "NCT06949410-inc-10",
      status: "pass",
      rationale: "LVEF 55% by echo on 2026-09-10, 18 days ago and within the 90-day window, above the normal lower limit.",
      evidence: [{ quote: "ECHO 2026-09-10: LVEF 55% (biplane Simpson's).", source: "Echo 2026-09-10" }],
    },
    {
      id: "NCT06949410-inc-11",
      status: "not-applicable",
      rationale: "Pregnancy test for women of childbearing potential; she is 66 and postmenopausal.",
      evidence: [{ quote: "66 yo postmenopausal F", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT06949410-inc-12",
      status: "not-applicable",
      rationale: "Contraception applies to women of childbearing potential and men; she is a postmenopausal woman.",
    },
    {
      id: "NCT06949410-inc-13",
      status: "not-applicable",
      rationale: "List of acceptable contraceptive methods; contraception does not apply to a postmenopausal woman.",
    },
    {
      id: "NCT06949410-exc-1",
      status: "fail",
      rationale: "She has distant metastatic disease (liver, lung, mediastinal nodes and brain), present since diagnosis and progressing in 7/2026.",
      evidence: [
        { quote: "Progression of hepatic metastases: segment VII lesion 2.8 cm (previously 1.6 cm), segment V lesion 2.2 cm (previously 1.1 cm), two new subcentimeter lesions.", source: "CT CAP 2026-07-20" },
        { quote: "MRI brain 7/22/26 w/ 3 new brain mets (largest 1.4 cm R frontal)", source: "Onc note 2026-09-24" },
      ],
    },
    {
      id: "NCT06949410-exc-2",
      status: "pass",
      confidence: "medium",
      rationale: "No malignancy other than breast cancer is recorded in an otherwise detailed history.",
    },
    {
      id: "NCT06949410-exc-3",
      status: "pass",
      rationale: "Her tumor is ER- and PR-negative; she has not received and is not planned for a CDK4/6 inhibitor.",
      evidence: [{ quote: "ER-/PR-/HER2 3+", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT06949410-exc-4",
      status: "unknown",
      confidence: "low",
      rationale: "The immediate-hypersensitivity skin test to the MVF-HER-2 peptides is a study screening procedure and has not been done.",
      actionNeeded: "Perform MVF-HER-2 peptide skin test at screening; a positive result excludes",
    },
    {
      id: "NCT06949410-exc-5",
      status: "pass",
      confidence: "medium",
      rationale: "Off dexamethasone since 8/30/26 with no edema on the 9/12/26 MRI and no other immunosuppressants; SRS-treated brain metastases carry some risk of future steroid need.",
      evidence: [{ quote: "dexamethasone - taper COMPLETED, last dose 08/30/2026", source: "Medications" }],
    },
    {
      id: "NCT06949410-exc-6",
      status: "pass",
      confidence: "medium",
      rationale: "No rheumatoid arthritis, lupus, scleroderma, myositis or vasculitis recorded; hypothyroidism is on replacement only.",
      evidence: [{ quote: "hypothyroidism (levothyroxine)", source: "PMH" }],
    },
    {
      id: "NCT06949410-exc-7",
      status: "pass",
      confidence: "medium",
      rationale: "Allergy list is NKDA and no vaccine reactions are recorded.",
      evidence: [{ quote: "ALLERGIES: NKDA", source: "Allergies" }],
      actionNeeded: "Confirm no prior anaphylaxis to any vaccine",
    },
    {
      id: "NCT06949410-exc-8",
      status: "pass",
      confidence: "medium",
      rationale: "No active infection or antibiotic use recorded; no cough or dyspnoea and SpO2 97%.",
      evidence: [{ quote: "No cough/SOB.", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT06949410-exc-9",
      status: "unknown",
      confidence: "low",
      rationale: "HIV, hepatitis B and hepatitis C serology are not documented.",
      actionNeeded: "Obtain HIV, HBsAg/anti-HBc and anti-HCV serology; seropositivity other than from vaccination excludes",
    },
    {
      id: "NCT06949410-exc-10",
      status: "pass",
      confidence: "medium",
      rationale: "No uncontrolled illness recorded: no infection, heart failure, angina or arrhythmia; LVEF 55%, BP 128/74, HR 82.",
      evidence: [{ quote: "BP 128/74 HR 82 SpO2 97% RA.", source: "Exam 2026-09-24" }],
    },
    {
      id: "NCT06949410-exc-11",
      status: "pass",
      confidence: "medium",
      rationale: "No heart failure, coronary disease or COPD: no CAD, never smoker, lungs clear and LVEF 55%.",
      evidence: [{ quote: "No CAD. Never smoker.", source: "PMH" }],
    },
    {
      id: "NCT06949410-exc-12",
      status: "pass",
      rationale: "No splenectomy; the surgical history lists only a port placement.",
      evidence: [{ quote: "PSH: port 2/2024. No breast surgery.", source: "PSH" }],
    },
    {
      id: "NCT06949410-exc-13",
      status: "not-applicable",
      rationale: "She is 66 and postmenopausal; pregnancy and breastfeeding do not apply.",
    },
  ],
);
