import { demoMatch } from "../../match-helpers";

export default demoMatch(
  "NCT07441889",
  "Fits the breast cohort · lymphocyte count and HIV/hepatitis serology still needed",
  "Rosa fits the metastatic breast cohort: HER2-positive disease that has progressed on two HER2-targeted lines, ECOG 1, RECIST-measurable liver metastases, off steroids for 4 weeks, and no autoimmune or cardiac exclusion (levothyroxine is exempt replacement therapy). Before registration she needs a CBC with differential showing an absolute lymphocyte count ≥ 400/mm³ and labs within 10 days, HIV and hepatitis B/C serology, and a CT within 28 days. The 5 weekly then 4 fortnightly infusions are a practical point to discuss given her wish to start promptly.",
  [
    {
      id: "NCT07441889-inc-1",
      status: "pass",
      confidence: "low",
      rationale: "Signed consent is obtained at screening; she is open to a trial.",
      evidence: [{ quote: "Pt open to trial if screening within 3-4 wks.", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT07441889-inc-2",
      status: "pass",
      confidence: "low",
      rationale: "Willingness and availability are confirmed at screening; she wants a trial but has asked for screening within 3–4 weeks, and dosing needs 5 weekly then 4 fortnightly infusions.",
      evidence: [{ quote: "Pt open to trial if screening within 3-4 wks.", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT07441889-inc-3",
      status: "pass",
      rationale: "She is 66 years old (born 1960).",
      evidence: [{ quote: "DOB: 1960 (66 yo F)", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT07441889-inc-4",
      status: "pass",
      confidence: "medium",
      rationale: "ECOG 1, normal bilirubin and albumin 3.6 despite progressing liver metastases, controlled brain disease and further standard options available; survival well beyond 3 months is expected.",
      evidence: [{ quote: "EXAM: ECOG 1.", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT07441889-inc-5",
      status: "pass",
      rationale: "ECOG 1 at the 2026-09-24 visit.",
      evidence: [{ quote: "EXAM: ECOG 1.", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT07441889-inc-6",
      status: "unknown",
      confidence: "medium",
      rationale: "Labs 2026-09-22 meet the listed limits (ANC 3.1, platelets 165, Hgb 10.9, creatinine 0.9, bilirubin 0.8, AST 1.3 × ULN), but absolute lymphocyte count is not reported and labs must fall within 10 days of registration.",
      evidence: [
        { quote: "WBC 5.8 | ANC 3.1 | Hgb 10.9 (L) | Plt 165", source: "Labs 2026-09-22" },
        { quote: "AST 52 (H, 1.3x ULN) | ALT 48 (H) | T bili 0.8", source: "Labs 2026-09-22" },
      ],
      actionNeeded: "Repeat CBC with differential and chemistry within 10 days of registration; absolute lymphocyte count ≥ 400/mm³ required",
    },
    {
      id: "NCT07441889-inc-7",
      status: "pass",
      confidence: "low",
      rationale: "Agreement to the protocol's lifestyle considerations is confirmed at screening.",
    },
    {
      id: "NCT07441889-inc-8",
      status: "pass",
      rationale: "Breast branch met: histologically confirmed invasive ductal carcinoma, previously treated metastatic disease, and RECIST-evaluable liver lesions of 2.8 and 2.2 cm.",
      evidence: [
        { quote: "Right breast core: Invasive ductal carcinoma, grade 3 (Nottingham 9/9).", source: "Pathology 2024-01-19" },
        { quote: "Measurable liver dz: seg VII 2.8 cm, seg V 2.2 cm.", source: "Onc note 2026-09-24" },
      ],
    },
    {
      id: "NCT07441889-inc-9",
      status: "pass",
      rationale: "Progressed on two HER2-targeted therapies: trastuzumab/pertuzumab after THP (PD 03/2025) and T-DXd (PD 07/2026).",
      evidence: [
        { quote: "Metastatic HER2+ (IHC 3+) HR-negative breast ca, de novo stage IV, PD on 1L THP/HP and 2L T-DXd.", source: "Onc note 2026-09-24" },
      ],
    },
    {
      id: "NCT07441889-inc-10",
      status: "pass",
      confidence: "medium",
      rationale: "Metastatic lesions are present (liver metastases on CT 07/20/2026; treated brain lesions on MRI 2026-09-12), but the CT is 70 days old and must be repeated within 28 days of registration.",
      evidence: [{ quote: "CT CHEST/ABDOMEN/PELVIS W/ CONTRAST - 07/20/2026", source: "Imaging" }],
      actionNeeded: "Repeat CT chest/abdomen/pelvis within 28 days before registration",
    },
    {
      id: "NCT07441889-exc-1",
      status: "not-applicable",
      rationale: "She is a 66-year-old postmenopausal woman; pregnancy testing and lactation exclusions cannot apply.",
    },
    {
      id: "NCT07441889-exc-2",
      status: "pass",
      rationale: "No myocardial infarction or coronary disease; the problem list states no CAD.",
      evidence: [{ quote: "No CAD. Never smoker.", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT07441889-exc-3",
      status: "pass",
      confidence: "medium",
      rationale: "No angina, arrhythmia, MI or heart failure is documented; echo 2026-09-10 shows LVEF 55% with no pericardial effusion.",
      evidence: [
        { quote: "ECHO 2026-09-10: LVEF 55% (biplane Simpson's).", source: "Echo 2026-09-10" },
        { quote: "No pericardial effusion.", source: "Echo 2026-09-10" },
      ],
    },
    {
      id: "NCT07441889-exc-4",
      status: "pass",
      rationale: "No immunodeficiency; dexamethasone stopped 2026-08-30 (29 days ago), and levothyroxine is replacement therapy, which the criterion exempts.",
      evidence: [
        { quote: "dexamethasone - taper COMPLETED, last dose 08/30/2026", source: "Medications" },
        { quote: "levothyroxine 100 mcg PO daily", source: "Medications" },
      ],
    },
    {
      id: "NCT07441889-exc-5",
      status: "pass",
      confidence: "medium",
      rationale: "No surgery, open biopsy, fracture, wound or trauma in the past 28 days; her only procedure was port placement in 02/2024.",
      evidence: [{ quote: "PSH: port 2/2024. No breast surgery.", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT07441889-exc-6",
      status: "pass",
      confidence: "medium",
      rationale: "Liver abnormalities (AST 1.3 × ULN, alk phos 130, tender liver edge) are explained by hepatic metastases; no cirrhosis or chronic hepatitis is recorded and she does not drink alcohol.",
      evidence: [
        { quote: "AST 52 (H, 1.3x ULN) | ALT 48 (H) | T bili 0.8 | Alk phos 130 (H) | Albumin 3.6", source: "Labs 2026-09-22" },
        { quote: "SH: lives w/ daughter, no EtOH.", source: "Onc note 2026-09-24" },
      ],
    },
    {
      id: "NCT07441889-exc-7",
      status: "unknown",
      confidence: "medium",
      rationale: "HIV, hepatitis B and hepatitis C status are not documented anywhere in the record.",
      actionNeeded: "Obtain HIV-1/2 antibody, HBsAg and HCV antibody (RNA if positive); HIV positivity or active HBV/HCV excludes",
    },
    {
      id: "NCT07441889-exc-8",
      status: "pass",
      rationale: "No bleeding (chronic mild anemia without a bleeding source), no anticoagulants, and no hemorrhage in the treated brain lesions.",
      evidence: [
        { quote: "Mild anemia Hgb 10.9, chronic, no bleeding.", source: "Onc note 2026-09-24" },
        { quote: "No new enhancing lesions. No vasogenic edema, no mass effect, no hemorrhage.", source: "MRI brain 2026-09-12" },
      ],
    },
    {
      id: "NCT07441889-exc-9",
      status: "pass",
      confidence: "medium",
      rationale: "No active infection or anti-infective therapy is documented.",
    },
    {
      id: "NCT07441889-exc-10",
      status: "pass",
      confidence: "medium",
      rationale: "Her comorbidities are controlled: BP 128/74 on lisinopril, HbA1c 6.9% on metformin, TSH 2.4 on levothyroxine.",
      evidence: [
        { quote: "BP 128/74 HR 82 SpO2 97% RA.", source: "Onc note 2026-09-24" },
        { quote: "HbA1c 6.9% (07/2026)", source: "Labs" },
        { quote: "TSH 2.4 (7/2026)", source: "Onc note 2026-09-24" },
      ],
    },
    {
      id: "NCT07441889-exc-11",
      status: "pass",
      confidence: "medium",
      rationale: "No history of tuberculosis is recorded, and chest CT shows only stable metastatic nodules.",
    },
    {
      id: "NCT07441889-exc-12",
      status: "pass",
      confidence: "low",
      rationale: "No recent vaccinations are recorded; absence of a live vaccine in the past 30 days is confirmed at screening.",
      actionNeeded: "Confirm no live vaccine within 30 days of registration",
    },
    {
      id: "NCT07441889-exc-13",
      status: "pass",
      confidence: "medium",
      rationale: "No investigational agent: her last systemic therapy was commercial T-DXd, last dose 2026-07-06.",
      evidence: [{ quote: "trastuzumab deruxtecan - DISCONTINUED 07/2026 (PD)", source: "Medications" }],
    },
    {
      id: "NCT07441889-exc-14",
      status: "pass",
      confidence: "medium",
      rationale: "No second malignancy is recorded; her only cancer is the 2024 HER2-positive breast cancer.",
    },
    {
      id: "NCT07441889-exc-15",
      status: "pass",
      confidence: "medium",
      rationale: "Hypothyroidism is treated with levothyroxine replacement, which the criterion exempts; no other autoimmune disease or immunosuppressive treatment is recorded.",
      evidence: [{ quote: "levothyroxine 100 mcg PO daily", source: "Medications" }],
    },
    {
      id: "NCT07441889-exc-16",
      status: "pass",
      confidence: "medium",
      rationale: "No confounding condition is documented beyond mild chronic anemia and the transaminase rise from liver metastases; final judgment rests with the investigator.",
    },
    {
      id: "NCT07441889-exc-17",
      status: "pass",
      confidence: "low",
      rationale: "No compliance concerns are recorded; she lives with her daughter. Confirmed at screening.",
      evidence: [{ quote: "SH: lives w/ daughter, no EtOH.", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT07441889-exc-18",
      status: "not-applicable",
      rationale: "Heading for the prostate cancer cohort exclusions; she would enter the breast cancer cohort.",
    },
    {
      id: "NCT07441889-exc-19",
      status: "pass",
      rationale: "Histology is invasive ductal carcinoma with no neuroendocrine component reported (this exclusion sits under the prostate cohort in any case).",
      evidence: [{ quote: "Right breast core: Invasive ductal carcinoma, grade 3 (Nottingham 9/9).", source: "Pathology 2024-01-19" }],
    },
    {
      id: "NCT07441889-exc-20",
      status: "not-applicable",
      rationale: "Listed under the prostate cancer cohort; the breast-cohort version of this BRCA exclusion is assessed separately.",
    },
    {
      id: "NCT07441889-exc-21",
      status: "pass",
      rationale: "Section heading introducing the breast-cohort exclusions that follow; it does not itself exclude patients with breast cancer.",
    },
    {
      id: "NCT07441889-exc-22",
      status: "pass",
      confidence: "medium",
      rationale: "BRCA status is untested (no NGS on file), but approved PARP inhibitors are indicated for germline BRCA-mutated HER2-negative disease, so no approved BRCA-directed therapy exists for her HER2-positive cancer.",
      evidence: [{ quote: "No NGS on file.", source: "Pathology" }],
      actionNeeded: "Investigator to confirm; germline BRCA testing is not on file",
    },
    {
      id: "NCT07441889-exc-23",
      status: "pass",
      rationale: "No visceral crisis: liver involvement is limited (2.8 and 2.2 cm plus two subcentimetre lesions) with normal bilirubin and albumin 3.6, and there are no effusions, lymphangitis or dyspnoea.",
      evidence: [
        { quote: "segment VII lesion 2.8 cm (previously 1.6 cm), segment V lesion 2.2 cm (previously 1.1 cm)", source: "CT CAP 07/20/2026" },
        { quote: "No cough/SOB.", source: "Onc note 2026-09-24" },
      ],
    },
  ],
);
