import { demoMatch } from "../../match-helpers";

export default demoMatch(
  "NCT05950945",
  "Excluded: HER2-low/IHC 0 trial; she is HER2 3+ and has already received T-DXd",
  "DESTINY-Breast15 studies T-DXd in HER2-low or HER2 IHC 0 disease in patients never treated with anti-HER2 therapy or an antibody-drug conjugate. Rosa is HER2 IHC 3+ on breast and liver tissue, has received trastuzumab, pertuzumab and T-DXd for metastatic disease, and progressed on T-DXd in July 2026. These blockers are inherent to her disease and treatment history, so no screening result would change the answer.",
  [
    {
      id: "NCT05950945-inc-1",
      status: "pass",
      confidence: "low",
      rationale: "Consent is obtained at screening; she is open to a trial.",
      evidence: [{ quote: "Pt open to trial if screening within 3-4 wks.", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT05950945-inc-2",
      status: "pass",
      confidence: "low",
      rationale: "Archival tissue exists from the breast core (01/2024) and liver biopsy (2024-01-23); agreement to provide tissue is confirmed at screening.",
      evidence: [{ quote: "Liver bx 2024-01-23: metastatic carcinoma c/w breast primary, HER2 IHC 3+.", source: "Pathology" }],
    },
    {
      id: "NCT05950945-inc-3",
      status: "pass",
      rationale: "Pathologically confirmed metastatic breast cancer that is hormone receptor-negative (ER 0%, PR 0%).",
      evidence: [
        { quote: "ER: negative (0%)", source: "Pathology 2024-01-19" },
        { quote: "PR: negative (0%)", source: "Pathology 2024-01-19" },
      ],
    },
    {
      id: "NCT05950945-inc-4",
      status: "pass",
      rationale: "The pathology report gives the percentage of stained cells for both receptors: ER 0% and PR 0%.",
      evidence: [
        { quote: "ER: negative (0%)", source: "Pathology 2024-01-19" },
        { quote: "PR: negative (0%)", source: "Pathology 2024-01-19" },
      ],
    },
    {
      id: "NCT05950945-inc-5",
      status: "fail",
      rationale: "HER2 is IHC 3+ on both the breast primary and the liver metastasis, not HER2-low or IHC 0.",
      evidence: [
        { quote: "HER2 IHC: 3+ (positive), complete intense circumferential staining in >10% of cells", source: "Pathology 2024-01-19" },
        { quote: "Liver bx 2024-01-23: metastatic carcinoma c/w breast primary, HER2 IHC 3+.", source: "Pathology" },
      ],
    },
    {
      id: "NCT05950945-inc-6",
      status: "fail",
      rationale: "She has been HER2-positive (IHC 3+) since diagnosis in January 2024.",
      evidence: [{ quote: "HER2 IHC: 3+ (positive), complete intense circumferential staining in >10% of cells", source: "Pathology 2024-01-19" }],
    },
    {
      id: "NCT05950945-inc-7",
      status: "fail",
      rationale: "She has received anti-HER2 therapy for metastatic disease: trastuzumab and pertuzumab (2024–2025), then T-DXd (2025–2026).",
      evidence: [
        { quote: "1L THP (docetaxel x6, 2/2024-6/2024) then HP maint (Phesgo), best response PR", source: "Onc note 2026-09-24" },
        { quote: "2L T-DXd 5.4 mg/kg 4/2025-7/2026 (last dose 07/06/2026)", source: "Onc note 2026-09-24" },
      ],
    },
    {
      id: "NCT05950945-inc-8",
      status: "pass",
      rationale: "Two prior lines for metastatic disease (THP with HP maintenance, then T-DXd), within the one-to-two range; the cohort 3 endocrine conditions apply only to HR-positive disease.",
      evidence: [
        { quote: "Metastatic HER2+ (IHC 3+) HR-negative breast ca, de novo stage IV, PD on 1L THP/HP and 2L T-DXd.", source: "Onc note 2026-09-24" },
      ],
    },
    {
      id: "NCT05950945-inc-9",
      status: "pass",
      rationale: "Measurable liver metastases of 2.8 cm (segment VII) and 2.2 cm (segment V) on CT 07/20/2026.",
      evidence: [{ quote: "Measurable liver dz: seg VII 2.8 cm, seg V 2.2 cm.", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT05950945-inc-10",
      status: "pass",
      confidence: "medium",
      rationale: "Her three brain metastases are small (now 0.3–0.8 cm), asymptomatic and stable off steroids; they were treated with SRS rather than untreated as the text describes, which the sponsor should confirm is acceptable.",
      evidence: [
        { quote: "right frontal 1.4 -> 0.8 cm, left cerebellar 0.9 -> 0.5 cm, right parietal 0.6 -> 0.3 cm", source: "MRI brain 2026-09-12" },
      ],
      actionNeeded: "Confirm with the sponsor that SRS-treated, stable brain metastases are permitted",
    },
    {
      id: "NCT05950945-inc-11",
      status: "pass",
      rationale: "ECOG 1 at the 2026-09-24 visit.",
      evidence: [{ quote: "EXAM: ECOG 1.", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT05950945-inc-12",
      status: "pass",
      confidence: "medium",
      rationale: "ECOG 1 with normal bilirubin and controlled brain disease; life expectancy well beyond 12 weeks is expected.",
    },
    {
      id: "NCT05950945-inc-13",
      status: "pass",
      rationale: "LVEF 55% on echo 2026-09-10 (18 days ago), within 28 days provided enrollment occurs by 2026-10-08.",
      evidence: [{ quote: "ECHO 2026-09-10: LVEF 55% (biplane Simpson's).", source: "Echo 2026-09-10" }],
    },
    {
      id: "NCT05950945-inc-14",
      status: "pass",
      rationale: "Labs 2026-09-22: ANC 3.1, platelets 165, Hgb 10.9, bilirubin 0.8, AST 1.3 × ULN with liver metastases, CrCl ~62 mL/min.",
      evidence: [
        { quote: "WBC 5.8 | ANC 3.1 | Hgb 10.9 (L) | Plt 165", source: "Labs 2026-09-22" },
        { quote: "AST 52 (H, 1.3x ULN) | ALT 48 (H) | T bili 0.8", source: "Labs 2026-09-22" },
      ],
    },
    {
      id: "NCT05950945-inc-15",
      status: "pass",
      rationale: "Last T-DXd 2026-07-06 (84 days) and SRS 2026-08-07 (52 days); the 'T-DXd C14 D1 today' line in the 09/24 note is a stale copy-forward contradicted by the HPI and medication list.",
      evidence: [{ quote: "trastuzumab deruxtecan - DISCONTINUED 07/2026 (PD)", source: "Medications" }],
    },
    {
      id: "NCT05950945-inc-16",
      status: "not-applicable",
      rationale: "Contraception rule for participants of reproductive potential; she is a 66-year-old postmenopausal woman.",
    },
    {
      id: "NCT05950945-exc-1",
      status: "fail",
      rationale: "Prior antibody-drug conjugate: T-DXd 5.4 mg/kg from 04/2025 to 07/2026.",
      evidence: [{ quote: "2L T-DXd 5.4 mg/kg 4/2025-7/2026 (last dose 07/06/2026)", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT05950945-exc-2",
      status: "pass",
      confidence: "medium",
      rationale: "No coronary disease, BP 128/74 on lisinopril and LVEF 55%; no uncontrolled or significant cardiovascular disease is documented.",
      evidence: [{ quote: "No CAD. Never smoker.", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT05950945-exc-3",
      status: "unknown",
      confidence: "medium",
      rationale: "No ECG or QTc measurement is documented.",
      actionNeeded: "Obtain 12-lead ECG; QTcF must be below the protocol limit (typically ≤ 470 ms)",
    },
    {
      id: "NCT05950945-exc-4",
      status: "pass",
      rationale: "No ILD or pneumonitis at any time on T-DXd, and CT 07/20/2026 shows no interstitial abnormality or ground-glass opacity.",
      evidence: [
        { quote: "no ILD/pneumonitis at any point (serial CT chest w/o interstitial changes)", source: "Onc note 2026-09-24" },
        { quote: "No interstitial lung abnormality or ground-glass opacity.", source: "CT CAP 07/20/2026" },
      ],
    },
    {
      id: "NCT05950945-exc-5",
      status: "pass",
      rationale: "Brain metastases are treated and inactive (smaller on MRI 2026-09-12, no edema, off steroids since 2026-08-30), and there are no signs of cord compression (gait steady, no deficits).",
      evidence: [
        { quote: "Treated brain mets (GK SRS 8/7/26) stable on 9/12 MRI, off steroids.", source: "Onc note 2026-09-24" },
        { quote: "Alert, CN II-XII intact, no drift, gait steady.", source: "Onc note 2026-09-24" },
      ],
    },
    {
      id: "NCT05950945-exc-6",
      status: "pass",
      confidence: "medium",
      rationale: "No other primary malignancy is recorded; her only cancer is the 2024 breast cancer.",
    },
    {
      id: "NCT05950945-exc-7",
      status: "pass",
      confidence: "medium",
      rationale: "She received T-DXd for 15 months without a recorded hypersensitivity reaction, and has no known drug allergies.",
      evidence: [{ quote: "ALLERGIES: NKDA", source: "Allergies" }],
    },
    {
      id: "NCT05950945-exc-8",
      status: "pass",
      confidence: "medium",
      rationale: "She received trastuzumab and pertuzumab (2024–2025) without a recorded reaction, and has no known drug allergies.",
      evidence: [{ quote: "ALLERGIES: NKDA", source: "Allergies" }],
    },
    {
      id: "NCT05950945-exc-9",
      status: "pass",
      confidence: "medium",
      rationale: "No infection requiring intravenous anti-infectives is documented.",
    },
    {
      id: "NCT05950945-exc-10",
      status: "unknown",
      confidence: "medium",
      rationale: "No immunodeficiency or known HIV is recorded, but hepatitis B and C status is not documented.",
      actionNeeded: "Obtain HBsAg, anti-HBc and HCV antibody (RNA if positive); active HBV or HCV excludes",
    },
    {
      id: "NCT05950945-exc-11",
      status: "pass",
      confidence: "low",
      rationale: "No recent vaccinations are recorded; absence of a live attenuated vaccine in the past 30 days is confirmed at screening.",
      actionNeeded: "Confirm no live attenuated vaccine within 30 days of first dose",
    },
    {
      id: "NCT05950945-exc-12",
      status: "fail",
      confidence: "medium",
      rationale: "Residual grade 2 docetaxel neuropathy has not resolved to grade ≤ 1. Chronic stable grade 2 neuropathy is sometimes accepted with sponsor approval, but the criterion as listed has no such exception.",
      evidence: [{ quote: "Residual G2 PN hands/feet from docetaxel", source: "Onc note 2026-09-24" }],
      actionNeeded: "Ask the sponsor whether chronic, stable grade 2 neuropathy is acceptable",
    },
    {
      id: "NCT05950945-exc-13",
      status: "not-applicable",
      rationale: "She is a 66-year-old postmenopausal woman; pregnancy and breastfeeding exclusions cannot apply.",
    },
    {
      id: "NCT05950945-exc-14",
      status: "pass",
      confidence: "medium",
      rationale: "Never smoker with clear lungs, SpO2 97% and no cough or dyspnoea; no intercurrent lung illness is recorded.",
      evidence: [{ quote: "No cough/SOB.", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT05950945-exc-15",
      status: "pass",
      confidence: "medium",
      rationale: "No autoimmune, connective tissue or inflammatory disorder is recorded; the cause of her treated hypothyroidism is not stated.",
      evidence: [{ quote: "hypothyroidism (levothyroxine)", source: "Onc note 2026-09-24" }],
      actionNeeded: "Clarify the cause of hypothyroidism if the sponsor counts autoimmune thyroiditis",
    },
    {
      id: "NCT05950945-exc-16",
      status: "pass",
      rationale: "No lung surgery; her surgical history is port placement only.",
      evidence: [{ quote: "PSH: port 2/2024. No breast surgery.", source: "Onc note 2026-09-24" }],
    },
  ],
);
