import { demoMatch } from "../../match-helpers";

export default demoMatch(
  "NCT04348747",
  "Excluded: needs an untreated target brain lesion, and all 3 of hers were treated with SRS 8/7/26",
  "This vaccine-plus-pembrolizumab study measures response in at least one untreated brain metastasis. All three of Rosa's lesions were treated with Gamma Knife SRS on 2026-08-07 and the 9/12/26 MRI shows no new lesions, so she has no evaluable target. The listed histology criterion also names only TNBC or HR-positive disease, although the title includes HER2-positive patients. She would become a candidate only if a new or unequivocally progressing, unirradiated lesion of 0.5-3.0 cm appeared on follow-up MRI; her extracranial liver progression, off therapy since July, would also need to be weighed.",
  [
    {
      id: "NCT04348747-inc-1",
      status: "pass",
      rationale: "66-year-old postmenopausal woman, so not of childbearing potential; pregnancy and breastfeeding do not apply.",
      evidence: [{ quote: "66 yo postmenopausal F", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT04348747-inc-2",
      status: "not-applicable",
      rationale: "Contraception rule for women of childbearing potential; she is 66 and postmenopausal.",
    },
    {
      id: "NCT04348747-inc-3",
      status: "not-applicable",
      rationale: "Pregnancy testing applies to women of childbearing potential; she is 66 and postmenopausal.",
    },
    {
      id: "NCT04348747-inc-4",
      status: "not-applicable",
      rationale: "Timing of the screening pregnancy test for women of childbearing potential; not applicable to a postmenopausal woman.",
    },
    {
      id: "NCT04348747-inc-5",
      status: "not-applicable",
      rationale: "Repeat pregnancy test before leukapheresis applies only to women of childbearing potential; she is postmenopausal.",
    },
    {
      id: "NCT04348747-inc-6",
      status: "not-applicable",
      rationale: "Per-cycle pregnancy testing is for women of childbearing potential; she is 66 and postmenopausal.",
    },
    {
      id: "NCT04348747-inc-7",
      status: "not-applicable",
      rationale: "End-of-treatment pregnancy test applies only to women of childbearing potential; she is postmenopausal.",
    },
    {
      id: "NCT04348747-inc-8",
      status: "not-applicable",
      rationale: "Pregnancy testing when pregnancy is suspected applies to women of childbearing potential; she is postmenopausal.",
    },
    {
      id: "NCT04348747-inc-9",
      status: "unknown",
      confidence: "medium",
      rationale: "Her tumor is ER 0%, PR 0%, HER2 IHC 3+, which is neither TNBC nor HR-positive as this criterion is written; the official title and the HER2-antibody provision indicate HER2-positive patients are also enrolled.",
      evidence: [
        { quote: "ER: negative (0%)", source: "Pathology 2024-01-19" },
        { quote: "HER2 IHC: 3+ (positive), complete intense circumferential staining in >10% of cells", source: "Pathology 2024-01-19" },
      ],
      actionNeeded: "Confirm with the Roswell Park study team that a HER2-positive cohort is open; the listed criterion names only TNBC or HR+",
    },
    {
      id: "NCT04348747-inc-10",
      status: "pass",
      rationale: "HER2 was tested by IHC on invasive carcinoma (primary core 01/2024) and on the liver metastasis biopsy, both 3+.",
      evidence: [
        { quote: "HER2 IHC: 3+ (positive), complete intense circumferential staining in >10% of cells", source: "Pathology 2024-01-19" },
        { quote: "Liver bx 2024-01-23: metastatic carcinoma c/w breast primary, HER2 IHC 3+.", source: "Pathology" },
      ],
    },
    {
      id: "NCT04348747-inc-11",
      status: "pass",
      rationale: "Her result meets the IHC 3+ definition exactly (complete, intense circumferential staining in >10% of cells), i.e. HER2-positive with no reflex ISH needed.",
      evidence: [{ quote: "HER2 IHC: 3+ (positive), complete intense circumferential staining in >10% of cells", source: "Pathology 2024-01-19" }],
    },
    {
      id: "NCT04348747-inc-12",
      status: "not-applicable",
      rationale: "ISH definitions apply to equivocal IHC results; her HER2 is IHC 3+ and no ISH was required or performed.",
    },
    {
      id: "NCT04348747-inc-13",
      status: "fail",
      rationale: "All three brain metastases were treated with Gamma Knife SRS on 8/7/26, and the 9/12/26 MRI shows no new enhancing lesions, so she has no untreated lesion of 0.5-3.0 cm to serve as a target.",
      evidence: [
        { quote: "GK SRS to all 3 lesions 8/7/26 (20 Gy).", source: "Onc note 2026-09-24" },
        { quote: "No new enhancing lesions. No vasogenic edema, no mass effect, no hemorrhage.", source: "MRI brain 2026-09-12" },
      ],
    },
    {
      id: "NCT04348747-inc-14",
      status: "pass",
      rationale: "The lesions that caused headache were all treated with SRS and none was ≥ 3 cm (largest 1.4 cm, now 0.8 cm); by this rule all three are now non-evaluable.",
      evidence: [{ quote: "MRI brain 7/22/26 w/ 3 new brain mets (largest 1.4 cm R frontal)", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT04348747-inc-15",
      status: "fail",
      rationale: "SRS on 8/7/26 (52 days ago) and last T-DXd on 7/6/26 (84 days ago) clear the timing windows, but SRS covered all three lesions, leaving no unirradiated lesion as target as this criterion requires.",
      evidence: [{ quote: "GK SRS to all 3 lesions 8/7/26 (20 Gy).", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT04348747-inc-16",
      status: "not-applicable",
      rationale: "She has had no whole-brain radiation; her brain metastases were treated with stereotactic radiosurgery only.",
    },
    {
      id: "NCT04348747-inc-17",
      status: "pass",
      rationale: "Defines SRS-treated lesions as non-target and places no limit on prior local therapy; her three SRS-treated lesions count as non-target.",
      evidence: [{ quote: "GK SRS to all 3 lesions 8/7/26 (20 Gy).", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT04348747-inc-18",
      status: "not-applicable",
      rationale: "No major surgery: her only procedure was port placement in 2/2024 and the breast primary was never resected.",
      evidence: [{ quote: "PSH: port 2/2024. No breast surgery.", source: "PSH" }],
    },
    {
      id: "NCT04348747-inc-19",
      status: "pass",
      rationale: "ECOG 1 at the 2026-09-24 visit.",
      evidence: [{ quote: "EXAM: ECOG 1.", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT04348747-inc-20",
      status: "pass",
      confidence: "medium",
      rationale: "Her one unresolved toxicity is stable grade 2 docetaxel neuropathy, which this criterion explicitly allows; her labs meet the listed thresholds.",
      evidence: [{ quote: "G2 PN (docetaxel): stable, gabapentin 300 mg qhs.", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT04348747-inc-21",
      status: "pass",
      confidence: "medium",
      rationale: "The 2026-09-22 labs (6 days old) meet each listed threshold on file; they will need repeating within 10 days of the first study treatment. Coagulation is not on file (see INR criterion).",
      evidence: [{ quote: "WBC 5.8 | ANC 3.1 | Hgb 10.9 (L) | Plt 165", source: "Labs 2026-09-22" }],
      actionNeeded: "Repeat CBC and chemistry within 10 days before the first study treatment",
    },
    {
      id: "NCT04348747-inc-22",
      status: "pass",
      rationale: "Hemoglobin 10.9 g/dL on 2026-09-22 (chronic mild anemia), above the 9 g/dL minimum.",
      evidence: [{ quote: "Hgb 10.9 (L)", source: "Labs 2026-09-22" }],
    },
    {
      id: "NCT04348747-inc-23",
      status: "pass",
      rationale: "WBC 5.8 × 10⁹/L on 2026-09-22, above the 3 × 10⁹/L minimum.",
      evidence: [{ quote: "WBC 5.8", source: "Labs 2026-09-22" }],
    },
    {
      id: "NCT04348747-inc-24",
      status: "pass",
      rationale: "ANC 3.1 × 10⁹/L on 2026-09-22, above the 1.5 × 10⁹/L minimum.",
      evidence: [{ quote: "ANC 3.1", source: "Labs 2026-09-22" }],
    },
    {
      id: "NCT04348747-inc-25",
      status: "pass",
      rationale: "Platelets 165 × 10⁹/L on 2026-09-22, above the 100 × 10⁹/L minimum.",
      evidence: [{ quote: "Plt 165", source: "Labs 2026-09-22" }],
    },
    {
      id: "NCT04348747-inc-26",
      status: "pass",
      rationale: "Total bilirubin 0.8 mg/dL on 2026-09-22, within normal limits.",
      evidence: [{ quote: "T bili 0.8", source: "Labs 2026-09-22" }],
    },
    {
      id: "NCT04348747-inc-27",
      status: "pass",
      rationale: "AST 52 (1.3 × ULN) and ALT 48 (mildly high) on 2026-09-22 with liver metastases; well within the ≤ 5 × ULN allowance and even the ≤ 2.5 × ULN limit.",
      evidence: [
        { quote: "AST 52 (H, 1.3x ULN)", source: "Labs 2026-09-22" },
        { quote: "ALT 48 (H)", source: "Labs 2026-09-22" },
      ],
    },
    {
      id: "NCT04348747-inc-28",
      status: "pass",
      rationale: "Creatinine 0.9 mg/dL with estimated CrCl ~62 mL/min (Cockcroft-Gault) on 2026-09-22.",
      evidence: [{ quote: "Cr 0.9 | est CrCl ~62 mL/min (CG)", source: "Labs 2026-09-22" }],
    },
    {
      id: "NCT04348747-inc-29",
      status: "unknown",
      confidence: "low",
      rationale: "No INR, PT or aPTT is recorded; she is on no anticoagulant.",
      actionNeeded: "Obtain INR/PT and aPTT; ≤ 1.5 × ULN required",
    },
    {
      id: "NCT04348747-inc-30",
      status: "pass",
      confidence: "medium",
      rationale: "The 9/12/26 contrast brain MRI describes only the three treated parenchymal lesions with no new enhancement, and there are no focal deficits; leptomeningeal disease is not described.",
      evidence: [{ quote: "No new enhancing lesions. No vasogenic edema, no mass effect, no hemorrhage.", source: "MRI brain 2026-09-12" }],
    },
    {
      id: "NCT04348747-inc-31",
      status: "pass",
      rationale: "She is off steroids: the dexamethasone taper was completed on 8/30/26 (29 days ago).",
      evidence: [{ quote: "dexamethasone - taper COMPLETED, last dose 08/30/2026", source: "Medications" }],
    },
    {
      id: "NCT04348747-inc-32",
      status: "pass",
      confidence: "medium",
      rationale: "ECOG 1 with normal bilirubin, controlled intracranial disease and further HER2-directed options available; life expectancy is well over 3 months.",
      evidence: [{ quote: "EXAM: ECOG 1.", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT04348747-inc-33",
      status: "not-applicable",
      rationale: "She has never received a checkpoint inhibitor; prior therapy was THP, trastuzumab/pertuzumab and T-DXd.",
    },
    {
      id: "NCT04348747-inc-34",
      status: "not-applicable",
      rationale: "Permissive provision for continuing current HER2 antibodies; she is off all systemic therapy since T-DXd was stopped in 7/2026, so there is nothing to continue.",
      evidence: [{ quote: "trastuzumab deruxtecan - DISCONTINUED 07/2026 (PD)", source: "Medications" }],
    },
    {
      id: "NCT04348747-inc-35",
      status: "pass",
      confidence: "low",
      rationale: "Procedural note on managing systemic disease; it sets no eligibility threshold, though her progressing liver disease would fall under these provisions.",
    },
    {
      id: "NCT04348747-exc-1",
      status: "pass",
      confidence: "medium",
      rationale: "No confounding condition is recorded beyond her cancer; comorbidities (T2DM, hypertension, hypothyroidism) are controlled.",
    },
    {
      id: "NCT04348747-exc-2",
      status: "pass",
      rationale: "Headaches resolved after SRS and she has no seizures or focal deficits, so her brain metastases are now asymptomatic.",
      evidence: [{ quote: "HA resolved since SRS. No seizures, no focal deficits.", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT04348747-exc-3",
      status: "pass",
      confidence: "medium",
      rationale: "All prior therapy was standard of care (THP, Phesgo, T-DXd); no investigational agent or device is recorded.",
    },
    {
      id: "NCT04348747-exc-4",
      status: "pass",
      confidence: "medium",
      rationale: "Last T-DXd 2026-07-06 is 84 days ago, well beyond 4 weeks. Grade 2 docetaxel neuropathy is unresolved but allowed by the toxicity inclusion criterion; no extracranial radiation.",
      evidence: [{ quote: "2L T-DXd 5.4 mg/kg 4/2025-7/2026 (last dose 07/06/2026)", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT04348747-exc-5",
      status: "unknown",
      confidence: "medium",
      rationale: "Liver metastases grew from 1.6 to 2.8 cm and 1.1 to 2.2 cm with two new lesions by 7/20/26, she now has RUQ discomfort and a tender liver edge, and she has been off therapy since 7/6.",
      evidence: [
        { quote: "Progression of hepatic metastases: segment VII lesion 2.8 cm (previously 1.6 cm), segment V lesion 2.2 cm (previously 1.1 cm), two new subcentimeter lesions.", source: "CT CAP 2026-07-20" },
        { quote: "Liver edge palpable, mildly tender.", source: "Exam 2026-09-24" },
      ],
      actionNeeded: "Restage CT chest/abdomen/pelvis (last 7/20/26) to judge pace of liver progression before a multi-month vaccine schedule",
    },
    {
      id: "NCT04348747-exc-6",
      status: "pass",
      confidence: "medium",
      rationale: "Hypothyroidism on levothyroxine (TSH 2.4) is replacement therapy, which is explicitly allowed; no other autoimmune disease is recorded.",
      evidence: [{ quote: "levothyroxine 100 mcg, TSH 2.4 (7/2026).", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT04348747-exc-7",
      status: "pass",
      confidence: "medium",
      rationale: "No transplant history in the PMH or PSH, which list only a port placement.",
      evidence: [{ quote: "PSH: port 2/2024. No breast surgery.", source: "PSH" }],
    },
    {
      id: "NCT04348747-exc-8",
      status: "pass",
      confidence: "medium",
      rationale: "No active infection recorded: no cough or dyspnoea, SpO2 97% and no antimicrobials on the medication list.",
      evidence: [{ quote: "No cough/SOB.", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT04348747-exc-9",
      status: "pass",
      confidence: "medium",
      rationale: "No known hepatitis B or C in the PMH, and this criterion applies only to known infection (testing not mandatory). Mild AST/ALT rise is explained by liver metastases.",
      evidence: [{ quote: "AST 52 (H, 1.3x ULN)", source: "Labs 2026-09-22" }],
    },
    {
      id: "NCT04348747-exc-10",
      status: "pass",
      confidence: "medium",
      rationale: "No known HIV or other immunosuppressive disease in the PMH; testing is not mandatory under this criterion.",
    },
    {
      id: "NCT04348747-exc-11",
      status: "pass",
      confidence: "medium",
      rationale: "Chronic mild anemia (Hgb 10.9) without bleeding; no transfusion is recorded.",
      evidence: [{ quote: "Mild anemia Hgb 10.9, chronic, no bleeding.", source: "Onc note 2026-09-24" }],
      actionNeeded: "Confirm no blood transfusion in the 2 weeks before leukapheresis",
    },
    {
      id: "NCT04348747-exc-12",
      status: "not-applicable",
      rationale: "She is 66 and postmenopausal; pregnancy and nursing do not apply.",
    },
    {
      id: "NCT04348747-exc-13",
      status: "pass",
      confidence: "low",
      rationale: "Willingness and ability to follow the protocol are confirmed at screening; she is open to a trial if screening is prompt.",
      evidence: [{ quote: "Pt open to trial if screening within 3-4 wks.", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT04348747-exc-14",
      status: "pass",
      rationale: "The 9/12/26 MRI shows no mass effect, edema or hemorrhage, so no midline shift or hydrocephalus.",
      evidence: [{ quote: "No new enhancing lesions. No vasogenic edema, no mass effect, no hemorrhage.", source: "MRI brain 2026-09-12" }],
    },
    {
      id: "NCT04348747-exc-15",
      status: "pass",
      rationale: "No corticosteroids for cerebral edema: dexamethasone was tapered off on 8/30/26 with no rebound symptoms.",
      evidence: [{ quote: "Dex tapered off, last dose 8/30/26.", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT04348747-exc-16",
      status: "pass",
      confidence: "medium",
      rationale: "No stroke or TIA recorded; brain MRI shows no hemorrhage and she has no focal deficits.",
      evidence: [{ quote: "Alert, CN II-XII intact, no drift, gait steady.", source: "Exam 2026-09-24" }],
    },
    {
      id: "NCT04348747-exc-17",
      status: "pass",
      rationale: "No pneumonitis or ILD at any point on T-DXd; CT 7/20/26 shows no interstitial abnormality or ground-glass opacity.",
      evidence: [
        { quote: "no ILD/pneumonitis at any point (serial CT chest w/o interstitial changes)", source: "Onc note 2026-09-24" },
        { quote: "No interstitial lung abnormality or ground-glass opacity.", source: "CT CAP 2026-07-20" },
      ],
    },
    {
      id: "NCT04348747-exc-18",
      status: "pass",
      confidence: "medium",
      rationale: "Leptomeningeal disease is not described on the 9/12/26 contrast MRI, which shows only the treated parenchymal lesions.",
      evidence: [{ quote: "all decreased, consistent with treatment response", source: "MRI brain 2026-09-12" }],
    },
    {
      id: "NCT04348747-exc-19",
      status: "pass",
      rationale: "She completed contrast brain MRIs on 7/22/26 and 9/12/26; her only implant is a port (2/2024).",
      evidence: [{ quote: "MRI BRAIN W/ AND W/O CONTRAST - 2026-09-12", source: "Imaging" }],
    },
    {
      id: "NCT04348747-exc-20",
      status: "pass",
      rationale: "SRS on 8/7/26 is 52 days ago (> 2 weeks); headaches resolved, she is off steroids since 8/30/26 and has had no radiation pneumonitis.",
      evidence: [
        { quote: "GK SRS to all 3 lesions 8/7/26 (20 Gy).", source: "Onc note 2026-09-24" },
        { quote: "Off dex ~3.5 wks, no rebound sx.", source: "Onc note 2026-09-24" },
      ],
    },
    {
      id: "NCT04348747-exc-21",
      status: "unknown",
      confidence: "low",
      rationale: "Vaccination history is not recorded.",
      actionNeeded: "Confirm no live or live-attenuated vaccine (e.g. intranasal influenza, MMR, yellow fever) within 30 days before first dose",
    },
    {
      id: "NCT04348747-exc-22",
      status: "pass",
      rationale: "No immunosuppressive therapy: dexamethasone was completed on 8/30/26 (29 days ago) and no other immunosuppressants are listed.",
      evidence: [{ quote: "dexamethasone - taper COMPLETED, last dose 08/30/2026", source: "Medications" }],
    },
    {
      id: "NCT04348747-exc-23",
      status: "pass",
      confidence: "medium",
      rationale: "No second malignancy is recorded in an otherwise detailed history; all metastatic sites are attributed to the breast primary.",
    },
    {
      id: "NCT04348747-exc-24",
      status: "not-applicable",
      rationale: "Pregnancy testing exclusion for women of childbearing potential; she is 66 and postmenopausal.",
    },
    {
      id: "NCT04348747-exc-25",
      status: "pass",
      confidence: "medium",
      rationale: "No carcinomatous meningitis is described on the 9/12/26 MRI and she has no new neurological symptoms.",
      evidence: [{ quote: "HA resolved since SRS. No seizures, no focal deficits.", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT04348747-exc-26",
      status: "pass",
      confidence: "medium",
      rationale: "No psychiatric history or substance use recorded; she drinks no alcohol and has never smoked.",
      evidence: [{ quote: "SH: lives w/ daughter, no EtOH.", source: "Social history" }],
    },
  ],
);
