import { demoMatch } from "../../match-helpers";

export default demoMatch(
  "NCT07459673",
  "Excluded: treatment-naive first-line study, and she has had THP/HP and T-DXd plus brain metastases",
  "HERizon-Breast is a first-line, curative-intent strategy for de novo HER2-positive metastatic disease, and Rosa does match its de novo stage IV, IHC 3+ entry profile. She is excluded on two documented grounds: she has already received two lines of anti-HER2 therapy (THP followed by Phesgo maintenance, then T-DXd), and she has known brain metastases treated with SRS in August 2026. Neither can change, so this trial is not an option; standard tucatinib-based therapy or a post-T-DXd trial is the relevant comparison.",
  [
    {
      id: "NCT07459673-inc-1",
      status: "pass",
      rationale: "66-year-old woman with biopsy-confirmed metastatic breast cancer (lung, nodal, liver and brain metastases).",
      evidence: [
        { quote: "66 yo postmenopausal F", source: "Onc note 2026-09-24" },
        { quote: "Liver bx 2024-01-23: metastatic carcinoma c/w breast primary, HER2 IHC 3+.", source: "Pathology" },
      ],
    },
    {
      id: "NCT07459673-inc-2",
      status: "pass",
      rationale: "Stage IV at diagnosis in January 2024 (cT3 cN2 M1 with lung, mediastinal nodal and liver metastases).",
      evidence: [
        { quote: "cT3 cN2 M1: bilat lung nodules, mediastinal LN, solitary liver lesion", source: "Onc note 2026-09-24" },
        { quote: "de novo stage IV", source: "Onc note 2026-09-24" },
      ],
    },
    {
      id: "NCT07459673-inc-3",
      status: "pass",
      rationale: "HER2 IHC 3+ on the primary core biopsy and on the liver metastasis (01/2024).",
      evidence: [
        { quote: "HER2 IHC: 3+ (positive), complete intense circumferential staining in >10% of cells", source: "Pathology 2024-01-19" },
        { quote: "Liver bx 2024-01-23: metastatic carcinoma c/w breast primary, HER2 IHC 3+.", source: "Pathology" },
      ],
    },
    {
      id: "NCT07459673-inc-4",
      status: "pass",
      confidence: "medium",
      rationale: "ECOG 1 with normal bilirubin, treated intracranial disease and further HER2-directed options; life expectancy well exceeds 12 weeks.",
      evidence: [{ quote: "EXAM: ECOG 1.", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT07459673-inc-5",
      status: "unknown",
      confidence: "medium",
      rationale: "Medically she is fit (ECOG 1, controlled comorbidities) and the 5 cm primary was never resected, but with progressing liver disease and new brain metastases surgery is not currently indicated; candidacy has not been assessed.",
      evidence: [{ quote: "R breast 5 cm UOQ mass, unchanged. R axillary adenopathy.", source: "Exam 2026-09-24" }],
      actionNeeded: "Obtain a surgical oncology opinion on locoregional surgical candidacy",
    },
    {
      id: "NCT07459673-inc-6",
      status: "unknown",
      confidence: "medium",
      rationale: "Liver lesions of 2.8 and 2.2 cm are measurable on CT (7/20/26), but PERCIST requires FDG-PET/CT, and no PET is on file.",
      evidence: [{ quote: "Measurable liver dz: seg VII 2.8 cm, seg V 2.2 cm.", source: "Onc note 2026-09-24" }],
      actionNeeded: "Obtain baseline FDG-PET/CT; at least one PERCIST 1.0-measurable lesion required",
    },
    {
      id: "NCT07459673-inc-7",
      status: "pass",
      confidence: "low",
      rationale: "Written informed consent is obtained at screening; no capacity concerns are recorded.",
    },
    {
      id: "NCT07459673-inc-8",
      status: "pass",
      rationale: "ECOG 1 at the 2026-09-24 visit.",
      evidence: [{ quote: "EXAM: ECOG 1.", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT07459673-inc-9",
      status: "pass",
      confidence: "medium",
      rationale: "Labs of 2026-09-22 (6 days old) meet the table thresholds that are on file (ANC 3.1, Plt 165, Hgb 10.9, Cr 0.9, bilirubin 0.8, AST 1.3 × ULN); they must be repeated within 14 days of starting.",
      evidence: [{ quote: "LABS 2026-09-22", source: "Labs" }],
      actionNeeded: "Repeat labs within 14 days before the first dose",
    },
    {
      id: "NCT07459673-inc-10",
      status: "pass",
      rationale: "66-year-old postmenopausal woman: not pregnant or breastfeeding and not of childbearing potential.",
      evidence: [{ quote: "66 yo postmenopausal F", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT07459673-inc-11",
      status: "pass",
      rationale: "She meets the first condition: as a 66-year-old postmenopausal woman she is not a woman of childbearing potential.",
      evidence: [{ quote: "66 yo postmenopausal F", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT07459673-inc-12",
      status: "not-applicable",
      rationale: "Pregnancy test for women of childbearing potential; she is 66 and postmenopausal.",
    },
    {
      id: "NCT07459673-inc-13",
      status: "not-applicable",
      rationale: "Ongoing pregnancy-testing requirements apply to women of childbearing potential; she is postmenopausal.",
    },
    {
      id: "NCT07459673-inc-14",
      status: "not-applicable",
      rationale: "Male-participant requirement; the patient is female.",
    },
    {
      id: "NCT07459673-inc-15",
      status: "not-applicable",
      rationale: "Male abstinence/contraception requirement; the patient is female.",
    },
    {
      id: "NCT07459673-inc-16",
      status: "not-applicable",
      rationale: "Male condom requirement; the patient is female.",
    },
    {
      id: "NCT07459673-inc-17",
      status: "unknown",
      confidence: "low",
      rationale: "Hepatitis B and C screening is required per MSK policy; no HBV or HCV serology is on file.",
      actionNeeded: "Obtain HBsAg, anti-HBc and anti-HCV serology",
    },
    {
      id: "NCT07459673-inc-18",
      status: "not-applicable",
      rationale: "Applies only to participants with active hepatitis B; none is recorded (serology is outstanding under the screening criterion).",
    },
    {
      id: "NCT07459673-inc-19",
      status: "not-applicable",
      rationale: "Applies only to participants with a history of hepatitis C; none is recorded.",
    },
    {
      id: "NCT07459673-inc-20",
      status: "not-applicable",
      rationale: "Curative antiviral washout applies to treated hepatitis C; she has no recorded HCV history or treatment.",
    },
    {
      id: "NCT07459673-inc-21",
      status: "pass",
      rationale: "ANC 3.1 × 10⁹/L (3100/µL), platelets 165 × 10⁹/L and hemoglobin 10.9 g/dL on 2026-09-22, all above the minimums.",
      evidence: [{ quote: "WBC 5.8 | ANC 3.1 | Hgb 10.9 (L) | Plt 165", source: "Labs 2026-09-22" }],
    },
    {
      id: "NCT07459673-inc-22",
      status: "pass",
      rationale: "Creatinine 0.9 mg/dL (normal) with estimated CrCl ~62 mL/min on 2026-09-22.",
      evidence: [{ quote: "Cr 0.9 | est CrCl ~62 mL/min (CG)", source: "Labs 2026-09-22" }],
    },
    {
      id: "NCT07459673-inc-23",
      status: "pass",
      rationale: "Total bilirubin 0.8 mg/dL; AST 52 (1.3 × ULN) and ALT 48 (mildly high) with liver metastases, within even a ≤ 2.5 × ULN limit (the AST/ALT threshold is cut off in this text).",
      evidence: [
        { quote: "T bili 0.8", source: "Labs 2026-09-22" },
        { quote: "AST 52 (H, 1.3x ULN)", source: "Labs 2026-09-22" },
      ],
    },
    {
      id: "NCT07459673-inc-24",
      status: "unknown",
      confidence: "low",
      rationale: "Coagulation section of the lab table: no INR, PT or aPTT is recorded.",
      actionNeeded: "Obtain INR/PT and aPTT; ≤ 1.5 × ULN required",
    },
    {
      id: "NCT07459673-inc-25",
      status: "unknown",
      confidence: "low",
      rationale: "No INR, PT or aPTT is recorded; she takes no anticoagulant.",
      actionNeeded: "Obtain INR/PT and aPTT; ≤ 1.5 × ULN required",
    },
    {
      id: "NCT07459673-inc-26",
      status: "unknown",
      confidence: "low",
      rationale: "The ≤ 1.5 × ULN coagulation threshold cannot be checked without INR/PT and aPTT; she is not anticoagulated, so the exception does not apply.",
      actionNeeded: "Obtain INR/PT and aPTT; ≤ 1.5 × ULN required",
    },
    {
      id: "NCT07459673-inc-27",
      status: "pass",
      confidence: "medium",
      rationale: "Her hemoglobin of 10.9 g/dL reflects chronic mild anemia without bleeding; no erythropoietin or transfusion is recorded. CrCl was calculated by Cockcroft-Gault.",
      evidence: [{ quote: "Mild anemia Hgb 10.9, chronic, no bleeding.", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT07459673-exc-1",
      status: "pass",
      rationale: "Her HER2 positivity is by IHC 3+, not IHC 1-2+ with positive ISH.",
      evidence: [{ quote: "HER2 IHC: 3+ (positive), complete intense circumferential staining in >10% of cells", source: "Pathology 2024-01-19" }],
    },
    {
      id: "NCT07459673-exc-2",
      status: "fail",
      rationale: "She has received two lines of anti-HER2 systemic therapy for metastatic disease: THP then Phesgo maintenance (2/2024-3/2025), then T-DXd (4/2025-7/2026).",
      evidence: [
        { quote: "1L THP (docetaxel x6, 2/2024-6/2024) then HP maint (Phesgo), best response PR", source: "Onc note 2026-09-24" },
        { quote: "2L T-DXd 5.4 mg/kg 4/2025-7/2026 (last dose 07/06/2026)", source: "Onc note 2026-09-24" },
      ],
    },
    {
      id: "NCT07459673-exc-3",
      status: "pass",
      confidence: "medium",
      rationale: "No investigational agent or device is recorded; all prior therapy was standard of care.",
    },
    {
      id: "NCT07459673-exc-4",
      status: "pass",
      rationale: "No immunosuppression: dexamethasone was completed on 8/30/26 (29 days ago), outside the 7-day window.",
      evidence: [{ quote: "dexamethasone - taper COMPLETED, last dose 08/30/2026", source: "Medications" }],
    },
    {
      id: "NCT07459673-exc-5",
      status: "pass",
      confidence: "medium",
      rationale: "No second malignancy is recorded in an otherwise detailed history.",
    },
    {
      id: "NCT07459673-exc-6",
      status: "fail",
      rationale: "She has known brain metastases: three lesions found on MRI 7/22/26 and treated with Gamma Knife SRS on 8/7/26.",
      evidence: [
        { quote: "MRI brain 7/22/26 w/ 3 new brain mets (largest 1.4 cm R frontal)", source: "Onc note 2026-09-24" },
        { quote: "GK SRS to all 3 lesions 8/7/26 (20 Gy).", source: "Onc note 2026-09-24" },
      ],
    },
    {
      id: "NCT07459673-exc-7",
      status: "pass",
      rationale: "No pneumonitis or ILD at any point, including on T-DXd; CT 7/20/26 shows no interstitial abnormality.",
      evidence: [
        { quote: "no ILD/pneumonitis at any point (serial CT chest w/o interstitial changes)", source: "Onc note 2026-09-24" },
        { quote: "No interstitial lung abnormality or ground-glass opacity.", source: "CT CAP 2026-07-20" },
      ],
    },
    {
      id: "NCT07459673-exc-8",
      status: "pass",
      rationale: "Her residual docetaxel neuropathy is grade 2, below the grade ≥ 3 threshold.",
      evidence: [{ quote: "Residual G2 PN hands/feet from docetaxel", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT07459673-exc-9",
      status: "pass",
      confidence: "medium",
      rationale: "No active infection or antibiotic use is recorded; no cough or dyspnoea and SpO2 97%.",
      evidence: [{ quote: "No cough/SOB.", source: "Onc note 2026-09-24" }],
    },
    {
      id: "NCT07459673-exc-10",
      status: "pass",
      confidence: "medium",
      rationale: "No known history of HIV in the PMH; the criterion applies to known infection.",
    },
    {
      id: "NCT07459673-exc-11",
      status: "pass",
      confidence: "medium",
      rationale: "She takes several oral tablets daily (metformin, lisinopril, levothyroxine, gabapentin); no swallowing problem is recorded.",
      evidence: [{ quote: "metformin 1000 mg PO BID", source: "Medications" }],
    },
    {
      id: "NCT07459673-exc-12",
      status: "pass",
      confidence: "medium",
      rationale: "No confounding condition beyond her cancer is recorded; diabetes (A1c 6.9%), hypertension and hypothyroidism are controlled.",
    },
    {
      id: "NCT07459673-exc-13",
      status: "pass",
      confidence: "medium",
      rationale: "No psychiatric or substance use disorder is recorded; no alcohol use.",
      evidence: [{ quote: "SH: lives w/ daughter, no EtOH.", source: "Social history" }],
    },
    {
      id: "NCT07459673-exc-14",
      status: "not-applicable",
      rationale: "She is 66 and postmenopausal; pregnancy, breastfeeding and conception do not apply.",
    },
    {
      id: "NCT07459673-exc-15",
      status: "pass",
      confidence: "medium",
      rationale: "No transplant history; the surgical history lists only a port placement.",
      evidence: [{ quote: "PSH: port 2/2024. No breast surgery.", source: "PSH" }],
    },
    {
      id: "NCT07459673-exc-16",
      status: "pass",
      confidence: "medium",
      rationale: "No heart failure, angina, MI, stroke or unstable arrhythmia in the past 12 months: no CAD, LVEF 55% and asymptomatic, BP 128/74, HR 82.",
      evidence: [
        { quote: "No CAD.", source: "PMH" },
        { quote: "LVEF 55% on 9/10/26 echo (baseline 62% in 2024), asymptomatic.", source: "Onc note 2026-09-24" },
      ],
    },
    {
      id: "NCT07459673-exc-17",
      status: "pass",
      rationale: "LVEF 55% by echo on 2026-09-10 (18 days ago), above 50%, though down from 62% in 2024.",
      evidence: [{ quote: "ECHO 2026-09-10: LVEF 55% (biplane Simpson's).", source: "Echo 2026-09-10" }],
    },
    {
      id: "NCT07459673-exc-18",
      status: "pass",
      rationale: "She received T-DXd for 15 months and pertuzumab in THP/Phesgo without documented intolerance; T-DXd was stopped for progression, not toxicity. NKDA.",
      evidence: [{ quote: "trastuzumab deruxtecan - DISCONTINUED 07/2026 (PD)", source: "Medications" }],
    },
    {
      id: "NCT07459673-exc-19",
      status: "pass",
      rationale: "No recent surgery: her only procedure was a port placement in 2/2024.",
      evidence: [{ quote: "PSH: port 2/2024. No breast surgery.", source: "PSH" }],
    },
  ],
);
