import { demoMatch } from "../../match-helpers";

export default demoMatch(
  "NCT07402473",
  "Fits cT3 N1 HER2+ neoadjuvant entry · left-breast biopsy, HBV/HCV/HIV and HARPS tissue pending",
  "Treatment-naive cT3 cN1 M0, HER2 IHC 3+ (ER 60%, PR 20%) IDC with ECOG 0, LVEF 63% and normal labs fits EUREKA's neoadjuvant TCHP/HP population, and the backbone matches the TCHP she would otherwise receive. Three items stay open: the 9/30 MRI-guided biopsy of the 6 mm left-breast focus (bilateral cancer excludes), the hepatitis B/C and HIV serologies drawn 9/22, and whether the 9/3 core biopsy leaves enough tissue for the HARPS assay. Letrozole she is taking for oocyte stimulation is not cancer-directed endocrine therapy, but confirm the study team agrees; a start after retrieval (~10/5) fits her target week of 10/12.",
  [
    {
      id: "NCT07402473-inc-1",
      status: "pass",
      rationale: "Clinical cT3 cN1: 5.4 cm right-breast mass on MRI 9/11 with an FNA-proven axillary node, within the cT2–T3 N0–2 range.",
      evidence: [
        { quote: "cT3 cN1 M0, clinical stage IIIA", source: "Consult 2026-09-23" },
        { quote: "Known R breast malignancy, 5.4 x 4.1 x 3.8 cm, clip in place.", source: "MRI 2026-09-11" },
      ],
    },
    {
      id: "NCT07402473-inc-2",
      status: "pass",
      rationale: "HER2 IHC 3+ on the 9/3 core biopsy, which is HER2-positive without reflex ISH.",
      evidence: [{ quote: "HER2 IHC: 3+ (positive), complete intense circumferential membrane staining in >10% of cells", source: "Pathology 2026-09-08" }],
    },
    {
      id: "NCT07402473-inc-3",
      status: "pass",
      rationale: "ER (60%, moderate) and PR (20%, weak to moderate) were reported locally on the 9/3 core biopsy.",
      evidence: [
        { quote: "ER: positive, 60% of tumor cells, moderate intensity", source: "Pathology 2026-09-08" },
        { quote: "PR: positive, 20% of tumor cells, weak to moderate intensity", source: "Pathology 2026-09-08" },
      ],
    },
    {
      id: "NCT07402473-inc-4",
      status: "unknown",
      confidence: "low",
      rationale: "Diagnosis rests on a single US-guided core biopsy (9/3); the remaining block volume is not documented, and HER2 ISH, NGS and other tissue studies have not been run on it.",
      evidence: [{ quote: "Specimen: A. Right breast 10 o'clock, US-guided core biopsy; B. Right axillary lymph node, FNA" }],
      actionNeeded: "Confirm with pathology that the 9/3 core block has enough tumor for HARPS testing, or plan a pre-treatment research biopsy",
    },
    {
      id: "NCT07402473-inc-5",
      status: "pass",
      confidence: "low",
      rationale: "No ctDNA has been drawn yet; this is a baseline study blood draw done at screening before the first dose, and nothing in the record prevents it.",
      actionNeeded: "Collect the baseline ctDNA sample before the first on-study dose",
    },
    {
      id: "NCT07402473-inc-6",
      status: "pass",
      rationale: "She completed a bilateral contrast-enhanced breast MRI on 9/11 with the biopsy clip in place.",
      evidence: [{ quote: "MRI BREASTS BILATERAL W/ AND W/O CONTRAST - Sept 11, 2026", source: "MRI 2026-09-11" }],
    },
    {
      id: "NCT07402473-inc-7",
      status: "pass",
      rationale: "LVEF 63% on echocardiogram 9/17/2026, above 50% and well within the 5-year window.",
      evidence: [{ quote: "ECHO 9/17/2026: LVEF 63%, normal LV size and function.", source: "Echo 2026-09-17" }],
    },
    {
      id: "NCT07402473-inc-8",
      status: "pass",
      rationale: "Treatment-naive: no prior chemotherapy of any kind, so no anthracycline exposure.",
      evidence: [{ quote: "No prior chemo, anti-HER2 tx, endocrine tx, RT or surgery for cancer.", source: "Consult 2026-09-23" }],
    },
    {
      id: "NCT07402473-inc-9",
      status: "pass",
      rationale: "Labs 9/22: ANC 4.1 × 10⁹/L, platelets 255 × 10⁹/L, Hgb 13.1 g/dL — all above the required thresholds.",
      evidence: [{ quote: "WBC 6.8 | ANC 4.1 | Hgb 13.1 | Plt 255", source: "Labs 2026-09-22" }],
    },
    {
      id: "NCT07402473-inc-10",
      status: "pass",
      rationale: "Labs 9/22: total bilirubin 0.4 mg/dL, AST 18 and ALT 21 U/L — all within normal limits.",
      evidence: [{ quote: "AST 18 | ALT 21 | T bili 0.4 | Alk phos 62 | Albumin 4.4", source: "Labs 2026-09-22" }],
    },
    {
      id: "NCT07402473-inc-11",
      status: "not-applicable",
      rationale: "No biliary obstruction: bilirubin 0.4 mg/dL, normal LFTs and no hepatobiliary findings on PET/CT 9/15.",
      evidence: [{ quote: "AST 18 | ALT 21 | T bili 0.4 | Alk phos 62 | Albumin 4.4", source: "Labs 2026-09-22" }],
    },
    {
      id: "NCT07402473-inc-12",
      status: "pass",
      rationale: "Creatinine 0.6 mg/dL on 9/22, well below 1.5 × ULN.",
      evidence: [{ quote: "Cr 0.6 | Na 140 | K 4.0", source: "Labs 2026-09-22" }],
    },
    {
      id: "NCT07402473-inc-13",
      status: "pass",
      confidence: "low",
      rationale: "Capacity and written consent are confirmed at screening; she is a software engineer actively asking about trials.",
      evidence: [{ quote: "Pt interested in trials (neoadj de-escalation or novel anti-HER2 agent) - referred to research coordinator." }],
    },
    {
      id: "NCT07402473-inc-14",
      status: "pass",
      confidence: "low",
      rationale: "Willingness to follow the visit schedule is confirmed at screening; note her oocyte retrieval (~10/5) must finish before treatment starts.",
    },
    {
      id: "NCT07402473-inc-15",
      status: "pass",
      confidence: "medium",
      rationale: "No prior cancer is recorded and this is a new right-breast primary with no prior surgery (PSH none). The 'Oncologic hx: s/p R lumpectomy' line is a stale template contradicted by the HPI and imaging.",
      evidence: [
        { quote: "CC: newly dx R breast ca, triple positive, neoadj tx planning.", source: "Consult 2026-09-23" },
        { quote: "PSH: none.", source: "Consult 2026-09-23" },
      ],
    },
    {
      id: "NCT07402473-exc-1",
      status: "pass",
      confidence: "medium",
      rationale: "No chemotherapy, anti-HER2 therapy, RT or endocrine therapy for the cancer. Letrozole 5 mg since 9/21 is part of oocyte stimulation, not cancer treatment, and should stop around retrieval (~10/5).",
      evidence: [
        { quote: "No prior chemo, anti-HER2 tx, endocrine tx, RT or surgery for cancer.", source: "Consult 2026-09-23" },
        { quote: "letrozole 5 mg PO daily - ovarian stimulation per REI, started 9/21/2026", source: "Medications" },
      ],
      actionNeeded: "Confirm with the PI that short-course letrozole for ovarian stimulation is not counted as prior endocrine therapy",
    },
    {
      id: "NCT07402473-exc-2",
      status: "pass",
      rationale: "cT3 cN1: no skin, nipple or chest-wall involvement (not T4) and only level I axillary nodes without internal mammary or supraclavicular disease (not N3).",
      evidence: [
        { quote: "No skin, nipple, pectoralis or chest wall involvement.", source: "MRI 2026-09-11" },
        { quote: "Three abnormal R level I axillary nodes. No internal mammary or supraclavicular adenopathy.", source: "MRI 2026-09-11" },
      ],
    },
    {
      id: "NCT07402473-exc-3",
      status: "pass",
      rationale: "Staging PET/CT 9/15 shows uptake only in the right breast and axilla, with no distant metastases.",
      evidence: [{ quote: "No FDG-avid distant metastases.", source: "PET/CT 2026-09-15" }],
    },
    {
      id: "NCT07402473-exc-4",
      status: "unknown",
      confidence: "medium",
      rationale: "Cancer is biopsy-proven on the right only, but a 6 mm BI-RADS 4 enhancing focus in the left breast (not FDG-avid) is awaiting MRI-guided biopsy on 9/30.",
      evidence: [
        { quote: "L breast upper inner quadrant 6 mm enhancing focus, plateau kinetics, indeterminate. BI-RADS 4. MRI-guided biopsy recommended.", source: "MRI 2026-09-11" },
        { quote: "ALSO 6 mm enhancing focus L breast, BI-RADS 4 -> MRI-guided bx scheduled 9/30, result pending.", source: "Consult 2026-09-23" },
      ],
      actionNeeded: "Obtain the 9/30 left-breast MRI-guided biopsy result; invasive carcinoma on the left excludes her",
    },
    {
      id: "NCT07402473-exc-5",
      status: "pass",
      confidence: "medium",
      rationale: "No other malignancy appears in the PMH, history or staging PET/CT of this 34-year-old.",
      evidence: [{ quote: "PMH: mild intermitent asthma (albuterol prn, never hospitalized). No cardiac hx. No DM." }],
    },
    {
      id: "NCT07402473-exc-6",
      status: "pass",
      rationale: "LVEF 63% by echocardiogram on 9/17/2026, above 50%.",
      evidence: [{ quote: "ECHO 9/17/2026: LVEF 63%, normal LV size and function.", source: "Echo 2026-09-17" }],
    },
    {
      id: "NCT07402473-exc-7",
      status: "pass",
      confidence: "medium",
      rationale: "No liver disease in the PMH and LFTs on 9/22 are normal (AST 18, ALT 21, bilirubin 0.4); hepatitis serologies are still pending (see the HBV/HCV criterion).",
      evidence: [{ quote: "AST 18 | ALT 21 | T bili 0.4 | Alk phos 62 | Albumin 4.4", source: "Labs 2026-09-22" }],
    },
    {
      id: "NCT07402473-exc-8",
      status: "pass",
      confidence: "medium",
      rationale: "All 9/22 labs are normal and her only comorbidity is mild intermittent asthma; final judgment rests with the investigator.",
      evidence: [{ quote: "WBC 6.8 | ANC 4.1 | Hgb 13.1 | Plt 255", source: "Labs 2026-09-22" }],
    },
    {
      id: "NCT07402473-exc-9",
      status: "pass",
      confidence: "medium",
      rationale: "No neuropathy is recorded and she has had no neurotoxic therapy; the record does not mention sensory symptoms.",
    },
    {
      id: "NCT07402473-exc-10",
      status: "pass",
      rationale: "No cardiac history; echo 9/17 shows LVEF 63% with normal LV size, ECG is sinus rhythm with QTc 412 ms, BP 116/72.",
      evidence: [
        { quote: "No cardiac hx.", source: "Consult 2026-09-23" },
        { quote: "ECG 9/17/2026: normal sinus rhythm, QTc 412 ms.", source: "ECG 2026-09-17" },
      ],
    },
    {
      id: "NCT07402473-exc-11",
      status: "pass",
      confidence: "medium",
      rationale: "No surgical history, wounds, ulcers or fractures are recorded; the 9/23 exam notes no skin changes.",
      evidence: [{ quote: "PSH: none.", source: "Consult 2026-09-23" }],
    },
    {
      id: "NCT07402473-exc-12",
      status: "unknown",
      confidence: "low",
      rationale: "Hepatitis B surface antigen, core antibody, HCV antibody and HIV Ag/Ab were drawn 9/22 and are still pending; no history of these infections is recorded.",
      evidence: [{ quote: "HBsAg, anti-HBc, HCV Ab, HIV Ag/Ab: pending", source: "Labs 2026-09-22" }],
      actionNeeded: "Obtain the pending HBsAg, anti-HBc, HCV Ab and HIV Ag/Ab results; active HBV/HCV or uncontrolled HIV excludes",
    },
    {
      id: "NCT07402473-exc-13",
      status: "pass",
      confidence: "medium",
      rationale: "NKDA, and she has never received trastuzumab, pertuzumab, docetaxel or carboplatin, so no prior reaction to the study drugs is possible.",
      evidence: [{ quote: "ALLERGIES: NKDA", source: "Allergies" }],
    },
    {
      id: "NCT07402473-exc-14",
      status: "pass",
      confidence: "medium",
      rationale: "Only mild intermittent asthma on albuterol as needed (never hospitalized); no psychiatric history or lab abnormality is recorded.",
      evidence: [{ quote: "PMH: mild intermitent asthma (albuterol prn, never hospitalized). No cardiac hx. No DM." }],
    },
  ],
);
