import { demoMatch } from "../../match-helpers";

export default demoMatch(
  "NCT07102381",
  "Fits stage III HER2+ neoadjuvant entry · left-breast biopsy, hepatitis B/C, live-vaccine history open",
  "Newly diagnosed, untreated stage IIIA (cT3 cN1) HER2 IHC 3+ IDC with ECOG 0, normal labs and LVEF 63% meets every inclusion criterion of this randomized neoadjuvant zanidatamab study. Open items: the 9/30 MRI-guided biopsy of the 6 mm left-breast focus (bilateral cancer excludes), pending hepatitis B/C serologies, and confirmation that no live vaccine was given in a pre-conception fertility workup. The 9/17 echo stays valid for randomization through 10/29; letrozole for oocyte stimulation is not cancer-directed therapy and should be finished at retrieval (~10/5).",
  [
    {
      id: "NCT07102381-inc-1",
      status: "pass",
      rationale: "Newly diagnosed, histologically confirmed IDC, clinical stage IIIA (cT3 cN1 M0).",
      evidence: [
        { quote: "R breast IDC grade 3, ER+/PR+/HER2+ (IHC 3+), cT3 cN1 M0, clinical stage IIIA, treatment-naive. Curative intent.", source: "Consult 2026-09-23" },
        { quote: "A. Invasive ductal carcinoma, grade 3 (Nottingham 8/9). LVI not identified.", source: "Pathology 2026-09-08" },
      ],
    },
    {
      id: "NCT07102381-inc-2",
      status: "pass",
      rationale: "HER2 IHC 3+ on the 9/3 core biopsy.",
      evidence: [{ quote: "HER2 IHC: 3+ (positive), complete intense circumferential membrane staining in >10% of cells", source: "Pathology 2026-09-08" }],
    },
    {
      id: "NCT07102381-inc-3",
      status: "pass",
      rationale: "Primary tumor HR status known: ER 60% and PR 20% positive.",
      evidence: [
        { quote: "ER: positive, 60% of tumor cells, moderate intensity", source: "Pathology 2026-09-08" },
        { quote: "PR: positive, 20% of tumor cells, weak to moderate intensity", source: "Pathology 2026-09-08" },
      ],
    },
    {
      id: "NCT07102381-inc-4",
      status: "pass",
      rationale: "Single right-breast mass; even if further foci were found, the largest tumor (5.4 cm) is ≥ 2 cm and HER2 IHC 3+.",
      evidence: [{ quote: "Known R breast malignancy, 5.4 x 4.1 x 3.8 cm, clip in place.", source: "MRI 2026-09-11" }],
    },
    {
      id: "NCT07102381-inc-5",
      status: "pass",
      confidence: "medium",
      rationale: "Surgery after neoadjuvant therapy is in the documented plan; her agreement is confirmed at consent.",
      evidence: [{ quote: "neoadj TCHP x6 (docetaxel/carboplatin/trastuzumab/pertuzumab) then surgery, adj tx per path response.", source: "Consult 2026-09-23" }],
    },
    {
      id: "NCT07102381-inc-6",
      status: "pass",
      rationale: "ECOG 0 at the 9/23 consult.",
      evidence: [{ quote: "EXAM: ECOG 0.", source: "Consult 2026-09-23" }],
    },
    {
      id: "NCT07102381-inc-7",
      status: "pass",
      rationale: "Labs 9/22 within standard limits: ANC 4.1, platelets 255, Hgb 13.1, creatinine 0.6, bilirubin 0.4, AST 18, ALT 21.",
      evidence: [
        { quote: "WBC 6.8 | ANC 4.1 | Hgb 13.1 | Plt 255", source: "Labs 2026-09-22" },
        { quote: "AST 18 | ALT 21 | T bili 0.4 | Alk phos 62 | Albumin 4.4", source: "Labs 2026-09-22" },
        { quote: "Cr 0.6 | Na 140 | K 4.0", source: "Labs 2026-09-22" },
      ],
    },
    {
      id: "NCT07102381-inc-8",
      status: "pass",
      rationale: "LVEF 63% on echo 9/17; the 6-week window runs to 10/29, covering a randomization in mid-October.",
      evidence: [{ quote: "ECHO 9/17/2026: LVEF 63%, normal LV size and function.", source: "Echo 2026-09-17" }],
      actionNeeded: "Repeat echocardiogram if randomization falls after 10/29",
    },
    {
      id: "NCT07102381-inc-9",
      status: "pass",
      confidence: "low",
      rationale: "Premenopausal and using condoms only; protocol contraception is agreed at screening.",
      evidence: [{ quote: "Contraception: condoms.", source: "Consult 2026-09-23" }],
      actionNeeded: "Confirm a protocol-acceptable highly effective method; non-hormonal options suit HR+ disease",
    },
    {
      id: "NCT07102381-inc-10",
      status: "pass",
      confidence: "medium",
      rationale: "Permissive criterion: no known HIV, and HIV Ag/Ab from 9/22 is pending; a positive result would need CD4 count and viral load reviewed.",
      evidence: [{ quote: "HBsAg, anti-HBc, HCV Ab, HIV Ag/Ab: pending", source: "Labs 2026-09-22" }],
    },
    {
      id: "NCT07102381-exc-1",
      status: "pass",
      rationale: "No distant metastases on PET/CT 9/15 (M0).",
      evidence: [{ quote: "No FDG-avid distant metastases.", source: "PET/CT 2026-09-15" }],
    },
    {
      id: "NCT07102381-exc-2",
      status: "unknown",
      confidence: "medium",
      rationale: "Only the right breast is biopsy-proven, but a 6 mm BI-RADS 4 left-breast focus (not FDG-avid) is awaiting MRI-guided biopsy on 9/30.",
      evidence: [{ quote: "ALSO 6 mm enhancing focus L breast, BI-RADS 4 -> MRI-guided bx scheduled 9/30, result pending.", source: "Consult 2026-09-23" }],
      actionNeeded: "Obtain the 9/30 left-breast biopsy result; invasive cancer on the left excludes her",
    },
    {
      id: "NCT07102381-exc-3",
      status: "pass",
      confidence: "medium",
      rationale: "No severe or uncontrolled condition: only mild intermittent asthma, never hospitalized.",
      evidence: [{ quote: "PMH: mild intermitent asthma (albuterol prn, never hospitalized). No cardiac hx. No DM." }],
    },
    {
      id: "NCT07102381-exc-4",
      status: "pass",
      rationale: "BP 116/72 on 9/23 with no antihypertensive therapy.",
      evidence: [{ quote: "BP 116/72 HR 74 afebrile.", source: "Consult 2026-09-23" }],
    },
    {
      id: "NCT07102381-exc-5",
      status: "pass",
      confidence: "medium",
      rationale: "No neuropathy recorded and no prior neurotoxic therapy.",
    },
    {
      id: "NCT07102381-exc-6",
      status: "pass",
      confidence: "medium",
      rationale: "Afebrile with clear lungs and no infection or antibiotic use recorded.",
      evidence: [{ quote: "BP 116/72 HR 74 afebrile.", source: "Consult 2026-09-23" }],
    },
    {
      id: "NCT07102381-exc-7",
      status: "pass",
      confidence: "medium",
      rationale: "NKDA; never exposed to a monoclonal antibody, and tolerating recombinant follitropin alfa without a recorded reaction.",
      evidence: [{ quote: "ALLERGIES: NKDA", source: "Allergies" }],
    },
    {
      id: "NCT07102381-exc-8",
      status: "unknown",
      confidence: "low",
      rationale: "No hepatitis history recorded; HBsAg, anti-HBc and HCV antibody drawn 9/22 are pending.",
      evidence: [{ quote: "HBsAg, anti-HBc, HCV Ab, HIV Ag/Ab: pending", source: "Labs 2026-09-22" }],
      actionNeeded: "Obtain pending HBsAg, anti-HBc and HCV Ab (with HBV DNA/HCV RNA if positive); active infection excludes",
    },
    {
      id: "NCT07102381-exc-9",
      status: "pass",
      confidence: "medium",
      rationale: "No other malignancy recorded, and no prior ipsilateral DCIS or invasive cancer; the 's/p R lumpectomy' line is a stale template contradicted by the HPI and PSH.",
      evidence: [
        { quote: "CC: newly dx R breast ca, triple positive, neoadj tx planning.", source: "Consult 2026-09-23" },
        { quote: "PSH: none.", source: "Consult 2026-09-23" },
      ],
    },
    {
      id: "NCT07102381-exc-10",
      status: "pass",
      confidence: "medium",
      rationale: "No surgery, chemotherapy, anti-HER2, radiation or endocrine therapy for the cancer; letrozole since 9/21 is for oocyte stimulation, not cancer treatment.",
      evidence: [
        { quote: "No prior chemo, anti-HER2 tx, endocrine tx, RT or surgery for cancer.", source: "Consult 2026-09-23" },
        { quote: "letrozole 5 mg PO daily - ovarian stimulation per REI, started 9/21/2026", source: "Medications" },
      ],
      actionNeeded: "Confirm with the sponsor that fertility-stimulation letrozole is not counted as prior endocrine therapy",
    },
    {
      id: "NCT07102381-exc-11",
      status: "pass",
      confidence: "medium",
      rationale: "No other investigational or anti-cancer therapy is planned; stimulation drugs should stop at oocyte retrieval (~10/5), before treatment.",
      evidence: [{ quote: "oocyte cryopreservation cycle in progress (letrozole + gonadotropins, random start 9/21), retrieval planned ~10/5." }],
    },
    {
      id: "NCT07102381-exc-12",
      status: "unknown",
      confidence: "low",
      rationale: "Vaccination history is not recorded; live vaccines (MMR, varicella) are sometimes given in pre-conception fertility workups.",
      actionNeeded: "Confirm no live vaccine in the 4 weeks before enrollment (ask REI about MMR/varicella)",
    },
    {
      id: "NCT07102381-exc-13",
      status: "pass",
      confidence: "medium",
      rationale: "NKDA, and she has never received zanidatamab, taxanes, carboplatin, trastuzumab or pertuzumab.",
      evidence: [{ quote: "ALLERGIES: NKDA", source: "Allergies" }],
    },
  ],
);
