import { demoMatch } from "../../match-helpers";

export default demoMatch(
  "NCT04329065",
  "Meets all inclusion criteria with TCHP planned · hepatitis B/C serologies pending",
  "Stage IIIA HER2 IHC 3+ disease with neoadjuvant TCHP already planned fits this WOKVAC study directly, and her ECOG 0, labs from 9/22 and LVEF 63% (9/17) meet every threshold. The one open exclusion is hepatitis B/C: the protocol excludes current or past infection, including dormant HBV, and the HBsAg/anti-HBc/HCV Ab drawn 9/22 are pending. She will need dual contraception from enrollment (condoms only today), and the 9/22 labs expire for this purpose on 10/20, so a start the week of 10/12 after oocyte retrieval fits. The 9/30 left-breast biopsy should still be reviewed before enrollment.",
  [
    {
      id: "NCT04329065-inc-1",
      status: "pass",
      rationale: "34 years old (DOB 1992).",
      evidence: [{ quote: "DOB: 1992 (34 yo F)", source: "Consult 2026-09-23" }],
    },
    {
      id: "NCT04329065-inc-2",
      status: "pass",
      rationale: "Clinical stage IIIA, HER2 IHC 3+ (ER/PR positive, allowed), with neoadjuvant TCHP x6 documented as the planned regimen.",
      evidence: [
        { quote: "cT3 cN1 M0, clinical stage IIIA", source: "Consult 2026-09-23" },
        { quote: "neoadj TCHP x6 (docetaxel/carboplatin/trastuzumab/pertuzumab) then surgery, adj tx per path response.", source: "Consult 2026-09-23" },
      ],
    },
    {
      id: "NCT04329065-inc-3",
      status: "not-applicable",
      rationale: "Applies only to patients who already started neoadjuvant chemotherapy; she is treatment-naive and could receive either THP or TCHP.",
      evidence: [{ quote: "No prior chemo, anti-HER2 tx, endocrine tx, RT or surgery for cancer.", source: "Consult 2026-09-23" }],
    },
    {
      id: "NCT04329065-inc-4",
      status: "pass",
      rationale: "ECOG 0 at the 9/23 consult.",
      evidence: [{ quote: "EXAM: ECOG 0.", source: "Consult 2026-09-23" }],
    },
    {
      id: "NCT04329065-inc-5",
      status: "pass",
      rationale: "WBC 6.8 × 10⁹/L (6,800/mm³) on 9/22; within 4 weeks of a start on or before 10/20.",
      evidence: [{ quote: "WBC 6.8 | ANC 4.1 | Hgb 13.1 | Plt 255", source: "Labs 2026-09-22" }],
      actionNeeded: "Repeat CBC if study treatment starts after 10/20",
    },
    {
      id: "NCT04329065-inc-6",
      status: "pass",
      confidence: "medium",
      rationale: "No differential is reported, but WBC 6.8 minus ANC 4.1 leaves 2.7 × 10⁹/L of non-neutrophil cells, so an absolute lymphocyte count ≥ 500/mm³ is near-certain.",
      evidence: [{ quote: "WBC 6.8 | ANC 4.1 | Hgb 13.1 | Plt 255", source: "Labs 2026-09-22" }],
      actionNeeded: "Confirm absolute lymphocyte count ≥ 500/mm³ on a CBC differential within 4 weeks of start",
    },
    {
      id: "NCT04329065-inc-7",
      status: "pass",
      rationale: "ANC 4.1 × 10⁹/L (4,100/µL) on 9/22, above 1,500/µL.",
      evidence: [{ quote: "WBC 6.8 | ANC 4.1 | Hgb 13.1 | Plt 255", source: "Labs 2026-09-22" }],
    },
    {
      id: "NCT04329065-inc-8",
      status: "pass",
      rationale: "Platelets 255 × 10⁹/L on 9/22, above 75,000/µL.",
      evidence: [{ quote: "WBC 6.8 | ANC 4.1 | Hgb 13.1 | Plt 255", source: "Labs 2026-09-22" }],
    },
    {
      id: "NCT04329065-inc-9",
      status: "pass",
      rationale: "Total bilirubin 0.4 mg/dL on 9/22, within normal limits.",
      evidence: [{ quote: "AST 18 | ALT 21 | T bili 0.4 | Alk phos 62 | Albumin 4.4", source: "Labs 2026-09-22" }],
    },
    {
      id: "NCT04329065-inc-10",
      status: "pass",
      rationale: "AST 18 and ALT 21 U/L on 9/22, within normal limits.",
      evidence: [{ quote: "AST 18 | ALT 21 | T bili 0.4 | Alk phos 62 | Albumin 4.4", source: "Labs 2026-09-22" }],
    },
    {
      id: "NCT04329065-inc-11",
      status: "pass",
      rationale: "Creatinine 0.6 mg/dL on 9/22, below 2.0 mg/dL.",
      evidence: [{ quote: "Cr 0.6 | Na 140 | K 4.0", source: "Labs 2026-09-22" }],
    },
    {
      id: "NCT04329065-inc-12",
      status: "pass",
      rationale: "LVEF 63% with normal LV function on echo 9/17, within 3 months of a mid-October start.",
      evidence: [{ quote: "ECHO 9/17/2026: LVEF 63%, normal LV size and function.", source: "Echo 2026-09-17" }],
    },
    {
      id: "NCT04329065-inc-13",
      status: "pass",
      confidence: "low",
      rationale: "Of child-bearing potential using condoms only; the protocol needs dual methods and a negative urine hCG at screening (serum hCG negative 9/22). Hormonal methods are generally avoided in HR+ disease.",
      evidence: [
        { quote: "Contraception: condoms.", source: "Consult 2026-09-23" },
        { quote: "hCG (serum) negative", source: "Labs 2026-09-22" },
      ],
      actionNeeded: "Confirm dual contraception (e.g. condoms plus copper IUD) through 3 months after the last vaccine; urine hCG at screening",
    },
    {
      id: "NCT04329065-inc-14",
      status: "pass",
      confidence: "low",
      rationale: "Capacity and written consent are confirmed at screening; she has asked about trial options.",
      evidence: [{ quote: "Pt interested in trials (neoadj de-escalation or novel anti-HER2 agent) - referred to research coordinator." }],
    },
    {
      id: "NCT04329065-exc-1",
      status: "pass",
      rationale: "No cardiac history; echo 9/17 shows LVEF 63% with normal LV size and function, excluding cardiomyopathy or heart failure.",
      evidence: [
        { quote: "No cardiac hx.", source: "Consult 2026-09-23" },
        { quote: "ECHO 9/17/2026: LVEF 63%, normal LV size and function.", source: "Echo 2026-09-17" },
      ],
    },
    {
      id: "NCT04329065-exc-2",
      status: "pass",
      confidence: "medium",
      rationale: "No autoimmune disease is recorded and she takes no systemic immunomodulating therapy.",
    },
    {
      id: "NCT04329065-exc-3",
      status: "pass",
      confidence: "medium",
      rationale: "NKDA and no prior GM-CSF exposure or known contraindication to it.",
      evidence: [{ quote: "ALLERGIES: NKDA", source: "Allergies" }],
    },
    {
      id: "NCT04329065-exc-4",
      status: "pass",
      rationale: "Not pregnant (serum hCG negative 9/22) and not breastfeeding (G0).",
      evidence: [
        { quote: "hCG (serum) negative", source: "Labs 2026-09-22" },
        { quote: "34 yo premenopausal F, G0", source: "Consult 2026-09-23" },
      ],
    },
    {
      id: "NCT04329065-exc-5",
      status: "pass",
      confidence: "medium",
      rationale: "Not known to be HIV-positive; the HIV Ag/Ab drawn 9/22 is pending and should be reviewed when it returns.",
      evidence: [{ quote: "HBsAg, anti-HBc, HCV Ab, HIV Ag/Ab: pending", source: "Labs 2026-09-22" }],
    },
    {
      id: "NCT04329065-exc-6",
      status: "pass",
      rationale: "No diabetes on the problem list.",
      evidence: [{ quote: "No cardiac hx. No DM.", source: "Consult 2026-09-23" }],
    },
    {
      id: "NCT04329065-exc-7",
      status: "unknown",
      confidence: "low",
      rationale: "No hepatitis history is recorded, but this criterion also excludes dormant or past HBV, which only serology shows; HBsAg, anti-HBc and HCV Ab from 9/22 are pending.",
      evidence: [{ quote: "HBsAg, anti-HBc, HCV Ab, HIV Ag/Ab: pending", source: "Labs 2026-09-22" }],
      actionNeeded: "Obtain pending HBsAg, anti-HBc and HCV Ab; any current or past HBV/HCV excludes unless treated and confirmed cleared",
    },
    {
      id: "NCT04329065-exc-8",
      status: "pass",
      rationale: "No prior surgery (PSH none); port placement and oocyte retrieval (~10/5) are minor procedures.",
      evidence: [
        { quote: "PSH: none.", source: "Consult 2026-09-23" },
        { quote: "Port placement to be scheduled.", source: "Consult 2026-09-23" },
      ],
    },
    {
      id: "NCT04329065-exc-9",
      status: "pass",
      rationale: "No systemic corticosteroids or immunosuppressants on the medication list; asthma is treated with as-needed albuterol only.",
      evidence: [{ quote: "albuterol HFA 2 puffs q4-6h prn wheeze", source: "Medications" }],
    },
    {
      id: "NCT04329065-exc-10",
      status: "pass",
      confidence: "medium",
      rationale: "Not enrolled in another interventional trial; she has only been referred to the research coordinator, so co-enrollment must be avoided.",
      evidence: [{ quote: "Pt interested in trials (neoadj de-escalation or novel anti-HER2 agent) - referred to research coordinator." }],
    },
    {
      id: "NCT04329065-exc-11",
      status: "pass",
      rationale: "No investigational agents on the medication list; current medications are albuterol, fertility drugs and a prenatal vitamin.",
      evidence: [{ quote: "prenatal vitamin PO daily", source: "Medications" }],
    },
  ],
);
