import { demoMatch } from "../../match-helpers";

export default demoMatch(
  "NCT06949410",
  "Not yet: needs ≥ 6 months of completed curative HER2 therapy; she is treatment-naive",
  "This HER2 peptide vaccine trial enrolls high-risk patients after curative-intent HER2-targeted therapy. She already meets the high-risk definition (clinical stage III, HER2 IHC 3+), but she has not started treatment, so the requirement for at least six months of trastuzumab-based therapy, last dose within six months of registration, cannot be met now. She could be reconsidered after completing neoadjuvant TCHP, surgery and adjuvant HER2 therapy, when the MVF-HER-2 skin test, hepatitis/HIV serologies, a repeat echo and pregnancy test would be needed.",
  [
    {
      id: "NCT06949410-inc-1",
      status: "pass",
      rationale: "34 years old (DOB 1992).",
      evidence: [{ quote: "DOB: 1992 (34 yo F)", source: "Consult 2026-09-23" }],
    },
    {
      id: "NCT06949410-inc-2",
      status: "pass",
      confidence: "low",
      rationale: "Written consent and HIPAA authorization are obtained at screening; nothing in the record suggests impaired capacity.",
    },
    {
      id: "NCT06949410-inc-3",
      status: "pass",
      rationale: "Histologically confirmed IDC with HER2 IHC 3+ on the 9/3 core biopsy; ER/PR status is not restricted.",
      evidence: [{ quote: "HER2 IHC: 3+ (positive), complete intense circumferential membrane staining in >10% of cells", source: "Pathology 2026-09-08" }],
    },
    {
      id: "NCT06949410-inc-4",
      status: "pass",
      rationale: "Clinical stage IIIA (cT3 cN1 M0) at diagnosis per the treating oncologist, one of the listed high-risk definitions.",
      evidence: [{ quote: "cT3 cN1 M0, clinical stage IIIA", source: "Consult 2026-09-23" }],
    },
    {
      id: "NCT06949410-inc-5",
      status: "fail",
      rationale: "She has received no HER2-targeted therapy at all; neoadjuvant TCHP is only being planned, so six months of curative-setting HER2 therapy is not met.",
      evidence: [{ quote: "No prior chemo, anti-HER2 tx, endocrine tx, RT or surgery for cancer.", source: "Consult 2026-09-23" }],
    },
    {
      id: "NCT06949410-inc-6",
      status: "fail",
      rationale: "No HER2-targeted therapy has been started or completed, so there is no last dose to fall within six months of registration.",
      evidence: [{ quote: "R breast IDC grade 3, ER+/PR+/HER2+ (IHC 3+), cT3 cN1 M0, clinical stage IIIA, treatment-naive. Curative intent.", source: "Consult 2026-09-23" }],
    },
    {
      id: "NCT06949410-inc-7",
      status: "not-applicable",
      rationale: "No chemotherapy or radiation has been given, so there is no washout or toxicity to resolve yet; this would apply after her planned neoadjuvant course.",
    },
    {
      id: "NCT06949410-inc-8",
      status: "pass",
      rationale: "ECOG 0 at the 9/23 consult.",
      evidence: [{ quote: "EXAM: ECOG 0.", source: "Consult 2026-09-23" }],
    },
    {
      id: "NCT06949410-inc-9",
      status: "pass",
      confidence: "medium",
      rationale: "Labs 9/22: bilirubin 0.4 mg/dL, AST 18, ALT 21, ANC 4.1, platelets 255. Weight is not recorded, but creatinine 0.6 at age 34 gives a Cockcroft-Gault CrCl far above 60 mL/min.",
      evidence: [
        { quote: "AST 18 | ALT 21 | T bili 0.4 | Alk phos 62 | Albumin 4.4", source: "Labs 2026-09-22" },
        { quote: "WBC 6.8 | ANC 4.1 | Hgb 13.1 | Plt 255", source: "Labs 2026-09-22" },
        { quote: "Cr 0.6 | Na 140 | K 4.0", source: "Labs 2026-09-22" },
      ],
    },
    {
      id: "NCT06949410-inc-10",
      status: "pass",
      rationale: "LVEF 63% on echo 9/17, above the lower limit of normal; a registration after HER2 therapy would need a repeat within 90 days.",
      evidence: [{ quote: "ECHO 9/17/2026: LVEF 63%, normal LV size and function.", source: "Echo 2026-09-17" }],
      actionNeeded: "Repeat echocardiogram within 90 days of registration",
    },
    {
      id: "NCT06949410-inc-11",
      status: "pass",
      confidence: "low",
      rationale: "Of childbearing potential (premenopausal, LMP 9/8); serum hCG negative on 9/22, to be repeated within 14 days of registration.",
      evidence: [{ quote: "hCG (serum) negative", source: "Labs 2026-09-22" }],
      actionNeeded: "Repeat serum hCG within 14 days of registration",
    },
    {
      id: "NCT06949410-inc-12",
      status: "pass",
      confidence: "low",
      rationale: "Agreement to effective contraception through 6 months after the last vaccine is confirmed at screening; condoms are her current method.",
      evidence: [{ quote: "Contraception: condoms.", source: "Consult 2026-09-23" }],
    },
    {
      id: "NCT06949410-inc-13",
      status: "pass",
      confidence: "low",
      rationale: "Condoms are documented without spermicide; the listed methods require condom plus spermicide, an IUD, or another listed method, confirmed at screening.",
      evidence: [{ quote: "Contraception: condoms.", source: "Consult 2026-09-23" }],
      actionNeeded: "Confirm a listed method, e.g. condom plus spermicide or a non-hormonal IUD",
    },
    {
      id: "NCT06949410-exc-1",
      status: "pass",
      rationale: "No distant disease: PET/CT 9/15 shows uptake only in the right breast and axilla.",
      evidence: [{ quote: "No FDG-avid distant metastases.", source: "PET/CT 2026-09-15" }],
    },
    {
      id: "NCT06949410-exc-2",
      status: "pass",
      confidence: "medium",
      rationale: "No malignancy other than the breast cancer appears in the PMH or staging.",
      evidence: [{ quote: "PMH: mild intermitent asthma (albuterol prn, never hospitalized). No cardiac hx. No DM." }],
    },
    {
      id: "NCT06949410-exc-3",
      status: "pass",
      confidence: "medium",
      rationale: "No adjuvant CDK4/6 inhibitor is planned; the plan is TCHP then adjuvant therapy guided by pathologic response.",
      evidence: [{ quote: "neoadj TCHP x6 (docetaxel/carboplatin/trastuzumab/pertuzumab) then surgery, adj tx per path response.", source: "Consult 2026-09-23" }],
    },
    {
      id: "NCT06949410-exc-4",
      status: "unknown",
      confidence: "low",
      rationale: "The MVF-HER-2 peptide immediate hypersensitivity skin test is a study screening procedure and has not been done.",
      actionNeeded: "Perform the MVF-HER-2(266-296)/(597-626) skin test at screening; a positive test excludes",
    },
    {
      id: "NCT06949410-exc-5",
      status: "pass",
      confidence: "medium",
      rationale: "No steroid or immunosuppressant use; asthma is mild intermittent on as-needed albuterol and has never required hospitalization.",
      evidence: [
        { quote: "PMH: mild intermitent asthma (albuterol prn, never hospitalized). No cardiac hx. No DM." },
        { quote: "albuterol HFA 2 puffs q4-6h prn wheeze", source: "Medications" },
      ],
    },
    {
      id: "NCT06949410-exc-6",
      status: "pass",
      confidence: "medium",
      rationale: "No autoimmune disease is recorded in the PMH.",
    },
    {
      id: "NCT06949410-exc-7",
      status: "pass",
      confidence: "medium",
      rationale: "Allergy list is NKDA with no vaccine anaphylaxis recorded; worth confirming directly at screening.",
      evidence: [{ quote: "ALLERGIES: NKDA", source: "Allergies" }],
      actionNeeded: "Confirm no prior anaphylaxis to any vaccine",
    },
    {
      id: "NCT06949410-exc-8",
      status: "pass",
      confidence: "medium",
      rationale: "Afebrile, lungs clear, no antibiotics on the medication list and no active infection recorded.",
      evidence: [{ quote: "BP 116/72 HR 74 afebrile.", source: "Consult 2026-09-23" }],
    },
    {
      id: "NCT06949410-exc-9",
      status: "unknown",
      confidence: "low",
      rationale: "HBsAg, anti-HBc, HCV antibody and HIV Ag/Ab were drawn 9/22 and are pending; no prior infection is recorded.",
      evidence: [{ quote: "HBsAg, anti-HBc, HCV Ab, HIV Ag/Ab: pending", source: "Labs 2026-09-22" }],
      actionNeeded: "Obtain pending HBV, HCV and HIV serologies; seropositivity not due to vaccination excludes",
    },
    {
      id: "NCT06949410-exc-10",
      status: "pass",
      confidence: "medium",
      rationale: "No uncontrolled illness: no cardiac history, no infection, asthma stable.",
      evidence: [{ quote: "3. Asthma: stable.", source: "Consult 2026-09-23" }],
    },
    {
      id: "NCT06949410-exc-11",
      status: "pass",
      rationale: "No cardiac history; her only pulmonary condition is mild intermittent asthma, never hospitalized and not COPD.",
      evidence: [{ quote: "PMH: mild intermitent asthma (albuterol prn, never hospitalized). No cardiac hx. No DM." }],
    },
    {
      id: "NCT06949410-exc-12",
      status: "pass",
      rationale: "No prior surgery of any kind (PSH none), so no splenectomy.",
      evidence: [{ quote: "PSH: none.", source: "Consult 2026-09-23" }],
    },
    {
      id: "NCT06949410-exc-13",
      status: "pass",
      rationale: "Not pregnant (serum hCG negative 9/22) and not breastfeeding (G0).",
      evidence: [
        { quote: "hCG (serum) negative", source: "Labs 2026-09-22" },
        { quote: "34 yo premenopausal F, G0", source: "Consult 2026-09-23" },
      ],
    },
  ],
);
