import { demoMatch } from "../../match-helpers";

export default demoMatch(
  "NCT05035836",
  "Excluded: low-risk node-negative ≤ 3 cm pilot; her tumor is 5.4 cm with an FNA-proven axillary node",
  "This single-agent zanidatamab pilot is limited to low-risk HER2+ tumors of > 1 to ≤ 3 cm that are clinically and radiographically node-negative. Her right-breast IDC measures 5.2 cm on ultrasound and 5.4 cm on MRI, with a positive axillary FNA (cT3 cN1, stage IIIA), so she falls outside the population regardless of the other items. She otherwise meets the HER2, performance and organ-function requirements; a node-positive stage III trial or standard TCHP is the appropriate route.",
  [
    {
      id: "NCT05035836-inc-1",
      status: "pass",
      confidence: "low",
      rationale: "Capacity and written consent are confirmed at screening; she is engaged and asking about trial options.",
    },
    {
      id: "NCT05035836-inc-2",
      status: "pass",
      rationale: "34 years old (DOB 1992).",
      evidence: [{ quote: "DOB: 1992 (34 yo F)", source: "Consult 2026-09-23" }],
    },
    {
      id: "NCT05035836-inc-3",
      status: "pass",
      confidence: "medium",
      rationale: "Surgery after neoadjuvant therapy is part of the plan and she has no surgical contraindication; willingness is confirmed at consent.",
      evidence: [{ quote: "neoadj TCHP x6 (docetaxel/carboplatin/trastuzumab/pertuzumab) then surgery, adj tx per path response.", source: "Consult 2026-09-23" }],
    },
    {
      id: "NCT05035836-inc-4",
      status: "pass",
      rationale: "ECOG 0 at the 9/23 consult.",
      evidence: [{ quote: "EXAM: ECOG 0.", source: "Consult 2026-09-23" }],
    },
    {
      id: "NCT05035836-inc-5",
      status: "fail",
      rationale: "Primary measures 5.2 cm on ultrasound (8/28) and 5.4 cm on MRI, above the 3 cm limit, and the axilla is node-positive (FNA-proven, 3 abnormal level I nodes).",
      evidence: [
        { quote: "DIAGNOSTIC MAMOGRAM + US - 08/28/2026: R breast 10:00 5.2 cm irregular hypoechoic mass, BI-RADS 5.", source: "Mammogram/US 2026-08-28" },
        { quote: "B. Positive for metastatic carcinoma, c/w breast primary.", source: "Pathology 2026-09-08" },
      ],
    },
    {
      id: "NCT05035836-inc-6",
      status: "pass",
      rationale: "HER2 IHC 3+ (positive by ASCO-CAP); ER 60% positive, which the trial allows.",
      evidence: [
        { quote: "HER2 IHC: 3+ (positive), complete intense circumferential membrane staining in >10% of cells", source: "Pathology 2026-09-08" },
        { quote: "ER: positive, 60% of tumor cells, moderate intensity", source: "Pathology 2026-09-08" },
      ],
    },
    {
      id: "NCT05035836-inc-7",
      status: "pass",
      confidence: "medium",
      rationale: "LVEF 63% with normal LV function on echo 9/17; the 4-week window runs to 10/15, so it covers a start the week of 10/12 but not a later one.",
      evidence: [{ quote: "ECHO 9/17/2026: LVEF 63%, normal LV size and function.", source: "Echo 2026-09-17" }],
      actionNeeded: "Repeat echocardiogram if first dose falls after 10/15",
    },
    {
      id: "NCT05035836-inc-8",
      status: "pass",
      rationale: "Labs 9/22: Hgb 13.1, ANC 4.1, platelets 255, bilirubin 0.4, AST 18, ALT 21, creatinine 0.6 mg/dL (GFR well above 50) — all within limits.",
      evidence: [
        { quote: "WBC 6.8 | ANC 4.1 | Hgb 13.1 | Plt 255", source: "Labs 2026-09-22" },
        { quote: "AST 18 | ALT 21 | T bili 0.4 | Alk phos 62 | Albumin 4.4", source: "Labs 2026-09-22" },
        { quote: "Cr 0.6 | Na 140 | K 4.0", source: "Labs 2026-09-22" },
      ],
    },
    {
      id: "NCT05035836-inc-9",
      status: "pass",
      confidence: "low",
      rationale: "Premenopausal and of reproductive potential, currently using condoms only; agreement to effective contraception is confirmed at screening. Banking her own oocytes (retrieval ~10/5) is not donation.",
      evidence: [{ quote: "Contraception: condoms.", source: "Consult 2026-09-23" }],
      actionNeeded: "Confirm she will use protocol-acceptable contraception and not donate oocytes through 12 months after treatment",
    },
    {
      id: "NCT05035836-inc-10",
      status: "pass",
      confidence: "low",
      rationale: "Serum hCG was negative on 9/22; the protocol needs a repeat test within 3 days of the first dose.",
      evidence: [{ quote: "hCG (serum) negative", source: "Labs 2026-09-22" }],
      actionNeeded: "Repeat pregnancy test within 3 days before first dose",
    },
    {
      id: "NCT05035836-exc-1",
      status: "pass",
      confidence: "low",
      rationale: "She is a software engineer with no recorded role in the study; confirmed at screening.",
      evidence: [{ quote: "SH: software engineer, never smoker, rare EtOH." }],
    },
    {
      id: "NCT05035836-exc-2",
      status: "pass",
      confidence: "medium",
      rationale: "No prior or concurrent non-breast malignancy is recorded; the PMH lists only mild asthma.",
      evidence: [{ quote: "PMH: mild intermitent asthma (albuterol prn, never hospitalized). No cardiac hx. No DM." }],
    },
    {
      id: "NCT05035836-exc-3",
      status: "pass",
      confidence: "medium",
      rationale: "No therapy has been given for this cancer. Letrozole since 9/21 is for oocyte stimulation, not cancer treatment; the 'Oncologic hx: s/p R lumpectomy' line is a stale template contradicted by the HPI.",
      evidence: [
        { quote: "No prior chemo, anti-HER2 tx, endocrine tx, RT or surgery for cancer.", source: "Consult 2026-09-23" },
        { quote: "letrozole 5 mg PO daily - ovarian stimulation per REI, started 9/21/2026", source: "Medications" },
      ],
      actionNeeded: "Confirm the PI does not count fertility-stimulation letrozole as prior endocrine therapy",
    },
    {
      id: "NCT05035836-exc-4",
      status: "pass",
      rationale: "QTc 412 ms on ECG 9/17, below 470 ms.",
      evidence: [{ quote: "ECG 9/17/2026: normal sinus rhythm, QTc 412 ms.", source: "ECG 2026-09-17" }],
    },
    {
      id: "NCT05035836-exc-5",
      status: "pass",
      confidence: "medium",
      rationale: "Afebrile, asthma stable, no infection, ulcer disease, bleeding disorder or psychiatric illness recorded.",
      evidence: [{ quote: "3. Asthma: stable.", source: "Consult 2026-09-23" }],
    },
    {
      id: "NCT05035836-exc-6",
      status: "pass",
      confidence: "low",
      rationale: "Not pregnant (serum hCG negative 9/22, G0) and not breastfeeding; she uses condoms, and use of an effective method is confirmed at screening.",
      evidence: [
        { quote: "hCG (serum) negative", source: "Labs 2026-09-22" },
        { quote: "Contraception: condoms.", source: "Consult 2026-09-23" },
      ],
      actionNeeded: "Confirm an effective contraceptive method; condoms alone are documented",
    },
    {
      id: "NCT05035836-exc-7",
      status: "pass",
      confidence: "medium",
      rationale: "No seizure disorder is recorded in the PMH.",
    },
    {
      id: "NCT05035836-exc-8",
      status: "pass",
      rationale: "No prior surgery (PSH none). The planned port is allowed and oocyte retrieval (~10/5) is a minor procedure.",
      evidence: [
        { quote: "PSH: none.", source: "Consult 2026-09-23" },
        { quote: "Port placement to be scheduled.", source: "Consult 2026-09-23" },
      ],
    },
    {
      id: "NCT05035836-exc-9",
      status: "pass",
      rationale: "No cardiac history, LVEF 63%, sinus rhythm, and BP 116/72 without antihypertensives.",
      evidence: [
        { quote: "No cardiac hx.", source: "Consult 2026-09-23" },
        { quote: "BP 116/72 HR 74 afebrile.", source: "Consult 2026-09-23" },
      ],
    },
    {
      id: "NCT05035836-exc-10",
      status: "pass",
      confidence: "medium",
      rationale: "No history of hepatitis B or C; the protocol does not require testing without such a history. Serologies drawn 9/22 are pending and should be reviewed when back.",
      evidence: [{ quote: "HBsAg, anti-HBc, HCV Ab, HIV Ag/Ab: pending", source: "Labs 2026-09-22" }],
    },
    {
      id: "NCT05035836-exc-11",
      status: "pass",
      confidence: "medium",
      rationale: "Not known to be HIV-positive, and the protocol does not require testing; the HIV Ag/Ab drawn 9/22 is pending.",
      evidence: [{ quote: "HBsAg, anti-HBc, HCV Ab, HIV Ag/Ab: pending", source: "Labs 2026-09-22" }],
    },
    {
      id: "NCT05035836-exc-12",
      status: "pass",
      rationale: "No prior chemotherapy, so lifetime anthracycline exposure is zero.",
      evidence: [{ quote: "No prior chemo, anti-HER2 tx, endocrine tx, RT or surgery for cancer.", source: "Consult 2026-09-23" }],
    },
    {
      id: "NCT05035836-exc-13",
      status: "pass",
      rationale: "Medication list has no systemic corticosteroids or immunosuppressants; asthma is managed with as-needed albuterol only.",
      evidence: [{ quote: "albuterol HFA 2 puffs q4-6h prn wheeze", source: "Medications" }],
    },
    {
      id: "NCT05035836-exc-14",
      status: "pass",
      confidence: "medium",
      rationale: "NKDA; she has never received a monoclonal antibody and is tolerating recombinant follitropin alfa without a recorded reaction.",
      evidence: [{ quote: "ALLERGIES: NKDA", source: "Allergies" }],
    },
    {
      id: "NCT05035836-exc-15",
      status: "pass",
      confidence: "medium",
      rationale: "PET/CT 9/15 shows no distant metastases; no brain imaging, but she has no neurological symptoms.",
      evidence: [{ quote: "No FDG-avid distant metastases.", source: "PET/CT 2026-09-15" }],
    },
    {
      id: "NCT05035836-exc-16",
      status: "pass",
      confidence: "medium",
      rationale: "No renal, pancreatic or liver disease recorded; creatinine 0.6, AST 18, ALT 21, bilirubin 0.4 on 9/22.",
      evidence: [{ quote: "AST 18 | ALT 21 | T bili 0.4 | Alk phos 62 | Albumin 4.4", source: "Labs 2026-09-22" }],
    },
    {
      id: "NCT05035836-exc-17",
      status: "pass",
      confidence: "medium",
      rationale: "No pulmonary embolism or thrombosis recorded; PET/CT 9/15 described no such finding.",
    },
    {
      id: "NCT05035836-exc-18",
      status: "unknown",
      confidence: "low",
      rationale: "Vaccination history is not recorded; live vaccines (e.g. MMR, varicella) are sometimes given in pre-conception fertility workups.",
      actionNeeded: "Confirm no live vaccine in the 4 weeks before randomization (ask REI about MMR/varicella)",
    },
  ],
);
