import type { PatientProfile } from "@/lib/types";
import { EXTRACTED_AT, ev, x } from "../profile-helpers";

// ---------------------------------------------------------------------------
// Aisha K. — de novo metastatic TNBC (HER2 IHC 0, PD-L1 CPS 15), progressed on
// first-line pembrolizumab + gemcitabine/carboplatin; ADC-naive; anti-HBc+
// ---------------------------------------------------------------------------

const A_NOTE = "Oncology follow-up note 2026-09-25";
const A_PATH = "Pathology report, lung core biopsy 2025-11-20";
const A_PRIOR = "Prior pathology, breast core biopsy 2025-11-12";
const A_MOL = "Tissue NGS report 2025-12-12";
const A_GEN = "Germline panel 2025-12-09";
const A_CT = "CT chest/abdomen/pelvis 2026-09-15";
const A_MRI = "MRI brain 2025-11-18";
const A_LABS = "Labs 2026-09-23";
const A_MEDS = "Medication list";
const A_ALLERGY = "Allergies";

export const PROFILE: PatientProfile = {
  id: "aisha-k",
  label: "Aisha K.",
  demographics: {
    age: x(46, "high", [ev("46 yo premenopausal F", A_NOTE)]),
    sex: x("female" as const, "high", [ev("46 yo premenopausal F", A_NOTE)]),
    menopausalStatus: x(
      "premenopausal" as const,
      "high",
      [ev("46 yo premenopausal F (s/p BTL 2014)", A_NOTE)],
      "Bilateral tubal ligation in 2014 (permanent contraception); no ovarian function suppression documented.",
    ),
  },
  diagnosis: {
    primary: x(
      "Invasive ductal carcinoma of the left breast, triple-negative, de novo metastatic (primary never resected)",
      "high",
      [
        ev("w/ de novo metastatic L breast IDC, grade 3, ER 0%/PR 0%/HER2 IHC 0 (TNBC, not HER2-low), dx Nov 2025.", A_NOTE),
        ev("Metastatic carcinoma, c/w breast primary (GATA3+, TTF-1 neg).", A_PATH),
      ],
    ),
    histology: x("Invasive ductal carcinoma", "high", [ev("IDC, grade 3 (Nottingham 9/9)", A_PRIOR)]),
    grade: x("Grade 3 (Nottingham 9/9)", "high", [ev("IDC, grade 3 (Nottingham 9/9)", A_PRIOR)]),
    laterality: x("left" as const, "high", [ev("de novo metastatic L breast IDC", A_NOTE)]),
    diagnosisDate: x(
      "2025-11",
      "high",
      [ev("dx Nov 2025", A_NOTE), ev("L breast core bx 11/12/2025", A_PRIOR)],
      "Breast core biopsy 2025-11-12; metastatic disease confirmed on the RLL lung biopsy 2025-11-20.",
    ),
    stageAtDiagnosis: x(
      "IV (de novo)",
      "high",
      [ev("lytic T11 + L iliac lesions (cT3 cN2 M1)", A_NOTE)],
      "'Stage IV' is not written; it follows directly from M1 disease at presentation.",
    ),
    tnm: x("cT3 cN2 M1", "high", [ev("lytic T11 + L iliac lesions (cT3 cN2 M1)", A_NOTE)]),
    currentStage: x(
      "IV",
      "high",
      [ev("De novo metastatic TNBC (HER2 IHC 0, PD-L1 CPS 15), lung/nodal/bone, now new liver met.", A_NOTE)],
    ),
    setting: x(
      "metastatic" as const,
      "high",
      [
        ev("De novo metastatic TNBC (HER2 IHC 0, PD-L1 CPS 15), lung/nodal/bone, now new liver met.", A_NOTE),
        ev("PD on 1L pembro + gem/carbo after ~9 mo.", A_NOTE),
      ],
      "De novo metastatic disease; one prior line in the metastatic setting (pembrolizumab + gemcitabine/carboplatin), now planning second line.",
    ),
    subtype: x(
      "TNBC",
      "high",
      [
        ev("ER 0%/PR 0%/HER2 IHC 0 (TNBC, not HER2-low)", A_NOTE),
        ev("HER2 IHC: 0 (no staining observed) - not HER2-low", A_PATH),
      ],
      "HER2 IHC 0 with no staining observed: HER2-negative, not HER2-low.",
    ),
    metastaticSites: x(
      [
        "lung (bilateral nodules; RLL nodule biopsy-proven)",
        "mediastinal/hilar lymph nodes",
        "bone (T11, left ilium)",
        "liver (new segment VI lesion, 2026-09)",
      ],
      "high",
      [
        ev("bilat lung nodules, mediastinal/hilar lymphadenopthy, lytic T11 + L iliac lesions (cT3 cN2 M1)", A_NOTE),
        ev("New 2.1 cm hypoattenuating lesion in hepatic segment VI, consistent with metastasis.", A_CT),
      ],
      "Liver lesion is radiological only (not biopsied). No CNS disease on the November 2025 baseline MRI.",
    ),
    measurableDisease: x(true, "high", [ev("Measurable dz: liver seg VI 2.1 cm, RLL 1.8 cm.", A_NOTE)]),
    cnsStatus: x(
      "none" as const,
      "medium",
      [
        ev("MRI BRAIN 11/18/2025 (baseline): no intracranial metastases.", A_MRI),
        ev("No brain imaging since baseline 11/2025; asymptomatic.", A_NOTE),
        ev("No HA, no visual chnages, no focal weakness.", A_NOTE),
      ],
      "Baseline brain MRI negative in November 2025 and not repeated since (about 10 months); no neurological symptoms.",
    ),
  },
  biomarkers: [
    {
      name: "ER",
      status: "negative",
      detail: "0% (lung metastasis 2025-11-20; 0% on the breast primary core 2025-11-12)",
      method: "IHC",
      date: "2025-11-20",
      specimen: "RLL lung core biopsy 2025-11 (concordant with breast core 2025-11-12)",
      evidence: [ev("ER: negative (0%)", A_PATH), ev("ER 0%, PR 0%, HER2 IHC 0, Ki-67 80%.", A_PRIOR)],
      confidence: "high",
    },
    {
      name: "PR",
      status: "negative",
      detail: "0% (lung metastasis 2025-11-20; 0% on the breast primary core 2025-11-12)",
      method: "IHC",
      date: "2025-11-20",
      specimen: "RLL lung core biopsy 2025-11 (concordant with breast core 2025-11-12)",
      evidence: [ev("PR: negative (0%)", A_PATH), ev("ER 0%, PR 0%, HER2 IHC 0, Ki-67 80%.", A_PRIOR)],
      confidence: "high",
    },
    {
      name: "HER2",
      status: "negative",
      detail: "IHC 0, no staining observed (not HER2-low), on lung metastasis and breast primary; not re-tested at progression",
      method: "IHC",
      date: "2025-11-20",
      specimen: "RLL lung core biopsy 2025-11 (concordant with breast core 2025-11-12)",
      evidence: [
        ev("HER2 IHC: 0 (no staining observed) - not HER2-low", A_PATH),
        ev("Note: no re-biopsy at progression; receptor status per 2025 tissue.", A_PATH),
      ],
      confidence: "high",
    },
    {
      name: "Ki-67",
      status: "high",
      detail: "80%",
      method: "IHC",
      date: "2025-11-12",
      specimen: "breast core biopsy 2025-11-12",
      evidence: [ev("Ki-67 80%", A_PRIOR)],
      confidence: "high",
    },
    {
      name: "PD-L1",
      status: "positive",
      detail: "CPS 15 (22C3 pharmDx); meets the CPS ≥ 10 threshold used in metastatic TNBC",
      method: "IHC",
      date: "2025-11-20",
      specimen: "RLL lung core biopsy 2025-11",
      evidence: [
        ev("PD-L1 IHC (22C3 pharmDx): CPS 15", A_PATH),
        ev("RLL nodule bx 11/20/25 c/w met TNBC, PD-L1 (22C3) CPS 15.", A_NOTE),
      ],
      confidence: "high",
    },
    {
      name: "TP53",
      status: "mutated",
      detail: "p.R248Q (c.743G>A), VAF 41%, pathogenic",
      method: "NGS",
      date: "2025-12-12",
      specimen: "RLL lung core biopsy 2025-11",
      evidence: [ev("TP53 p.R248Q (c.743G>A), VAF 41% - pathogenic", A_MOL)],
      confidence: "high",
    },
    {
      name: "PIK3CA",
      status: "wild-type",
      detail: "No alterations detected",
      method: "NGS",
      date: "2025-12-12",
      specimen: "RLL lung core biopsy 2025-11",
      evidence: [ev("PIK3CA: no alterations detected (wild-type)", A_MOL)],
      confidence: "high",
    },
    {
      name: "gBRCA",
      status: "negative",
      detail: "Germline multigene panel negative (BRCA1, BRCA2, PALB2, TP53, CHEK2, ATM)",
      method: "germline",
      date: "2025-12-09",
      specimen: "blood (germline)",
      evidence: [
        ev("Germline panel (blood), reported 12/09/2025: NEGATIVE (BRCA1, BRCA2, PALB2, TP53, CHEK2, ATM).", A_GEN),
        ev("Germline panel neg.", A_NOTE),
      ],
      confidence: "high",
    },
    {
      name: "BRCA1",
      status: "wild-type",
      detail: "No somatic alteration on tissue NGS; germline panel negative",
      method: "NGS",
      date: "2025-12-12",
      specimen: "RLL lung core biopsy 2025-11",
      evidence: [ev("BRCA1/BRCA2: no alterations detected", A_MOL)],
      confidence: "high",
    },
    {
      name: "BRCA2",
      status: "wild-type",
      detail: "No somatic alteration on tissue NGS; germline panel negative",
      method: "NGS",
      date: "2025-12-12",
      specimen: "RLL lung core biopsy 2025-11",
      evidence: [ev("BRCA1/BRCA2: no alterations detected", A_MOL)],
      confidence: "high",
    },
    {
      name: "PALB2",
      status: "wild-type",
      detail: "No pathogenic variant (germline)",
      method: "germline",
      date: "2025-12-09",
      specimen: "blood (germline)",
      evidence: [ev("NEGATIVE (BRCA1, BRCA2, PALB2, TP53, CHEK2, ATM)", A_GEN)],
      confidence: "high",
    },
    {
      name: "TMB",
      status: "low",
      detail: "4 mut/Mb",
      method: "NGS",
      date: "2025-12-12",
      specimen: "RLL lung core biopsy 2025-11",
      evidence: [ev("TMB: 4 mut/Mb (low).", A_MOL)],
      confidence: "high",
    },
    {
      name: "MSI",
      status: "negative",
      detail: "Microsatellite stable (MSS)",
      method: "NGS",
      date: "2025-12-12",
      specimen: "RLL lung core biopsy 2025-11",
      evidence: [ev("MSI: stable (MSS).", A_MOL)],
      confidence: "high",
    },
  ],
  treatments: [
    {
      name: "Pembrolizumab + gemcitabine/carboplatin (KEYNOTE-355, first-line metastatic)",
      agents: ["pembrolizumab", "gemcitabine", "carboplatin"],
      category: "immunotherapy",
      intent: "metastatic",
      line: 1,
      startDate: "2025-12",
      endDate: "2026-09-02",
      status: "discontinued",
      bestResponse: "PR",
      reasonStopped:
        "progression on CT 2026-09-15 (new liver lesion, growing RLL nodule) after ~9 months; last gemcitabine/carboplatin 2026-08-26, last pembrolizumab 2026-09-02",
      evidence: [
        ev("1L pembrolizumab + gemcitabine/carboplatin (KEYNOTE-355) started 12/2025", A_NOTE),
        ev("Best response PR (CT 3/2026).", A_NOTE),
        ev("Last gem/carbo 8/26/26.", A_NOTE),
        ev("Pembro deferred 1 wk for AST/ALT ~2x ULN (HBV DNA neg), last dose 9/2/26.", A_NOTE),
        ev("pembrolizumab + gemcitabine/carboplatin - DISCONTINUED 9/2026 (PD)", A_MEDS),
      ],
      confidence: "high",
    },
    {
      name: "Denosumab (bone-targeted supportive therapy)",
      agents: ["denosumab"],
      category: "other",
      intent: "metastatic",
      startDate: "2025-12",
      status: "ongoing",
      evidence: [
        ev("w/ denosumab + entecavir ppx", A_NOTE),
        ev("Bone mets: denosumab 120 mg q4w + Ca/vit D.", A_NOTE),
      ],
      confidence: "high",
    },
  ],
  performance: {
    ecog: x(1, "high", [ev("EXAM: ECOG 1.", A_NOTE)], "Grade 1 fatigue; working part-time from home."),
  },
  labs: [
    { name: "WBC", value: "3.9", unit: "x10^9/L", date: "2026-09-23", flag: "abnormal", evidence: [ev("WBC 3.9 (L)", A_LABS)] },
    { name: "ANC", value: "1.6", unit: "x10^9/L", date: "2026-09-23", flag: "normal", evidence: [ev("ANC 1.6", A_LABS)] },
    { name: "Hemoglobin", value: "9.8", unit: "g/dL", date: "2026-09-23", flag: "abnormal", evidence: [ev("Hgb 9.8 (L)", A_LABS)] },
    { name: "Platelets", value: "132", unit: "x10^9/L", date: "2026-09-23", flag: "abnormal", evidence: [ev("Plt 132 (L)", A_LABS)] },
    { name: "Creatinine", value: "0.7", unit: "mg/dL", date: "2026-09-23", flag: "normal", evidence: [ev("Cr 0.7", A_LABS)] },
    {
      name: "AST",
      value: "58 (1.5x ULN)",
      unit: "U/L",
      date: "2026-09-23",
      flag: "abnormal",
      evidence: [ev("AST 58 (H, 1.5x ULN)", A_LABS)],
    },
    {
      name: "ALT",
      value: "61 (1.5x ULN)",
      unit: "U/L",
      date: "2026-09-23",
      flag: "abnormal",
      evidence: [ev("ALT 61 (H, 1.5x ULN)", A_LABS)],
    },
    { name: "Total bilirubin", value: "0.9", unit: "mg/dL", date: "2026-09-23", flag: "normal", evidence: [ev("T bili 0.9", A_LABS)] },
    {
      name: "Alkaline phosphatase",
      value: "162",
      unit: "U/L",
      date: "2026-09-23",
      flag: "abnormal",
      evidence: [ev("Alk phos 162 (H)", A_LABS)],
    },
    { name: "Albumin", value: "3.7", unit: "g/dL", date: "2026-09-23", flag: "normal", evidence: [ev("Albumin 3.7", A_LABS)] },
    { name: "TSH", value: "2.2", unit: "mIU/L", date: "2026-09-23", flag: "normal", evidence: [ev("TSH 2.2", A_LABS)] },
    {
      name: "HBV DNA",
      value: "not detected",
      date: "2026-08-28",
      flag: "normal",
      evidence: [ev("HBV DNA 08/28/2026: not detected", A_LABS)],
    },
    { name: "HBsAg", value: "negative", date: "2025-12", flag: "normal", evidence: [ev("HBsAg neg", A_LABS)] },
    { name: "Anti-HBc", value: "positive", date: "2025-12", flag: "abnormal", evidence: [ev("anti-HBc POS", A_LABS)] },
    { name: "HCV antibody", value: "negative", date: "2025-12", flag: "normal", evidence: [ev("HCV Ab neg", A_LABS)] },
    { name: "HIV-1/2 Ag/Ab", value: "negative", date: "2025-12", flag: "normal", evidence: [ev("HIV Ag/Ab neg", A_LABS)] },
  ],
  comorbidities: [
    x(
      "Immune-related hypothyroidism, grade 2 (from pembrolizumab; on levothyroxine, TSH normal)",
      "high",
      [
        ev("irAE hypothyroidism G2 2/2026 -> levothyroxine; no pneumonitis/colitis.", A_NOTE),
        ev("irAE hypothyroidism G2: levothyroxine 88 mcg, TSH 2.2, continue.", A_NOTE),
      ],
      "No pneumonitis or colitis; no autoimmune disease before pembrolizumab ('No autoimmune dz prior to pembro.').",
    ),
    x(
      "Resolved hepatitis B infection (anti-HBc positive, HBsAg negative, HBV DNA undetectable) on entecavir prophylaxis",
      "high",
      [
        ev("HBV (anti-HBc+, HBsAg neg): entecavir ppx, HBV DNA undetectable 8/2026.", A_NOTE),
        ev("HBV DNA 08/28/2026: not detected", A_LABS),
      ],
      "Hepatitis C antibody and HIV negative (12/2025). Entecavir to continue for at least 12 months after the last anticancer therapy.",
    ),
    x(
      "Chemotherapy-related anemia (Hgb 9.8 g/dL; 1 unit PRBC 7/2026)",
      "high",
      [ev("Anemia (chemo-related): Hgb 9.8, no bleeding.", A_NOTE), ev("1u PRBC 7/2026 for chemo-related anemia.", A_NOTE)],
    ),
    x(
      "Grade 1 transaminase elevation (AST/ALT ~1.5x ULN), attributed to liver metastasis",
      "high",
      [ev("AST/ALT ~1.5x ULN, bili nl: likely liver met, no features of immune hepatitis.", A_NOTE)],
      "Peaked at ~2x ULN in late August 2026 (pembrolizumab deferred one week); bilirubin normal.",
    ),
    x("Grade 1 fatigue", "high", [ev("G1 fatigue, works part-time from home.", A_NOTE)], "No diabetes or cardiac history ('No DM, no cardiac hx.')."),
  ],
  medications: [
    x("Levothyroxine 88 mcg daily", "high", [ev("levothyroxine 88 mcg PO daily", A_MEDS)]),
    x(
      "Entecavir 0.5 mg daily (HBV prophylaxis)",
      "high",
      [ev("entecavir 0.5 mg PO daily (HBV ppx)", A_MEDS)],
      "Antiviral prophylaxis for anti-HBc positivity; trials that allow resolved HBV usually require it to continue.",
    ),
    x("Denosumab 120 mg SC every 4 weeks", "high", [ev("denosumab 120 mg SC q4 weeks", A_MEDS)]),
    x(
      "Ondansetron 8 mg PO every 8 hours as needed",
      "high",
      [ev("ondansetron 8 mg PO q8h prn nausea", A_MEDS)],
      "QT-prolonging antiemetic (as needed); no ECG on file.",
    ),
    x(
      "Calcium carbonate 600 mg / vitamin D3 800 IU daily",
      "high",
      [ev("calcium carbonate 600 mg / vitamin D3 800 IU daily", A_MEDS)],
      "No anticoagulants, systemic steroids or strong CYP3A4 inhibitors/inducers on the list.",
    ),
    x(
      "Pembrolizumab + gemcitabine/carboplatin — discontinued 9/2026",
      "high",
      [ev("pembrolizumab + gemcitabine/carboplatin - DISCONTINUED 9/2026 (PD)", A_MEDS)],
      "Listed for washout purposes; last gemcitabine/carboplatin 2026-08-26, last pembrolizumab 2026-09-02. Not a current medication.",
    ),
  ],
  allergies: [x("Penicillin (hives)", "high", [ev("ALLERGIES: penicillin (hives)", A_ALLERGY)])],
  keyDates: [
    { label: "Initial diagnosis (de novo metastatic)", date: "2025-11", evidence: [ev("dx Nov 2025", A_NOTE)] },
    { label: "Breast core biopsy", date: "2025-11-12", evidence: [ev("L breast core bx 11/12/2025", A_PRIOR)] },
    {
      label: "Baseline brain MRI (negative)",
      date: "2025-11-18",
      evidence: [ev("MRI BRAIN 11/18/2025 (baseline): no intracranial metastases.", A_MRI)],
    },
    { label: "Metastatic biopsy (RLL lung nodule)", date: "2025-11-20", evidence: [ev("Collected: 11/20/2025", A_PATH)] },
    { label: "Germline panel result (negative)", date: "2025-12-09", evidence: [ev("reported 12/09/2025: NEGATIVE", A_GEN)] },
    {
      label: "Start of first-line metastatic therapy",
      date: "2025-12",
      evidence: [ev("1L pembrolizumab + gemcitabine/carboplatin (KEYNOTE-355) started 12/2025", A_NOTE)],
    },
    { label: "Last dose of gemcitabine/carboplatin", date: "2026-08-26", evidence: [ev("Last gem/carbo 8/26/26.", A_NOTE)] },
    { label: "HBV DNA (not detected)", date: "2026-08-28", evidence: [ev("HBV DNA 08/28/2026: not detected", A_LABS)] },
    { label: "Last dose of pembrolizumab", date: "2026-09-02", evidence: [ev("last dose 9/2/26", A_NOTE)] },
    {
      label: "Progression on first-line therapy (CT)",
      date: "2026-09-15",
      evidence: [ev("CT CAP 9/15/26 w/ PD", A_NOTE), ev("CT CHEST/ABDOMEN/PELVIS W/ CONTRAST - 2026-09-15", A_CT)],
    },
    {
      label: "Last imaging (CT chest/abdomen/pelvis)",
      date: "2026-09-15",
      evidence: [ev("CT CHEST/ABDOMEN/PELVIS W/ CONTRAST - 2026-09-15", A_CT)],
    },
    { label: "Most recent labs", date: "2026-09-23", evidence: [ev("LABS 2026-09-23", A_LABS)] },
    { label: "Most recent clinic visit", date: "2026-09-25", evidence: [ev("Date of service: 9/25/26", A_NOTE)] },
  ],
  openQuestions: [
    "UGT1A1 genotype is not on file (plan is to send it); sacituzumab govitecan and topoisomerase-I-payload ADC trials often exclude or dose-modify UGT1A1*28 homozygotes.",
    "No echocardiogram or LVEF on file (no prior anthracycline or HER2-directed therapy); many ADC trials require LVEF ≥ 50% at screening.",
    "ECG/QTc not documented; she takes ondansetron as needed (QT-prolonging).",
    "No brain imaging since the negative baseline MRI on 2025-11-18 (asymptomatic); trials commonly require brain MRI within 28 days of enrollment.",
    "HER2 IHC 0 and receptor status come from November 2025 tissue with no re-biopsy at progression; the new liver lesion has not been biopsied. Fresh tissue may be required (patient open to liver biopsy), and re-testing could reclassify HER2 status.",
    "Washout: last pembrolizumab 2026-09-02 and last gemcitabine/carboplatin 2026-08-26; a 4-week anti-PD-1 washout completes about 2026-09-30. The 2026-09-25 A/P carries a stale copy-forward line ('C9 D1 pembro/gem/carbo today ... continue q3w'); treatment was stopped for progression.",
    "Hemoglobin 9.8 g/dL (transfused 1 unit in July 2026) meets ≥ 9 g/dL thresholds but not ≥ 10 g/dL; many trials also bar transfusion within 2 weeks of screening labs.",
    "AST/ALT ~1.5x ULN with liver metastasis is within usual limits (≤ 2.5x ULN, or ≤ 5x with liver involvement), and ANC 1.6 / platelets 132 are adequate but near common thresholds; repeat before screening.",
    "Hepatitis B: anti-HBc positive, HBsAg negative, HBV DNA undetectable on entecavir. Confirm each trial's wording; many allow resolved infection with undetectable DNA on prophylaxis, some exclude any anti-HBc positivity.",
    "Prior immune-related adverse event (grade 2 hypothyroidism, on replacement); trials re-challenging with checkpoint inhibitors may ask about irAE grade and resolution.",
    "No prior taxane: some second-line TNBC trials require prior taxane exposure, while ADC trials with taxane-naive arms may not.",
    "Pregnancy test not documented; bilateral tubal ligation (2014) usually counts as highly effective contraception, but a negative pregnancy test is typically still required at screening.",
  ],
  summary:
    "46-year-old premenopausal woman with de novo metastatic triple-negative breast cancer (ER 0%, PR 0%, HER2 IHC 0, not HER2-low; PD-L1 CPS 15; germline panel negative; TP53-mutated, PIK3CA wild-type) involving lung, mediastinal/hilar nodes and bone since November 2025. She progressed after about 9 months of first-line pembrolizumab + gemcitabine/carboplatin (best response PR; last pembrolizumab 2026-09-02) with a new segment VI liver lesion and a growing RLL nodule on CT 2026-09-15; she has measurable disease, ECOG 1, Hgb 9.8 g/dL and AST/ALT ~1.5x ULN, and has never received a taxane, anthracycline, ADC or PARP inhibitor. Second-line sacituzumab govitecan vs a novel-ADC trial is under discussion; anti-HBc positivity on entecavir, UGT1A1 genotype, LVEF/ECG and repeat brain imaging are the main screening issues.",
  extractedAt: EXTRACTED_AT,
  source: "demo",
};
