import type { PatientProfile } from "@/lib/types";
import { EXTRACTED_AT, ev, x } from "../profile-helpers";

// ---------------------------------------------------------------------------
// James T. — male breast cancer, HR+/HER2-low metastatic, germline BRCA2,
// progressed on first-line AI + GnRH agonist + CDK4/6 inhibitor
// ---------------------------------------------------------------------------

const J_NOTE = "Oncology follow-up note 2026-09-25";
const J_PATH = "Pathology report, lung core biopsy 2025-01-22";
const J_PRIOR = "Prior pathology summary, mastectomy 2021-05";
const J_GEN = "Germline panel 2021-06";
const J_MOL = "Tissue NGS report 2025-02-12";
const J_CT = "CT chest/abdomen/pelvis 2026-09-11";
const J_LABS = "Labs 2026-09-22";
const J_MEDS = "Medication list";
const J_ALLERGY = "Allergies";

export const PROFILE: PatientProfile = {
  id: "james-t",
  label: "James T.",
  demographics: {
    age: x(61, "high", [ev("61 yo M w/ hx L breast IDC", J_NOTE)]),
    sex: x(
      "male" as const,
      "high",
      [ev("61 yo M w/ hx L breast IDC", J_NOTE), ev("metastatic male breast ca", J_NOTE)],
      "Male breast cancer; menopausal status does not apply. Trials restricted to female participants will exclude him.",
    ),
  },
  diagnosis: {
    primary: x(
      "Invasive ductal carcinoma of the left breast (male breast cancer), now metastatic to lung, right hilar lymph node and bone",
      "high",
      [ev("hx L breast IDC dx 4/2021", J_NOTE), ev("Metastatic carcinoma, consistent with breast primary.", J_PATH)],
    ),
    histology: x("Invasive ductal carcinoma", "high", [ev("IDC, grade 2 (Nottingham 7/9)", J_PRIOR)]),
    grade: x("Grade 2 (Nottingham 7/9)", "high", [ev("IDC, grade 2 (Nottingham 7/9)", J_PRIOR)]),
    laterality: x("left" as const, "high", [ev("hx L breast IDC", J_NOTE)]),
    diagnosisDate: x("2021-04", "high", [ev("L breast IDC dx 4/2021", J_NOTE)]),
    stageAtDiagnosis: x("IIB", "high", [ev("stage IIB (pT2 pN1a)", J_NOTE)]),
    tnm: x(
      "pT2 pN1a M0",
      "high",
      [ev("stage IIB (pT2 pN1a)", J_NOTE), ev("2.6 cm, margins neg, 2/12 LNs positive (no ENE). pT2 pN1a.", J_PRIOR)],
      "M0 inferred from stage IIB at diagnosis.",
    ),
    currentStage: x(
      "IV",
      "medium",
      [ev("Metastatic HR+/HER2-low male breast ca", J_NOTE)],
      "Metastatic recurrence January 2025; 'stage IV' is not written explicitly.",
    ),
    setting: x(
      "metastatic" as const,
      "high",
      [
        ev(
          "Metastatic HR+/HER2-low male breast ca (lung, R hilar LN, bone), gBRCA2, PD on 1L AI + GnRH agonist + CDK4/6i after ~19 mo.",
          J_NOTE,
        ),
      ],
      "Recurrent metastatic disease (lung, bone) since January 2025 while on adjuvant tamoxifen; now progressing after one line of metastatic therapy.",
    ),
    subtype: x(
      "HR+/HER2-low",
      "high",
      [ev("Metastatic HR+/HER2-low male breast ca", J_NOTE), ev("HER2 IHC: 1+ (negative by ASCO/CAP; HER2-low)", J_PATH)],
    ),
    metastaticSites: x(
      ["lung (bilateral nodules; RUL 1.6 cm, LLL 0.6 cm)", "right hilar lymph node (1.7 cm short axis)", "bone (T6, L2, left iliac)"],
      "high",
      [
        ev("bilat lung nodules, bone mets (T6, L2, L iliac)", J_NOTE),
        ev(
          "1. RUL nodule 1.6 cm (previously 1.1 cm); new right hilar lymph node 1.7 cm short axis. LLL nodule 0.6 cm, unchanged.",
          J_CT,
        ),
        ev("2. Sclerotic osseous metastases T6, L2 and left iliac bone, unchanged.", J_CT),
      ],
      "No other sites reported on CT 2026-09-11; the brain has never been imaged.",
    ),
    measurableDisease: x(
      true,
      "high",
      [ev("Measurable dz: RUL nodule 1.6 cm, R hilar LN 1.7 cm SA.", J_NOTE)],
      "RUL nodule (≥ 10 mm) and hilar node (≥ 15 mm short axis) both qualify as RECIST 1.1 target lesions.",
    ),
    cnsStatus: x(
      "none" as const,
      "medium",
      [
        ev("No HA, visual change or focal weakness. Has never had brain imaging.", J_NOTE),
        ev("No brain MRI (asymptomatic); obtain if required for trial baseline.", J_NOTE),
      ],
      "No known CNS disease, but brain imaging has never been performed.",
    ),
  },
  biomarkers: [
    {
      name: "ER",
      status: "positive",
      detail: "85%, strong (lung metastasis 2025); 90% on the 2021 primary",
      method: "IHC",
      date: "2025-01-22",
      specimen: "lung core biopsy, left lower lobe",
      evidence: [ev("ER: positive, 85% of tumor cells, strong intensity", J_PATH), ev("ER 90%, PR 70%", J_PRIOR)],
      confidence: "high",
    },
    {
      name: "PR",
      status: "positive",
      detail: "30%, moderate (lung metastasis 2025); 70% on the 2021 primary",
      method: "IHC",
      date: "2025-01-22",
      specimen: "lung core biopsy, left lower lobe",
      evidence: [ev("PR: positive, 30% of tumor cells, moderate intensity", J_PATH), ev("ER 90%, PR 70%", J_PRIOR)],
      confidence: "high",
    },
    {
      name: "HER2",
      status: "low",
      detail: "IHC 1+, ISH not amplified (HER2/CEP17 ratio 1.3) — HER2-low; IHC 1+ on the 2021 primary",
      method: "IHC + ISH",
      date: "2025-01-22",
      specimen: "lung core biopsy, left lower lobe",
      evidence: [
        ev("HER2 IHC: 1+ (negative by ASCO/CAP; HER2-low)", J_PATH),
        ev("HER2 ISH: not amplified (HER2/CEP17 ratio 1.3)", J_PATH),
        ev("HER2 IHC 1+ (negative)", J_PRIOR),
      ],
      confidence: "high",
    },
    {
      name: "BRCA2",
      status: "mutated",
      detail:
        "c.5946delT (p.Ser1982ArgfsTer22), pathogenic — germline; same variant on tumor NGS 2025 (VAF 81%) with loss of heterozygosity",
      method: "germline",
      date: "2021-06",
      specimen: "blood (germline panel); confirmed in lung biopsy NGS 2025-02",
      evidence: [
        ev("BRCA2 c.5946delT (p.Ser1982ArgfsTer22) - PATHOGENIC", J_GEN),
        ev("Germline BRCA2 pathogenic variant 6/2021.", J_NOTE),
        ev("BRCA2 c.5946delT, VAF 81% - germline variant w/ loss of heterozygosity", J_MOL),
      ],
      confidence: "high",
    },
    {
      name: "gBRCA",
      status: "positive",
      detail: "Germline BRCA2 pathogenic variant (c.5946delT)",
      method: "germline",
      date: "2021-06",
      specimen: "blood (germline panel)",
      evidence: [ev("BRCA2 c.5946delT (p.Ser1982ArgfsTer22) - PATHOGENIC", J_GEN)],
      confidence: "high",
    },
    {
      name: "PIK3CA",
      status: "wild-type",
      detail: "No alterations detected (February 2025 tissue)",
      method: "NGS",
      date: "2025-02-12",
      specimen: "lung core biopsy 2025-01",
      evidence: [ev("PIK3CA: no alterations detected (wild-type)", J_MOL)],
      confidence: "high",
    },
    {
      name: "ESR1",
      status: "wild-type",
      detail: "No alterations detected on February 2025 tissue (before aromatase inhibitor exposure); not re-tested at progression",
      method: "NGS",
      date: "2025-02-12",
      specimen: "lung core biopsy 2025-01",
      evidence: [
        ev("ESR1: no alterations detected (wild-type)", J_MOL),
        ev("Consider ctDNA to reassess ESR1 at PD - not yet sent.", J_NOTE),
      ],
      confidence: "high",
    },
    {
      name: "AKT1",
      status: "wild-type",
      detail: "No alterations detected",
      method: "NGS",
      date: "2025-02-12",
      specimen: "lung core biopsy 2025-01",
      evidence: [ev("AKT1/PTEN: no alterations detected", J_MOL)],
      confidence: "high",
    },
    {
      name: "PTEN",
      status: "wild-type",
      detail: "No alterations detected",
      method: "NGS",
      date: "2025-02-12",
      specimen: "lung core biopsy 2025-01",
      evidence: [ev("AKT1/PTEN: no alterations detected", J_MOL)],
      confidence: "high",
    },
    {
      name: "BRCA1",
      status: "wild-type",
      detail: "No germline pathogenic variant",
      method: "germline",
      date: "2021-06",
      specimen: "blood (germline panel)",
      evidence: [ev("No other pathogenic variants (BRCA1, PALB2, CHEK2, ATM, TP53 negative).", J_GEN)],
      confidence: "high",
    },
    {
      name: "Ki-67",
      status: "low",
      detail: "15% (2021 primary; not repeated on the metastatic biopsy)",
      method: "IHC",
      date: "2021-05",
      specimen: "primary 2021",
      evidence: [ev("Ki-67 15%", J_PRIOR)],
      confidence: "medium",
    },
    {
      name: "TMB",
      status: "low",
      detail: "5 mut/Mb",
      method: "NGS",
      date: "2025-02-12",
      specimen: "lung core biopsy 2025-01",
      evidence: [ev("TMB: 5 mut/Mb (low).", J_MOL)],
      confidence: "high",
    },
    {
      name: "MSI",
      status: "negative",
      detail: "Microsatellite stable",
      method: "NGS",
      date: "2025-02-12",
      specimen: "lung core biopsy 2025-01",
      evidence: [ev("MSI: stable.", J_MOL)],
      confidence: "high",
    },
  ],
  treatments: [
    {
      name: "Left mastectomy + axillary lymph node dissection",
      category: "surgery",
      intent: "unknown",
      startDate: "2021-05",
      status: "completed",
      bestResponse: "pT2 (2.6 cm) pN1a (2/12), margins negative",
      evidence: [ev("s/p L mastectomy + ALND 5/2021", J_NOTE), ev("L mastectomy + ALND 05/2021", J_PRIOR)],
      confidence: "high",
    },
    {
      name: "Dose-dense doxorubicin + cyclophosphamide → paclitaxel (ddAC-T)",
      agents: ["doxorubicin", "cyclophosphamide", "paclitaxel"],
      category: "chemotherapy",
      intent: "adjuvant",
      startDate: "2021-06",
      endDate: "2021-10",
      status: "completed",
      reasonStopped: "completed planned course",
      evidence: [ev("adj ddAC-T 6/2021-10/2021", J_NOTE)],
      confidence: "high",
    },
    {
      name: "Post-mastectomy radiation (PMRT)",
      category: "radiation",
      intent: "adjuvant",
      startDate: "2021-11",
      endDate: "2021-12",
      status: "completed",
      reasonStopped: "completed planned course",
      evidence: [ev("PMRT 11-12/2021", J_NOTE)],
      confidence: "high",
    },
    {
      name: "Tamoxifen",
      agents: ["tamoxifen"],
      category: "endocrine",
      intent: "adjuvant",
      startDate: "2022-01",
      endDate: "2025-01",
      status: "discontinued",
      reasonStopped: "metastatic recurrence on therapy (January 2025, about 3 years in)",
      evidence: [
        ev("then adj tamoxifen from 1/2022", J_NOTE),
        ev("Jan 2025 (~3 yrs into tamoxifen) cough + back pain", J_NOTE),
      ],
      confidence: "medium",
    },
    {
      name: "Letrozole + leuprolide + abemaciclib (first-line metastatic, with denosumab)",
      agents: ["letrozole", "leuprolide", "abemaciclib"],
      category: "endocrine",
      intent: "metastatic",
      line: 1,
      startDate: "2025-02",
      endDate: "2026-09-15",
      status: "discontinued",
      bestResponse: "PR",
      reasonStopped: "progression in the chest on CT 2026-09-11 (~19 months on therapy); leuprolide continued",
      evidence: [
        ev("Started 1L letrozole + leuprolide + abemaciclib 2/2025 w/ denosumab, best response PR.", J_NOTE),
        ev("Abema/letrozole stopped 9/15/26; leuprolide continues (last inj 8/14/26).", J_NOTE),
        ev("abemaciclib 150 mg BID + letrozole 2.5 mg daily - DISCONTINUED 9/15/2026 (PD)", J_MEDS),
      ],
      confidence: "high",
    },
    {
      name: "Leuprolide (GnRH agonist, continued after first-line progression)",
      agents: ["leuprolide"],
      category: "endocrine",
      intent: "metastatic",
      startDate: "2025-02",
      status: "ongoing",
      evidence: [
        ev("3. Continue leuprolide 22.5 mg q3 mo for now; testosterone castrate.", J_NOTE),
        ev("leuprolide 22.5 mg IM q3 months (last 08/14/2026)", J_MEDS),
      ],
      confidence: "high",
    },
    {
      name: "Denosumab (bone-targeted supportive therapy)",
      agents: ["denosumab"],
      category: "other",
      intent: "metastatic",
      startDate: "2025-02",
      status: "ongoing",
      evidence: [
        ev("Started 1L letrozole + leuprolide + abemaciclib 2/2025 w/ denosumab, best response PR.", J_NOTE),
        ev("2. Bone mets: continue denosumab 120 mg q4w + Ca/vit D.", J_NOTE),
      ],
      confidence: "high",
    },
  ],
  performance: {
    ecog: x(1, "high", [ev("EXAM: ECOG 1.", J_NOTE)], "Mild dry cough; no other functional limitation documented."),
  },
  labs: [
    { name: "WBC", value: "4.2", unit: "x10^9/L", date: "2026-09-22", flag: "normal", evidence: [ev("WBC 4.2", J_LABS)] },
    { name: "ANC", value: "1.7", unit: "x10^9/L", date: "2026-09-22", flag: "normal", evidence: [ev("ANC 1.7", J_LABS)] },
    { name: "Hemoglobin", value: "11.8", unit: "g/dL", date: "2026-09-22", flag: "abnormal", evidence: [ev("Hgb 11.8 (L)", J_LABS)] },
    { name: "Platelets", value: "190", unit: "x10^9/L", date: "2026-09-22", flag: "normal", evidence: [ev("Plt 190", J_LABS)] },
    { name: "Creatinine", value: "1.1", unit: "mg/dL", date: "2026-09-22", flag: "normal", evidence: [ev("Cr 1.1", J_LABS)] },
    { name: "eGFR", value: "74", unit: "mL/min/1.73m²", date: "2026-09-22", flag: "normal", evidence: [ev("eGFR 74", J_LABS)] },
    { name: "AST", value: "26", unit: "U/L", date: "2026-09-22", flag: "normal", evidence: [ev("AST 26", J_LABS)] },
    { name: "ALT", value: "31", unit: "U/L", date: "2026-09-22", flag: "normal", evidence: [ev("ALT 31", J_LABS)] },
    { name: "Total bilirubin", value: "0.7", unit: "mg/dL", date: "2026-09-22", flag: "normal", evidence: [ev("T bili 0.7", J_LABS)] },
    { name: "Alkaline phosphatase", value: "118", unit: "U/L", date: "2026-09-22", flag: "normal", evidence: [ev("Alk phos 118", J_LABS)] },
    {
      name: "PSA",
      value: "0.2",
      unit: "ng/mL",
      date: "2026-09-22",
      flag: "normal",
      evidence: [ev("PSA 0.2 (pre-leuprolide 4.1, 12/2024)", J_LABS)],
    },
    { name: "PSA (pre-leuprolide)", value: "4.1", unit: "ng/mL", date: "2024-12", evidence: [ev("PSA 0.2 (pre-leuprolide 4.1, 12/2024)", J_LABS)] },
    {
      name: "Testosterone",
      value: "<20",
      unit: "ng/dL",
      date: "2026-09-22",
      flag: "abnormal",
      evidence: [ev("Testosterone <20 ng/dL (castrate)", J_LABS)],
    },
    {
      name: "LVEF",
      value: "60",
      unit: "%",
      date: "2021",
      flag: "normal",
      evidence: [ev("Echo: last TTE pre-AC 2021 (LVEF 60%); repeat if trial requires.", J_NOTE)],
    },
  ],
  comorbidities: [
    x(
      "Prostate adenocarcinoma, Gleason 3+3=6 (grade group 1), low risk, diagnosed 2023-11 — on active surveillance, never treated",
      "high",
      [
        ev("Prostate adenocarcinoma Gleason 3+3=6 (GG1), dx 11/2023 (PSA 4.6), low risk, on active surveillance w/ urology - never treated.", J_NOTE),
        ev("4. Prostate ca on AS: PSA suppressed on leuprolide; urology following w/ MRI.", J_NOTE),
      ],
      "Second primary malignancy within the last 3 years. PSA is now suppressed by leuprolide, so surveillance relies on MRI. May trigger 'other malignancy within 3–5 years' exclusions unless the trial exempts low-risk prostate cancer on surveillance.",
    ),
    x(
      "Hypertension (lisinopril)",
      "high",
      [ev("PMH: HTN, HLD.", J_NOTE), ev("5. HTN/HLD - lisinopril, rosuvastatin.", J_NOTE)],
      "No diabetes and no history of VTE ('No VTE. No DM.').",
    ),
    x("Hyperlipidemia (rosuvastatin)", "high", [ev("5. HTN/HLD - lisinopril, rosuvastatin.", J_NOTE)]),
    x("Former smoker, 20 pack-years, quit 2010", "high", [ev("SH: Former smoker, 20 pack-yrs, quit 2010.", J_NOTE)]),
  ],
  medications: [
    x(
      "Leuprolide 22.5 mg IM every 3 months (last injection 2026-08-14)",
      "high",
      [ev("leuprolide 22.5 mg IM q3 months (last 08/14/2026)", J_MEDS)],
      "GnRH agonist for testicular suppression; testosterone castrate (<20 ng/dL). Continuing for now pending the second-line choice.",
    ),
    x("Denosumab 120 mg SC every 4 weeks", "high", [ev("denosumab 120 mg SC q4 weeks", J_MEDS)]),
    x(
      "Lisinopril 20 mg daily",
      "high",
      [ev("lisinopril 20 mg PO daily", J_MEDS)],
      "No anticoagulants, systemic steroids or strong CYP3A4 inhibitors/inducers on the list.",
    ),
    x("Rosuvastatin 10 mg daily", "high", [ev("rosuvastatin 10 mg PO daily", J_MEDS)]),
    x("Calcium 600 mg + vitamin D3 800 IU daily", "high", [ev("calcium 600 mg + vitamin D3 800 IU daily", J_MEDS)]),
    x(
      "Abemaciclib 150 mg BID + letrozole 2.5 mg daily — discontinued 2026-09-15",
      "high",
      [ev("abemaciclib 150 mg BID + letrozole 2.5 mg daily - DISCONTINUED 9/15/2026 (PD)", J_MEDS)],
      "Listed for washout purposes; not a current medication despite the stale 'continue' line in the A/P.",
    ),
  ],
  allergies: [x("No known drug allergies", "high", [ev("ALLERGIES: NKDA", J_ALLERGY)])],
  keyDates: [
    { label: "Initial diagnosis", date: "2021-04", evidence: [ev("L breast IDC dx 4/2021", J_NOTE)] },
    { label: "Primary surgery (mastectomy + ALND)", date: "2021-05", evidence: [ev("s/p L mastectomy + ALND 5/2021", J_NOTE)] },
    {
      label: "Germline BRCA2 result",
      date: "2021-06",
      evidence: [ev("Germline BRCA2 pathogenic variant 6/2021.", J_NOTE), ev("GENETICS - Germline panel (blood), reported 06/2021:", J_GEN)],
    },
    { label: "Last adjuvant chemotherapy", date: "2021-10", evidence: [ev("adj ddAC-T 6/2021-10/2021", J_NOTE)] },
    { label: "Prostate cancer diagnosis", date: "2023-11", evidence: [ev("dx 11/2023 (PSA 4.6)", J_NOTE)] },
    { label: "Metastatic recurrence", date: "2025-01", evidence: [ev("Jan 2025 (~3 yrs into tamoxifen)", J_NOTE)] },
    {
      label: "Metastatic biopsy (lung)",
      date: "2025-01-22",
      evidence: [ev("Collected: 2025-01-22", J_PATH), ev("CT-guided LLL bx 1/22/25", J_NOTE)],
    },
    {
      label: "Start of first-line metastatic therapy",
      date: "2025-02",
      evidence: [ev("Started 1L letrozole + leuprolide + abemaciclib 2/2025", J_NOTE)],
    },
    {
      label: "Progression on first-line therapy (CT)",
      date: "2026-09-11",
      evidence: [ev("CT 9/11/26 w/ PD in chest", J_NOTE), ev("CT CHEST/ABDOMEN/PELVIS W/ CONTRAST - 09/11/2026", J_CT)],
    },
    { label: "Last leuprolide injection", date: "2026-08-14", evidence: [ev("leuprolide 22.5 mg IM q3 months (last 08/14/2026)", J_MEDS)] },
    { label: "Last dose of abemaciclib/letrozole", date: "2026-09-15", evidence: [ev("Abema/letrozole stopped 9/15/26", J_NOTE)] },
    {
      label: "Last imaging (CT chest/abdomen/pelvis)",
      date: "2026-09-11",
      evidence: [ev("CT CHEST/ABDOMEN/PELVIS W/ CONTRAST - 09/11/2026", J_CT)],
    },
    { label: "Last echocardiogram", date: "2021", evidence: [ev("Echo: last TTE pre-AC 2021 (LVEF 60%)", J_NOTE)] },
    { label: "Most recent labs", date: "2026-09-22", evidence: [ev("LABS 2026-09-22", J_LABS)] },
    { label: "Most recent clinic visit", date: "2026-09-25", evidence: [ev("Date of service: 9/25/2026", J_NOTE)] },
  ],
  openQuestions: [
    "Patient is male: confirm each trial's eligible sex on ClinicalTrials.gov — many breast cancer trials enroll women only, and criteria written around menopausal status or ovarian suppression need reinterpreting for a man on leuprolide.",
    "Second malignancy: low-risk prostate adenocarcinoma (Gleason 3+3, grade group 1) diagnosed 2023-11, untreated on active surveillance. Check whether each trial's 'other malignancy within 3–5 years' exclusion exempts low-risk prostate cancer on surveillance.",
    "No echocardiogram since the pre-anthracycline study in 2021 (LVEF 60%); most trials require LVEF within the last 6–12 months or at screening.",
    "Brain imaging has never been performed (asymptomatic); trials that mandate a baseline brain MRI will need one.",
    "Hepatitis B/C and HIV status are not documented.",
    "No repeat tumor or ctDNA genotyping at progression; ESR1 and PIK3CA status are from February 2025 tissue taken before aromatase inhibitor exposure (ctDNA considered, not yet sent).",
    "Confirm 2026-09-15 as the last dose of abemaciclib/letrozole for washout windows; the 2026-09-25 A/P carries a stale copy-forward line ('Abemaciclib 150 mg BID C19 … continue').",
    "Prior therapy count: one endocrine + CDK4/6 inhibitor line in the metastatic setting; no PARP inhibitor, platinum, fulvestrant or chemotherapy for metastatic disease. Adjuvant anthracycline exposure (ddAC-T 2021) is relevant to cardiac criteria.",
    "Whether leuprolide continues alongside second-line therapy is undecided; check whether a trial permits a concurrent GnRH agonist.",
    "Contraception: trials often require effective contraception for men with partners of childbearing potential; vasectomy (2005) is documented but partner status is not.",
    "PSA (0.2 ng/mL) is suppressed by leuprolide and cannot be used to follow the prostate cancer; prostate MRI results are not in the record.",
    "ECG/QTc not documented.",
  ],
  summary:
    "61-year-old man with HR+/HER2-low (IHC 1+, ISH not amplified) metastatic breast cancer and a germline BRCA2 pathogenic variant (c.5946delT, with loss of heterozygosity in tumor), PIK3CA and ESR1 wild-type, recurrent to lung and bone in January 2025 on adjuvant tamoxifen after stage IIB disease treated with mastectomy, ddAC-T and PMRT. He progressed in the chest on first-line letrozole + leuprolide + abemaciclib (best response PR, about 19 months; stopped 2026-09-15), has measurable disease (RUL nodule 1.6 cm, right hilar node 1.7 cm), ECOG 1 and adequate organ function, and has had no PARP inhibitor, platinum or chemotherapy for metastatic disease. Candidate for a PARP inhibitor or a trial that enrolls men; a low-risk prostate cancer on active surveillance, no echocardiogram since 2021 and no brain imaging may affect eligibility.",
  extractedAt: EXTRACTED_AT,
  source: "demo",
};
