import type { PatientProfile } from "@/lib/types";
import { EXTRACTED_AT, ev, x } from "../profile-helpers";

// ---------------------------------------------------------------------------
// Linda P. — HR+/HER2- (IHC 0) lobular, bone-only metastatic, ESR1 Y537S after AI + CDK4/6i
// ---------------------------------------------------------------------------

const L_NOTE = "Oncology follow-up note 2026-09-25";
const L_PATH = "Pathology report, left iliac bone biopsy 2024-05-21";
const L_PRIOR = "Prior pathology summary, mastectomy 2017-08";
const L_CTDNA = "Guardant360 ctDNA report 2026-09-23";
const L_PET = "FDG PET/CT 2026-09-09";
const L_ECG = "ECG 2026-09-17";
const L_LABS = "Labs 2026-09-22";
const L_MEDS = "Medication list";
const L_ALLERGY = "Allergies";

export const PROFILE: PatientProfile = {
  id: "linda-p",
  label: "Linda P.",
  demographics: {
    age: x(67, "high", [ev("67 yo postmenopausal F", L_NOTE)]),
    sex: x("female" as const, "high", [ev("67 yo postmenopausal F", L_NOTE)]),
    menopausalStatus: x("postmenopausal" as const, "high", [ev("67 yo postmenopausal F", L_NOTE)], "Age 67; no ovarian suppression required."),
  },
  diagnosis: {
    primary: x(
      "Invasive lobular carcinoma of the left breast (classic type), now metastatic to bone only",
      "high",
      [ev("L breast ILC (classic) dx 7/2017", L_NOTE), ev("DIAGNOSIS: Metastatic carcinoma c/w breast primary, lobular phenotype.", L_PATH)],
    ),
    histology: x(
      "Invasive lobular carcinoma, classic type (E-cadherin negative)",
      "high",
      [ev("invasive lobular carcinoma, classic type, grade 2", L_PRIOR), ev("IHC: GATA3+, CK7+, E-cadherin negative.", L_PATH)],
    ),
    grade: x("Grade 2", "high", [ev("invasive lobular carcinoma, classic type, grade 2", L_PRIOR)]),
    laterality: x("left" as const, "high", [ev("L breast ILC (classic)", L_NOTE)]),
    diagnosisDate: x("2017-07", "high", [ev("L breast ILC (classic) dx 7/2017", L_NOTE)]),
    stageAtDiagnosis: x("IIB", "high", [ev("stage IIB (pT2 pN1mi)", L_NOTE)]),
    tnm: x(
      "pT2 pN1mi M0",
      "high",
      [ev("stage IIB (pT2 pN1mi)", L_NOTE), ev("3.4 cm, margins neg, 1/3 SLN micromet (1.2 mm)", L_PRIOR)],
      "M0 inferred from stage IIB at diagnosis; nodal disease was a single sentinel-node micrometastasis.",
    ),
    currentStage: x(
      "IV",
      "medium",
      [ev("Metastatic HR+/HER2-neg (IHC 0) ILC, bone-only", L_NOTE)],
      "Metastatic recurrence May 2024; 'stage IV' is not written explicitly.",
    ),
    setting: x(
      "metastatic" as const,
      "high",
      [ev("Metastatic HR+/HER2-neg (IHC 0) ILC, bone-only, ESR1 Y537S on ctDNA, PD on 1L AI + CDK4/6i after ~27 mo.", L_NOTE)],
      "Recurrent bone-only metastatic disease since May 2024, about 19 months after completing 5 years of adjuvant anastrozole.",
    ),
    subtype: x(
      "HR+/HER2-",
      "high",
      [ev("Metastatic HR+/HER2-neg (IHC 0)", L_NOTE), ev("HER2 IHC: 0 (negative)", L_PATH), ev("ER: positive, 90%, strong", L_PATH)],
      "HER2 IHC 0 on both the primary and the bone metastasis: HER2-negative, not HER2-low.",
    ),
    metastaticSites: x(
      [
        "bone (thoracolumbar spine: T10, L1, L4)",
        "bone (pelvis/sacrum: left ilium, sacrum, right acetabulum)",
        "bone (left 7th rib)",
        "bone (left proximal femur, irradiated 2024-07)",
      ],
      "high",
      [
        ev("multiple bone mets (T/L spine, pelvis, ribs, L prox femur), no visceral dz", L_NOTE),
        ev(
          "new FDG-avid sclerotic/mixed lesions at T10, sacrum and R acetabulum; increased uptake in known L1, L4, L ilium and L 7th rib lesions.",
          L_PET,
        ),
        ev("No FDG-avid visceral, nodal or soft tissue disease.", L_PET),
      ],
      "Bone-only disease; no visceral, nodal, soft-tissue or known CNS involvement.",
    ),
    measurableDisease: x(
      false,
      "high",
      [
        ev("Bone-only dz, NOT measurable by RECIST 1.1 (evaluable only).", L_NOTE),
        ev("Mixed lytic/sclerotic L iliac lesion, lytic component 2.3 cm, no extraosseous soft tissue component.", L_PET),
      ],
      "Left iliac lesion has a 2.3 cm lytic component but no soft-tissue mass, so it is not RECIST-measurable; criteria accepting 'at least one lytic or mixed bone lesion' are arguable and need investigator review.",
    ),
    cnsStatus: x(
      "none" as const,
      "medium",
      [ev("No brain imaging to date (asymptomatic); MRI if trial requires.", L_NOTE), ev("No HA or visual chnages.", L_NOTE)],
      "No known CNS disease, but brain imaging has never been performed.",
    ),
  },
  biomarkers: [
    {
      name: "ER",
      status: "positive",
      detail: "90%, strong (iliac bone metastasis 2024); 95% strong on the 2017 primary",
      method: "IHC",
      date: "2024-05-21",
      specimen: "left iliac bone core biopsy (decalcified)",
      evidence: [ev("ER: positive, 90%, strong", L_PATH), ev("ER 95% strong", L_PRIOR)],
      confidence: "high",
    },
    {
      name: "PR",
      status: "positive",
      detail: "5%, weak (iliac bone metastasis 2024); 40% on the 2017 primary",
      method: "IHC",
      date: "2024-05-21",
      specimen: "left iliac bone core biopsy (decalcified)",
      evidence: [ev("PR: positive, 5%, weak", L_PATH), ev("PR 40%", L_PRIOR)],
      confidence: "high",
    },
    {
      name: "HER2",
      status: "negative",
      detail: "IHC 0 on the 2024 bone metastasis and the 2017 primary (HER2-zero, not HER2-low); HER2-ultralow not reported",
      method: "IHC",
      date: "2024-05-21",
      specimen: "left iliac bone core biopsy (decalcified)",
      evidence: [ev("HER2 IHC: 0 (negative)", L_PATH), ev("HER2 IHC 0.", L_PRIOR)],
      confidence: "high",
    },
    {
      name: "ESR1",
      status: "mutated",
      detail: "p.Y537S, VAF 2.1% (ligand-binding domain); detected on ctDNA after progression on AI + CDK4/6i",
      method: "ctDNA",
      date: "2026-09-16",
      specimen: "plasma ctDNA (Guardant360 CDx), collected 2026-09-16",
      evidence: [ev("ESR1 p.Y537S, VAF 2.1%", L_CTDNA), ev("ESR1 Y537S on ctDNA", L_NOTE)],
      confidence: "high",
    },
    {
      name: "PIK3CA",
      status: "wild-type",
      detail: "Not detected on ctDNA; no tissue NGS (bone biopsy decalcified) — a negative plasma result does not exclude a mutation",
      method: "ctDNA",
      date: "2026-09-16",
      specimen: "plasma ctDNA (Guardant360 CDx), collected 2026-09-16",
      evidence: [
        ev("PIK3CA, AKT1, PTEN: not detected", L_CTDNA),
        ev("PIK3CA/AKT1/PTEN neg on ctDNA only; bone bx decalcified, no tissue NGS.", L_NOTE),
      ],
      confidence: "medium",
    },
    {
      name: "AKT1",
      status: "wild-type",
      detail: "Not detected on ctDNA; tissue not tested",
      method: "ctDNA",
      date: "2026-09-16",
      specimen: "plasma ctDNA (Guardant360 CDx), collected 2026-09-16",
      evidence: [ev("PIK3CA, AKT1, PTEN: not detected", L_CTDNA)],
      confidence: "medium",
    },
    {
      name: "PTEN",
      status: "wild-type",
      detail: "Not detected on ctDNA; tissue not tested",
      method: "ctDNA",
      date: "2026-09-16",
      specimen: "plasma ctDNA (Guardant360 CDx), collected 2026-09-16",
      evidence: [ev("PIK3CA, AKT1, PTEN: not detected", L_CTDNA)],
      confidence: "medium",
    },
    {
      name: "CDH1",
      status: "mutated",
      detail: "p.Q706* (truncating), VAF 1.8% — consistent with lobular histology",
      method: "ctDNA",
      date: "2026-09-16",
      specimen: "plasma ctDNA (Guardant360 CDx), collected 2026-09-16",
      evidence: [ev("CDH1 p.Q706*, VAF 1.8%", L_CTDNA)],
      confidence: "high",
    },
    {
      name: "ERBB2",
      status: "wild-type",
      detail: "No ERBB2 (HER2) mutation or amplification on ctDNA",
      method: "ctDNA",
      date: "2026-09-16",
      specimen: "plasma ctDNA (Guardant360 CDx), collected 2026-09-16",
      evidence: [ev("ERBB2: no alterations detected", L_CTDNA)],
      confidence: "high",
    },
    {
      name: "BRCA1",
      status: "wild-type",
      detail: "Not detected on ctDNA (plasma assay); germline status never tested",
      method: "ctDNA",
      date: "2026-09-16",
      specimen: "plasma ctDNA (Guardant360 CDx), collected 2026-09-16",
      evidence: [ev("BRCA1/BRCA2: not detected", L_CTDNA)],
      confidence: "medium",
    },
    {
      name: "BRCA2",
      status: "wild-type",
      detail: "Not detected on ctDNA (plasma assay); germline status never tested",
      method: "ctDNA",
      date: "2026-09-16",
      specimen: "plasma ctDNA (Guardant360 CDx), collected 2026-09-16",
      evidence: [ev("BRCA1/BRCA2: not detected", L_CTDNA)],
      confidence: "medium",
    },
    {
      name: "gBRCA",
      status: "unknown",
      detail: "Germline genetic testing never done; offered 2026-09-25 and to be sent",
      method: "germline",
      specimen: "blood (germline) — not yet collected",
      evidence: [ev("Germline genetic testing never done.", L_NOTE), ev("Germline testing offered, pt agreeable, will send.", L_NOTE)],
      confidence: "high",
    },
    {
      name: "E-cadherin",
      status: "negative",
      detail: "Loss of E-cadherin on the 2017 primary and the 2024 bone metastasis (lobular phenotype)",
      method: "IHC",
      date: "2024-05-21",
      specimen: "left iliac bone core biopsy; primary 2017",
      evidence: [ev("IHC: GATA3+, CK7+, E-cadherin negative.", L_PATH), ev("pT2 pN1mi. E-cadherin negative.", L_PRIOR)],
      confidence: "high",
    },
    {
      name: "Oncotype DX",
      status: "low",
      detail: "Recurrence Score 14 (2017 primary); adjuvant chemotherapy omitted",
      method: "PCR",
      date: "2017",
      specimen: "primary 2017",
      evidence: [ev("Oncotype DX RS 14.", L_PRIOR), ev("Oncotype RS 14 -> no chemo, no PMRT.", L_NOTE)],
      confidence: "high",
    },
  ],
  treatments: [
    {
      name: "Left mastectomy + sentinel lymph node biopsy",
      category: "surgery",
      intent: "unknown",
      startDate: "2017-08",
      status: "completed",
      bestResponse: "pT2 (3.4 cm) pN1mi (1/3 SLN micrometastasis), margins negative",
      evidence: [
        ev("s/p L mastectomy + SLNB 8/2017", L_NOTE),
        ev("L mastectomy + SLNB 08/2017: invasive lobular carcinoma, classic type, grade 2, 3.4 cm, margins neg, 1/3 SLN micromet (1.2 mm).", L_PRIOR),
      ],
      confidence: "high",
    },
    {
      name: "Anastrozole",
      agents: ["anastrozole"],
      category: "endocrine",
      intent: "adjuvant",
      startDate: "2017-10",
      endDate: "2022-10",
      status: "completed",
      reasonStopped: "completed planned 5-year course",
      evidence: [ev("Adj anastrozole 10/2017-10/2022 (5 yrs completed).", L_NOTE)],
      confidence: "high",
    },
    {
      name: "Letrozole + ribociclib (first-line metastatic; ribociclib reduced to 400 mg from 2024-10 for G3 neutropenia)",
      agents: ["letrozole", "ribociclib"],
      category: "endocrine",
      intent: "metastatic",
      line: 1,
      startDate: "2024-06",
      endDate: "2026-09-14",
      status: "discontinued",
      bestResponse: "SD",
      reasonStopped: "progression in bone on PET/CT 2026-09-09 (~27 months on therapy)",
      evidence: [
        ev("1L letrozole + ribociclib from 6/2024 (400 mg from 10/2024, G3 neutropenia) + zoledronic acid, best response SD.", L_NOTE),
        ev("Ribociclib/letrozole stopped 9/14/26 (~27 mo).", L_NOTE),
        ev("letrozole 2.5 mg daily + ribociclib 400 mg - DISCONTINUED 9/14/2026 (PD)", L_MEDS),
      ],
      confidence: "high",
    },
    {
      name: "Zoledronic acid (bone-targeted supportive therapy)",
      agents: ["zoledronic acid"],
      category: "other",
      intent: "metastatic",
      startDate: "2024-06",
      status: "ongoing",
      evidence: [
        ev("1L letrozole + ribociclib from 6/2024 (400 mg from 10/2024, G3 neutropenia) + zoledronic acid, best response SD.", L_NOTE),
        ev("zoledronic acid q12 wks (last 8/14/26)", L_NOTE),
        ev("zoledronic acid 3.5 mg IV q12 weeks (renal dose)", L_MEDS),
      ],
      confidence: "medium",
    },
    {
      name: "Palliative radiation to the left hip, 8 Gy x1",
      category: "radiation",
      intent: "palliative",
      startDate: "2024-07",
      endDate: "2024-07",
      status: "completed",
      reasonStopped: "completed planned course",
      evidence: [ev("Palliative RT L hip 8 Gy x1 7/2024.", L_NOTE)],
      confidence: "high",
    },
  ],
  performance: {
    ecog: x(
      1,
      "high",
      [ev("EXAM: ECOG 1.", L_NOTE), ev("walking limited to ~2 blocks, cane outdoors, independant in ADLs", L_NOTE)],
      "Bone pain limits walking distance; independent in ADLs.",
    ),
  },
  labs: [
    { name: "WBC", value: "3.6", unit: "x10^9/L", date: "2026-09-22", flag: "abnormal", evidence: [ev("WBC 3.6 (L)", L_LABS)] },
    { name: "ANC", value: "1.7", unit: "x10^9/L", date: "2026-09-22", flag: "normal", evidence: [ev("ANC 1.7", L_LABS)] },
    { name: "Hemoglobin", value: "11.4", unit: "g/dL", date: "2026-09-22", flag: "abnormal", evidence: [ev("Hgb 11.4 (L)", L_LABS)] },
    { name: "Platelets", value: "168", unit: "x10^9/L", date: "2026-09-22", flag: "normal", evidence: [ev("Plt 168", L_LABS)] },
    { name: "Creatinine", value: "1.1", unit: "mg/dL", date: "2026-09-22", flag: "normal", evidence: [ev("Cr 1.1", L_LABS)] },
    {
      name: "eGFR",
      value: "52",
      unit: "mL/min/1.73m²",
      date: "2026-09-22",
      flag: "abnormal",
      evidence: [ev("eGFR 52 (L)", L_LABS), ev("CKD 3a - eGFR 52, stable.", L_NOTE)],
    },
    { name: "Potassium", value: "4.2", unit: "mmol/L", date: "2026-09-22", flag: "normal", evidence: [ev("K 4.2", L_LABS)] },
    { name: "Magnesium", value: "1.9", unit: "mg/dL", date: "2026-09-22", flag: "normal", evidence: [ev("Mg 1.9", L_LABS)] },
    { name: "Calcium", value: "9.4", unit: "mg/dL", date: "2026-09-22", flag: "normal", evidence: [ev("Ca 9.4", L_LABS)] },
    { name: "AST", value: "24", unit: "U/L", date: "2026-09-22", flag: "normal", evidence: [ev("AST 24", L_LABS)] },
    { name: "ALT", value: "19", unit: "U/L", date: "2026-09-22", flag: "normal", evidence: [ev("ALT 19", L_LABS)] },
    { name: "Total bilirubin", value: "0.5", unit: "mg/dL", date: "2026-09-22", flag: "normal", evidence: [ev("T bili 0.5", L_LABS)] },
    {
      name: "Alkaline phosphatase",
      value: "162",
      unit: "U/L",
      date: "2026-09-22",
      flag: "abnormal",
      evidence: [ev("Alk phos 162 (H)", L_LABS)],
    },
    { name: "Albumin", value: "3.8", unit: "g/dL", date: "2026-09-22", flag: "normal", evidence: [ev("Albumin 3.8", L_LABS)] },
    {
      name: "CA 27.29",
      value: "142",
      unit: "U/mL",
      date: "2026-09-22",
      flag: "abnormal",
      evidence: [ev("CA 27.29 142 (H) (06/2026: 88)", L_LABS)],
    },
    { name: "HbA1c", value: "6.4", unit: "%", date: "2026-08", flag: "abnormal", evidence: [ev("HbA1c 6.4% (08/2026)", L_LABS)] },
    {
      name: "QTcF",
      value: "462",
      unit: "ms",
      date: "2026-09-17",
      flag: "abnormal",
      evidence: [ev("ECG 9/17/2026: NSR 68, QTcF 462 ms.", L_ECG)],
    },
  ],
  comorbidities: [
    x(
      "Chronic kidney disease stage 3a (eGFR 52)",
      "high",
      [ev("CKD 3a - eGFR 52, stable.", L_NOTE)],
      "Zoledronic acid renally dosed (3.5 mg); Cockcroft-Gault creatinine clearance not documented.",
    ),
    x(
      "Type 2 diabetes, diet-controlled (HbA1c 6.4%, 2026-08)",
      "high",
      [ev("T2DM diet-controlled (A1c 6.4% 8/2026)", L_NOTE)],
      "No glucose-lowering medication.",
    ),
    x("Osteoporosis (DEXA 2021, T-score -2.6)", "high", [ev("osteoporosis (DEXA 2021 T-score -2.6)", L_NOTE)]),
    x("Depression (escitalopram 10 mg, stable)", "high", [ev("Depression - escitalopram 10 mg, stable.", L_NOTE)]),
    x(
      "Borderline QTc prolongation (QTcF 462 ms on 2026-09-17)",
      "high",
      [ev("QTcF 462 ms on 9/17 ECG (440-455 on ribociclib), on escitalopram.", L_NOTE), ev("K/Mg ok.", L_NOTE)],
      "ECG three days after the last ribociclib dose, on escitalopram; ribociclib-era QTcF 440–455 ms; K and Mg normal.",
    ),
  ],
  medications: [
    x(
      "Zoledronic acid 3.5 mg IV every 12 weeks (renally adjusted)",
      "high",
      [ev("zoledronic acid 3.5 mg IV q12 weeks (renal dose)", L_MEDS), ev("zoledronic acid q12 wks (last 8/14/26)", L_NOTE)],
      "Last dose 2026-08-14; no osteonecrosis of the jaw.",
    ),
    x(
      "Tramadol 50 mg PO every 6 hours as needed (bone pain)",
      "high",
      [ev("tramadol 50 mg PO q6h prn pain", L_MEDS), ev("tramadol 1-2x/day", L_NOTE)],
      "Using one to two doses a day; serotonergic, additive with escitalopram.",
    ),
    x(
      "Escitalopram 10 mg daily (QT-prolonging)",
      "high",
      [ev("escitalopram 10 mg PO daily", L_MEDS), ev("If trial requires QTcF <450 consider switch to sertraline.", L_NOTE)],
      "Known QT-prolonging drug; trials excluding concomitant QT-prolonging medication will flag it. Switch to sertraline considered.",
    ),
    x(
      "Calcium + vitamin D3 daily",
      "high",
      [ev("calcium + vitamin D3 daily", L_MEDS)],
      "No anticoagulants, systemic steroids or strong CYP3A4 inhibitors/inducers on the list.",
    ),
    x(
      "Letrozole 2.5 mg + ribociclib 400 mg — discontinued 2026-09-14",
      "high",
      [ev("letrozole 2.5 mg daily + ribociclib 400 mg - DISCONTINUED 9/14/2026 (PD)", L_MEDS)],
      "Listed for washout purposes; not a current medication despite the stale 'Continue ribociclib' line in the A/P.",
    ),
  ],
  allergies: [
    x("Codeine (nausea)", "high", [ev("ALLERGIES: codeine (nausea)", L_ALLERGY)], "Intolerance rather than a true allergy."),
  ],
  keyDates: [
    { label: "Initial diagnosis", date: "2017-07", evidence: [ev("L breast ILC (classic) dx 7/2017", L_NOTE)] },
    { label: "Primary surgery (mastectomy + SLNB)", date: "2017-08", evidence: [ev("s/p L mastectomy + SLNB 8/2017", L_NOTE)] },
    {
      label: "Completion of adjuvant anastrozole",
      date: "2022-10",
      evidence: [ev("Adj anastrozole 10/2017-10/2022 (5 yrs completed).", L_NOTE)],
    },
    {
      label: "Metastatic recurrence (bone)",
      date: "2024-05",
      evidence: [ev("May 2024 hip/back pain -> bone scan + CT: multiple bone mets", L_NOTE)],
    },
    { label: "Metastatic biopsy (left iliac bone)", date: "2024-05-21", evidence: [ev("Collected: 05/21/2024", L_PATH)] },
    {
      label: "Start of first-line metastatic therapy",
      date: "2024-06",
      evidence: [ev("1L letrozole + ribociclib from 6/2024", L_NOTE)],
    },
    { label: "Palliative radiation (left hip)", date: "2024-07", evidence: [ev("Palliative RT L hip 8 Gy x1 7/2024.", L_NOTE)] },
    { label: "Last zoledronic acid dose", date: "2026-08-14", evidence: [ev("zoledronic acid q12 wks (last 8/14/26)", L_NOTE)] },
    {
      label: "Progression on first-line therapy (PET/CT)",
      date: "2026-09-09",
      evidence: [ev("PET/CT 9/9/26 w/ bone PD", L_NOTE), ev("FDG PET/CT - 09/09/2026", L_PET)],
    },
    {
      label: "Last dose of ribociclib/letrozole",
      date: "2026-09-14",
      evidence: [ev("Ribociclib/letrozole stopped 9/14/26 (~27 mo).", L_NOTE)],
    },
    {
      label: "ctDNA collected (Guardant360)",
      date: "2026-09-16",
      evidence: [ev("MOLECULAR - Guardant360 CDx (ctDNA), collected 2026-09-16, reported 2026-09-23:", L_CTDNA)],
    },
    { label: "Last ECG", date: "2026-09-17", evidence: [ev("ECG 9/17/2026: NSR 68, QTcF 462 ms.", L_ECG)] },
    { label: "Last imaging (FDG PET/CT)", date: "2026-09-09", evidence: [ev("FDG PET/CT - 09/09/2026", L_PET)] },
    { label: "Most recent labs", date: "2026-09-22", evidence: [ev("LABS 2026-09-22", L_LABS)] },
    { label: "Most recent clinic visit", date: "2026-09-25", evidence: [ev("Date of service: 25-Sep-2026", L_NOTE)] },
  ],
  openQuestions: [
    "No RECIST 1.1-measurable disease (bone-only). The left iliac lesion has a 2.3 cm lytic component without a soft-tissue mass; trials requiring measurable disease will exclude her, and those accepting 'at least one lytic or mixed lytic/blastic bone lesion' need investigator confirmation.",
    "LVEF has never been documented (no echocardiogram on file); many trials require LVEF at screening.",
    "Germline BRCA1/2 status unknown: germline testing never done (offered at this visit). ctDNA BRCA1/2 'not detected' does not establish germline status.",
    "QTcF 462 ms on 2026-09-17 while on escitalopram (QT-prolonging); trials commonly exclude QTcF > 470 ms (some > 450 ms) or concurrent QT-prolonging drugs. Repeat ECG off ribociclib and consider the switch to sertraline noted in the A/P.",
    "PIK3CA, AKT1 and PTEN tested on ctDNA only (not detected); the bone biopsy was decalcified and tissue NGS was never done, so PI3K/AKT-pathway trials may require tissue testing.",
    "Hepatitis B/C and HIV serology not documented.",
    "Brain imaging has never been performed (asymptomatic); trials that mandate a baseline brain MRI will need one.",
    "HER2 reported as IHC 0 on both specimens; HER2-ultralow (IHC >0 to <1+) was not assessed, which matters for HER2-ultralow T-DXd trials.",
    "Confirm 2026-09-14 as the last dose of ribociclib/letrozole for washout windows; the 2026-09-25 A/P carries a stale copy-forward line ('Continue ribociclib 400 mg ... + letrozole').",
    "Renal function: eGFR 52 (CKD 3a); Cockcroft-Gault creatinine clearance, which many trials specify, is not documented.",
  ],
  summary:
    "67-year-old postmenopausal woman with HR+/HER2-negative (IHC 0) invasive lobular carcinoma, bone-only metastatic since May 2024 after 5 years of adjuvant anastrozole, now progressing in bone on first-line letrozole + ribociclib (best response SD, about 27 months; stopped 2026-09-14) with ESR1 Y537S on ctDNA and PIK3CA/AKT1/PTEN not detected. Disease is not RECIST-measurable; ECOG 1, organ function adequate apart from CKD 3a (eGFR 52), and no prior chemotherapy, fulvestrant, oral SERD or PI3K/AKT/mTOR inhibitor. Candidate for elacestrant or an oral SERD trial; QTcF 462 ms on escitalopram, and no LVEF or germline testing on file.",
  extractedAt: EXTRACTED_AT,
  source: "demo",
};
