import { demoMatch } from "../../match-helpers";

export default demoMatch(
  "NCT05929768",
  "Excluded: for untreated TNBC, and she has completed KEYNOTE-522, mastectomy and radiation",
  "SCARLET randomizes treatment-naive early TNBC to shorter anthracycline-free versus standard neoadjuvant chemo-immunotherapy. Her tumor biology and stage at diagnosis fit (cT2 cN1 TNBC), but she has already completed KEYNOTE-522 including pembrolizumab, had definitive mastectomy and axillary dissection on 2026-06-11 and finished post-mastectomy radiation, so the prior-therapy, prior-surgery and prior anti-PD-1 criteria fail outright. Nothing in the record would change this; it does not address her post-neoadjuvant residual-disease setting.",
  [
    {
      id: "NCT05929768-inc-1",
      status: "pass",
      rationale: "ER 0%, PR 0% (< 5%) and HER2 IHC 0 on the 11/2025 core biopsy, concordant on the residual tumor in 6/2026.",
      evidence: [
        { quote: "ER 0%, PR 0%, HER2 IHC 0 (negative), Ki-67 75%.", source: "Core biopsy 11/2025" },
        { quote: "Receptors repeated on residual tumor: ER 0%, PR 0%, HER2 IHC 0 - triple negative, concordant with core bx.", source: "Pathology 2026-06-17" },
      ],
    },
    {
      id: "NCT05929768-inc-2",
      status: "pass",
      rationale: "Clinical stage at diagnosis was cT2 cN1 M0 with the node confirmed by core biopsy, which falls in the T1-3 N1-2 M0 group.",
      evidence: [
        { quote: "R breast IDC grade 3, TNBC, cT2 (3.1 cm) cN1 (bx-proven axillary node) M0, stage IIB, dx 11/2025.", source: "Clinic note 2026-09-22" },
        { quote: "Axillary node core: metastatic carcinoma.", source: "Core biopsy 11/2025" },
      ],
    },
    {
      id: "NCT05929768-inc-3",
      status: "fail",
      confidence: "medium",
      rationale: "No breast or axillary imaging within 49 days is documented, and after bilateral mastectomy on 2026-06-11 there is no primary tumor left to image as the pre-treatment baseline this requires.",
      evidence: [{ quote: "Surgery 6/11/26: bilateral mastectomy (L risk-reducing) + R ALND -> ypT1c (1.2 cm) ypN1a (2/11), RCB class II (RCB 2.6), margins neg.", source: "Clinic note 2026-09-22" }],
    },
    {
      id: "NCT05929768-inc-4",
      status: "pass",
      rationale: "Staged cT2 cN1 at diagnosis: not T4, not N3 and not inflammatory.",
      evidence: [{ quote: "R breast IDC grade 3, TNBC, cT2 (3.1 cm) cN1 (bx-proven axillary node) M0, stage IIB, dx 11/2025.", source: "Clinic note 2026-09-22" }],
    },
    {
      id: "NCT05929768-inc-5",
      status: "pass",
      rationale: "M0: baseline CT CAP and bone scan in 11/2025 and post-operative CT CAP on 2026-07-09 showed no distant disease.",
      evidence: [
        { quote: "Baseline staging 11/2025: CT CAP + bone scan without distant disease.", source: "Imaging" },
        { quote: "No evidence of metastatic disease in the chest, abdomen or pelvis.", source: "CT CAP 2026-07-09" },
      ],
    },
    {
      id: "NCT05929768-inc-6",
      status: "fail",
      rationale: "She has completed curative-intent neoadjuvant KEYNOTE-522 chemo-immunotherapy (12/2025–5/2026) and post-mastectomy radiation (2026-07-20 to 2026-08-28) for this cancer.",
      evidence: [
        { quote: "Neoadj per KEYNOTE-522: pembro + weekly paclitaxel + carboplatin x12 wks (12/2025-3/2026) then pembro + ddAC x4 (3/2026-5/2026).", source: "Clinic note 2026-09-22" },
        { quote: "PMRT 7/20/26-8/28/26, completed.", source: "Clinic note 2026-09-22" },
      ],
    },
    {
      id: "NCT05929768-inc-7",
      status: "fail",
      rationale: "Definitive ipsilateral surgery has been done: right total mastectomy with axillary dissection on 2026-06-11.",
      evidence: [{ quote: "Procedure date: 2026-06-11", source: "Pathology 2026-06-17" }],
    },
    {
      id: "NCT05929768-inc-8",
      status: "pass",
      confidence: "medium",
      rationale: "No investigational agent is on her medication list or planned; her current anticancer therapy is standard adjuvant pembrolizumab.",
      evidence: [{ quote: "pembrolizumab 200 mg IV q3 weeks (adjuvant, C4 of 9)", source: "Medications" }],
    },
    {
      id: "NCT05929768-inc-9",
      status: "pass",
      rationale: "She has received paclitaxel, carboplatin, doxorubicin, cyclophosphamide and pembrolizumab without any recorded allergic reaction, and records NKDA.",
      evidence: [{ quote: "ALLERGIES: NKDA", source: "Allergies" }],
    },
    {
      id: "NCT05929768-inc-10",
      status: "pass",
      rationale: "No pembrolizumab hypersensitivity: she is tolerating adjuvant pembrolizumab (cycle 4 given 2026-09-22) and records NKDA.",
      evidence: [{ quote: "pembrolizumab 200 mg IV q3 weeks (adjuvant, C4 of 9)", source: "Medications" }],
    },
    {
      id: "NCT05929768-inc-11",
      status: "fail",
      rationale: "She has received the anti-PD-1 antibody pembrolizumab, neoadjuvantly since 12/2025 and adjuvantly since 2026-07-21 (cycle 4 of 9).",
      evidence: [
        { quote: "Neoadj per KEYNOTE-522", source: "Clinic note 2026-09-22" },
        { quote: "pembrolizumab 200 mg IV q3 weeks (adjuvant, C4 of 9)", source: "Medications" },
      ],
    },
    {
      id: "NCT05929768-inc-12",
      status: "pass",
      confidence: "medium",
      rationale: "No investigational agent or device in the past 28 days is recorded; all treatment to date has been standard of care.",
      evidence: [],
    },
    {
      id: "NCT05929768-inc-13",
      status: "pass",
      rationale: "She is 39 years old (born 1987).",
      evidence: [{ quote: "DOB: 1987 (39 yo F)", source: "Clinic note 2026-09-22" }],
    },
    {
      id: "NCT05929768-inc-14",
      status: "pass",
      rationale: "ECOG 0 on 2026-09-22 (equivalent to Zubrod 0).",
      evidence: [{ quote: "EXAM: ECOG 0.", source: "Clinic note 2026-09-22" }],
    },
    {
      id: "NCT05929768-inc-15",
      status: "pass",
      rationale: "Paclitaxel neuropathy improved from grade 2 to grade 1 (toes), stable without functional limitation at the 2026-09-22 visit.",
      evidence: [{ quote: "PN stable G1, no functional limitation.", source: "Clinic note 2026-09-22" }],
    },
    {
      id: "NCT05929768-inc-16",
      status: "pass",
      rationale: "Full history and examination documented at the oncology visit on 2026-09-22, six days ago.",
      evidence: [{ quote: "Date of service: 2026-09-22", source: "Clinic note 2026-09-22" }],
    },
    {
      id: "NCT05929768-inc-17",
      status: "pass",
      rationale: "Hemoglobin 12.4 g/dL on 2026-09-19 with no transfusion or erythropoietin recorded.",
      evidence: [{ quote: "WBC 3.4 (L) | ANC 1.9 | Hgb 12.4 | Plt 180", source: "Labs 2026-09-19" }],
    },
    {
      id: "NCT05929768-inc-18",
      status: "pass",
      rationale: "WBC 3.4 × 10³/µL on 2026-09-19 — flagged low by the lab but above the 3.0 threshold.",
      evidence: [{ quote: "WBC 3.4 (L) | ANC 1.9 | Hgb 12.4 | Plt 180", source: "Labs 2026-09-19" }],
    },
    {
      id: "NCT05929768-inc-19",
      status: "pass",
      rationale: "ANC 1.9 × 10³/µL on 2026-09-19, above 1.5 though called borderline in the note.",
      evidence: [{ quote: "WBC 3.4 (L) | ANC 1.9 | Hgb 12.4 | Plt 180", source: "Labs 2026-09-19" }],
    },
    {
      id: "NCT05929768-inc-20",
      status: "pass",
      rationale: "Platelets 180 × 10³/µL on 2026-09-19.",
      evidence: [{ quote: "WBC 3.4 (L) | ANC 1.9 | Hgb 12.4 | Plt 180", source: "Labs 2026-09-19" }],
    },
    {
      id: "NCT05929768-inc-21",
      status: "pass",
      rationale: "Total bilirubin 0.5 mg/dL on 2026-09-19, within normal limits.",
      evidence: [{ quote: "AST 22 | ALT 25 | T bili 0.5 | Alk phos 71", source: "Labs 2026-09-19" }],
    },
    {
      id: "NCT05929768-inc-22",
      status: "pass",
      rationale: "AST 22 and ALT 25 U/L on 2026-09-19, within normal limits.",
      evidence: [{ quote: "AST 22 | ALT 25 | T bili 0.5 | Alk phos 71", source: "Labs 2026-09-19" }],
    },
    {
      id: "NCT05929768-inc-23",
      status: "pass",
      rationale: "Serum creatinine 0.7 mg/dL on 2026-09-19, unflagged and within normal limits.",
      evidence: [{ quote: "Cr 0.7", source: "Labs 2026-09-19" }],
    },
    {
      id: "NCT05929768-inc-24",
      status: "unknown",
      confidence: "medium",
      rationale: "Last LVEF was 60% on 2026-03-04, before dose-dense doxorubicin and almost 7 months ago; no echo within 28 days is on file, and prior cardiotoxic therapy also requires an NYHA assessment.",
      evidence: [{ quote: "Echo 3/4/26 pre-AC LVEF 60%.", source: "Clinic note 2026-09-22" }],
      actionNeeded: "Repeat echocardiogram within 28 days of registration (LVEF ≥ 50%) and document NYHA class",
    },
    {
      id: "NCT05929768-inc-25",
      status: "pass",
      confidence: "medium",
      rationale: "Applies only to people with known HIV infection; none is recorded in her history.",
      evidence: [],
    },
    {
      id: "NCT05929768-inc-26",
      status: "pass",
      confidence: "medium",
      rationale: "Applies only to chronic hepatitis B; none is recorded, LFTs are normal, and the protocol does not require testing.",
      evidence: [{ quote: "AST 22 | ALT 25 | T bili 0.5 | Alk phos 71", source: "Labs 2026-09-19" }],
    },
    {
      id: "NCT05929768-inc-27",
      status: "pass",
      confidence: "medium",
      rationale: "Applies only to a history of hepatitis C; none is recorded, LFTs are normal, and the protocol does not require testing.",
      evidence: [],
    },
    {
      id: "NCT05929768-inc-28",
      status: "pass",
      rationale: "No diabetes is documented.",
      evidence: [{ quote: "No DM.", source: "PMH" }],
    },
    {
      id: "NCT05929768-inc-29",
      status: "pass",
      confidence: "medium",
      rationale: "No hypertension on her problem list and vitals were within normal limits on 2026-09-22.",
      evidence: [{ quote: "Vitals wnl.", source: "Exam 2026-09-22" }],
    },
    {
      id: "NCT05929768-inc-30",
      status: "pass",
      rationale: "Last major surgery was on 2026-06-11, 109 days ago, and the mastectomy scars are well healed.",
      evidence: [{ quote: "Mastectomy scars well healed, no chest wall nodularity.", source: "Exam 2026-09-22" }],
    },
    {
      id: "NCT05929768-inc-31",
      status: "pass",
      confidence: "medium",
      rationale: "No recent infection, hospitalization or antibiotic use is recorded at the 2026-09-22 visit.",
      evidence: [],
    },
    {
      id: "NCT05929768-inc-32",
      status: "pass",
      confidence: "medium",
      rationale: "No immunodeficiency is recorded and her medications include no steroids or immunosuppressants.",
      evidence: [],
    },
    {
      id: "NCT05929768-inc-33",
      status: "pass",
      rationale: "Her only autoimmune condition is immune-related hypothyroidism treated with levothyroxine, which is replacement therapy and explicitly not counted; no autoimmune disease before pembrolizumab.",
      evidence: [
        { quote: "irAE hypothyroidism G2 -> levothyroxine, TSH now nl.", source: "Clinic note 2026-09-22" },
        { quote: "No autoimmune dz prior to pembro.", source: "PMH" },
      ],
    },
    {
      id: "NCT05929768-inc-34",
      status: "pass",
      confidence: "medium",
      rationale: "No pneumonitis is recorded; she has no cough, lungs are clear and the 2026-07-09 chest CT showed only post-surgical changes.",
      evidence: [{ quote: "Lungs clear.", source: "Exam 2026-09-22" }],
    },
    {
      id: "NCT05929768-inc-35",
      status: "unknown",
      confidence: "low",
      rationale: "Vaccination history is not documented in the record.",
      evidence: [],
      actionNeeded: "Confirm no live vaccine (e.g., MMR, varicella/zoster live, intranasal influenza) within 30 days before randomization",
    },
    {
      id: "NCT05929768-inc-36",
      status: "pass",
      confidence: "medium",
      rationale: "No malignancy other than the index right breast cancer is recorded.",
      evidence: [],
    },
    {
      id: "NCT05929768-inc-37",
      status: "pass",
      rationale: "Not pregnant or breastfeeding, serum hCG negative on 2026-09-19, and she has reproductive potential with a levonorgestrel IUD in place as effective contraception.",
      evidence: [
        { quote: "Not pregnant, not breastfeeding.", source: "Clinic note 2026-09-22" },
        { quote: "hCG (serum) negative", source: "Labs 2026-09-19" },
        { quote: "levonorgestrel IUD (placed 2023)", source: "Medications" },
      ],
    },
    {
      id: "NCT05929768-inc-38",
      status: "pass",
      confidence: "medium",
      rationale: "A pretreatment core biopsy was taken in 11/2025, so an H&E slide should be obtainable; the record names only the surgical specimen as available archival tissue.",
      evidence: [{ quote: "Archival tissue available (surgical specimen 6/2026).", source: "Clinic note 2026-09-22" }],
      actionNeeded: "Confirm an H&E slide can be cut from the 11/2025 core biopsy block",
    },
    {
      id: "NCT05929768-inc-39",
      status: "pass",
      confidence: "low",
      rationale: "An offer of specimen banking is a site obligation made at consent, not a patient characteristic.",
      evidence: [],
    },
    {
      id: "NCT05929768-inc-40",
      status: "pass",
      confidence: "low",
      rationale: "An offer of the patient-reported outcome study is made at consent; nothing suggests she could not complete questionnaires.",
      evidence: [],
    },
    {
      id: "NCT05929768-inc-41",
      status: "not-applicable",
      rationale: "Administrative registration note about the site's IRB approval date, not a patient criterion.",
      evidence: [],
    },
    {
      id: "NCT05929768-inc-42",
      status: "pass",
      confidence: "low",
      rationale: "Informed consent is obtained at screening; she is engaged in the trial discussion.",
      evidence: [],
    },
    {
      id: "NCT05929768-inc-43",
      status: "not-applicable",
      rationale: "Concerns consent by a legally authorized representative; she has full decision-making capacity.",
      evidence: [],
    },
    {
      id: "NCT05929768-inc-44",
      status: "not-applicable",
      rationale: "Administrative registration note about the site's IRB approval date, not a patient criterion.",
      evidence: [],
    },
  ],
);
