import { demoMatch } from "../../match-helpers";

export default demoMatch(
  "NCT06637306",
  "Excluded: neoadjuvant trial for untreated TNBC; she has completed KEYNOTE-522, surgery and PMRT",
  "This pilot adds dupilumab to neoadjuvant pembrolizumab with paclitaxel/carboplatin in previously untreated, operable TNBC. Danielle has already completed that neoadjuvant regimen (12/2025–5/2026), bilateral mastectomy with ALND on 2026-06-11 and PMRT ending 2026-08-28, and is now on adjuvant pembrolizumab, so the untreated-disease requirements and the prior-therapy exclusion are definitive blockers; there is also no tumor left to biopsy. Her biology and fitness (TNBC, ECOG 0, adequate labs, hypothyroidism on replacement only) would otherwise fit, but nothing in her course can change this; post-neoadjuvant residual-disease trials are the relevant category.",
  [
    {
      id: "NCT06637306-inc-1",
      status: "pass",
      rationale: "Triple-negative by ASCO/CAP criteria (ER 0%, PR 0%, HER2 IHC 0) on the core biopsy, confirmed on the residual tumor at surgery.",
      evidence: [
        { quote: "IDC, grade 3 (Nottingham 9/9), ER 0%, PR 0%, HER2 IHC 0 (negative), Ki-67 75%.", source: "Core biopsy 11/2025" },
        { quote: "Receptors repeated on residual tumor: ER 0%, PR 0%, HER2 IHC 0 - triple negative, concordant with core bx.", source: "Pathology 2026-06-17" },
      ],
    },
    {
      id: "NCT06637306-inc-2",
      status: "fail",
      rationale: "Her cT2 (3.1 cm) cN1 tumor met the size and nodal thresholds at diagnosis in 11/2025, but the disease is no longer untreated: she completed neoadjuvant KEYNOTE-522 and surgery.",
      evidence: [
        { quote: "R breast IDC grade 3, TNBC, cT2 (3.1 cm) cN1 (bx-proven axillary node) M0, stage IIB, dx 11/2025.", source: "Clinic note 2026-09-22" },
        { quote: "Neoadj per KEYNOTE-522: pembro + weekly paclitaxel + carboplatin x12 wks (12/2025-3/2026) then pembro + ddAC x4 (3/2026-5/2026).", source: "Clinic note 2026-09-22" },
      ],
    },
    {
      id: "NCT06637306-inc-3",
      status: "fail",
      rationale: "She has had all three prohibited treatments: neoadjuvant chemotherapy (12/2025–5/2026), definitive bilateral mastectomy with ALND on 2026-06-11, and PMRT completed 2026-08-28.",
      evidence: [
        { quote: "Surgery 6/11/26: bilateral mastectomy (L risk-reducing) + R ALND -> ypT1c (1.2 cm) ypN1a (2/11), RCB class II (RCB 2.6), margins neg.", source: "Clinic note 2026-09-22" },
        { quote: "PMRT 7/20/26-8/28/26, completed.", source: "Clinic note 2026-09-22" },
      ],
    },
    {
      id: "NCT06637306-inc-4",
      status: "pass",
      confidence: "medium",
      rationale: "She tolerated 12 weeks of paclitaxel/carboplatin; the grade 2 neuropathy has settled to grade 1 without functional limitation and counts and organ function are adequate, so neither agent is contraindicated.",
      evidence: [
        { quote: "Tox: G2 PN on paclitaxel, now G1 (toes)", source: "Clinic note 2026-09-22" },
        { quote: "PN stable G1, no functional limitation.", source: "Clinic note 2026-09-22" },
      ],
    },
    {
      id: "NCT06637306-inc-5",
      status: "pass",
      confidence: "low",
      rationale: "Willingness to provide research blood samples is confirmed at screening; she already has a port in place.",
      evidence: [{ quote: "Port in situ.", source: "CT CAP 2026-07-09" }],
    },
    {
      id: "NCT06637306-inc-6",
      status: "fail",
      confidence: "medium",
      rationale: "Requires pre-treatment core biopsies of the tumor, but she has no tumor in situ: both breasts and the axillary nodes were removed with negative margins and she is NED. The protocol's allowance covers inadequate samples, not absent tumor.",
      evidence: [
        { quote: "Currently NED.", source: "Clinic note 2026-09-22" },
        { quote: "Mastectomy scars well healed, no chest wall nodularity.", source: "Exam 2026-09-22" },
      ],
    },
    {
      id: "NCT06637306-inc-7",
      status: "pass",
      rationale: "39 years old (born 1987), above the minimum age of 18.",
      evidence: [{ quote: "39 yo premenopausal F", source: "Clinic note 2026-09-22" }],
    },
    {
      id: "NCT06637306-inc-8",
      status: "pass",
      rationale: "ECOG 0 on examination 2026-09-22.",
      evidence: [{ quote: "EXAM: ECOG 0.", source: "Clinic note 2026-09-22" }],
    },
    {
      id: "NCT06637306-inc-9",
      status: "pass",
      rationale: "Labs 2026-09-19 meet each threshold: ANC 1.9 ×10⁹/L (≥ 1.5, borderline), platelets 180, bilirubin 0.5, AST 22 / ALT 25 and creatinine 0.7, all within normal limits.",
      evidence: [
        { quote: "WBC 3.4 (L) | ANC 1.9 | Hgb 12.4 | Plt 180", source: "Labs 2026-09-19" },
        { quote: "AST 22 | ALT 25 | T bili 0.5 | Alk phos 71", source: "Labs 2026-09-19" },
        { quote: "Cr 0.7", source: "Labs 2026-09-19" },
      ],
    },
    {
      id: "NCT06637306-inc-10",
      status: "pass",
      confidence: "low",
      rationale: "The contraception agreement is confirmed at screening; she has had a levonorgestrel IUD in place since 2023.",
      evidence: [{ quote: "levonorgestrel IUD (placed 2023)", source: "Medications" }],
    },
    {
      id: "NCT06637306-inc-11",
      status: "pass",
      confidence: "medium",
      rationale: "Part of the protocol's definition of childbearing potential rather than an eligibility rule: no hysterectomy or oophorectomy is recorded and an IUD is in place, so she counts as of childbearing potential.",
      evidence: [{ quote: "39 yo premenopausal F, G2P2, LNG-IUD in place", source: "Clinic note 2026-09-22" }],
    },
    {
      id: "NCT06637306-inc-12",
      status: "pass",
      rationale: "Part of the childbearing-potential definition: she is premenopausal with spotting as recently as ~8/26, so the contraception and pregnancy-testing rules apply to her.",
      evidence: [{ quote: "Menses irregular since chemo, last spotting ~8/26.", source: "Clinic note 2026-09-22" }],
    },
    {
      id: "NCT06637306-inc-13",
      status: "pass",
      confidence: "low",
      rationale: "Capacity and willingness to consent are confirmed at screening; she is a registered nurse actively asking about trials.",
      evidence: [{ quote: "SH: RN, 2 kids, never smoker, no EtOH.", source: "Clinic note 2026-09-22" }],
    },
    {
      id: "NCT06637306-exc-1",
      status: "fail",
      rationale: "PMRT ended 2026-08-28 (31 days ago, just outside 4 weeks), but she has had extensive therapeutic-intent treatment (neoadjuvant chemoimmunotherapy, surgery, PMRT) and is on adjuvant pembrolizumab, cycle 4 given 2026-09-22.",
      evidence: [
        { quote: "PMRT 7/20/26-8/28/26, completed.", source: "Clinic note 2026-09-22" },
        { quote: "pembrolizumab 200 mg IV q3 weeks (adjuvant, C4 of 9)", source: "Medications" },
      ],
    },
    {
      id: "NCT06637306-exc-2",
      status: "pass",
      confidence: "medium",
      rationale: "No investigational agent is on her medication list; her only anticancer drug is standard-of-care adjuvant pembrolizumab.",
      evidence: [{ quote: "pembrolizumab 200 mg IV q3 weeks (adjuvant, C4 of 9)", source: "Medications" }],
    },
    {
      id: "NCT06637306-exc-3",
      status: "pass",
      rationale: "No distant metastases on baseline staging (11/2025) or on the post-operative CT of 2026-07-09.",
      evidence: [
        { quote: "No evidence of metastatic disease in the chest, abdomen or pelvis.", source: "CT CAP 2026-07-09" },
        { quote: "Baseline staging 11/2025: CT CAP + bone scan without distant disease.", source: "Imaging" },
      ],
    },
    {
      id: "NCT06637306-exc-4",
      status: "pass",
      confidence: "medium",
      rationale: "No immunodeficiency is recorded and she takes no systemic steroids or immunosuppressants; her medications are pembrolizumab, levothyroxine, sertraline and a levonorgestrel IUD.",
      evidence: [{ quote: "levothyroxine 75 mcg PO daily", source: "Medications" }],
    },
    {
      id: "NCT06637306-exc-5",
      status: "pass",
      rationale: "Her only autoimmune condition is pembrolizumab-induced hypothyroidism treated with levothyroxine replacement, which the criterion explicitly allows; no autoimmune disease preceded pembrolizumab.",
      evidence: [
        { quote: "irAE hypothyroidism G2 -> levothyroxine, TSH now nl.", source: "Clinic note 2026-09-22" },
        { quote: "No autoimmune dz prior to pembro.", source: "Clinic note 2026-09-22" },
      ],
    },
    {
      id: "NCT06637306-exc-6",
      status: "pass",
      confidence: "medium",
      rationale: "Her comorbidities (hypothyroidism on replacement, stable anxiety, grade 1 neuropathy) would not confound the study; her prior treatment is handled by the specific criteria above.",
      evidence: [{ quote: "PMH: irAE hypothyroidism (on levo), anxiety (sertraline). No DM. No autoimmune dz prior to pembro.", source: "Clinic note 2026-09-22" }],
    },
    {
      id: "NCT06637306-exc-7",
      status: "pass",
      rationale: "NKDA, and she has already received paclitaxel, carboplatin and pembrolizumab (a monoclonal antibody) without a recorded reaction; she has never had dupilumab.",
      evidence: [{ quote: "ALLERGIES: NKDA", source: "Allergies" }],
    },
    {
      id: "NCT06637306-exc-8",
      status: "unknown",
      confidence: "low",
      rationale: "HIV status is not documented in the record.",
      evidence: [],
      actionNeeded: "Obtain HIV antibody/antigen test; if positive, undetectable viral load on stable HAART and CD4 ≥ 350/µL are required",
    },
    {
      id: "NCT06637306-exc-9",
      status: "unknown",
      confidence: "low",
      rationale: "Hepatitis B and C serology is not recorded; LFTs are normal (AST 22, ALT 25).",
      evidence: [],
      actionNeeded: "Obtain HBsAg, anti-HBc and HCV antibody (HCV RNA if positive); active HBV or HCV excludes unless HBV DNA is undetectable on antivirals",
    },
    {
      id: "NCT06637306-exc-10",
      status: "pass",
      confidence: "medium",
      rationale: "No helminth infection appears in an otherwise complete past medical history.",
      evidence: [],
    },
    {
      id: "NCT06637306-exc-11",
      status: "pass",
      confidence: "medium",
      rationale: "No stem cell or solid organ transplant is recorded; her past medical history lists only immune hypothyroidism and anxiety.",
      evidence: [{ quote: "PMH: irAE hypothyroidism (on levo), anxiety (sertraline). No DM. No autoimmune dz prior to pembro.", source: "Clinic note 2026-09-22" }],
    },
    {
      id: "NCT06637306-exc-12",
      status: "pass",
      confidence: "low",
      rationale: "Vaccination history is not recorded; the 30-day live-vaccine window is confirmed at screening.",
      evidence: [],
      actionNeeded: "Confirm no live vaccine (e.g., MMR, varicella/zoster live, intranasal influenza) within 30 days before the first dose",
    },
    {
      id: "NCT06637306-exc-13",
      status: "pass",
      rationale: "Her irAE is grade 2 hypothyroidism, an endocrinopathy controlled on levothyroxine (TSH 3.1), which the criterion carves out; no other irAE is recorded.",
      evidence: [{ quote: "2. irAE hypothyroidism G2 - levothyroxine 75 mcg, TSH 3.1, continue.", source: "Clinic note 2026-09-22" }],
    },
    {
      id: "NCT06637306-exc-14",
      status: "pass",
      confidence: "medium",
      rationale: "No ILD or pneumonitis from pembrolizumab or from PMRT (completed 2026-08-28): no cough and lungs clear on 2026-09-22. The 2026-07-09 CT predates radiation.",
      evidence: [
        { quote: "No new lumps, bone pain, HA or cough.", source: "Clinic note 2026-09-22" },
        { quote: "Lungs clear.", source: "Exam 2026-09-22" },
      ],
    },
    {
      id: "NCT06637306-exc-15",
      status: "pass",
      confidence: "medium",
      rationale: "No active infection, heart failure, angina or arrhythmia is recorded (LVEF 60% in 3/2026), and her anxiety is stable on sertraline.",
      evidence: [
        { quote: "ECHO 03/04/2026: LVEF 60%, normal LV size and function.", source: "Echo 2026-03-04" },
        { quote: "4. Anxiety - sertraline 50 mg, stable.", source: "Clinic note 2026-09-22" },
      ],
    },
    {
      id: "NCT06637306-exc-16",
      status: "pass",
      rationale: "Not pregnant or nursing per the 2026-09-22 note, with a negative serum hCG on 2026-09-19.",
      evidence: [
        { quote: "Not pregnant, not breastfeeding.", source: "Clinic note 2026-09-22" },
        { quote: "hCG (serum) negative", source: "Labs 2026-09-19" },
      ],
    },
  ],
);
