import { demoMatch } from "../../match-helpers";

export default demoMatch(
  "NCT05812807",
  "Excluded: for pCR only, and she has residual disease (RCB-II, ypT1c ypN1a) past the 12-week window",
  "OptimICE-pCR randomizes patients who achieved a pathologic complete response after neoadjuvant chemo-immunotherapy to adjuvant pembrolizumab or observation. She had residual invasive disease in the breast and 2 of 11 axillary nodes (ypT1c ypN1a, RCB class II), surgery was on 2026-06-11 so the 12-week randomization window closed on 2026-09-03, and she has already received four adjuvant pembrolizumab cycles against a two-dose maximum. Nothing in the record would change this.",
  [
    {
      id: "NCT05812807-inc-1",
      status: "pass",
      rationale: "She is 39 years old (born 1987).",
      evidence: [{ quote: "DOB: 1987 (39 yo F)", source: "Clinic note 2026-09-22" }],
    },
    {
      id: "NCT05812807-inc-2",
      status: "pass",
      rationale: "ECOG 0 at the 2026-09-22 visit.",
      evidence: [{ quote: "EXAM: ECOG 0.", source: "Clinic note 2026-09-22" }],
    },
    {
      id: "NCT05812807-inc-3",
      status: "pass",
      rationale: "Triple-negative on the 11/2025 core biopsy and again on the residual tumor in 6/2026 (ER 0%, PR 0%, HER2 IHC 0).",
      evidence: [{ quote: "Receptors repeated on residual tumor: ER 0%, PR 0%, HER2 IHC 0 - triple negative, concordant with core bx.", source: "Pathology 2026-06-17" }],
    },
    {
      id: "NCT05812807-inc-4",
      status: "pass",
      rationale: "Clinical stage at diagnosis was cT2 (3.1 cm) cN1 with a biopsy-proven axillary node, M0 — stage IIB, within the T2-4 N0-2 range.",
      evidence: [{ quote: "R breast IDC grade 3, TNBC, cT2 (3.1 cm) cN1 (bx-proven axillary node) M0, stage IIB, dx 11/2025.", source: "Clinic note 2026-09-22" }],
    },
    {
      id: "NCT05812807-inc-5",
      status: "fail",
      rationale: "She did not achieve pCR: the 2026-06-11 mastectomy showed a 1.2 cm residual invasive focus and 2 of 11 positive nodes (ypT1c ypN1a, RCB class II, score 2.6).",
      evidence: [
        { quote: "Pathologic stage (AJCC 8th): ypT1c ypN1a", source: "Pathology 2026-06-17" },
        { quote: "Residual Cancer Burden: RCB class II (RCB score 2.6)", source: "Pathology 2026-06-17" },
      ],
    },
    {
      id: "NCT05812807-inc-6",
      status: "pass",
      rationale: "ER 0%, PR 0% (≤ 10%) and HER2 IHC 0 on the core biopsy, concordant on the residual tumor.",
      evidence: [{ quote: "ER 0%, PR 0%, HER2 IHC 0 (negative), Ki-67 75%.", source: "Core biopsy 11/2025" }],
    },
    {
      id: "NCT05812807-inc-7",
      status: "not-applicable",
      rationale: "Invasive disease was confined to the right breast; the risk-reducing left mastectomy showed benign tissue with no carcinoma.",
      evidence: [{ quote: "C. Left breast: benign breast tissue, no atypia, no carcinoma.", source: "Pathology 2026-06-17" }],
    },
    {
      id: "NCT05812807-inc-8",
      status: "pass",
      rationale: "KEYNOTE-522 delivered pembrolizumab with chemotherapy over 12 weeks of paclitaxel/carboplatin then 4 cycles of ddAC (about 8 three-weekly pembrolizumab cycles), all completed before surgery in 5/2026.",
      evidence: [{ quote: "Neoadj per KEYNOTE-522: pembro + weekly paclitaxel + carboplatin x12 wks (12/2025-3/2026) then pembro + ddAC x4 (3/2026-5/2026).", source: "Clinic note 2026-09-22" }],
    },
    {
      id: "NCT05812807-inc-9",
      status: "fail",
      rationale: "Surgery was on 2026-06-11, so the 12-week window closed on 2026-09-03 (today is 15.6 weeks post-op), and she has had four adjuvant pembrolizumab cycles since 2026-07-21, exceeding the two-dose limit.",
      evidence: [
        { quote: "Procedure date: 2026-06-11", source: "Pathology 2026-06-17" },
        { quote: "pembrolizumab 200 mg IV q3 weeks (adjuvant, C4 of 9)", source: "Medications" },
      ],
    },
    {
      id: "NCT05812807-inc-10",
      status: "pass",
      confidence: "medium",
      rationale: "No investigational anti-cancer agent is on her medication list; her only anticancer drug is standard adjuvant pembrolizumab.",
      evidence: [{ quote: "pembrolizumab 200 mg IV q3 weeks (adjuvant, C4 of 9)", source: "Medications" }],
    },
    {
      id: "NCT05812807-inc-11",
      status: "pass",
      rationale: "All clinically evident disease was removed by right mastectomy with negative margins and right axillary dissection on 2026-06-11.",
      evidence: [{ quote: "Margins negative (closest deep 4 mm).", source: "Pathology 2026-06-17" }],
    },
    {
      id: "NCT05812807-inc-12",
      status: "pass",
      rationale: "Right total mastectomy with histologically negative margins (closest deep margin 4 mm).",
      evidence: [{ quote: "Margins negative (closest deep 4 mm).", source: "Pathology 2026-06-17" }],
    },
    {
      id: "NCT05812807-inc-13",
      status: "not-applicable",
      rationale: "Applies to clinically node-negative patients; she was cN1 with a biopsy-proven axillary node at diagnosis.",
      evidence: [{ quote: "Axillary node core: metastatic carcinoma.", source: "Core biopsy 11/2025" }],
    },
    {
      id: "NCT05812807-inc-14",
      status: "fail",
      rationale: "Biopsy-proven cN1 at diagnosis; post-treatment axillary dissection found 2 of 11 nodes positive (ypN1a). The required axillary surgery was done, but residual nodal disease is exactly what this pathway excludes.",
      evidence: [
        { quote: "Axillary node core: metastatic carcinoma.", source: "Core biopsy 11/2025" },
        { quote: "2 of 11 lymph nodes positive for metastatic carcinoma with treatment effect", source: "Pathology 2026-06-17" },
      ],
    },
    {
      id: "NCT05812807-inc-15",
      status: "not-applicable",
      rationale: "No sentinel node biopsy was done before neoadjuvant therapy; nodal status was established by core biopsy of the axillary node.",
      evidence: [{ quote: "Axillary node core: metastatic carcinoma.", source: "Core biopsy 11/2025" }],
    },
    {
      id: "NCT05812807-inc-16",
      status: "not-applicable",
      rationale: "Concerns internal-mammary-only sentinel nodes; she had a full right axillary dissection rather than sentinel node mapping.",
      evidence: [],
    },
    {
      id: "NCT05812807-inc-17",
      status: "not-applicable",
      rationale: "Concerns a negative post-treatment sentinel node evaluation; she had an axillary dissection, which was node-positive.",
      evidence: [],
    },
    {
      id: "NCT05812807-inc-18",
      status: "pass",
      rationale: "Axillary dissection was her sole post-treatment axillary evaluation (right level I–II ALND on 2026-06-11), which this criterion permits.",
      evidence: [{ quote: "B. Right axillary contents, level I-II", source: "Pathology 2026-06-17" }],
    },
    {
      id: "NCT05812807-inc-19",
      status: "not-applicable",
      rationale: "Applies to breast-conserving surgery; she had bilateral mastectomy followed by post-mastectomy radiation.",
      evidence: [],
    },
    {
      id: "NCT05812807-inc-20",
      status: "pass",
      confidence: "medium",
      rationale: "Not pregnant or breastfeeding and serum hCG negative on 2026-09-19; she is of childbearing potential, so a test within 7 days of randomization would be needed.",
      evidence: [
        { quote: "Not pregnant, not breastfeeding.", source: "Clinic note 2026-09-22" },
        { quote: "hCG (serum) negative", source: "Labs 2026-09-19" },
      ],
    },
    {
      id: "NCT05812807-inc-21",
      status: "pass",
      rationale: "ANC 1.9 × 10⁹/L (1,900/mm³) on 2026-09-19, above the 1,000 threshold.",
      evidence: [{ quote: "WBC 3.4 (L) | ANC 1.9 | Hgb 12.4 | Plt 180", source: "Labs 2026-09-19" }],
    },
    {
      id: "NCT05812807-inc-22",
      status: "pass",
      rationale: "Platelets 180 × 10⁹/L on 2026-09-19.",
      evidence: [{ quote: "WBC 3.4 (L) | ANC 1.9 | Hgb 12.4 | Plt 180", source: "Labs 2026-09-19" }],
    },
    {
      id: "NCT05812807-inc-23",
      status: "pass",
      rationale: "Creatinine 0.7 mg/dL on 2026-09-19, corresponding to an eGFR far above 15 mL/min/1.73 m².",
      evidence: [{ quote: "Cr 0.7", source: "Labs 2026-09-19" }],
    },
    {
      id: "NCT05812807-inc-24",
      status: "pass",
      rationale: "Total bilirubin 0.5 mg/dL on 2026-09-19, within normal limits.",
      evidence: [{ quote: "AST 22 | ALT 25 | T bili 0.5 | Alk phos 71", source: "Labs 2026-09-19" }],
    },
    {
      id: "NCT05812807-inc-25",
      status: "pass",
      rationale: "AST 22 and ALT 25 U/L on 2026-09-19, within normal limits.",
      evidence: [{ quote: "AST 22 | ALT 25 | T bili 0.5 | Alk phos 71", source: "Labs 2026-09-19" }],
    },
    {
      id: "NCT05812807-inc-26",
      status: "pass",
      confidence: "low",
      rationale: "Willingness to release diagnostic core biopsy tissue is confirmed at consent; inadequate tissue would not affect eligibility.",
      evidence: [],
    },
    {
      id: "NCT05812807-inc-27",
      status: "pass",
      confidence: "medium",
      rationale: "No malignancy other than the index breast cancer is recorded; the germline panel and history mention none.",
      evidence: [],
    },
    {
      id: "NCT05812807-inc-28",
      status: "pass",
      confidence: "medium",
      rationale: "She received doxorubicin (ddAC), so NYHA assessment applies; she is asymptomatic, ECOG 0, with LVEF 60% on the pre-anthracycline echo (2026-03-04), consistent with NYHA class I.",
      evidence: [{ quote: "ECHO 03/04/2026: LVEF 60%, normal LV size and function.", source: "Echo 2026-03-04" }],
      actionNeeded: "Document NYHA class at screening given prior doxorubicin",
    },
    {
      id: "NCT05812807-inc-29",
      status: "pass",
      confidence: "medium",
      rationale: "Applies only to people with known HIV; no HIV infection is recorded in her history.",
      evidence: [],
    },
    {
      id: "NCT05812807-exc-1",
      status: "pass",
      rationale: "No stage IV disease: baseline staging and the 2026-07-09 CT CAP showed no distant metastases.",
      evidence: [
        { quote: "Baseline staging 11/2025: CT CAP + bone scan without distant disease.", source: "Imaging" },
        { quote: "No evidence of metastatic disease in the chest, abdomen or pelvis.", source: "CT CAP 2026-07-09" },
      ],
    },
    {
      id: "NCT05812807-exc-2",
      status: "pass",
      rationale: "The 11/2025 right breast cancer is her first; the risk-reducing left mastectomy showed no carcinoma.",
      evidence: [{ quote: "C. Left breast: benign breast tissue, no atypia, no carcinoma.", source: "Pathology 2026-06-17" }],
    },
    {
      id: "NCT05812807-exc-3",
      status: "pass",
      rationale: "No recurrence since surgery: CT CAP 2026-07-09 without metastases and no chest wall nodularity or adenopathy on the 2026-09-22 exam.",
      evidence: [
        { quote: "Post-op CT CAP 7/9/26 NED.", source: "Clinic note 2026-09-22" },
        { quote: "No cervical/supraclav/axillary adenopathy.", source: "Exam 2026-09-22" },
      ],
    },
    {
      id: "NCT05812807-exc-4",
      status: "pass",
      confidence: "medium",
      rationale: "No liver disease is recorded and AST 22, ALT 25, bilirubin 0.5 and ALP 71 are normal (2026-09-19); hepatitis serology is not on file.",
      evidence: [{ quote: "AST 22 | ALT 25 | T bili 0.5 | Alk phos 71", source: "Labs 2026-09-19" }],
    },
    {
      id: "NCT05812807-exc-5",
      status: "pass",
      rationale: "No pembrolizumab hypersensitivity; her grade 2 immune hypothyroidism is controlled on levothyroxine and she has continued pembrolizumab — the stated exception for endocrinopathies.",
      evidence: [{ quote: "irAE hypothyroidism G2 -> levothyroxine, TSH now nl.", source: "Clinic note 2026-09-22" }],
    },
    {
      id: "NCT05812807-exc-6",
      status: "pass",
      rationale: "No systemic steroids or immunosuppressants; levothyroxine is replacement therapy and is explicitly not counted.",
      evidence: [{ quote: "levothyroxine 75 mcg PO daily", source: "Medications" }],
    },
    {
      id: "NCT05812807-exc-7",
      status: "pass",
      confidence: "low",
      rationale: "Ability and willingness to comply are confirmed at screening; nothing in the record suggests otherwise.",
      evidence: [],
    },
  ],
);
