import { demoMatch } from "../../match-helpers";

export default demoMatch(
  "NCT04434040",
  "Fits the residual-disease population · hinges on a positive central ctDNA (Signatera pending)",
  "She matches the target population: TNBC with residual invasive disease after neoadjuvant chemotherapy (ypT1c ypN1a), NED, and within 4 months of finishing radiation (window closes ~2026-12-28). Eligibility turns on a positive, centrally tested ctDNA; her Signatera from 2026-08-25 is pending and was drawn three days before radiation ended, so a post-radiation sample is needed. Questions for the PI: atezolizumab would replace her ongoing adjuvant pembrolizumab, and her levonorgestrel IUD is a hormonal method the protocol does not accept. Starting adjuvant capecitabine would exclude her.",
  [
    {
      id: "NCT04434040-inc-1",
      status: "pass",
      rationale: "Residual invasive carcinoma after neoadjuvant chemotherapy in both the breast (single 1.2 cm focus) and 2 of 11 axillary nodes at surgery on 2026-06-11.",
      evidence: [
        { quote: "residual invasive ductal carcinoma, grade 3, single focus 1.2 cm with treatment effect", source: "Pathology 2026-06-17" },
        { quote: "2 of 11 lymph nodes positive for metastatic carcinoma with treatment effect", source: "Pathology 2026-06-17" },
      ],
    },
    {
      id: "NCT04434040-inc-2",
      status: "pass",
      rationale: "HER2 IHC 0 on the pre-treatment core biopsy (11/2025), concordant on the residual tumor.",
      evidence: [{ quote: "ER 0%, PR 0%, HER2 IHC 0 (negative), Ki-67 75%.", source: "Core biopsy 11/2025" }],
    },
    {
      id: "NCT04434040-inc-3",
      status: "pass",
      rationale: "ER 0% and PR 0% on the pre-treatment core biopsy, well below the 10% cut-off.",
      evidence: [{ quote: "ER 0%, PR 0%, HER2 IHC 0 (negative), Ki-67 75%.", source: "Core biopsy 11/2025" }],
    },
    {
      id: "NCT04434040-inc-4",
      status: "pass",
      rationale: "She completed neoadjuvant KEYNOTE-522 chemotherapy (12/2025–5/2026) before surgery on 2026-06-11.",
      evidence: [{ quote: "Neoadj per KEYNOTE-522: pembro + weekly paclitaxel + carboplatin x12 wks (12/2025-3/2026) then pembro + ddAC x4 (3/2026-5/2026).", source: "Clinic note 2026-09-22" }],
    },
    {
      id: "NCT04434040-inc-5",
      status: "pass",
      rationale: "Last locoregional therapy was radiation ending 2026-08-28 (31 days ago, window closes ~2026-12-28); definitive surgery was mastectomy with clear margins plus axillary dissection.",
      evidence: [
        { quote: "PMRT 7/20/26-8/28/26, completed.", source: "Clinic note 2026-09-22" },
        { quote: "Margins negative (closest deep 4 mm).", source: "Pathology 2026-06-17" },
      ],
    },
    {
      id: "NCT04434040-inc-6",
      status: "unknown",
      confidence: "high",
      rationale: "Signatera ctDNA drawn on 2026-08-25 is pending; it was collected before radiation finished on 2026-08-28 and is not the trial's central assay, so it cannot establish eligibility.",
      evidence: [{ quote: "Signatera (ctDNA) sent 8/25/26 - result pending.", source: "Clinic note 2026-09-22" }],
      actionNeeded: "Send a post-radiation blood sample for central ctDNA testing; any tumor-specific mutation detected is required",
    },
    {
      id: "NCT04434040-inc-7",
      status: "pass",
      rationale: "Permissive criterion; she is not receiving bisphosphonates or denosumab.",
      evidence: [],
    },
    {
      id: "NCT04434040-inc-8",
      status: "pass",
      confidence: "medium",
      rationale: "Neoadjuvant pembrolizumab is permitted. The criteria do not address the adjuvant pembrolizumab she is receiving now (C4 of 9), which atezolizumab would replace.",
      evidence: [{ quote: "pembrolizumab 200 mg IV q3 weeks (adjuvant, C4 of 9)", source: "Medications" }],
      actionNeeded: "Confirm with the PI how ongoing adjuvant pembrolizumab is handled and the washout before atezolizumab",
    },
    {
      id: "NCT04434040-inc-9",
      status: "pass",
      rationale: "ECOG 0 at the 2026-09-22 visit.",
      evidence: [{ quote: "EXAM: ECOG 0.", source: "Clinic note 2026-09-22" }],
    },
    {
      id: "NCT04434040-inc-10",
      status: "pass",
      rationale: "She is 39 years old (born 1987).",
      evidence: [{ quote: "DOB: 1987 (39 yo F)", source: "Clinic note 2026-09-22" }],
    },
    {
      id: "NCT04434040-inc-11",
      status: "unknown",
      confidence: "medium",
      rationale: "On 2026-09-19: ANC 1.9 (borderline), WBC 3.4, Plt 180, Hgb 12.4, Cr 0.7, AST/ALT/ALP/bilirubin normal — all meet thresholds. Lymphocyte count, albumin and INR/aPTT are not reported.",
      evidence: [
        { quote: "WBC 3.4 (L) | ANC 1.9 | Hgb 12.4 | Plt 180", source: "Labs 2026-09-19" },
        { quote: "AST 22 | ALT 25 | T bili 0.5 | Alk phos 71", source: "Labs 2026-09-19" },
      ],
      actionNeeded: "Obtain lymphocyte count (≥ 500/µL), albumin (≥ 2.5 g/dL) and INR/aPTT (≤ 1.5 × ULN); repeat ANC (≥ 1,500/µL)",
    },
    {
      id: "NCT04434040-inc-12",
      status: "pass",
      confidence: "medium",
      rationale: "Premenopausal (spotting ~8/26, within 12 months) so a test is required; serum hCG was negative on 2026-09-19 but must be repeated within 7 days of starting therapy.",
      evidence: [
        { quote: "Menses irregular since chemo, last spotting ~8/26.", source: "Clinic note 2026-09-22" },
        { quote: "hCG (serum) negative", source: "Labs 2026-09-19" },
      ],
      actionNeeded: "Repeat serum or urine hCG within 7 days before day 1",
    },
    {
      id: "NCT04434040-inc-13",
      status: "unknown",
      confidence: "medium",
      rationale: "Her contraception is a levonorgestrel IUD, a hormonal method; the protocol states hormonal contraceptives are not acceptable.",
      evidence: [{ quote: "levonorgestrel IUD (placed 2023)", source: "Medications" }],
      actionNeeded: "Ask the PI whether the levonorgestrel IUD is acceptable; otherwise switch to a non-hormonal method (copper IUD or barrier)",
    },
    {
      id: "NCT04434040-inc-14",
      status: "pass",
      confidence: "low",
      rationale: "Capacity and willingness to consent are confirmed at screening; she is actively asking about residual-disease trials.",
      evidence: [{ quote: "Pt leaning olaparib but wants to hear about trials for residual disease first.", source: "Clinic note 2026-09-22" }],
    },
    {
      id: "NCT04434040-exc-1",
      status: "pass",
      rationale: "No sacituzumab govitecan, irinotecan or topoisomerase I ADC: her systemic therapy has been KEYNOTE-522 chemotherapy and pembrolizumab only.",
      evidence: [{ quote: "Neoadj per KEYNOTE-522", source: "Clinic note 2026-09-22" }],
    },
    {
      id: "NCT04434040-exc-2",
      status: "pass",
      confidence: "medium",
      rationale: "All chemotherapy was preoperative (ended 5/2026) and her only current anticancer drug is pembrolizumab; the A/P 'continue weekly paclitaxel/carbo' line is a stale copy-forward. Adjuvant capecitabine is under discussion.",
      evidence: [
        { quote: "then pembro + ddAC x4 (3/2026-5/2026)", source: "Clinic note 2026-09-22" },
        { quote: "pembrolizumab 200 mg IV q3 weeks (adjuvant, C4 of 9)", source: "Medications" },
      ],
      actionNeeded: "Confirm no chemotherapy since 5/2026; capecitabine must not be started before enrollment",
    },
    {
      id: "NCT04434040-exc-3",
      status: "pass",
      confidence: "medium",
      rationale: "She has never received atezolizumab or sacituzumab govitecan, records NKDA and tolerates pembrolizumab.",
      evidence: [{ quote: "ALLERGIES: NKDA", source: "Allergies" }],
    },
    {
      id: "NCT04434040-exc-4",
      status: "pass",
      rationale: "No metastatic disease on the 2026-07-09 CT CAP or on exam (no chest wall nodularity, no adenopathy).",
      evidence: [
        { quote: "No evidence of metastatic disease in the chest, abdomen or pelvis.", source: "CT CAP 2026-07-09" },
        { quote: "No cervical/supraclav/axillary adenopathy.", source: "Exam 2026-09-22" },
      ],
    },
    {
      id: "NCT04434040-exc-5",
      status: "pass",
      rationale: "Residual disease is invasive in both breast and nodes (ypT1c ypN1a), not DCIS/LCIS alone, pT0N0i+ or pT0N1mi.",
      evidence: [{ quote: "Pathologic stage (AJCC 8th): ypT1c ypN1a", source: "Pathology 2026-06-17" }],
    },
    {
      id: "NCT04434040-exc-6",
      status: "pass",
      confidence: "medium",
      rationale: "She is not enrolled on any other investigational therapy trial; all treatment to date has been standard of care.",
      evidence: [],
    },
    {
      id: "NCT04434040-exc-7",
      status: "pass",
      confidence: "medium",
      rationale: "Neuropathy is grade 1 (and exempt anyway). Immune hypothyroidism remains grade 2 on levothyroxine with normal TSH; the protocol accepts hypothyroidism on replacement elsewhere (exc-13).",
      evidence: [
        { quote: "PN stable G1, no functional limitation.", source: "Clinic note 2026-09-22" },
        { quote: "TSH 3.1 | free T4 1.1", source: "Labs 2026-09-19" },
      ],
      actionNeeded: "Confirm with the PI that hypothyroidism controlled on levothyroxine counts as resolved",
    },
    {
      id: "NCT04434040-exc-8",
      status: "pass",
      rationale: "Last major surgery was on 2026-06-11, 109 days ago; no further surgery is planned in the record.",
      evidence: [{ quote: "Procedure date: 2026-06-11", source: "Pathology 2026-06-17" }],
    },
    {
      id: "NCT04434040-exc-9",
      status: "pass",
      confidence: "medium",
      rationale: "No antibiotics are on her medication list and no recent infection is recorded.",
      evidence: [],
    },
    {
      id: "NCT04434040-exc-10",
      status: "pass",
      confidence: "medium",
      rationale: "No infection, liver disease, bleeding disorder or diabetes is recorded and LFTs are normal; lipids and calcium are not reported.",
      evidence: [
        { quote: "No DM.", source: "PMH" },
        { quote: "AST 22 | ALT 25 | T bili 0.5 | Alk phos 71", source: "Labs 2026-09-19" },
      ],
      actionNeeded: "Check lipid panel and calcium at screening",
    },
    {
      id: "NCT04434040-exc-11",
      status: "pass",
      confidence: "medium",
      rationale: "No cardiovascular disease is recorded; vitals normal and LVEF 60% on 2026-03-04 (pre-anthracycline).",
      evidence: [{ quote: "ECHO 03/04/2026: LVEF 60%, normal LV size and function.", source: "Echo 2026-03-04" }],
    },
    {
      id: "NCT04434040-exc-12",
      status: "pass",
      confidence: "medium",
      rationale: "No pneumonitis or fibrotic lung disease is recorded; no cough and lungs clear. The last chest CT (2026-07-09) predates radiation, so the screening CT must confirm no active pneumonitis.",
      evidence: [
        { quote: "No new lumps, bone pain, HA or cough.", source: "Clinic note 2026-09-22" },
        { quote: "Lungs clear.", source: "Exam 2026-09-22" },
      ],
      actionNeeded: "Screening chest CT must show no active pneumonitis",
    },
    {
      id: "NCT04434040-exc-13",
      status: "pass",
      rationale: "Her only autoimmune condition is hypothyroidism on thyroid replacement, which is explicitly excepted; no autoimmune disease before pembrolizumab.",
      evidence: [
        { quote: "irAE hypothyroidism G2 -> levothyroxine, TSH now nl.", source: "Clinic note 2026-09-22" },
        { quote: "No autoimmune dz prior to pembro.", source: "PMH" },
      ],
    },
    {
      id: "NCT04434040-exc-14",
      status: "pass",
      confidence: "medium",
      rationale: "No gastrointestinal disease, malabsorption or bowel surgery is recorded and the abdominal exam is benign.",
      evidence: [{ quote: "Abd benign.", source: "Exam 2026-09-22" }],
    },
    {
      id: "NCT04434040-exc-15",
      status: "unknown",
      confidence: "low",
      rationale: "No ECG or QTcF is in the record; she takes sertraline.",
      evidence: [],
      actionNeeded: "Obtain screening ECG; QTcF must be ≤ 480 ms",
    },
    {
      id: "NCT04434040-exc-16",
      status: "unknown",
      confidence: "low",
      rationale: "HIV, hepatitis B surface antigen and HCV RNA results are not in the record.",
      evidence: [],
      actionNeeded: "Obtain HIV antibody, HBsAg and HCV antibody with reflex HCV RNA; all must be negative",
    },
    {
      id: "NCT04434040-exc-17",
      status: "pass",
      rationale: "The 11/2025 right breast cancer is her first; the left breast was benign at risk-reducing mastectomy.",
      evidence: [{ quote: "C. Left breast: benign breast tissue, no atypia, no carcinoma.", source: "Pathology 2026-06-17" }],
    },
    {
      id: "NCT04434040-exc-18",
      status: "pass",
      confidence: "medium",
      rationale: "No malignancy other than breast cancer is recorded in her history.",
      evidence: [],
    },
    {
      id: "NCT04434040-exc-19",
      status: "pass",
      rationale: "Her medications (pembrolizumab, levothyroxine, sertraline, levonorgestrel IUD) include no strong UGT1A1 inhibitor or inducer.",
      evidence: [{ quote: "sertraline 50 mg PO daily", source: "Medications" }],
    },
    {
      id: "NCT04434040-exc-20",
      status: "unknown",
      confidence: "low",
      rationale: "Vaccination history is not documented in the record.",
      evidence: [],
      actionNeeded: "Confirm no live attenuated vaccine within 4 weeks before day 1 and none planned on treatment",
    },
    {
      id: "NCT04434040-exc-21",
      status: "pass",
      rationale: "NKDA, and she is tolerating pembrolizumab, a humanized antibody produced in CHO cells, without reaction.",
      evidence: [
        { quote: "ALLERGIES: NKDA", source: "Allergies" },
        { quote: "pembrolizumab 200 mg IV q3 weeks (adjuvant, C4 of 9)", source: "Medications" },
      ],
    },
    {
      id: "NCT04434040-exc-22",
      status: "pass",
      rationale: "No corticosteroids or other immunosuppressants on her medication list, and none anticipated.",
      evidence: [{ quote: "levothyroxine 75 mcg PO daily", source: "Medications" }],
    },
    {
      id: "NCT04434040-exc-23",
      status: "pass",
      rationale: "Not pregnant or breastfeeding; serum hCG negative on 2026-09-19.",
      evidence: [
        { quote: "Not pregnant, not breastfeeding.", source: "Clinic note 2026-09-22" },
        { quote: "hCG (serum) negative", source: "Labs 2026-09-19" },
      ],
    },
  ],
);
