import { demoMatch } from "../../match-helpers";

export default demoMatch(
  "NCT06324240",
  "Excluded: vaccine tissue is taken at mastectomy (done 2026-06-11); on adjuvant pembrolizumab",
  "As a KEYNOTE-522 patient with residual disease she would be routed to Cohort B, but that schedule gives the vaccine before the first three adjuvant pembrolizumab cycles and she is already at cycle 4, leaving only Cohort A after pembrolizumab ends (~2027-02 at the earliest, with olaparib deferred to the Week 12 draw). The deciding problem is the vaccine itself: it is made from ≥ 1 g of tumor collected at the mastectomy, which was done on 2026-06-11 before referral, and her residual tumor was a single 1.2 cm focus with treatment effect now in archival pathology. Only confirmation from the study team that suitable banked tissue exists would change this.",
  [
    {
      id: "NCT06324240-inc-1",
      status: "pass",
      confidence: "low",
      rationale: "Written consent and HIPAA authorization are obtained at screening.",
      evidence: [],
    },
    {
      id: "NCT06324240-inc-2",
      status: "pass",
      rationale: "She is 39 years old (born 1987).",
      evidence: [{ quote: "DOB: 1987 (39 yo F)", source: "Clinic note 2026-09-22" }],
    },
    {
      id: "NCT06324240-inc-3",
      status: "pass",
      rationale: "ECOG 0 on 2026-09-22; would need re-documenting within 14 days of tissue consent.",
      evidence: [{ quote: "EXAM: ECOG 0.", source: "Clinic note 2026-09-22" }],
    },
    {
      id: "NCT06324240-inc-4",
      status: "pass",
      confidence: "medium",
      rationale: "ANC 1.9 × 10⁹/L (1,900/µL) on 2026-09-19 exceeds 1,500 but was called borderline, and labs must be repeated within 14 days of the first vaccine.",
      evidence: [
        { quote: "WBC 3.4 (L) | ANC 1.9 | Hgb 12.4 | Plt 180", source: "Labs 2026-09-19" },
        { quote: "ANC 1.9 today, borderline, recheck.", source: "Clinic note 2026-09-22" },
      ],
      actionNeeded: "Repeat CBC within 14 days of the first vaccine; ANC > 1,500/µL",
    },
    {
      id: "NCT06324240-inc-5",
      status: "unknown",
      confidence: "medium",
      rationale: "No lymphocyte count is reported; WBC 3.4 with ANC 1.9 leaves at most 1.5 × 10⁹/L for all other white cells.",
      evidence: [{ quote: "WBC 3.4 (L) | ANC 1.9 | Hgb 12.4 | Plt 180", source: "Labs 2026-09-19" }],
      actionNeeded: "Obtain CBC with differential within 14 days of the first vaccine; ALC ≥ 600/µL",
    },
    {
      id: "NCT06324240-inc-6",
      status: "pass",
      rationale: "Platelets 180 × 10⁹/L on 2026-09-19; to be repeated within 14 days of vaccination.",
      evidence: [{ quote: "WBC 3.4 (L) | ANC 1.9 | Hgb 12.4 | Plt 180", source: "Labs 2026-09-19" }],
    },
    {
      id: "NCT06324240-inc-7",
      status: "pass",
      rationale: "Hemoglobin 12.4 g/dL on 2026-09-19.",
      evidence: [{ quote: "WBC 3.4 (L) | ANC 1.9 | Hgb 12.4 | Plt 180", source: "Labs 2026-09-19" }],
    },
    {
      id: "NCT06324240-inc-8",
      status: "pass",
      rationale: "Serum creatinine 0.7 mg/dL on 2026-09-19, within normal limits.",
      evidence: [{ quote: "Cr 0.7", source: "Labs 2026-09-19" }],
    },
    {
      id: "NCT06324240-inc-9",
      status: "pass",
      rationale: "Total bilirubin 0.5 mg/dL on 2026-09-19, within normal limits.",
      evidence: [{ quote: "AST 22 | ALT 25 | T bili 0.5 | Alk phos 71", source: "Labs 2026-09-19" }],
    },
    {
      id: "NCT06324240-inc-10",
      status: "pass",
      rationale: "AST 22 and ALT 25 U/L on 2026-09-19, within normal limits; no liver metastases.",
      evidence: [{ quote: "AST 22 | ALT 25 | T bili 0.5 | Alk phos 71", source: "Labs 2026-09-19" }],
    },
    {
      id: "NCT06324240-inc-11",
      status: "pass",
      rationale: "Bilirubin 0.5 mg/dL on 2026-09-19, well under 1.5 × ULN.",
      evidence: [{ quote: "AST 22 | ALT 25 | T bili 0.5 | Alk phos 71", source: "Labs 2026-09-19" }],
    },
    {
      id: "NCT06324240-inc-12",
      status: "unknown",
      confidence: "medium",
      rationale: "No PT/INR is reported; she is not on anticoagulation.",
      evidence: [],
      actionNeeded: "Obtain PT/INR within 14 days of the first vaccine; ≤ 1.5 × ULN",
    },
    {
      id: "NCT06324240-inc-13",
      status: "unknown",
      confidence: "medium",
      rationale: "No aPTT is reported; she is not on anticoagulation.",
      evidence: [],
      actionNeeded: "Obtain aPTT within 14 days of the first vaccine; ≤ 1.5 × ULN",
    },
    {
      id: "NCT06324240-inc-14",
      status: "pass",
      rationale: "ER 0%, PR 0% and HER2 IHC 0 on the core biopsy and again on the residual tumor.",
      evidence: [{ quote: "Receptors repeated on residual tumor: ER 0%, PR 0%, HER2 IHC 0 - triple negative, concordant with core bx.", source: "Pathology 2026-06-17" }],
    },
    {
      id: "NCT06324240-inc-15",
      status: "not-applicable",
      rationale: "Defines the metastatic/inoperable group; she has resected early-stage disease with no metastases (CT CAP 2026-07-09) and falls under the early-stage criteria.",
      evidence: [{ quote: "No evidence of metastatic disease in the chest, abdomen or pelvis.", source: "CT CAP 2026-07-09" }],
    },
    {
      id: "NCT06324240-inc-16",
      status: "not-applicable",
      rationale: "Lines-of-therapy limit for the metastatic/advanced group; she has had no metastatic-setting therapy. The washouts it repeats are assessed under exc-4.",
      evidence: [],
    },
    {
      id: "NCT06324240-inc-17",
      status: "pass",
      rationale: "Prior checkpoint inhibitor is permitted; her PD-L1 CPS is 8 (below 10) and she has received pembrolizumab regardless.",
      evidence: [{ quote: "PD-L1 (22C3) CPS 8.", source: "Core biopsy 11/2025" }],
    },
    {
      id: "NCT06324240-inc-18",
      status: "not-applicable",
      rationale: "Cohort assignment rules for metastatic or inoperable patients; she has early-stage disease.",
      evidence: [],
    },
    {
      id: "NCT06324240-inc-19",
      status: "pass",
      rationale: "Early-stage TNBC: clinical stage IIB (cT2 cN1 M0) at diagnosis in 11/2025.",
      evidence: [{ quote: "R breast IDC grade 3, TNBC, cT2 (3.1 cm) cN1 (bx-proven axillary node) M0, stage IIB, dx 11/2025.", source: "Clinic note 2026-09-22" }],
    },
    {
      id: "NCT06324240-inc-20",
      status: "pass",
      rationale: "Disease in the breast and axilla has been resected: right mastectomy with negative margins and level I–II ALND on 2026-06-11.",
      evidence: [{ quote: "Margins negative (closest deep 4 mm).", source: "Pathology 2026-06-17" }],
    },
    {
      id: "NCT06324240-inc-21",
      status: "pass",
      rationale: "Post-mastectomy radiation was completed on 2026-08-28, 31 days ago (more than 14 days).",
      evidence: [{ quote: "PMRT 7/20/26-8/28/26, completed.", source: "Clinic note 2026-09-22" }],
    },
    {
      id: "NCT06324240-inc-22",
      status: "pass",
      confidence: "medium",
      rationale: "Capecitabine has not been started and she is leaning toward olaparib; if capecitabine were chosen, Cohort A would require deferring it until after the Week 12 draw.",
      evidence: [{ quote: "Adj olaparib vs cape: pt to decide by next visit.", source: "Clinic note 2026-09-22" }],
    },
    {
      id: "NCT06324240-inc-23",
      status: "unknown",
      confidence: "medium",
      rationale: "She has a pathogenic gBRCA1 variant with residual TNBC (meets the olaparib indication) and leans toward olaparib. Cohort A needs olaparib deferred until after the Week 12 draw; otherwise enrollment waits ≥ 28 days after a year of olaparib.",
      evidence: [
        { quote: "BRCA1 c.68_69delAG (p.Glu23ValfsTer17) - PATHOGENIC", source: "Germline panel 2025-12-15" },
        { quote: "Pt leaning olaparib but wants to hear about trials for residual disease first.", source: "Clinic note 2026-09-22" },
      ],
      actionNeeded: "Decide olaparib timing: defer until after the Week 12 immune draw (Cohort A) or enroll ≥ 28 days after the last olaparib dose",
    },
    {
      id: "NCT06324240-inc-24",
      status: "not-applicable",
      rationale: "Applies to patients treated with upfront surgery and adjuvant chemotherapy; she received neoadjuvant therapy.",
      evidence: [],
    },
    {
      id: "NCT06324240-inc-25",
      status: "pass",
      rationale: "Residual disease (ypT1c ypN1a, RCB class II) after completing the KEYNOTE-522 regimen: pembrolizumab + paclitaxel/carboplatin, then pembrolizumab + ddAC ×4.",
      evidence: [
        { quote: "Neoadj per KEYNOTE-522: pembro + weekly paclitaxel + carboplatin x12 wks (12/2025-3/2026) then pembro + ddAC x4 (3/2026-5/2026).", source: "Clinic note 2026-09-22" },
        { quote: "Residual Cancer Burden: RCB class II (RCB score 2.6)", source: "Pathology 2026-06-17" },
      ],
    },
    {
      id: "NCT06324240-inc-26",
      status: "pass",
      confidence: "medium",
      rationale: "Cohort A timing: she is on adjuvant pembrolizumab C4 of 9, with the final cycle expected ~2027-01-05, so the first vaccine could be given from ~2027-02-02. This sets a start date rather than blocking entry.",
      evidence: [{ quote: "pembrolizumab 200 mg IV q3 weeks (adjuvant, C4 of 9)", source: "Medications" }],
      actionNeeded: "Schedule the first vaccine ≥ 28 days after the final adjuvant pembrolizumab cycle",
    },
    {
      id: "NCT06324240-inc-27",
      status: "not-applicable",
      rationale: "Applies to Phase 1b Cohorts B/C. Cohort B gives the vaccine before the first three adjuvant pembrolizumab cycles; she started adjuvant pembrolizumab on 2026-07-21 and is at C4, so Cohort A is her only route.",
      evidence: [{ quote: "Adj pembro started 7/21/26 (9 cycles planned).", source: "Clinic note 2026-09-22" }],
    },
    {
      id: "NCT06324240-inc-28",
      status: "not-applicable",
      rationale: "Applies to residual disease after ddAC→paclitaxel or docetaxel-cyclophosphamide; she received the KEYNOTE-522 regimen.",
      evidence: [],
    },
    {
      id: "NCT06324240-inc-29",
      status: "fail",
      confidence: "medium",
      rationale: "Her residual tumor was a single 1.2 cm focus with treatment effect, already processed for pathology at the 2026-06-11 mastectomy; at least 1 g of tumor for vaccine manufacture is very unlikely to be obtainable.",
      evidence: [
        { quote: "residual invasive ductal carcinoma, grade 3, single focus 1.2 cm with treatment effect", source: "Pathology 2026-06-17" },
        { quote: "Archival tissue available (surgical specimen 6/2026).", source: "Clinic note 2026-09-22" },
      ],
    },
    {
      id: "NCT06324240-inc-30",
      status: "fail",
      rationale: "For early-stage patients the vaccine tissue is retrieved during the planned mastectomy; hers was done on 2026-06-11, before the trial referral on 2026-09-22, and only archival pathology tissue is documented.",
      evidence: [
        { quote: "Procedure date: 2026-06-11", source: "Pathology 2026-06-17" },
        { quote: "Trials: referred to research coordinator re: post-neoadjuvant residual disease trials. Archival tissue available (surgical specimen 6/2026).", source: "Clinic note 2026-09-22" },
      ],
    },
    {
      id: "NCT06324240-inc-31",
      status: "not-applicable",
      rationale: "Concerns tumor yield from biopsy in metastatic patients; she has early-stage disease with no metastases.",
      evidence: [],
    },
    {
      id: "NCT06324240-inc-32",
      status: "pass",
      rationale: "Germline testing has already been done: pathogenic BRCA1 variant reported 2025-12-15.",
      evidence: [{ quote: "BRCA1 c.68_69delAG (p.Glu23ValfsTer17) - PATHOGENIC", source: "Germline panel 2025-12-15" }],
    },
    {
      id: "NCT06324240-inc-33",
      status: "pass",
      confidence: "low",
      rationale: "Ability and willingness to complete the study schedule are confirmed at screening.",
      evidence: [],
    },
    {
      id: "NCT06324240-inc-34",
      status: "pass",
      confidence: "low",
      rationale: "Written informed consent is obtained at screening; she is actively seeking residual-disease trials.",
      evidence: [],
    },
    {
      id: "NCT06324240-exc-1",
      status: "fail",
      confidence: "medium",
      rationale: "The only tumor available is the archived 1.2 cm residual focus with treatment effect from the 2026-06-11 mastectomy, which would yield less than the 1 g needed for vaccine production.",
      evidence: [{ quote: "residual invasive ductal carcinoma, grade 3, single focus 1.2 cm with treatment effect", source: "Pathology 2026-06-17" }],
    },
    {
      id: "NCT06324240-exc-2",
      status: "pass",
      confidence: "medium",
      rationale: "No cardiovascular disease, arrhythmia medication or infection is recorded; vitals normal and LVEF 60% (2026-03-04).",
      evidence: [{ quote: "Vitals wnl.", source: "Exam 2026-09-22" }],
    },
    {
      id: "NCT06324240-exc-3",
      status: "pass",
      confidence: "medium",
      rationale: "No malignancy other than the current breast cancer is recorded in her history.",
      evidence: [],
    },
    {
      id: "NCT06324240-exc-4",
      status: "fail",
      rationale: "She is on adjuvant pembrolizumab (C4 of 9, 2026-09-22) with olaparib or capecitabine planned; this clears only ≥ 28 days after the final cycle (~2027-01-05) and if olaparib is deferred. Chemotherapy ended 5/2026 and radiation 2026-08-28, both outside their washouts.",
      evidence: [
        { quote: "Currently NED. Adj pembro C4 of 9 today.", source: "Clinic note 2026-09-22" },
        { quote: "Adj olaparib vs cape: pt to decide by next visit.", source: "Clinic note 2026-09-22" },
      ],
    },
    {
      id: "NCT06324240-exc-5",
      status: "pass",
      confidence: "medium",
      rationale: "Not pregnant or breastfeeding (serum hCG negative 2026-09-19) and using a levonorgestrel IUD; plans to conceive are confirmed at screening.",
      evidence: [
        { quote: "Not pregnant, not breastfeeding.", source: "Clinic note 2026-09-22" },
        { quote: "hCG (serum) negative", source: "Labs 2026-09-19" },
      ],
    },
    {
      id: "NCT06324240-exc-6",
      status: "pass",
      confidence: "medium",
      rationale: "No history of tuberculosis is recorded.",
      evidence: [],
    },
    {
      id: "NCT06324240-exc-7",
      status: "pass",
      confidence: "medium",
      rationale: "No organ transplant is recorded in her history.",
      evidence: [],
    },
    {
      id: "NCT06324240-exc-8",
      status: "pass",
      confidence: "medium",
      rationale: "No known CNS metastases: she has no headache or neurologic symptoms, though no brain imaging has been done.",
      evidence: [{ quote: "No new lumps, bone pain, HA or cough.", source: "Clinic note 2026-09-22" }],
    },
    {
      id: "NCT06324240-exc-9",
      status: "pass",
      confidence: "medium",
      rationale: "No immunodeficiency is recorded and her medications (pembrolizumab, levothyroxine, sertraline, IUD) include no steroids or immunosuppressants.",
      evidence: [{ quote: "levothyroxine 75 mcg PO daily", source: "Medications" }],
    },
    {
      id: "NCT06324240-exc-10",
      status: "pass",
      rationale: "Her immune hypothyroidism is treated with levothyroxine, which is replacement therapy and not counted; no autoimmune disease before pembrolizumab.",
      evidence: [
        { quote: "irAE hypothyroidism G2 -> levothyroxine, TSH now nl.", source: "Clinic note 2026-09-22" },
        { quote: "No autoimmune dz prior to pembro.", source: "PMH" },
      ],
    },
    {
      id: "NCT06324240-exc-11",
      status: "pass",
      confidence: "medium",
      rationale: "No pneumonitis is recorded; no cough, lungs clear, and the 2026-07-09 chest CT showed only post-surgical changes.",
      evidence: [{ quote: "Lungs clear.", source: "Exam 2026-09-22" }],
    },
    {
      id: "NCT06324240-exc-12",
      status: "pass",
      rationale: "No grade 3–4 toxicity is recorded: neuropathy peaked at grade 2 (now grade 1) and immune hypothyroidism at grade 2.",
      evidence: [{ quote: "Tox: G2 PN on paclitaxel, now G1 (toes)", source: "Clinic note 2026-09-22" }],
    },
    {
      id: "NCT06324240-exc-13",
      status: "not-applicable",
      rationale: "Applies to the Phase 1b combination cohorts; she would enter Cohort A. Her only irAE was grade 2 hypothyroidism, controlled on levothyroxine.",
      evidence: [{ quote: "irAE hypothyroidism G2 - levothyroxine 75 mcg, TSH 3.1, continue.", source: "Clinic note 2026-09-22" }],
    },
  ],
);
