import { demoMatch } from "../../match-helpers";

export default demoMatch(
  "NCT07407920",
  "Excluded: residual disease (RCB-II), not pCR, and 4 adjuvant pembrolizumab cycles already given",
  "This de-escalation trial is only for patients who reached a pathological complete response and are ctDNA-negative. Surgery on 6/11/26 showed residual invasive disease (ypT1c ypN1a, RCB class II), so she cannot enter the TNBC cohort, and with cycle 4 of adjuvant pembrolizumab given on 9/22/26 she has also reached the 4-cycle exclusion. Nothing pending would change this; post-neoadjuvant residual-disease trials are the relevant route for her.",
  [
    {
      id: "NCT07407920-inc-1",
      status: "not-applicable",
      rationale: "Applies to the HER2-positive cohort only; her tumor is HER2 IHC 0 on both the core biopsy and the residual tumor, so she would be screened for the TNBC cohort.",
      evidence: [{ quote: "ER 0%, PR 0%, HER2 IHC 0 - triple negative, concordant with core bx.", source: "Pathology 2026-06-17" }],
    },
    {
      id: "NCT07407920-inc-2",
      status: "pass",
      rationale: "Biopsy-proven invasive TNBC: core biopsy 11/2025 ER 0%, PR 0%, HER2 IHC 0, confirmed on the residual tumor in 6/2026, well under the 10% ER/PR cut-off.",
      evidence: [
        { quote: "IDC, grade 3 (Nottingham 9/9), ER 0%, PR 0%, HER2 IHC 0 (negative), Ki-67 75%.", source: "Core biopsy 11/2025" },
        { quote: "ER 0%, PR 0%, HER2 IHC 0 - triple negative, concordant with core bx.", source: "Pathology 2026-06-17" },
      ],
    },
    {
      id: "NCT07407920-inc-3",
      status: "pass",
      rationale: "Invasive ductal carcinoma, grade 3 (Nottingham 9/9); any grade and histological subtype is accepted.",
      evidence: [{ quote: "IDC, grade 3 (Nottingham 9/9)", source: "Core biopsy 11/2025" }],
    },
    {
      id: "NCT07407920-inc-4",
      status: "pass",
      rationale: "Clinical stage cT2 cN1 M0 (stage IIB, 11/2025) is within T1-4, N0-2a, M0, and post-operative CT on 7/9/26 showed no locoregional or distant disease.",
      evidence: [
        { quote: "cT2 (3.1 cm) cN1 (bx-proven axillary node) M0, stage IIB", source: "Clinic note 2026-09-22" },
        { quote: "No evidence of metastatic disease in the chest, abdomen or pelvis.", source: "CT CAP 2026-07-09" },
      ],
    },
    {
      id: "NCT07407920-inc-5",
      status: "not-applicable",
      rationale: "Applies to the HER2-positive cohort (trastuzumab/pertuzumab-based neoadjuvant therapy) only; she is HER2 IHC 0 and received the KEYNOTE-522 regimen.",
    },
    {
      id: "NCT07407920-inc-6",
      status: "fail",
      rationale: "She completed KEYNOTE-522 neoadjuvant therapy, but surgery on 6/11/26 showed residual disease (ypT1c ypN1a, RCB class II), not a pCR (ypT0/Tis ypN0).",
      evidence: [
        { quote: "Pathologic stage (AJCC 8th): ypT1c ypN1a", source: "Pathology 2026-06-17" },
        { quote: "Residual Cancer Burden: RCB class II (RCB score 2.6)", source: "Pathology 2026-06-17" },
      ],
    },
    {
      id: "NCT07407920-inc-7",
      status: "fail",
      rationale: "The surgical pathology report (6/17/26) shows a 1.2 cm focus of residual invasive carcinoma and 2 of 11 positive axillary nodes, so the pCR requirement is not met.",
      evidence: [
        { quote: "residual invasive ductal carcinoma, grade 3, single focus 1.2 cm with treatment effect", source: "Pathology 2026-06-17" },
        { quote: "2 of 11 lymph nodes positive for metastatic carcinoma with treatment effect", source: "Pathology 2026-06-17" },
      ],
    },
    {
      id: "NCT07407920-inc-8",
      status: "unknown",
      confidence: "medium",
      rationale: "Archival tissue is documented only for the 6/2026 surgical specimen; whether the 11/2025 core biopsy block is available and adequate for the Personalis assay is not recorded.",
      evidence: [{ quote: "Archival tissue available (surgical specimen 6/2026).", source: "Clinic note 2026-09-22" }],
      actionNeeded: "Confirm the 11/2025 core biopsy block is retrievable and adequate for the Personalis tumor-informed assay",
    },
    {
      id: "NCT07407920-inc-9",
      status: "pass",
      rationale: "She is 39 years old.",
      evidence: [{ quote: "39 yo premenopausal F", source: "Clinic note 2026-09-22" }],
    },
    {
      id: "NCT07407920-inc-10",
      status: "pass",
      rationale: "ECOG 0 at the 9/22/26 visit, within the ECOG ≤ 2 requirement.",
      evidence: [{ quote: "EXAM: ECOG 0.", source: "Clinic note 2026-09-22" }],
    },
    {
      id: "NCT07407920-inc-11",
      status: "pass",
      rationale: "ANC 1.9 × 10⁹/L (1,900/mcL) on 9/19/26, above the 1,000/mcL threshold.",
      evidence: [{ quote: "WBC 3.4 (L) | ANC 1.9 | Hgb 12.4 | Plt 180", source: "Labs 2026-09-19" }],
    },
    {
      id: "NCT07407920-inc-12",
      status: "pass",
      rationale: "Hemoglobin 12.4 g/dL on 9/19/26, above the 9.0 g/dL threshold.",
      evidence: [{ quote: "WBC 3.4 (L) | ANC 1.9 | Hgb 12.4 | Plt 180", source: "Labs 2026-09-19" }],
    },
    {
      id: "NCT07407920-inc-13",
      status: "pass",
      rationale: "Platelets 180 × 10⁹/L (180,000/mcL) on 9/19/26, above the 100,000/mcL threshold.",
      evidence: [{ quote: "WBC 3.4 (L) | ANC 1.9 | Hgb 12.4 | Plt 180", source: "Labs 2026-09-19" }],
    },
    {
      id: "NCT07407920-inc-14",
      status: "pass",
      rationale: "Total bilirubin 0.5 mg/dL on 9/19/26, well under 1.5 × ULN; no Gilbert's syndrome is documented.",
      evidence: [{ quote: "AST 22 | ALT 25 | T bili 0.5 | Alk phos 71", source: "Labs 2026-09-19" }],
    },
    {
      id: "NCT07407920-inc-15",
      status: "pass",
      rationale: "AST 22 and ALT 25 U/L on 9/19/26, within normal limits and far below 3 × ULN.",
      evidence: [{ quote: "AST 22 | ALT 25 | T bili 0.5 | Alk phos 71", source: "Labs 2026-09-19" }],
    },
    {
      id: "NCT07407920-inc-16",
      status: "pass",
      rationale: "Creatinine 0.7 mg/dL on 9/19/26, below the 1.5 mg/dL limit.",
      evidence: [{ quote: "Cr 0.7", source: "Labs 2026-09-19" }],
    },
    {
      id: "NCT07407920-inc-17",
      status: "unknown",
      confidence: "medium",
      rationale: "Hepatitis B status is not documented; the criterion only restricts patients with chronic HBV, which cannot be ruled out without serology.",
      actionNeeded: "Obtain HBsAg and anti-HBc; if chronic HBV, viral load must be undetectable on suppressive therapy",
    },
    {
      id: "NCT07407920-inc-18",
      status: "unknown",
      confidence: "medium",
      rationale: "No hepatitis C history or serology is recorded.",
      actionNeeded: "Obtain HCV antibody (HCV RNA if positive); prior HCV must be cured or viral load undetectable on treatment",
    },
    {
      id: "NCT07407920-inc-19",
      status: "unknown",
      confidence: "medium",
      rationale: "HIV status is not documented; no HIV diagnosis is on the problem list and no antiretrovirals are on the medication list.",
      actionNeeded: "Confirm HIV status; if positive, viral load must have been undetectable on antiretroviral therapy within 6 months",
    },
    {
      id: "NCT07407920-inc-20",
      status: "pass",
      rationale: "She is premenopausal; both pre- and postmenopausal women are eligible.",
      evidence: [{ quote: "39 yo premenopausal F, G2P2, LNG-IUD in place", source: "Clinic note 2026-09-22" }],
    },
    {
      id: "NCT07407920-inc-21",
      status: "pass",
      confidence: "low",
      rationale: "Ability and willingness to consent is confirmed at screening; she has asked to hear about trial options.",
      evidence: [{ quote: "wants to hear about trials for residual disease first", source: "Clinic note 2026-09-22" }],
    },
    {
      id: "NCT07407920-exc-1",
      status: "pass",
      rationale: "Clinical nodal stage was cN1 (single biopsy-proven axillary node), not cN2b or cN3.",
      evidence: [{ quote: "cT2 (3.1 cm) cN1 (bx-proven axillary node) M0", source: "Clinic note 2026-09-22" }],
    },
    {
      id: "NCT07407920-exc-2",
      status: "pass",
      confidence: "medium",
      rationale: "No other cancer is recorded in her history, and the risk-reducing left mastectomy showed benign tissue without carcinoma.",
      evidence: [{ quote: "C. Left breast: benign breast tissue, no atypia, no carcinoma.", source: "Pathology 2026-06-17" }],
    },
    {
      id: "NCT07407920-exc-3",
      status: "pass",
      confidence: "medium",
      rationale: "Her only anticancer agent is standard adjuvant pembrolizumab; no investigational agent appears on the medication list.",
      evidence: [{ quote: "pembrolizumab 200 mg IV q3 weeks (adjuvant, C4 of 9)", source: "Medications" }],
    },
    {
      id: "NCT07407920-exc-4",
      status: "pass",
      rationale: "CT chest/abdomen/pelvis on 7/9/26 showed no metastatic disease; baseline CT and bone scan in 11/2025 were also negative.",
      evidence: [
        { quote: "No evidence of metastatic disease in the chest, abdomen or pelvis.", source: "CT CAP 2026-07-09" },
        { quote: "Baseline staging 11/2025: CT CAP + bone scan without distant disease.", source: "Imaging" },
      ],
    },
    {
      id: "NCT07407920-exc-5",
      status: "pass",
      confidence: "medium",
      rationale: "No active infection or cardiac disease is documented; immune-related hypothyroidism is controlled on levothyroxine (TSH 3.1) and LVEF was 60% in 3/2026.",
      evidence: [{ quote: "levothyroxine 75 mcg, TSH 3.1, continue.", source: "Clinic note 2026-09-22" }],
    },
    {
      id: "NCT07407920-exc-6",
      status: "pass",
      confidence: "medium",
      rationale: "Anxiety is stable on sertraline 50 mg and nothing in the record suggests a barrier to study compliance.",
      evidence: [{ quote: "Anxiety - sertraline 50 mg, stable.", source: "Clinic note 2026-09-22" }],
    },
    {
      id: "NCT07407920-exc-7",
      status: "pass",
      confidence: "medium",
      rationale: "No blood transfusion is recorded and hemoglobin was 12.4 g/dL on 9/19/26, so a recent transfusion is unlikely.",
      evidence: [{ quote: "WBC 3.4 (L) | ANC 1.9 | Hgb 12.4 | Plt 180", source: "Labs 2026-09-19" }],
      actionNeeded: "Confirm no transfusion in the 2 weeks before the ctDNA draw",
    },
    {
      id: "NCT07407920-exc-8",
      status: "fail",
      rationale: "Adjuvant pembrolizumab began 7/21/26 and cycle 4 of 9 was given on 9/22/26, so she has received 4 cycles, which meets the exclusion threshold.",
      evidence: [
        { quote: "Adj pembro started 7/21/26 (9 cycles planned).", source: "Clinic note 2026-09-22" },
        { quote: "Adj pembro C4 of 9 today.", source: "Clinic note 2026-09-22" },
      ],
    },
    {
      id: "NCT07407920-exc-9",
      status: "pass",
      rationale: "Serum hCG was negative on 9/19/26 and the 9/22/26 note records that she is not pregnant.",
      evidence: [
        { quote: "hCG (serum) negative", source: "Labs 2026-09-19" },
        { quote: "Not pregnant, not breastfeeding.", source: "Clinic note 2026-09-22" },
      ],
    },
  ],
);
