import { demoMatch } from "../../match-helpers";

export default demoMatch(
  "NCT06393374",
  "Excluded: gBRCA1 carrier eligible for adjuvant olaparib; 16-week post-surgery window closes 10/1",
  "The trial's backbone fits her — KEYNOTE-522 with residual disease (RCB-II), NED, radiation complete — but it excludes known germline BRCA carriers who are eligible for adjuvant olaparib, which describes her exactly (BRCA1 c.68_69delAG, non-pCR TNBC). Independently, randomization must occur within 16 weeks of surgery (2026-06-11), a window that closes on 2026-10-01, three days from now. Whether the four adjuvant pembrolizumab cycles already given would be accepted is unclear from the criteria, but this is moot given the BRCA exclusion.",
  [
    {
      id: "NCT06393374-inc-1",
      status: "pass",
      confidence: "medium",
      rationale: "Locally TNBC on both the core biopsy and the residual tumor (ER 0%, PR 0%, HER2 IHC 0); central confirmation has not yet been done but discordance is unlikely.",
      evidence: [{ quote: "Receptors repeated on residual tumor: ER 0%, PR 0%, HER2 IHC 0 - triple negative, concordant with core bx.", source: "Pathology 2026-06-17" }],
      actionNeeded: "Submit tissue for central TNBC confirmation",
    },
    {
      id: "NCT06393374-inc-2",
      status: "pass",
      rationale: "No locoregional or distant relapse: CT CAP 2026-07-09 without metastases and no chest wall nodularity or adenopathy on 2026-09-22.",
      evidence: [
        { quote: "No evidence of metastatic disease in the chest, abdomen or pelvis.", source: "CT CAP 2026-07-09" },
        { quote: "Mastectomy scars well healed, no chest wall nodularity.", source: "Exam 2026-09-22" },
      ],
    },
    {
      id: "NCT06393374-inc-3",
      status: "pass",
      rationale: "Completed neoadjuvant KEYNOTE-522 (pembrolizumab + paclitaxel/carboplatin, then pembrolizumab + ddAC) followed by surgery on 2026-06-11.",
      evidence: [{ quote: "Neoadj per KEYNOTE-522: pembro + weekly paclitaxel + carboplatin x12 wks (12/2025-3/2026) then pembro + ddAC x4 (3/2026-5/2026).", source: "Clinic note 2026-09-22" }],
    },
    {
      id: "NCT06393374-inc-4",
      status: "pass",
      rationale: "Right mastectomy with negative margins (closest 4 mm) and level I–II axillary dissection removed all evident disease; scars are well healed.",
      evidence: [
        { quote: "Margins negative (closest deep 4 mm).", source: "Pathology 2026-06-17" },
        { quote: "Mastectomy scars well healed, no chest wall nodularity.", source: "Exam 2026-09-22" },
      ],
    },
    {
      id: "NCT06393374-inc-5",
      status: "pass",
      rationale: "Non-pCR: 1.2 cm residual invasive carcinoma and 2 of 11 positive nodes (ypT1c ypN1a, RCB class II).",
      evidence: [
        { quote: "Pathologic stage (AJCC 8th): ypT1c ypN1a", source: "Pathology 2026-06-17" },
        { quote: "Residual Cancer Burden: RCB class II (RCB score 2.6)", source: "Pathology 2026-06-17" },
      ],
    },
    {
      id: "NCT06393374-inc-6",
      status: "pass",
      rationale: "She is tolerating adjuvant pembrolizumab (cycle 4 of 9 on 2026-09-22) and her grade 2 immune hypothyroidism is controlled on levothyroxine.",
      evidence: [
        { quote: "pembrolizumab 200 mg IV q3 weeks (adjuvant, C4 of 9)", source: "Medications" },
        { quote: "irAE hypothyroidism G2 -> levothyroxine, TSH now nl.", source: "Clinic note 2026-09-22" },
      ],
    },
    {
      id: "NCT06393374-inc-7",
      status: "fail",
      confidence: "medium",
      rationale: "Surgery was on 2026-06-11, so the 16-week window ends 2026-10-01, three days away; central TNBC confirmation and TROP2 tissue submission could not realistically be completed before then.",
      evidence: [{ quote: "Procedure date: 2026-06-11", source: "Pathology 2026-06-17" }],
    },
    {
      id: "NCT06393374-inc-8",
      status: "pass",
      rationale: "Post-mastectomy radiation was completed on 2026-08-28; only mild residual chest wall erythema remains and fatigue is improving.",
      evidence: [
        { quote: "PMRT 7/20/26-8/28/26, completed.", source: "Clinic note 2026-09-22" },
        { quote: "R chest wall mild residual erythma.", source: "Clinic note 2026-09-22" },
      ],
    },
    {
      id: "NCT06393374-inc-9",
      status: "pass",
      confidence: "medium",
      rationale: "Archival tissue from the 2026-06-11 surgical resection is available for central TROP2 testing; it has not yet been submitted.",
      evidence: [{ quote: "Archival tissue available (surgical specimen 6/2026).", source: "Clinic note 2026-09-22" }],
      actionNeeded: "Confirm the surgical block can be released for central TROP2 testing",
    },
    {
      id: "NCT06393374-inc-10",
      status: "not-applicable",
      rationale: "Applies to participants capable of producing sperm; she is female.",
      evidence: [],
    },
    {
      id: "NCT06393374-inc-11",
      status: "pass",
      rationale: "Not pregnant or breastfeeding (serum hCG negative 2026-09-19); of childbearing potential with a levonorgestrel IUD, a highly effective method.",
      evidence: [
        { quote: "Not pregnant, not breastfeeding.", source: "Clinic note 2026-09-22" },
        { quote: "levonorgestrel IUD (placed 2023)", source: "Medications" },
      ],
    },
    {
      id: "NCT06393374-inc-12",
      status: "pass",
      confidence: "medium",
      rationale: "Neuropathy is grade 1; immune hypothyroidism (grade 2) is stable on levothyroxine with normal TSH, which is usually accepted as baseline for endocrinopathies on replacement.",
      evidence: [
        { quote: "PN stable G1, no functional limitation.", source: "Clinic note 2026-09-22" },
        { quote: "TSH 3.1 | free T4 1.1", source: "Labs 2026-09-19" },
      ],
      actionNeeded: "Confirm hypothyroidism controlled on levothyroxine is accepted as baseline",
    },
    {
      id: "NCT06393374-inc-13",
      status: "pass",
      confidence: "medium",
      rationale: "Applies only to people living with HIV; no HIV infection is recorded.",
      evidence: [],
    },
    {
      id: "NCT06393374-inc-14",
      status: "pass",
      rationale: "ECOG 0 on 2026-09-22; would need re-documenting within 7 days of the first dose.",
      evidence: [{ quote: "EXAM: ECOG 0.", source: "Clinic note 2026-09-22" }],
    },
    {
      id: "NCT06393374-inc-15",
      status: "pass",
      confidence: "medium",
      rationale: "Applies only to HBsAg-positive participants; no hepatitis B is recorded and LFTs are normal.",
      evidence: [{ quote: "AST 22 | ALT 25 | T bili 0.5 | Alk phos 71", source: "Labs 2026-09-19" }],
    },
    {
      id: "NCT06393374-exc-1",
      status: "fail",
      rationale: "She carries a germline pathogenic BRCA1 variant and, with TNBC and residual disease after neoadjuvant chemotherapy, meets the approved indication for adjuvant olaparib, which is under active discussion.",
      evidence: [
        { quote: "BRCA1 c.68_69delAG (p.Glu23ValfsTer17) - PATHOGENIC", source: "Germline panel 2025-12-15" },
        { quote: "Discussed adj olaparib x1 yr (OlympiA) vs capecitabine (CREATE-X) for residual dz w/ gBRCA1.", source: "Clinic note 2026-09-22" },
      ],
    },
    {
      id: "NCT06393374-exc-2",
      status: "pass",
      rationale: "Peripheral neuropathy is grade 1 (toes), stable without functional limitation.",
      evidence: [{ quote: "PN stable G1, no functional limitation.", source: "Clinic note 2026-09-22" }],
    },
    {
      id: "NCT06393374-exc-3",
      status: "pass",
      confidence: "medium",
      rationale: "No dry eye, Meibomian gland, blepharitis or corneal disease appears in her history.",
      evidence: [],
      actionNeeded: "Confirm no significant ocular surface disease at screening",
    },
    {
      id: "NCT06393374-exc-4",
      status: "pass",
      confidence: "medium",
      rationale: "No inflammatory bowel disease or chronic diarrhea is recorded and the abdominal exam is benign.",
      evidence: [{ quote: "Abd benign.", source: "Exam 2026-09-22" }],
    },
    {
      id: "NCT06393374-exc-5",
      status: "unknown",
      confidence: "medium",
      rationale: "No cardiovascular or cerebrovascular disease is recorded (LVEF 60% pre-anthracycline, vitals normal), but no ECG or QTcF is on file and she takes sertraline.",
      evidence: [{ quote: "ECHO 03/04/2026: LVEF 60%, normal LV size and function.", source: "Echo 2026-03-04" }],
      actionNeeded: "Obtain ECG; QTcF must be ≤ 480 ms",
    },
    {
      id: "NCT06393374-exc-6",
      status: "pass",
      rationale: "No TROP2-directed or topoisomerase I-containing ADC: her systemic therapy has been KEYNOTE-522 chemotherapy and pembrolizumab only.",
      evidence: [{ quote: "Neoadj per KEYNOTE-522", source: "Clinic note 2026-09-22" }],
    },
    {
      id: "NCT06393374-exc-7",
      status: "unknown",
      confidence: "medium",
      rationale: "No adjuvant chemotherapy or PARP inhibitor has been given (the A/P paclitaxel/carboplatin line is a stale copy-forward), but she has had 4 cycles of adjuvant pembrolizumab, which the text lists while inc-6 expects pembrolizumab to continue.",
      evidence: [{ quote: "Adj pembro started 7/21/26 (9 cycles planned).", source: "Clinic note 2026-09-22" }],
      actionNeeded: "Confirm with the sponsor whether adjuvant pembrolizumab started before randomization is permitted",
    },
    {
      id: "NCT06393374-exc-8",
      status: "pass",
      rationale: "Her medications (pembrolizumab, levothyroxine, sertraline, levonorgestrel IUD) include no strong CYP3A4 inducer or inhibitor.",
      evidence: [{ quote: "sertraline 50 mg PO daily", source: "Medications" }],
    },
    {
      id: "NCT06393374-exc-9",
      status: "pass",
      confidence: "medium",
      rationale: "Her only checkpoint inhibitor is pembrolizumab, given neoadjuvantly per KEYNOTE-522 (the stated exception) and continued adjuvantly (see exc-7).",
      evidence: [{ quote: "Neoadj per KEYNOTE-522", source: "Clinic note 2026-09-22" }],
    },
    {
      id: "NCT06393374-exc-10",
      status: "unknown",
      confidence: "medium",
      rationale: "Neoadjuvant chemotherapy ended in 5/2026, but adjuvant pembrolizumab was given on 2026-09-22, within 4 weeks; whether ongoing pembrolizumab counts here is unclear given inc-6.",
      evidence: [{ quote: "Currently NED. Adj pembro C4 of 9 today.", source: "Clinic note 2026-09-22" }],
      actionNeeded: "Confirm with the sponsor that ongoing adjuvant pembrolizumab is exempt from the 4-week washout",
    },
    {
      id: "NCT06393374-exc-11",
      status: "pass",
      rationale: "Radiation finished on 2026-08-28, 31 days ago (more than 3 weeks), and no steroids are being taken for radiation toxicity.",
      evidence: [{ quote: "PMRT 7/20/26-8/28/26, completed.", source: "Clinic note 2026-09-22" }],
    },
    {
      id: "NCT06393374-exc-12",
      status: "unknown",
      confidence: "low",
      rationale: "Vaccination history is not documented in the record.",
      evidence: [],
      actionNeeded: "Confirm no live or live-attenuated vaccine within 30 days before the first dose",
    },
    {
      id: "NCT06393374-exc-13",
      status: "pass",
      confidence: "medium",
      rationale: "No investigational agent or device is recorded; all treatment to date has been standard of care.",
      evidence: [],
    },
    {
      id: "NCT06393374-exc-14",
      status: "pass",
      confidence: "medium",
      rationale: "No malignancy other than the index breast cancer is recorded in the history.",
      evidence: [],
    },
    {
      id: "NCT06393374-exc-15",
      status: "pass",
      confidence: "medium",
      rationale: "No immunodeficiency is recorded and her medications include no steroids or immunosuppressants.",
      evidence: [],
    },
    {
      id: "NCT06393374-exc-16",
      status: "pass",
      rationale: "Her immune hypothyroidism is treated with levothyroxine replacement only, which is allowed; no autoimmune disease before pembrolizumab.",
      evidence: [
        { quote: "irAE hypothyroidism G2 -> levothyroxine, TSH now nl.", source: "Clinic note 2026-09-22" },
        { quote: "No autoimmune dz prior to pembro.", source: "PMH" },
      ],
    },
    {
      id: "NCT06393374-exc-17",
      status: "pass",
      confidence: "medium",
      rationale: "No pneumonitis or ILD is recorded; no cough, lungs clear, and the 2026-07-09 chest CT showed only post-surgical changes.",
      evidence: [{ quote: "Lungs clear.", source: "Exam 2026-09-22" }],
    },
    {
      id: "NCT06393374-exc-18",
      status: "pass",
      confidence: "medium",
      rationale: "No active infection or antibiotic therapy is recorded at the 2026-09-22 visit.",
      evidence: [],
    },
    {
      id: "NCT06393374-exc-19",
      status: "pass",
      confidence: "medium",
      rationale: "No HIV infection, Kaposi's sarcoma or Castleman disease is recorded.",
      evidence: [],
    },
    {
      id: "NCT06393374-exc-20",
      status: "unknown",
      confidence: "low",
      rationale: "Hepatitis B and C serology are not in the record; LFTs are normal.",
      evidence: [{ quote: "AST 22 | ALT 25 | T bili 0.5 | Alk phos 71", source: "Labs 2026-09-19" }],
      actionNeeded: "Obtain HBsAg and HCV antibody (reflex HCV RNA) to exclude concurrent active infection",
    },
    {
      id: "NCT06393374-exc-21",
      status: "pass",
      confidence: "medium",
      rationale: "No allogeneic tissue or organ transplant is recorded.",
      evidence: [],
    },
  ],
);
