import { demoMatch } from "../../match-helpers";

export default demoMatch(
  "NCT07652242",
  "Fits Part B (vaccine + adjuvant pembrolizumab and olaparib/cape) · ECG and hepatitis serology needed",
  "She fits Part B, which adds ITI-5000 to standard adjuvant therapy: KEYNOTE-522 with residual disease (RCB-II), adjuvant pembrolizumab ongoing with 5 of 9 cycles left, and olaparib or capecitabine about to be chosen — either qualifies. Part B needs ≥ 3 pembrolizumab cycles remaining at the first vaccine dose, so screening should start now (C7 is due ~2026-11-24). Open items are screening tests: triplicate ECG on sertraline, hepatitis B/C serology, and timing of autumn flu or COVID vaccines (none within 28 days). Her grade 2 immune hypothyroidism is an ICI endocrinopathy the protocol explicitly tolerates.",
  [
    {
      id: "NCT07652242-inc-1",
      status: "not-applicable",
      rationale: "Applies to Part A (vaccine alone after completing adjuvant pembrolizumab); she is on cycle 4 of 9 and would enter Part B alongside ongoing pembrolizumab.",
      evidence: [{ quote: "pembrolizumab 200 mg IV q3 weeks (adjuvant, C4 of 9)", source: "Medications" }],
    },
    {
      id: "NCT07652242-inc-2",
      status: "pass",
      rationale: "Neoadjuvant chemotherapy with pembrolizumab (KEYNOTE-522), then mastectomy on 2026-06-11 without pCR (ypT1c ypN1a, RCB class II).",
      evidence: [
        { quote: "Neoadj per KEYNOTE-522", source: "Clinic note 2026-09-22" },
        { quote: "Residual Cancer Burden: RCB class II (RCB score 2.6)", source: "Pathology 2026-06-17" },
      ],
    },
    {
      id: "NCT07652242-inc-3",
      status: "pass",
      confidence: "medium",
      rationale: "On adjuvant pembrolizumab 200 mg q3w with 5 cycles left after C4 (2026-09-22), and olaparib or capecitabine is planned (decision at next visit). The first vaccine must precede ~C7 (~2026-11-24) to keep ≥ 3 cycles remaining.",
      evidence: [
        { quote: "pembrolizumab 200 mg IV q3 weeks (adjuvant, C4 of 9)", source: "Medications" },
        { quote: "Adj olaparib vs cape: pt to decide by next visit.", source: "Clinic note 2026-09-22" },
      ],
      actionNeeded: "Confirm olaparib or capecitabine start and give vaccination #1 by ~C7 (≥ 3 pembrolizumab cycles remaining)",
    },
    {
      id: "NCT07652242-inc-4",
      status: "pass",
      rationale: "She is 39 years old (born 1987).",
      evidence: [{ quote: "DOB: 1987 (39 yo F)", source: "Clinic note 2026-09-22" }],
    },
    {
      id: "NCT07652242-inc-5",
      status: "pass",
      confidence: "low",
      rationale: "Signed consent is obtained at screening; she is actively seeking residual-disease trials.",
      evidence: [{ quote: "Pt leaning olaparib but wants to hear about trials for residual disease first.", source: "Clinic note 2026-09-22" }],
    },
    {
      id: "NCT07652242-inc-6",
      status: "pass",
      confidence: "low",
      rationale: "Agreement to defer routine vaccinations until 30 days after the last study vaccine is confirmed at consent; relevant given seasonal flu and COVID boosters.",
      evidence: [],
      actionNeeded: "Plan influenza/COVID vaccination timing around the study vaccine schedule",
    },
    {
      id: "NCT07652242-inc-7",
      status: "pass",
      rationale: "TNBC (ER 0%, PR 0%, HER2 IHC 0 on core and residual tumor), stage II (cT2 cN1 IIB; ypT1c ypN1a), gBRCA1 allowed, and no endocrine or CDK4/6 therapy.",
      evidence: [
        { quote: "Receptors repeated on residual tumor: ER 0%, PR 0%, HER2 IHC 0 - triple negative, concordant with core bx.", source: "Pathology 2026-06-17" },
        { quote: "Pathologic stage (AJCC 8th): ypT1c ypN1a", source: "Pathology 2026-06-17" },
      ],
    },
    {
      id: "NCT07652242-inc-8",
      status: "not-applicable",
      rationale: "Applies to Part A only (more than 4 weeks off all therapy); she would enter Part B with concurrent adjuvant therapy.",
      evidence: [],
    },
    {
      id: "NCT07652242-inc-9",
      status: "not-applicable",
      rationale: "Applies to Part A only (all planned treatment completed); she would enter Part B while adjuvant therapy continues.",
      evidence: [],
    },
    {
      id: "NCT07652242-inc-10",
      status: "pass",
      rationale: "ECOG 0 at the 2026-09-22 visit.",
      evidence: [{ quote: "EXAM: ECOG 0.", source: "Clinic note 2026-09-22" }],
    },
    {
      id: "NCT07652242-inc-11",
      status: "unknown",
      confidence: "medium",
      rationale: "No ischemic heart disease or MI is recorded, but no ECG or QTcF is on file and she takes sertraline; the triplicate screening ECG decides this.",
      evidence: [],
      actionNeeded: "Obtain triplicate ECG at screening; mean QTcF must be ≤ 470 ms",
    },
    {
      id: "NCT07652242-inc-12",
      status: "pass",
      confidence: "medium",
      rationale: "Hematology on 2026-09-19 is adequate without transfusion or growth factors (ANC 1.9, Hgb 12.4, Plt 180) but is 9 days old, outside the 7-day window.",
      evidence: [{ quote: "WBC 3.4 (L) | ANC 1.9 | Hgb 12.4 | Plt 180", source: "Labs 2026-09-19" }],
      actionNeeded: "Repeat CBC and chemistry within 7 days before enrollment",
    },
    {
      id: "NCT07652242-inc-13",
      status: "pass",
      rationale: "Hgb 12.4 g/dL, ANC 1.9 × 10⁹/L and platelets 180 × 10⁹/L on 2026-09-19, all above thresholds.",
      evidence: [{ quote: "WBC 3.4 (L) | ANC 1.9 | Hgb 12.4 | Plt 180", source: "Labs 2026-09-19" }],
    },
    {
      id: "NCT07652242-inc-14",
      status: "pass",
      confidence: "medium",
      rationale: "AST 22, ALT 25, ALP 71, bilirubin 0.5 and creatinine 0.7 are normal (CrCl well above 50). She is of childbearing potential with a levonorgestrel IUD; hCG was negative 2026-09-19 but must be repeated within 3 days of vaccination #1.",
      evidence: [
        { quote: "AST 22 | ALT 25 | T bili 0.5 | Alk phos 71", source: "Labs 2026-09-19" },
        { quote: "hCG (serum) negative", source: "Labs 2026-09-19" },
      ],
      actionNeeded: "Repeat serum hCG within 3 days before vaccination #1",
    },
    {
      id: "NCT07652242-inc-15",
      status: "pass",
      confidence: "low",
      rationale: "She is of childbearing potential (irregular menses since chemotherapy, last spotting ~8/26, no oophorectomy), so pregnancy testing and contraception apply; ability to attend visits is confirmed at screening.",
      evidence: [{ quote: "Menses irregular since chemo, last spotting ~8/26.", source: "Clinic note 2026-09-22" }],
    },
    {
      id: "NCT07652242-inc-16",
      status: "pass",
      confidence: "low",
      rationale: "Capacity to understand and sign consent is confirmed at screening; nothing suggests impairment (she works as an RN).",
      evidence: [],
    },
    {
      id: "NCT07652242-inc-17",
      status: "pass",
      confidence: "low",
      rationale: "No herbal or alternative therapies are on her medication list; agreement to avoid them is confirmed at consent.",
      evidence: [],
    },
    {
      id: "NCT07652242-inc-18",
      status: "pass",
      confidence: "low",
      rationale: "Definition of alternative therapies; her medication list contains no herbal, homeopathic or high-dose supplement products.",
      evidence: [],
    },
    {
      id: "NCT07652242-exc-1",
      status: "pass",
      rationale: "She has not discontinued pembrolizumab for an irAE: grade 2 hypothyroidism was managed with levothyroxine and pembrolizumab continues (C4 on 2026-09-22).",
      evidence: [
        { quote: "irAE hypothyroidism G2 -> levothyroxine, TSH now nl.", source: "Clinic note 2026-09-22" },
        { quote: "Currently NED. Adj pembro C4 of 9 today.", source: "Clinic note 2026-09-22" },
      ],
    },
    {
      id: "NCT07652242-exc-2",
      status: "pass",
      rationale: "Surgery was 2026-06-11 (well over 4 weeks) and no investigational agent is recorded. The Part A therapy washout does not apply to Part B, and her only PD-1 inhibitor is pembrolizumab.",
      evidence: [{ quote: "Procedure date: 2026-06-11", source: "Pathology 2026-06-17" }],
    },
    {
      id: "NCT07652242-exc-3",
      status: "pass",
      rationale: "Her only immunotherapy toxicity is grade 2 hypothyroidism, an ICI endocrinopathy controlled on levothyroxine (TSH 3.1) — the type the criterion accepts. No cardiac toxicity is recorded.",
      evidence: [
        { quote: "irAE hypothyroidism G2 - levothyroxine 75 mcg, TSH 3.1, continue.", source: "Clinic note 2026-09-22" },
      ],
    },
    {
      id: "NCT07652242-exc-4",
      status: "pass",
      confidence: "medium",
      rationale: "Chemotherapy neuropathy is grade 1 and stable without functional limitation. No cardiac toxicity is recorded, though LVEF has not been re-measured since doxorubicin.",
      evidence: [
        { quote: "PN stable G1, no functional limitation.", source: "Clinic note 2026-09-22" },
        { quote: "Echo 3/4/26 pre-AC LVEF 60%.", source: "Clinic note 2026-09-22" },
      ],
    },
    {
      id: "NCT07652242-exc-5",
      status: "pass",
      confidence: "medium",
      rationale: "No significant illness beyond treated hypothyroidism and anxiety; mild leukopenia (WBC 3.4, ANC 1.9) is the only abnormal lab and is borderline rather than prohibitive.",
      evidence: [
        { quote: "WBC 3.4 (L) | ANC 1.9 | Hgb 12.4 | Plt 180", source: "Labs 2026-09-19" },
        { quote: "ANC 1.9 today, borderline, recheck.", source: "Clinic note 2026-09-22" },
      ],
    },
    {
      id: "NCT07652242-exc-6",
      status: "pass",
      rationale: "No autoimmune disease requiring immunosuppression: her hypothyroidism is an irAE (excluded from this rule) treated with replacement only, and she had no autoimmune disease before pembrolizumab.",
      evidence: [{ quote: "No autoimmune dz prior to pembro.", source: "PMH" }],
    },
    {
      id: "NCT07652242-exc-7",
      status: "pass",
      rationale: "Not pregnant or breastfeeding, with a levonorgestrel IUD in place.",
      evidence: [
        { quote: "Not pregnant, not breastfeeding.", source: "Clinic note 2026-09-22" },
        { quote: "Contraception: LNG-IUD, counseled.", source: "Clinic note 2026-09-22" },
      ],
    },
    {
      id: "NCT07652242-exc-8",
      status: "pass",
      confidence: "medium",
      rationale: "Serum hCG was negative on 2026-09-19; repeat serum and baseline urine tests are done at screening.",
      evidence: [{ quote: "hCG (serum) negative", source: "Labs 2026-09-19" }],
    },
    {
      id: "NCT07652242-exc-9",
      status: "pass",
      confidence: "medium",
      rationale: "She is not enrolled in another interventional trial; all treatment to date has been standard of care.",
      evidence: [],
    },
    {
      id: "NCT07652242-exc-10",
      status: "pass",
      confidence: "medium",
      rationale: "NKDA; no known allergy to lipid nanoparticle or PEG components is recorded.",
      evidence: [{ quote: "ALLERGIES: NKDA", source: "Allergies" }],
      actionNeeded: "Confirm no known PEG or lipid nanoparticle allergy",
    },
    {
      id: "NCT07652242-exc-11",
      status: "pass",
      confidence: "medium",
      rationale: "NKDA and no anaphylaxis is recorded; reactions to prior mRNA (COVID-19) vaccines are not specifically documented.",
      evidence: [{ quote: "ALLERGIES: NKDA", source: "Allergies" }],
      actionNeeded: "Confirm no prior anaphylaxis or severe reaction to an mRNA vaccine",
    },
    {
      id: "NCT07652242-exc-12",
      status: "pass",
      confidence: "medium",
      rationale: "No stroke, TIA, unstable angina or MI is recorded in her history.",
      evidence: [],
    },
    {
      id: "NCT07652242-exc-13",
      status: "pass",
      confidence: "medium",
      rationale: "No myocarditis or pericarditis is recorded despite ongoing pembrolizumab; no cardiac symptoms are noted.",
      evidence: [],
    },
    {
      id: "NCT07652242-exc-14",
      status: "pass",
      confidence: "medium",
      rationale: "No heart failure or arrhythmia is recorded; LVEF was 60% on 2026-03-04, but that echo predates doxorubicin and is almost 7 months old.",
      evidence: [{ quote: "ECHO 03/04/2026: LVEF 60%, normal LV size and function.", source: "Echo 2026-03-04" }],
      actionNeeded: "Consider a post-anthracycline echocardiogram; LVEF must not be < 45%",
    },
    {
      id: "NCT07652242-exc-15",
      status: "pass",
      confidence: "medium",
      rationale: "No heart failure or family history of long QT is recorded. Sertraline 50 mg carries at most a conditional QT risk, generally regarded as low; potassium is not reported.",
      evidence: [{ quote: "sertraline 50 mg PO daily", source: "Medications" }],
      actionNeeded: "Confirm sertraline is acceptable to the sponsor and check potassium",
    },
    {
      id: "NCT07652242-exc-16",
      status: "unknown",
      confidence: "medium",
      rationale: "Vaccination history is not documented, and it is flu and COVID booster season.",
      evidence: [],
      actionNeeded: "Confirm no mRNA, live, influenza or COVID-19 vaccine within 28 days before vaccination #1",
    },
    {
      id: "NCT07652242-exc-17",
      status: "pass",
      confidence: "medium",
      rationale: "No malignancy other than the index TNBC is recorded in her history.",
      evidence: [],
    },
    {
      id: "NCT07652242-exc-18",
      status: "pass",
      confidence: "medium",
      rationale: "No organ transplant or HIV infection is recorded in her history.",
      evidence: [],
    },
    {
      id: "NCT07652242-exc-19",
      status: "unknown",
      confidence: "low",
      rationale: "Hepatitis B and C results are not in the record; LFTs are normal.",
      evidence: [{ quote: "AST 22 | ALT 25 | T bili 0.5 | Alk phos 71", source: "Labs 2026-09-19" }],
      actionNeeded: "Obtain HBsAg and HCV antibody (reflex HCV RNA); positive results need undetectable viral load",
    },
    {
      id: "NCT07652242-exc-20",
      status: "pass",
      confidence: "low",
      rationale: "Ability and willingness to follow the schedule are confirmed at screening; nothing in the record suggests otherwise.",
      evidence: [],
    },
    {
      id: "NCT07652242-exc-21",
      status: "pass",
      confidence: "medium",
      rationale: "No anticoagulation and platelets 180. After right ALND, injections and blood draws should use the left arm (risk-reducing mastectomy only, no axillary surgery).",
      evidence: [{ quote: "WBC 3.4 (L) | ANC 1.9 | Hgb 12.4 | Plt 180", source: "Labs 2026-09-19" }],
    },
  ],
);
