import { demoMatch } from "../../match-helpers";

export default demoMatch(
  "NCT04333706",
  "Fits Phase II residual-TNBC cohort · HBV serology and ongoing adjuvant pembro to confirm",
  "She would enter the Phase II cohort (stage I–III TNBC with residual disease after neoadjuvant therapy): ER/PR 0%, HER2 IHC 0, RCB class II (ypT1c ypN1a) after KEYNOTE-522, which contained no capecitabine or sarilumab; the Phase I criteria for metastatic disease do not apply. ECOG 0, labs from 2026-09-19 and her levonorgestrel IUD satisfy the remaining requirements, and hepatitis B serology is the only undocumented exclusion. Two points need discussion: the study pairs sarilumab with capecitabine, so enrolling means taking the CREATE-X backbone instead of the adjuvant olaparib she is leaning toward as a gBRCA1 carrier (OlympiA); and the criteria do not say whether her ongoing adjuvant pembrolizumab (cycle 4 of 9) may continue.",
  [
    {
      id: "NCT04333706-inc-1",
      status: "pass",
      confidence: "low",
      rationale: "Consent and ability to comply are confirmed at screening; she is actively asking about residual-disease trials and attends 3-weekly treatment visits.",
      evidence: [{ quote: "Pt leaning olaparib but wants to hear about trials for residual disease first.", source: "Clinic note 2026-09-22" }],
    },
    {
      id: "NCT04333706-inc-2",
      status: "pass",
      rationale: "39-year-old woman; the study enrolls both sexes from age 18.",
      evidence: [{ quote: "39 yo premenopausal F", source: "Clinic note 2026-09-22" }],
    },
    {
      id: "NCT04333706-inc-3",
      status: "not-applicable",
      rationale: "Phase I only (metastatic HER2-negative disease). She would enter the Phase II residual-disease cohort and has no metastatic disease on the 2026-07-09 CT.",
      evidence: [{ quote: "No evidence of metastatic disease in the chest, abdomen or pelvis.", source: "CT CAP 2026-07-09" }],
    },
    {
      id: "NCT04333706-inc-4",
      status: "not-applicable",
      rationale: "Phase I only; the Phase II residual-disease cohort she would enter has no life-expectancy requirement.",
      evidence: [],
    },
    {
      id: "NCT04333706-inc-5",
      status: "not-applicable",
      rationale: "Phase I only. For reference, her last cytotoxic chemotherapy (ddAC) ended in 5/2026, about 4 months ago, and she has never received capecitabine.",
      evidence: [],
    },
    {
      id: "NCT04333706-inc-6",
      status: "pass",
      rationale: "Triple-negative on the 11/2025 core biopsy (ER 0%, PR 0%, HER2 IHC 0) and again on the residual tumor at surgery, well under the < 10% ER/PR cut-off.",
      evidence: [
        { quote: "IDC, grade 3 (Nottingham 9/9), ER 0%, PR 0%, HER2 IHC 0 (negative), Ki-67 75%.", source: "Core biopsy 11/2025" },
        { quote: "Receptors repeated on residual tumor: ER 0%, PR 0%, HER2 IHC 0 - triple negative, concordant with core bx.", source: "Pathology 2026-06-17" },
      ],
    },
    {
      id: "NCT04333706-inc-7",
      status: "pass",
      rationale: "Stage IIB (cT2 cN1) at diagnosis with residual invasive disease at surgery on 2026-06-11: 1.2 cm tumor and 2/11 nodes positive (ypT1c ypN1a, RCB class II), so not a pCR.",
      evidence: [
        { quote: "Pathologic stage (AJCC 8th): ypT1c ypN1a", source: "Pathology 2026-06-17" },
        { quote: "Residual Cancer Burden: RCB class II (RCB score 2.6)", source: "Pathology 2026-06-17" },
      ],
    },
    {
      id: "NCT04333706-inc-8",
      status: "pass",
      confidence: "medium",
      rationale: "Her only systemic therapy is KEYNOTE-522 (pembrolizumab, paclitaxel/carboplatin, ddAC), with no capecitabine or sarilumab; the ongoing adjuvant pembrolizumab continues that regimen. The A/P line 'continue weekly paclitaxel/carbo' is a stale copy-forward; chemotherapy ended 5/2026.",
      evidence: [
        { quote: "Neoadj per KEYNOTE-522: pembro + weekly paclitaxel + carboplatin x12 wks (12/2025-3/2026) then pembro + ddAC x4 (3/2026-5/2026).", source: "Clinic note 2026-09-22" },
        { quote: "pembrolizumab 200 mg IV q3 weeks (adjuvant, C4 of 9)", source: "Medications" },
      ],
      actionNeeded: "Confirm with the study team that ongoing adjuvant pembrolizumab is acceptable and whether it must stop before sarilumab/capecitabine",
    },
    {
      id: "NCT04333706-inc-9",
      status: "pass",
      rationale: "ECOG 0 on examination 2026-09-22.",
      evidence: [{ quote: "EXAM: ECOG 0.", source: "Clinic note 2026-09-22" }],
    },
    {
      id: "NCT04333706-inc-10",
      status: "pass",
      rationale: "Labs 2026-09-19 (9 days old) meet every threshold: ANC 1.9 ×10⁹/L (> 1.5), platelets 180, Hgb 12.4, AST 22 / ALT 25 and bilirubin 0.5 (normal), creatinine 0.7 (eGFR well above 30). ANC is borderline with WBC 3.4 and was flagged for recheck.",
      evidence: [
        { quote: "WBC 3.4 (L) | ANC 1.9 | Hgb 12.4 | Plt 180", source: "Labs 2026-09-19" },
        { quote: "AST 22 | ALT 25 | T bili 0.5 | Alk phos 71", source: "Labs 2026-09-19" },
        { quote: "Cr 0.7", source: "Labs 2026-09-19" },
      ],
      actionNeeded: "Repeat CBC at screening; ANC must remain > 1,500/mcL (G-CSF permitted)",
    },
    {
      id: "NCT04333706-inc-11",
      status: "pass",
      confidence: "medium",
      rationale: "Of childbearing potential (premenopausal, irregular menses since chemotherapy, last spotting ~8/26) and already using a levonorgestrel IUD, a highly effective method; continuing it for 24 weeks after the last dose is confirmed at screening.",
      evidence: [
        { quote: "levonorgestrel IUD (placed 2023)", source: "Medications" },
        { quote: "Menses irregular since chemo, last spotting ~8/26.", source: "Clinic note 2026-09-22" },
      ],
    },
    {
      id: "NCT04333706-inc-12",
      status: "not-applicable",
      rationale: "Applies to male participants only; she is a woman.",
      evidence: [],
    },
    {
      id: "NCT04333706-exc-1",
      status: "pass",
      confidence: "medium",
      rationale: "She has used a levonorgestrel IUD since 2023 and was counseled on contraception on 2026-09-22; nothing suggests she is unwilling to continue it through 24 weeks after treatment.",
      evidence: [{ quote: "Contraception: LNG-IUD, counseled.", source: "Clinic note 2026-09-22" }],
    },
    {
      id: "NCT04333706-exc-2",
      status: "pass",
      rationale: "Not pregnant or breastfeeding per the 2026-09-22 note, with a negative serum hCG on 2026-09-19.",
      evidence: [
        { quote: "Not pregnant, not breastfeeding.", source: "Clinic note 2026-09-22" },
        { quote: "hCG (serum) negative", source: "Labs 2026-09-19" },
      ],
    },
    {
      id: "NCT04333706-exc-3",
      status: "pass",
      confidence: "medium",
      rationale: "Comorbidities are controlled (immune hypothyroidism on levothyroxine, anxiety on sertraline, grade 1 neuropathy without functional limitation). The one flag is ANC 1.9 with WBC 3.4: sarilumab itself lowers neutrophils, and its label advises against starting below ANC 2,000/mm³.",
      evidence: [
        { quote: "PMH: irAE hypothyroidism (on levo), anxiety (sertraline). No DM. No autoimmune dz prior to pembro.", source: "Clinic note 2026-09-22" },
        { quote: "ANC 1.9 today, borderline, recheck.", source: "Clinic note 2026-09-22" },
      ],
      actionNeeded: "Treating physician to weigh the borderline ANC against sarilumab's neutropenia risk; repeat CBC before the first dose",
    },
    {
      id: "NCT04333706-exc-4",
      status: "unknown",
      confidence: "low",
      rationale: "Hepatitis B serology is not documented; any current or past HBV infection excludes, while vaccine-only immunity is allowed.",
      evidence: [],
      actionNeeded: "Obtain HBsAg, anti-HBc and anti-HBs; positive HBsAg or anti-HBc excludes, isolated anti-HBs (vaccination) is allowed",
    },
    {
      id: "NCT04333706-exc-5",
      status: "pass",
      confidence: "medium",
      rationale: "No tuberculosis history in an otherwise complete past medical history. Latent TB screening is still standard before starting an IL-6 receptor antibody such as sarilumab.",
      evidence: [{ quote: "PMH: irAE hypothyroidism (on levo), anxiety (sertraline). No DM. No autoimmune dz prior to pembro.", source: "Clinic note 2026-09-22" }],
      actionNeeded: "Screen for latent TB (IGRA) before sarilumab",
    },
    {
      id: "NCT04333706-exc-6",
      status: "pass",
      confidence: "medium",
      rationale: "No diverticulitis or other GI history in an otherwise complete past medical history; relevant because sarilumab carries a risk of GI perforation.",
      evidence: [{ quote: "PMH: irAE hypothyroidism (on levo), anxiety (sertraline). No DM. No autoimmune dz prior to pembro.", source: "Clinic note 2026-09-22" }],
    },
    {
      id: "NCT04333706-exc-7",
      status: "pass",
      confidence: "low",
      rationale: "Vaccination history is not recorded; live vaccines would normally be avoided while on pembrolizumab, and the 30-day window is confirmed at screening.",
      evidence: [],
      actionNeeded: "Confirm no live vaccine (e.g., MMR, varicella/zoster live, intranasal influenza) within 30 days before the first dose",
    },
    {
      id: "NCT04333706-exc-8",
      status: "pass",
      confidence: "medium",
      rationale: "No other malignancy is recorded: the risk-reducing left mastectomy was benign and the germline panel found only the BRCA1 variant.",
      evidence: [{ quote: "C. Left breast: benign breast tissue, no atypia, no carcinoma.", source: "Pathology 2026-06-17" }],
    },
    {
      id: "NCT04333706-exc-9",
      status: "pass",
      confidence: "medium",
      rationale: "Works as a registered nurse and has two children; nothing in the social history suggests incarceration.",
      evidence: [{ quote: "SH: RN, 2 kids, never smoker, no EtOH.", source: "Clinic note 2026-09-22" }],
    },
    {
      id: "NCT04333706-exc-10",
      status: "pass",
      confidence: "medium",
      rationale: "Outpatient with anxiety stable on sertraline 50 mg; no psychiatric or medical detention is recorded.",
      evidence: [{ quote: "4. Anxiety - sertraline 50 mg, stable.", source: "Clinic note 2026-09-22" }],
    },
    {
      id: "NCT04333706-exc-11",
      status: "pass",
      confidence: "low",
      rationale: "No barrier to compliance is recorded: she completed neoadjuvant therapy, surgery and PMRT and attends 3-weekly pembrolizumab visits; confirmed at screening.",
      evidence: [{ quote: "RTC 3 wks for C5.", source: "Clinic note 2026-09-22" }],
    },
  ],
);
