/**
 * Regenerates lib/demo/matches.ts, the import list for the precomputed demo
 * verdicts (one file per patient × trial under lib/demo/matches/<patient>/).
 *   npm run demo:index
 */
import { readdirSync, statSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(here, "../lib/demo/matches");
const OUT = resolve(here, "../lib/demo/matches.ts");

const patients = readdirSync(ROOT)
  .filter((name) => statSync(resolve(ROOT, name)).isDirectory())
  .sort();

const imports: string[] = [];
const entries: string[] = [];
let n = 0;
for (const patient of patients) {
  const ids = readdirSync(resolve(ROOT, patient))
    .filter((f) => /^NCT\d{8}\.ts$/.test(f))
    .map((f) => f.replace(/\.ts$/, ""))
    .sort();
  const rows: string[] = [];
  for (const id of ids) {
    const name = `m${n++}`;
    imports.push(`import ${name} from "./matches/${patient}/${id}";`);
    rows.push(`    ${id}: ${name},`);
  }
  entries.push(`  "${patient}": {\n${rows.join("\n")}\n  },`);
}

const body = `// Generated by scripts/build-match-index.ts (npm run demo:index). Do not edit by hand.
import type { TrialMatch } from "@/lib/types";
${imports.join("\n")}

/**
 * Precomputed criterion-level matches for demo mode:
 *   DEMO_MATCHES[patientId][nctId] → TrialMatch
 * One file per patient × trial under ./matches/<patient>/, authored with
 * demoMatch() from ./match-helpers and checked by ./matches.test.ts.
 */
export const DEMO_MATCHES: Record<string, Record<string, TrialMatch>> = {
${entries.join("\n")}
};
`;
writeFileSync(OUT, body);
console.log(`Wrote ${OUT}: ${n} matches for ${patients.length} patients`);
